### ISSUE TITLE
How to remove provider manually

### ISSUE THREAD

**Issue by lonely4flow** [rrousselGit/provider#100]
In my case,When I request new data,I need remove old provider from Providers and add new proivider,what api could i call?

**Comment by rrousselGit** [comment]
I do not understand.
Do you have an example?

**Comment by lonely4flow** [comment]
class CountDownItemModel  with ChangeNotifier{
  int countTime = 0;
  countDown(){
    countTime--;
    notifyListeners();
  }
}

@override
  void initState() {
    mTimerUtil = new TimerUtil(mInterval: 1000);
    mTimerUtil.setOnTimerTickCallback((int tick) {
      for(int i=0;i<homeService.countDownList.length;i++){
          CountDownItemModel data = homeService.countDownList[i];
          data.countDown();
        }
}
void requestCounDownPlay(){
    // request dataList from network
    homeService.requestCountDownList((bool isSuccess,String msg,dynamic data){
      setState(() {
       // Todo,I want to remove old data
      // how to remove old data by scope here
      // add data by scope
        for(int i=0;i<homeService.countDownList.length;i++){
            CountDownItemModel model = homeService.countDownList[i];
            ProviderUtil.provide(Provider<CountDownItemModel>.value(model),scope: 'home_countdown'+i.toString());
        }
      // start count down timer here
       
      });
    });
  }

  Widget _createCountDownRow(){
    List<Widget> list = [];
    for(int i=0;i<homeService.countDownList.length;i++){
       var data = homeService.countDownList[i];
       if(i>0){
          list.add(SizedBox(width:10));
       }
       list.add(
         Provide<CountDownItemModel>(
              scope: ProviderUtil.getScope('home_countdown'+i.toString()),
              builder: (context, child, countModel) {
                return HomeCountDownItemCell(countModel,index:i,onPressed: (){
                    print(data);
                },);
              },
            )
          );
        
    }

**Comment by rrousselGit** [comment]
If that's not solved, consider asking that on Stackoverflow or Gitter
