### ISSUE TITLE
how to load initial data without pressing any key..

### ISSUE THREAD

**Issue by kunaldodiya** [rrousselGit/provider#101]
@override Widget build(BuildContext context) { final UserBloc userBloc = Provider.of<UserBloc>(context); userBloc.getUser(); } this send continuous request to server.. how can i get initial data from server as soon as screen load ???

**Comment by rrousselGit** [comment]
Hello, thanks for the issue!

This question better fits Stackoverflow/Slack/gitter. Would you mind asking it there?

**Comment by hoangduchuu** [comment]
any solution for this ?
