### ISSUE TITLE
Rebuild a single item in a listview

### ISSUE THREAD

**Issue by peekpt** [rrousselGit/provider#107]
In the Google IO the hosts presented a game with avatars. At certain time they say that the avatars will change without rebuilding the entire list of avatars, only the item on the list that needs to be rebuilt. 
How to achieve this? If you have a list of a type, let's call it avatars.
In a list of avatars , how to place the consumers and providers that will update each avatar independently
https://youtu.be/d_m5csmrf7I @23:18

**Comment by rrousselGit** [comment]
Expose the avatar through a provider instead of passing it to the widget constructor

**Comment by peekpt** [comment]
I understand now... Shall I include in the class avatar a function something like :
provider(child: ..) that will wrap the current in a provider already, so in the main code we only call for avatar.provider(child: ItemWidget()) ?

**Comment by peekpt** [comment]
In cases we have simple Provider-Consumer-Widget without widgets in-between we could have something like Prosumer widget

**Comment by rrousselGit** [comment]
There are far too many variations for such widget. That isn't worth the maintaince cost.

You're free to make your own "Prosumer" widget
