### ISSUE TITLE
Form validation using providers

### ISSUE THREAD

**Issue by codelooneytunes** [rrousselGit/provider#109]
Anyone using provider for form field validations?
I have done the same using streams and BLOC where validations are done using streams and errors are cascaded up to the UI using Bloc

Example a Login Form username and password fields using Textfield widget. 
Requirement is to use provider to perform validations and also provide errors back to the textfield error label.

I did try it using providers and I am able to perform the validations in the ChangeNotifier class, but I am looking for a clean way to cascade username and password field validation errors to the UI
Regards
code

**Comment by rrousselGit** [comment]
Hello!

That kind of content doesn't really belong to github. Consider asking that on Reddit/Gitter
