### ISSUE TITLE
Confusing builder: dispose:

### ISSUE THREAD

**Issue by peekpt** [rrousselGit/provider#116]
Shouldn't builder: be called initValue: .
Since we already using this "policy" in widgets with initState and dispose. 
Having builder and  child together on the parameters is confusing.

**Comment by rrousselGit** [comment]
While I agree, I don't think the change is worth it.

The type system is here to prevent potential mistakes anyway, and the name is technically correct.

**Comment by jtlapp** [comment]
Good names make code easier to understand and maintain.

**Comment by rrousselGit** [comment]
I agree. But there's the opposite situation:

Most developers tend to use what's the shortest to write. It's not legitimate, but still a reality. 

The thing is, the default default constructor is usually what you should go for. But out of lazyness, many use the `.value` constructor to not have to write a `() =>` — which can cause memory leaks and other issues. 


Having longer names may increase that problem, when it's already pretty bad.

**Comment by jtlapp** [comment]
Yeah, the longer the name, the more devs will gripe -- unless they're a Java dev. I maintain some extraordinarily complex code, and to survive, I've had to rename simple names to accurate names across the board. I can now drop nearly anywhere in the code and understand what's going on.

I prefer `builder` and `child` to `initValue` and `child`, but would have liked `builder` and `fixedChild` or `prebuiltChild` or even just `prebuilt` instead.

Right now, every time I see `builder` and `child` together I have to stop and work to recall the relationship between two apparently identical things. I'm sure that will go away as I get more experience with the package.

**Comment by rrousselGit** [comment]
`child` is the name used by convention in the framework. There are other examples using the same name:

```dart
AnimatedBuilder(
  builder: (context, child) {
  },
  child: Foo(),
)
```
