### ISSUE TITLE
[Question] Passing data through onTap Navigation does not update

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/provider#118]
I'm still very much new to Flutter and Provider so apologies if this is a silly question. I have this widget that holds a list of games. When someone clicks a game, they get taken through

```dart
var roster = Provider.of<AppState>(context).roster;

/*...*/

onTap: () {
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) => EditRosterPage(roster: roster),
    ),
}
```

to a roster page where they get to alter the roster by adding or removing players. All modifications happen from helper methods on the `AppState` which has  a `ChangeNotifier`. For example, to edit the roster, I'll call `Provider.of<AppState>(context).updateRoster(updatedRoster)`, which successfully updates the roster and calls `notifyListeners()`. However, the changes are not visible in the UI because although the original list of games rebuilds, the newest roster is never passed through the `builder: (context) => EditRosterPage(roster: roster)` line inside the `onTap` handler.

My gut feeling is that this is expected behavior but I can't be sure

(Also, I made a few simplifications from my original code)

**Comment by rrousselGit** [comment]
That's because by passing the value to the widget constructor instead of using Provider.of.

Instead consider removing the variable passed to `EditRosterPage`, and wrap the widget into a `ChangeNotifierProvider.value(value: roaster)`

**Comment by Nolence** [comment]
Thanks @rrousselGit ! I got it working :)
