### ISSUE TITLE
Update documentation: ProxyProvider landed in 3.0

### ISSUE THREAD

**Issue by daniel-v** [rrousselGit/provider#122]
Seems like Provided 3.0 landed ProxyProvider, however the Readme makes no mention of it. It'd be nice to have info on it.

**Comment by rrousselGit** [comment]
I've added a mention about it in the readme (currently not merged. You can find it here: https://github.com/rrousselGit/provider/tree/proxy-provider-documentation#proxyprovider)

Is that good enough?

**Comment by daniel-v** [comment]
Awesome, thank you!
