### ISSUE TITLE
ChangeNotifierProvider problem, call multiple times.

### ISSUE THREAD

**Issue by hoaquo** [rrousselGit/provider#123]
Hi,

I have a problem with a ChangeNotifierProvider

I have a ChangeNotifierProvider build function

```dart
ChangeNotifierProvider(
      builder: (_) => Repository(data: data),
      child: Consumer<Repository>(
        builder: (context, Repository repository, _) {
          return Scaffold(
            appBar: AppBar(
              title: Text("Title"),
            ),
            body: _buildBody(repository)
          );
        }
      )
```

with ``data`` is changed after http fetch. ``Repository`` is a simple class extend ``ChangeNotifier``

The problem is the builder is called repeat again and again multiple times (> 4 - 1x). I don't have much experience on provider. 

Is the data changed causes calling the builder run again and again?

Many thanks

**Comment by rrousselGit** [comment]
What builder are you talking about?

**Comment by hoaquo** [comment]
The builder function inside ``Consume<Repository>``. Data is initialize with a simple data structure with URL and some simple info, then it is loaded inside the ``_buildBody()`` function for more information, after data is loaded, I call ``notifyListeners()`` in repository. to update the UI

**Comment by hoaquo** [comment]
Damn, I found the problem, it's not provider problem. The root problem is this piece of code

```dart

Widget build(BuildContext context) {
    if (loading) {
      return child;
    }
    else {
       return Stack(children: [child,  _buildLoadingIndicator()));
    }
  }

```

This code update the widget tree and make the call repeatly. I don't know why. If I change the code to

```dart

Widget build(BuildContext context) {
    final children = [child];
    if (loading) {
      children.add(_buildLoadingIndicator());
    }

    return Stack(children: children);
  }

```

It works fine. 

BTW Thank you very much

**Comment by tp** [comment]
>  I don't know why.

@hoaquo The reason was that you wrapped around the `Stack` conditionally, so the tree would change and all associated state would be dropped and recreated when transitioning between different values of `loading`.

I think this video covers how state is kept alive / attached (though in the context of `keys`, but the concept also applies to "place/position in the tree" when there are no keys around): https://www.youtube.com/watch?v=kn0EOS-ZiIc

**Comment by rrousselGit** [comment]
Cool that you found the issue. .:ok_hand:
