### ISSUE TITLE
Doubt with rendering same MultiProvider in a if/else statement inside the builder function of FutureBuilder

### ISSUE THREAD

**Issue by anargu** [rrousselGit/provider#129]
Maybe I'm not correctly understanding how widget rebuild works but for example in this chunk of code. because the initial value is false then the flow goes for the else block and create the MultiProvider widget in that block, all is working fine. Then after the future completes it returns true so it goes for the if block but the MultiProvider is not recreated again and the properties I put does not reflect on the nested widgets like the Stream I am attaching in providers argument. Also I debugged with breakpoints and in effect, the program does not call the someProviderOfStream.streamWithAcceptedPermissions() function. So my question is how actually this works, and how can I recreate the MultiProvider Object.

```
return FutureBuilder(
    initialData: false,
    future: someObj.fetchHasPermission(), // true or false
    builder: (context, snapshot) {
      if (!snapshot.hasData) return Text('no data');
      bool hasPermission = snapshot.data;
      if (hasPermission) {
        return MultiProvider(
          providers: [
            StreamProvider<String>(builder: (context) => someProviderOfStream.streamWithAcceptedPermissions()),
            ChangeNotifierProvider<SomeProvider>.value(value: _someProvider),
          ],
          child: SomeWidget()
        );
      } else {
        return MultiProvider(
          providers: [
            StreamProvider<String>(builder: (context) => someProviderOfStream.emptyStream()),
            ChangeNotifierProvider<SomeProvider>.value(value: _someProvider),
          ],
          child: SomeWidget()
        );
      }
    }
  );
```

Also I tested with returning a different Widget in the else block for example a Text() widget and the program works correctly. It seems like Flutter optimizes the build function and avoid to recreate Same-Type Widgets before created, but I'm not sure if it's related to Flutter or Provider library optimization.

```
return FutureBuilder(
    initialData: false,
    future: someObj.fetchHasPermission(), // true or false
    builder: (context, snapshot) {
      if (!snapshot.hasData) return Text('no data');
      bool hasPermission = snapshot.data;
      if (hasPermission) {
        return MultiProvider(
          providers: [
            StreamProvider<String>(builder: (context) => someProviderOfStream.streamWithAcceptedPermissions()),
            ChangeNotifierProvider<SomeProvider>.value(value: _someProvider),
          ],
          child: SomeWidget()
        );
      } else {
        return Text('has no Permission');
      }
    }
  );
```

**Comment by rrousselGit** [comment]
This kind of questions belongs to stackoverflow or gitter.

But TD;DR, consider using keys on `MultiProvider`:

```dart
if (foo) {
  return MultiProvider(key: Key('something'));
}
else {
  return MultiProvider(key: Key('something else'));
}
```

**Comment by anargu** [comment]
I forgot the use of keys, sorry for the silly question, but thanks for answering.
