### ISSUE TITLE
User Provider inside another Provider

### ISSUE THREAD

**Issue by Newbie012** [rrousselGit/provider#135]
I have a SecureStorageProvider which handles all of the storage BI. Above that, I have an AuthProvider which handles all of the Auth BI.

The catch here is that AuthProvider uses SecureStorageProvider to determine if the user is already logged in.

The problem is that when I want to user a given provider, I have to pass a context which I don't have outside of Widgets.

**Comment by rrousselGit** [comment]
You either want to look into ProxyProvider (and it's different variants) or consider Consumer, pt `listen: false` on `Provider.of`

**Comment by Newbie012** [comment]
Regarding ProxyProvider, what if I want to "inject" multiple providers to a given provider?

My current solution is declaring in the main the "injectable" providers and then pass them to the other providers' constructors, like so:

```
ApiService _apiService = ApiService();
StorageService _storageService = StorageService();

...

providers: [
  Provider<AuthService>.value(value: AuthService(api: _apiService, storage: _storageService))
]
```

I'm not sure if it's considered either good or bad practice, but the idea of nesting ProxyProvider inside another ProxyProvider to inject two providers inside a single provider sounds too much code for a simple task.

**Comment by rrousselGit** [comment]
> Regarding ProxyProvider, what if I want to "inject" multiple providers to a given provider?

That's why ProxyProvider comes under multiple variations as explained here https://github.com/rrousselGit/provider#proxyprovider


```dart
ProxyProvider2<ApiService, StorageService, AuthService>(
  builder: (_, api, storage, __) => AuthService(api: api, storage: storage),
)
```

**Comment by Newbie012** [comment]
> > Regarding ProxyProvider, what if I want to "inject" multiple providers to a given provider?
> 
> That's why ProxyProvider comes under multiple variations as explained here https://github.com/rrousselGit/provider#proxyprovider
> 
> ```dart
> ProxyProvider2<ApiService, StorageService, AuthService>(
>   builder: (_, api, storage, __) => AuthService(api: api, storage: storage),
> )
> ```

Oh! I didn't notice that, thank you! Kudos <3
