### ISSUE TITLE
A small issue here, how would you call navigator.push when changenotifier rebuilds the ui ?

### ISSUE THREAD

**Issue by Jayanth-L** [rrousselGit/provider#138]
how would you call navigator.push when changenotifier rebuilds the ui ?

when calling the navigator.push like below i get error

`if(Provider.of<AppProviderState>(context).getProgress == "finished") {`
`       Provider.of<AppProviderState>(context).resetProgress();`
`        Navigator.of(context).push(MaterialPageRoute(`
`              builder: (BuildContext context) => NextPage()`
`        ));`
`}`

The error is somewhat like this

`
I/flutter (11295): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (11295): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (11295): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (11295): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (11295): Otherwise, the framework might not visit this widget during this build phase.
`

I believe the above error is because i am telling to to navigate to other page when the it was rebuilding the ui, that's ok for me but how would you implement the above situation ?

Please do help me if anybody has the solution ?
I am new to the provider,
Any resource link would be helpful

Thank you in advance!

**Comment by Jayanth-L** [comment]
Solved the issue 
by calling the method after the build process is done using SchedulerBinding

code: 
`SchedulerBinding.instance.addPostFrameCallback((_) {
          _openNextPage();
        });`

**Comment by renanboni** [comment]
flutter =  mess
