### ISSUE TITLE
Question about how ChangeNotifierProvider's builder works

### ISSUE THREAD

**Issue by tuannguyendotme** [rrousselGit/provider#140]
I have a bit confusion on how ChangeNotifierProvider's builder works. Here are my sample code:

```
   // This code works fine
   return ChangeNotifierProvider<LoginViewModel>.value(
      value: LoginViewModel(
        authenticationService: Provider.of<AuthenticationService>(context),
        storage: Provider.of<Storage>(context),
      ),
      child: Consumer<LoginViewModel>(
        builder: (context, viewModel, child) => Scaffold(
          appBar: AppBar(
            title: Text(Configuration.AppName),
          ),
          body: Center(
            child: Text('Login'),
          ),
        ),
      ),
    );
```

```
   // This code works fine
   var vm = LoginViewModel(
      authenticationService: Provider.of(context),
      storage: Provider.of(context),
    );

    return ChangeNotifierProvider<LoginViewModel>(
      builder: (context) => vm,
      child: Consumer<LoginViewModel>(
        builder: (context, viewModel, child) => Scaffold(
          appBar: AppBar(
            title: Text(Configuration.AppName),
          ),
          body: Center(
            child: Text('Login'),
          ),
        ),
      ),
    );
```

```
   // But this code doesn't work
   return ChangeNotifierProvider<LoginViewModel>(
      builder: (context) => LoginViewModel(
        authenticationService: Provider.of(context),
        storage: Provider.of(context),
      ),
      child: Consumer<LoginViewModel>(
        builder: (context, viewModel, child) => Scaffold(
          appBar: AppBar(
            title: Text(Configuration.AppName),
          ),
          body: Center(
            child: Text('Login'),
          ),
        ),
      ),
    );
```

The last code fragment throws exception

> flutter: The following assertion was thrown building LoginScreen(dependencies: [InheritedProvider<Storage>,
> flutter: InheritedProvider<AuthenticationService>]):
> flutter: inheritFromWidgetOfExactType(InheritedProvider<AuthenticationService>) or inheritFromElement() was
> flutter: called before _BuilderListenableDelegate<LoginViewModel>.initDelegate() completed.
> flutter: When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
> flutter: widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
> flutter: or an initDelegate() method, then the rebuilt dependent widget will not reflect the changes in the
> flutter: inherited widget.
> flutter: Typically references to inherited widgets should occur in widget build() methods. Alternatively,
> flutter: initialization based on inherited widgets can be placed in the didChangeDependencies method, which
> flutter: is called after initDelegate and whenever the dependencies change thereafter.

Is it a must to initialize LoginViewModel before return it in builder? Thanks.

**Comment by tuannguyendotme** [comment]
As LoginViewModel requires dependencies from other providers, I need to use

```
    return ChangeNotifierProxyProvider2<AuthenticationService, Storage,
        LoginViewModel>(
      builder: (context, autheticationService, storage, viewModel) =>
          LoginViewModel(
        authenticationService: autheticationService,
        storage: storage,
      ),
      child: Consumer<LoginViewModel>(
        builder: (context, viewModel, child) => Scaffold(
          appBar: AppBar(
            title: Text(Configuration.AppName),
          ),
          body: Center(
            child: Text('Login'),
          ),
        ),
      ),
    );
```

The documentation for ChangeNotifierProvider should be updated to mention it.

**Comment by wpietri** [comment]
Ah, thanks for this. I was totally mystified by this error message, but you cleared this up for me. The error should perhaps suggest using ProxyProviders, as that wasn't at all what I got from it.

**Comment by rrousselGit** [comment]
The v4.0 will replace this error message with a  custom one that suggest proxy provider

**Comment by wpietri** [comment]
Glad to hear it. Thanks!
