### ISSUE TITLE
 The right time to initialize the data in Provider

### ISSUE THREAD

**Issue by Vadaski** [rrousselGit/provider#141]
When should I initialize the data?
If I have a model provide by Provider, and I want to use it in the sub Widget。 I need to get the Model by using Provider.of(context) in didChangeDependence like this.
``` dart
 @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final counter = Provider.of(context);
    counter.increment();
    }
```
But this will cause side effects, causing counter.increment to be called again. I check the source code and find this comment.

  /// If [listen] is `true` (default), later value changes will trigger a new
  /// [State.build] to widgets, and [State.didChangeDependencies] for
  /// [StatefulWidget].

So how can I initialize data without side effects?

**Comment by Vadaski** [comment]
@rrousselGit  hi Remi , could you give some advice ?

**Comment by Nolence** [comment]
Here's what I've heard so far on the subject:

```dart
// Example one
class Example extends StatefulWidget {
  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool didInit = false;

  @override
  void didChangeDependencies() {
    if (!didInit) {
      final counter = Provider.of<T>(context, listen: false);
      counter.increment();
      didInit = true;
    }
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Placeholder();
  }
}
```
This might be the preferred way as you don't have to do anything hacky to get at the initialized context. (I saw this on a Udemy course by Maximillian.) Or there's:

```dart
// Example two
class ExampleTwo extends StatefulWidget {
  @override
  _ExampleTwoState createState() => _ExampleTwoState();
}

class _ExampleTwoState extends State<ExampleTwo> {
  @override
  void initState() {
    final counter = Provider.of<T>(context, listen: false);
    counter.increment();

    // If you need context for something else, you can use an IIFE an await
    // () async {
    //   await Future.delayed(Duration.zero);
    //   final counter = await Provider.of<T>(context);
    //   counter.increment();
    //   Scaffold.of(context).showSnackBar(...);
    // }();

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Placeholder();
  }
}
```
This one I got partially from this [SO answer](https://stackoverflow.com/a/49458289/8213910), but I think if you're just dispatching an event (or incrementing a counter) setting `listen` to `false` should be all you need to do

**Comment by rrousselGit** [comment]
This code is relatively unsafe. There's more than one reason for `didChangeDependencies` to be called.

You probably want something similar to:

```dart
MyCounter counter;

@override
void didChangeDependencies() {
  final counter = Provider.of<MyCounter>(context);
  if (conter != this.counter) {
    this.counter = counter;
    counter.increment();
  }
}
```

This should trigger `increment` only once.

**Comment by Vadaski** [comment]
thanks man
