### ISSUE TITLE
ProxyProvider6

### ISSUE THREAD

**Issue by timrijckaert** [rrousselGit/provider#142]
Hi, 

Currently the `ProxyProvider` class has a maximum of 6 type parameters.
However I have a case where I would like more.

Could more be added, possibly even be code generated to a more sane amount?

```
ProxyProvider6<Dio, UserStorage, VRTThemeBuilder, VRTNavigator, DeepLinkHelper, SomeRepository, AppBloc>(
  dispose: (context, val) => val.dispose(),
  builder: (
    BuildContext context,
    Dio dio,
    UserStorage userStorage,
    VRTThemeBuilder vrtThemeBuilder,
    VRTNavigator vrtNavigator,
    DeepLinkHelper deepLinkHelper,
    SomeRepository repository,
    AppBloc previous,
  ) =>
      AppBloc(
        tabBarChoices.first,
        dio,
        _defaultEnv,
        userStorage,
        vrtThemeBuilder,
        vrtNavigator,
        repository,
        deepLinkHelper,
      ),
```

Thanks in advance

Tim

**Comment by rrousselGit** [comment]
How many do you need?

**Comment by rrousselGit** [comment]
Note that you can call `Provider.of(context)` inside `builder` for an unlimited amount.

That'll work

**Comment by timrijckaert** [comment]
Currently I need 7.
I could make it work using the `Provider.of(context)` _trick_, but it kinda feels like a limitation in the `ProxyProvider` API.

Instead it would be nice if you/we could somehow generate a `ProxyProvider` with an arbitrary amount of type parameters.

What do you think?

**Comment by rrousselGit** [comment]
> I could make it work using the Provider.of(context) trick, but it kinda feels like a limitation in the ProxyProvider API.

That's a design choice. The generic argument is just there to make it easier to use, but it works with any inherited widgets.

**Comment by timrijckaert** [comment]
Hmm, so I guess this can be closed then?

**Comment by rrousselGit** [comment]
Hum no. I'll leave this open as a reminder to document that aspect.

And if peoples want some with more arguments, they can :+1: or make a PR. If its often requested, I'll make some more.

**Comment by MrMonotone** [comment]
I ran into this issue as well. I think that it would be good to not only make note of it in the documentation, but include an example using the Provider.of(context) trick as well. I think that would help people out.
