### ISSUE TITLE
Reducing providers by consuming value notifiers contained within a provider

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/provider#143]
I have a "session" provider that acts as a holder for a number of state holders, for example, the current user and workplace.  So far I create each of these as separate ChangeNotifier classes and insert them into the widget tree.  This works fine and allows me to rebuild a widget sub-tree only when the corresponding data changes.

I wonder whether it would be easier if there was a variant of Consumer and Provider.of that would allow me to get my session provider from the widget tree, but subscribe to a value notifier within the provider instead of the provider itself?  This would save having to add a provider for each state holder whilst avoiding rebuilds due to changes to other state holders.

I think it also easier to follow when there's a root state holder that keeps things together.

Here's a contrived example:

````
class Session with ChangeNotifier {
  static Session of(BuildContext context, {bool listen = false}) {
    return Provider.of<Session>(context, listen: listen);
  }

  final CurrentUser currentUser = CurrentUser();
  final CurrentWorkplace currentWorkplace = CurrentWorkplace();

  void _load() async {
    var userWorkplace = await UserService.getCurrentUser();
    this.currentUser.data = userWorkplace?.user;
    this.currentWorkplace.data = userWorkplace?.workplace;
  }

}

abstract class DataHolder<D> with ChangeNotifier {
  D _data;

  D get data => _data;

  set data(D data) {
    _data = data;
    notifyListeners();
  }
}

class CurrentUser extends DataHolder<User> {
  static User of(BuildContext context, {bool listen = false}) {
    return Provider.of<CurrentUser>(context, listen: listen).data;
  }
}

class CurrentWorkplace extends DataHolder<Workplace> {
  static Workplace of(BuildContext context, {bool listen = false}) {
    return Provider.of<CurrentWorkplace>(context, listen: listen).data;
  }
}
````

````
MultiProvider(
  providers: [
    ChangeNotifierProvider<Session>(
      builder: (context) => Session(),
    ),
    ChangeNotifierProxyProvider<Session, CurrentUser>(
      builder: (_, session, __) => session.currentUser,
    ),
    ChangeNotifierProxyProvider<Session, CurrentWorkplace>(
      builder: (_, session, __) => session.currentWorkplace,
    ),
  ],
  child: Column(
    children: <Widget>[
      Consumer<CurrentUser>(
          builder: (context, currentUser, _) => UserInfo(user: currentUser.data),
      ),
      Consumer<CurrentWorkplace>(
        builder: (context, currentWorkplace, _) => WorkplaceInfo(user: currentWorkplace.data),
      ),
    ],
  )
)
````

I'm thinking that this could become something simpler like the following, where the consumer asks for and subscribes to a change notifier within the provider instead.  This would remove the need for classes like CurrentUser and CurrentWorkplace, which would become ValueNotifier's instead.

````
ChangeNotifierProvider<Session>(
  builder: (context) => Session(),
  child: Column(
    children: <Widget>[
      ValueNotifierConsumer<Session>(
          valueNotifier: (session) => session.currentUser,
          builder: (context, currentUser) => UserInfo(user: currentUser),
      ),
      ValueNotifierConsumer<Session>(
        valueNotifier: (session) => session.currentWorkplace
        builder: (context, currentWorkplace) => WorkplaceInfo(user: currentWorkplace),
      ),
    ],
  )
)
````

**Comment by scopendo** [comment]
I've suggested using ValueNotifier's instead, though I guess they could be any Listenable.

**Comment by rrousselGit** [comment]
Hello!
I do not want to have multiple kind of consumers. `Provider.of` should be the only way of reading a value. Even `Consumer` uses `Provider.of`.


Instead of a `ChangeNotifierConsumer`, a `ChangeNotifierProxyProvider` is usually enough.

Instead of:

```dart
ChangeNotifierConsumer<Foo, Bar>(
  value: (_, foo) => foo.bar,
  builder: (_, bar) => Something(bar),
)
```

we can have:

```dart
ChangeNotifierProxyProvider<Foo, Bar>(
  builder: (_, foo, __) => foo.bar,
  child: const Something(), // obtains `Bar` through `Provider.of<Bar>(context)`
)
```

**Comment by scopendo** [comment]
Sorry Remi, I have just realised that I can actually do exactly this already, just by using ValueNotifier within the provider and ValueListenableBuilder, which is even simpler.

````
class Session {
  static Session of(BuildContext context) {
    return Provider.of<Session>(context, listen: false);
  }

  final ValueNotifier<User> currentUser = ValueNotifier(null);
  final ValueNotifier<Workplace> currentWorkplace = ValueNotifier(null);
}

Provider<Session>(
  builder: (context) => Session(),
  child: Column(
    children: <Widget>[
      ValueListenableBuilder<User>(
          valueListenable: Session.of(context).currentUser,
          builder: (context, currentUser, _) => UserInfo(user: currentUser),
      ),
      ValueListenableBuilder<Workplace>(
          valueListenable: Session.of(context).currentWorkplace,
          builder: (context, currentUser, _) => WorkplaceInfo(workplace: currentWorkplace),
      ),
    ],
  ),
)
````

**Comment by sreeramu** [comment]
> Hello!
> I do not want to have multiple kind of consumers. `Provider.of` should be the only way of reading a value. Even `Consumer` uses `Provider.of`.
> 
> Instead of a `ChangeNotifierConsumer`, a `ChangeNotifierProxyProvider` is usually enough.
> 
> Instead of:
> 
> ```dart
> ChangeNotifierConsumer<Foo, Bar>(
>   value: (_, foo) => foo.bar,
>   builder: (_, bar) => Something(bar),
> )
> ```
> 
> we can have:
> 
> ```dart
> ChangeNotifierProxyProvider<Foo, Bar>(
>   builder: (_, foo, __) => foo.bar,
>   child: const Something(), // obtains `Bar` through `Provider.of<Bar>(context)`
> )
> ```

@rrousselGit if we use like this foo.bar will be disposed after used widget is disposed, so we can't user foo.bar again when we construct the widget again, so is there is any other option avoid  dispose of foo.bar

**Comment by rrousselGit** [comment]
Indeed.

Instead  of using ChnageNotifierProxyProvixer, you can have a Consumer into ChangeNotifierProvider.value

**Comment by sreeramu** [comment]
> Indeed.
> 
> Instead of using ChnageNotifierProxyProvixer, you can have a Consumer into ChangeNotifierProvider.value

But use case which scopendo hand mentioned can be achieved using ChangeNotifierProxyProvider , if we just use Consumer we may not be able to achieve this, can you provide simple example for achieving this use case.?
