### ISSUE TITLE
Multiple state updates with change notifier.

### ISSUE THREAD

**Issue by SbSaiSantosh** [rrousselGit/provider#145]
-----main.dart-------

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'user.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [ChangeNotifierProvider<User>.value(value: User())],
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[],
          ),
        ),
      ),
    );
  }
}

-------user.dart-----------

import 'package:flutter/foundation.dart';

class User with ChangeNotifier {
  User() {
    print('Constructor');
  }
}

-----Console output -----

flutter: Constructor
flutter: Constructor

When i run the app  , constructor of user model is called twice . is this the normal behaviour or have i implemented something wrong. The issue being when i am navigating from splash to login, it navigates twice from splash to login as the state updates.

**Comment by peekpt** [comment]
You can't use Multiprovider inside build method, you need to use it on the widget three right after a child or body

**Comment by rrousselGit** [comment]
Don't:

```dart
ChangeNotifierProvider.value(value: User())
```

Do:

```dart
ChangeNotifierProvider(builder: () => User())
```

**Comment by JarvanMo** [comment]
I got the same problem too.Would you mind explain the diffrence be
