### ISSUE TITLE
Does all child widgets get rebuild for ChangeNotifierProvider?

### ISSUE THREAD

**Issue by PandaGeek1024** [rrousselGit/provider#146]
Hi, Im really new to provider. I just want to clarify something.

In the case of ChangeNotifierProvider(maybe the same for listenableProvider?), when the notifier calls notifyListener, does all the child widgets under the provider gets rebuild or simply just those widgets who use Provider.of or Consumer in its build method? 

The doc is a bit confusing to me. It seems like it is saying only widgets that depend on the notifier gets rebuild. But in my test code, it seems like when notifyListener is called, all child widgets of Provider is rebuild. Im really confusing about this or maybe I got something wrong. Thanks in advance for any help.

**Comment by rrousselGit** [comment]
Only the widgets that do a `Provider.of(context)` where `listen` != true are updated (which includes `Consumer`).

If in your app, more then that is updated, then it is not because of `provider` but something else that you did (like `setState` for example).

**Comment by szerner** [comment]
> Only the widgets that do a `Provider.of(context)` where `listen` != true are updated (which includes `Consumer`).

Shouldn't it say "... where `listen` != **false** are updated ..."?

**Comment by rrousselGit** [comment]
Right, my mistake
