### ISSUE TITLE
ValueNotifier  disposed

### ISSUE THREAD

**Issue by jasonlaw** [rrousselGit/provider#147]
Hi,

I have a ValueNotifier in my class to monitoring the async progress:
ValueNotifier<bool> asyncInProgressNotifier = ValueNotifier<bool>(false);

In the class dispose method I will dispose the notifier:
asyncInProgressNotifier.dispose();

I am using ValueListenableProvider to listen to the changes:
 @override
  Widget build(BuildContext context) {
    return ValueListenableProvider<bool>.value(
        value: bloc.asyncInProgressNotifier,
        child: Consumer<bool>(
          builder: (context, inAsyncCall, _) => ModalProgressHUD(
              inAsyncCall: inAsyncCall, opacity: 0.0, child: child),
        ));
  }

Problem:
When I switch to other page, I will get an error:
A ValueNotifier<bool> was used after being disposed.
I/flutter (31064): Once you have called dispose() on a ValueNotifier<bool>, it can no longer be used

Understood that the provider will try to dispose the notifier when necessary, however, in my case, how do I dispose the notifier manually if it is not being consume by the provider? I have no way to check if it is being disposed or not. Or, am I doing the wrong way? Please advice.

Thanks in advance.

**Comment by rrousselGit** [comment]
This looks unrelated to `provider`. 

When using `ValueListenableProvider.value`, `provider` will not dispose your `ValueNotifier`. So that's a bug on your end
