### ISSUE TITLE
The builder of ChangeNotifierProxyProvider is recalled when pushing a new route 

### ISSUE THREAD

**Issue by letsar** [rrousselGit/provider#150]
Hi !

I started to use the `*ProxyProvider` classes in order to create `ChangeNotifiers` that depend on others, but I have an issue with `ChangeNotifierProxyProvider`.
The `builder` is called after I push a new route. Therefore my `ChangeNotifier` is recreated and the previous value is deleted.

This is how you can reproduce this issue:
```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class Repository {
  Future<String> getData() => Future.value('From Repo');
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider(
      builder: (_) => Repository(),
      child: MaterialApp(
        home: View(),
      ),
    );
  }
}

class ViewModel extends ChangeNotifier {
  ViewModel(this.repository);
  final Repository repository;

  String _data = 'No data';
  String get data => _data;
  set data(String value) {
    _data = value;
    notifyListeners();
  }

  Future<void> loadData() async => data = await repository.getData();
}

class View extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProxyProvider<Repository, ViewModel>(
      builder: (_, repo, __) => ViewModel(repo),
      child: Scaffold(
        body: Consumer<ViewModel>(
          builder: (context, viewModel, child) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  RaisedButton(
                    child: Text('Load data'),
                    onPressed: () => viewModel.loadData(),
                  ),
                  Text(viewModel.data),
                  RaisedButton(
                    child: Text('Navigate'),
                    onPressed: () => Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => OtherView(),
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}

class OtherView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
    );
  }
}
```

If you click on **Load data**, the text below changes to **From Repo**, then you can click on **Navigate**. After you go back to the screen, the text came back to **No data**, because the `ViewModel` was recreated.  I expected my first `ViewModel` to be alive when going back to the screen as it is the case if I use `ChangeNotifierProvider` and if `ViewModel` doesn't depend on `Repository`.

Is it a bug or did I misused the `ChangeNotifierProxyProvider`?

**Comment by rrousselGit** [comment]
You'll instead want something similar to:

```dart
ChangeNotifierProxyProvider<Repository, ViewModel>(
  initialBuilder: (_) => ViewModel(),
  builder: (_, repository, viewModel) => viewModel
    ..repository = repository,
  child: ...
)
```

**Comment by soleverlee** [comment]
@rrousselGit so that means we also cannot use constructor injection on ViewModel class because it has to call a default constructor?

```
class ViewModel extends ChangeNotifier {
  ViewModel(): repository=null;
  Repository repository;
 // ...
}
```

**Comment by rrousselGit** [comment]
@soleverlee I don't understand what you mean by that.
But the code you gave is perfectly valid.

**Comment by soleverlee** [comment]
@rrousselGit I mean in order to create the `ViewModel` when we use `initialBuilder`, then we cannot put `repository` in the constructor since we don't have such a dependency at that time, and also we could not mark it as `final` even it should never be changed after initialized~ thanks for your answer, I now believe that I'm doing in a right way.

**Comment by rrousselGit** [comment]
Well, if it **never** change, you can do:

```dart
initialBuilder: (context) {
  return MyModel(Provider.of<MyRepo>(context, listen: false));
}
```

The point is to make it explicit

**Comment by soleverlee** [comment]
oh yeah, that make sense:p

**Comment by biklas7** [comment]
So there's no benefit in using the `ChangeNotifierProxyProvider` in this case right? You can simply use the `ChangeNotifierProvider` and in the builder, you can inject your repository using `Provider.of(context, listen: false)`. Or am I wrong? :thinking:

**Comment by rrousselGit** [comment]
Right right. Although I'm thinking of merging both the proxy and non-proxy variant. They're ultimately quite similar.

**Comment by biklas7** [comment]
That would be awesome in my opinion. It's a bit harder to understand the functionality if we have several variants as we have now. Thanks :+1:

**Comment by CodeRedDev** [comment]
As I currently try to understand provider better and after looking into source and not fully understanding everything, I just want to ask for final clarity:

If `Provider<A>` was defined above another `Provider<B>` than `A` is accessible via `Provider.of<A>()` in the `builder` or now `create` block of `Provider<B>`?

**Comment by rrousselGit** [comment]
Yes, that is the case
