### ISSUE TITLE
Potential issue when creating a MultiProvider for each page

### ISSUE THREAD

**Issue by johanlantz** [rrousselGit/provider#155]
This scenario is a little bit hard to explain so please bear with me and I am more than happy to provide more details but I am stuck with this for the whole day so I need some external input.

I have a very specific use-case. I create widgets based on an input value. The "factory" function looks more or less like the below (i have added a randomized widget key to track down the problem). Each "page" has its own state represented by the InputState class.

```
static Widget getPage(String contentKey) {
    InputState inputState = InputState(contentKey);

    String kk = Random().nextInt(1000).toString();
    print('New objectect uses key $kk');
    return MultiProvider(providers: [
      ChangeNotifierProvider<InputState>(builder: (context) => inputState),
    ], child: _PageBuilder(key: Key(kk)));
  }
```

Then the page is built with something like this:
```
class __PageBuilderState extends State<__PageBuilder> {
  @override
  Widget build(BuildContext context) {
    var inputState = Provider.of<InputState>(context);
    print('building object with key ${this.widget.key}');
    return ...
      
  }
}
```

Now let me try to describe the problem.

When I create the first page, everything is perfectly fine. The debug logs look something like this:
```
I/flutter (20324): Creating new input state for firstPage  with hashCode 85617722
I/flutter (20324): New object uses key 76
I/flutter (20324): building an object with key [<'76'>]
I/flutter (20324): inputState hashcode is 85617722
```

First we see a log from the InputState constructor telling us that we have created the new InputState with hashCode 85617722. We assign this input state inside our MultiProvider and use our PageBuilder as child. All of this works just fine. The new object with id 76 correctly uses InputState 85617722,

Then I create my second page calling the getPage function above again and the accumulated output is this:
```

I/flutter (20324): Creating new input state for firstPage  with hashCode 85617722
I/flutter (20324): New object uses key 76
I/flutter (20324): building object with key [<'76'>]
I/flutter (20324): inputState hashcode is 85617722
// New output starts there for the second page
I/flutter (20324): Creating new input state for secondPage  with hashCode 610610423
I/flutter (20324): New object uses key 120
I/flutter (20324): building object with key [<'120'>]
I/flutter (20324): inputState hashcode is 85617722   //This is wrong
```

The problem is the last line here, the inputState for the second object I created with the getPage() function is using the first InputState object. The second object correctly created the new InputState object with hashCode 610610423. However when the build function is called forfor the second object (with key 120) and I use :
```
var inputState = Provider.of<InputState>(context);
```

I do not get the InputState instance with hashCode 610610423 that I expected, instead, I get the InputState with hashCode 85617722 which corresponds to the first InputState we created that was assigned to the first widget (with key 76).

Somehow we get the wrong InputState instance when doing Provider.of<InputState> for the second widget even though two unique InputState instances were created.

I hope this makes sense, happy to elaborate more if it is unclear.

**Comment by rrousselGit** [comment]
Hello,

I do not understand the issue.
Could you make a fully working example, stating what is the expected
outcome VS what is happening?

**Comment by johanlantz** [comment]
Hi, many thanks for the super quick reply. I completely understand the description was a bit hard to digest.

I have reproduced it with a minimal example here:
https://github.com/johanlantz/flutter_provider_issue

Happy to provide more input

**Comment by rrousselGit** [comment]
Instead of:

```dart
class PageBuilder {
  static Widget getPage(String contentKey) {
    InputState inputState = InputState(contentKey);

    String kk = Random().nextInt(1000).toString();
    print('New objectect uses key $kk');
    return MultiProvider(providers: [
      ChangeNotifierProvider<InputState>(builder: (context) => inputState),
    ], child: _BuilderPage(key: Key(kk)));
  }
}
```

you probably want:


```dart
class PageBuilder {
  static Widget getPage(String contentKey) {

    String kk = Random().nextInt(1000).toString();
    print('New objectect uses key $kk');
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<InputState>(key: kk, builder: (context) => InputState(contentKey)),
      ],
      child: _BuilderPage(key: Key(kk)),
    );
  }
}
```

**Comment by johanlantz** [comment]
Thank you sooo much, ping me if you ever come to Barcelona and I buy you a beer.

I am blown away. It works perfectly and I have no idea why. 

I do not want to waste your time but would you mind explaining why adding the key to the provider fixed this? Now I see that the InputState is immediately disposed of when I change the page so I guess previously it was reused or something like that?

**Comment by rrousselGit** [comment]
Yes that's it.

Overall I'd say, don't use static functions to build widgets. Make two stateless widgets: Page1 and Page2.
But keys are another solution
