### ISSUE TITLE
Acessing ChangeNotifire model to mounted value

### ISSUE THREAD

**Issue by h8hawk** [rrousselGit/provider#157]
I am using `ChangeNotifier` inherited object with `ChangeNotifierProvider`. The problem is some time `notifyListeners()` called after disposing child widget in `ChangeNotifierProvider` . 

error message log on notifyListeners
`FlutterError (A <SomeModel extends ChangeNotifire> was used after being disposed.
Once you have called dispose() on a <SomeModel>, it can no longer be used.)
` 

Problem is something like [this](https://stackoverflow.com/questions/49340116/setstate-called-after-dispose). But there is not way using `mounted` in `ChangeNotifire` Inherited class. Exception handling didn't work either. 
What is proper way to determine whether Widget used by model is disposed or not?

**Comment by rrousselGit** [comment]
You can override `dispose` to do custom work there, either to make a mounted variable, or to cancel your pending requests.

**Comment by dpedrinha** [comment]
I'm facing the same problem. If I have 3 tabs and I go from the first to the third. For some reason the `build `is being called on the second tab (doesn't happen if going from 3 to 1), followed by` dispose()`, but if it's a `ChangeNotifierProvider `it fires up the `ChangeNotifier `which fetch some data and then `notifyListeners().` Problem is that the second tab was already disposed when this happens and I'm getting this exception.

I get the workaround. I can also override the `notifyListeners()` to check for `mounted `before calling `super `to make it a little bit more robust. But wouldn't it be better if the plugin just ignored if `(_listeners == null)`? Or implement this solution itself?

> bool mounted = true;
  
  @override
  void dispose() {
    mounted = false;
    super.dispose();
  }

  @override
  void notifyListeners() {
    if (mounted) super.notifyListeners();
  }
