### ISSUE TITLE
[Question] Multiple pushed routes do not pass provider values

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/provider#158]
Hello!

I've got a parent widget that has a button. When clicked, the button pushes a material page route to the first page with a value `foo`:

```dart
// parent.dart
Navigator.push(
  context,
  MaterialPageRoute(
    builder: (BuildContext context) {
      return ChangeNotifierProvider<Foo>.value(
        value: foo,
        child: FirstPage(),
      );
    },
  ),
);
```

The `FirstPage` successfully grabs `foo` by using a consumer and displays it. `FirstPage` also has button but that leads to a SecondPage.

```dart
// first_page.dart
Navigator.push(
  context,
  MaterialPageRoute(
    builder: (context) => SecondPage(),
  ),
);
```

It's on `SecondPage` that I can't get the value of `foo` and get:

```
ProviderNotFoundError (Error: Could not find the correct Provider<Foo> above this SecondPage Widget
...
```

I think I can easily fix the error by doing another `ChangeNotifierProvider<Foo>.value` on the second push but I guess this is more of a question on why it didn't work in the first place. (Sorry if this turns out to be related to how routes work and not provider!)

**Comment by rrousselGit** [comment]
Providers are scoped to a widget tree.
And each routes are in their own widget tree.

As such, a provider inside one route is not accessible inside the other routes.

A solution is either to add it on all the necessary routes, or to move the provider to a common ancestor of all routes (above Navigator)
