### ISSUE TITLE
Using provider data to init controllers

### ISSUE THREAD

**Issue by febg11** [rrousselGit/provider#160]
Hi, this isnt really an issue I just need some help.  
I recently refactored half my app to use the provider pattern and i now have a problem. The main issue is that i need to initialise controllers in the init (e.g. a text controller to have an initial value or the list size of a tab controller)

How am i meant to init Controllers if the data i need has to come from the state in the build method.

For example.

// This must go in the build as it requires state
myTabsController = TabController(length: myState.list.length, vsync: this);

I'm initialising the controller every time it builds now... How am i meant to put this in the init but still access the state variables (as there is no context).

I've tried using the afterFirstLayout() callback from the AfterLayoutMixin library but that just causes more problems. Currently with the tab bar it flashes error as no tab initialised for the first frame and then displays properly when the afterFirstLayout is called and initialises the tab. This seems like a hacky fix

I would like to learn more about how to use this pattern properly and what would be the best solution to this problem. 

Thanks

**Comment by rrousselGit** [comment]
> // This must go in the build as it requires state
> myTabsController = TabController(length: myState.list.length, vsync: this);

Why can't you use `initState` here?

**Comment by febg11** [comment]
myState= Provider.of<MyState>(context); needs to be in the build. The myState to initialise the length is null in the init

**Comment by rrousselGit** [comment]
You can call `of` inside initState if you pass `listen: false` as parameter

**Comment by febg11** [comment]
Oh ok.. does that not need context as a param then. Also if this list changes in length does this not fire and if so is there any way of knowing so i can dispose and reinitialize the controller?

**Comment by rrousselGit** [comment]
If you need updates, then use didChangeDependencies instead of initState

**Comment by febg11** [comment]
Ok that has helped alot, however its caused recursive loop. I set a variable in the state that determines the item being viewed in the tab., which when set notifies again and rebuilds the entire tab controller. Is there anyway to check what has actually changed?

**Comment by rrousselGit** [comment]
That's kind of outside the scope of `provider`.
Consider asking that on gitter/stack-overflow

**Comment by febg11** [comment]
Ok no problem, i realise I've asked a lot of you but i have one last question more linked to the library. Is there any advantage/disadvantages with getting the providers in the initState, didChangeDependencies or build. Thank you for all your help.
