### ISSUE TITLE
repeated navigation if pushnamed used  with Provider

### ISSUE THREAD

**Issue by aakashguptaa** [rrousselGit/provider#167]
import 'package:base_application/core/auth/enums/auth_state.enum.dart';
import 'package:base_application/core/auth/services/auth.service.dart';
import 'package:base_application/core/locator.dart';
import 'package:base_application/core/routing/app_routing.dart';
import 'package:base_application/module/splash/services/splash.service.dart';
import 'package:base_application/module/splash/widgets/splash.Timer.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class SplashScreen extends StatefulWidget {

  @override
  _SplashScreenState createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  Widget build(BuildContext context) {

    final SplashService splashService = locator<SplashService>();
    final AuthService authService = Provider.of<AuthService>(context);

    splashService.checkAuthStatus(authService).then((String routeName){
      print('routerName $routeName');
      // Navigator.pushReplacementNamed(context, AppRouting.PhoneNumberLoginRoute, );
      Navigator.pushNamed(context, AppRouting.PhoneNumberLoginRoute, );
      return;
    });

    print('authState ${authService.authState}');
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          OutlineButton(
            onPressed: () async {
              await authService.signInAnonymously();
            },
            child: Text('Login'),
          ),
          OutlineButton(
            onPressed: () async {
              await authService.signOut();
            },
            child: Text('Logout'),
          ),
        ],
      ),
      body: Container(
        child: Icon(Icons.add_circle),
      ),
    );
  }

 Future<void> navigateTo(BuildContext context,String routeName) async{
  await  Navigator.pushNamed(context, routeName);
 }

 @override
  void dispose() {
    print('Splash Cleaned');
    super.dispose();
  }

}

Terminal Log:
Launching lib/main.dart on XT1804 in debug mode...
[{"event":"app.progress","params":{"appId":"b3192afe-3a1b-4ce4-8365-a323c7d67e01","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...

[{"event":"app.progress","params":{"appId":"b3192afe-3a1b-4ce4-8365-a323c7d67e01","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...

Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
[{"event":"app.progress","params":{"appId":"b3192afe-3a1b-4ce4-8365-a323c7d67e01","id":"3","progressId":null,"message":"Installing build/app/outputs/apk/app.apk..."}}]Installing build/app/outputs/apk/app.apk...

I/flutter ( 3215): Locator Called
Syncing files to device XT1804...
I/flutter ( 3215): ConnectingState.CONNECTED
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): Auth Chaged: firebaseUser
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): Data connection is available.
I/flutter ( 3215): ConnectingState.CONNECTED
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATED
I/flutter ( 3215): routerName /login
I/flutter ( 3215): authState AuthState.UNAUTHENTICATE

**Comment by rrousselGit** [comment]
You're not supposed to push routes inside `build`. 

Use `initState` or `didChangeDependencies` or `didUpdateWidget` instead.
