### ISSUE TITLE
Provider: Race condition ? 

### ISSUE THREAD

**Issue by gopalramadugu** [rrousselGit/provider#173]
I am trying a simple example. I call a rest api in the initstate method of a stateful widget using provider before calling it I update a loading flag (The flag is used to show a spinner), then I notify the listeners.  This is the problem code as soon as I call notify listeners I get below exception.   I understand the intial call might not have completed executing build method and then notify listeners is trying to rebuild. How can I prevent this or what is a way around this ?

> flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
> flutter: The following assertion was thrown while dispatching notifications for ProductsProvider:
> flutter: setState() or markNeedsBuild() called during build.
> flutter: This ListenableProvider<ProductsProvider> widget cannot be marked as needing to build because the
> flutter: framework is already in the process of building widgets.  A widget can be marked as needing to be
> flutter: built during the build phase only if one of its ancestors is currently building. This exception is
> flutter: allowed because the framework builds parent widgets before children, which means a dirty descendant
> flutter: will always be built. Otherwise, the framework might not visit this widget during this build phase.
> flutter: The widget on which setState() or markNeedsBuild() was called was:
> flutter:   ListenableProvider<ProductsProvider>

**Comment by rrousselGit** [comment]
Hello!

Github isn't exactly the place for this kind of question. 
Consider asking these on Gitter or Stackoverflow instead.
