### ISSUE TITLE
Updated provider from global funtion

### ISSUE THREAD

**Issue by bsutton** [rrousselGit/provider#174]
I think this is an enhancment request or maybe I've just missed something.

The requirement is to be able to update a provider's state from a global function.

We have an android/ios plugin that receives notifications and then calls into dart with data recieved via the notification.

The plugin essentially calls into dart via a callback to a global function.

The issue is how do we update the provider's state?

Given that the global function isn't in the widget tree the normal Provider.of method doesn't work.
To get around this problem we declare the provider at the global level in  main.dart.

```

ChangeNotifierProvider<MyState> provider;

class MyState
{
   int count;
   incCount() { count++};

}
```

We have found that if we have a global function 'notificationCallback' that we can call:

```
void notificationCallback()
{
provider.delgate.value.incCount();
}
```

However this generates a warning that 'delgate' is protected.

What I think we need is something like

```
void notificationCallback()
{
       provider.getState().incCount();
}
```

Am I on the right track?

**Comment by rrousselGit** [comment]
The whole point of provider is to stop using globals, so I don't want to encourage using them.

You shouldn't use `delegate` either. It's just an implementation detail.

You should instead modify your code such that your function isn't a global, but instead created by a descendant of your provider.

**Comment by bsutton** [comment]
The function has to be called from an iOS plugin.
The plugin takes a notification which causes iOS to launch the app and
calls a dart callback function.

The call back function has to be registered when the app is installed.

As such it can't call into an object instance method as the object won't
exist when the app is relaunched and the method is called.

Hence I need a global :(

**Comment by rrousselGit** [comment]
Do you have a more concrete exemple?

**Comment by bsutton** [comment]
Actually I worked out how to do it and no global required.

So the path is:

IOS -> dart public method ...
```
// Callback method from IOS or Android native plugin
void notificationRecieved(someValue)
{
    var pluginSource  = PluginSource();
    pluginSource.update(someValue);
}
```
We then create a factory based ChangeNotifier
```
class PluginSource extends ChangeNotifier
{ 
  static PluginSource _self = PluginSource._internal();
  String someValue;
   factory PluginSource() 
   {
     return _self;
   }
  
   PluginSource._internal();

   update(someValue)
   {
     this.someValue = someValue;
      notifyListeners();
   }
}
```


We now just need a standard Provider/Consumer

```
ChangeNotifyProvider<PluginSource>(
        child: Consumer<PluginSource>(builder: (context, pluginSource, _) {
                          return Text(pluginSource.someValue);
```

**Comment by bsutton** [comment]
Thanks for forcing me to thing about the problem :)

**Comment by bsutton** [comment]
Might be nice if this was used to document this path for others.
