### ISSUE TITLE
How to provide a value to selected named routes

### ISSUE THREAD

**Issue by basketball-ico** [rrousselGit/provider#177]
For example I have `LoginPage`(facebook, twitter, google)  and other pages like `EmailLoginPage` `EmailRegisterPage`, all this pages need `AuthenticationBloc`.

I want to create the bloc in `LoginPage` and dispose in this page,  and provide this bloc to the other pages that will pushed from this page.

* I don't want to provide this bloc like a parent of `MaterialApp`(Navigator) , because I only need this bloc in this pages,
* I don't want to pass the bloc like argument in each page, I want to use `Provider.of`
* I know how to do that with push, but I want to do this with named routes
```dart
Navigator.push(context, MaterialPageRoute(builder: (_) =>
    Provider.value(
      value: myBloc,
      child: EmailRegisterPage(),
    ),
));
```

Thank you 🤗

**Comment by UnoDeTantos** [comment]
I don't know if I understood correctly, but I think you can do that with `MaterialApp`:

```dart
MaterialApp(
  routes: {
    '/': (context) => HomePage(),
    '/login': (context) => Provider<AuthenticationBloc>(
      builder: (context) => AuthenticationBloc(),
      dispose: (context, value) => value.dispose()
      child: LoginPage(),
    ),
  }
)
```

Now you can push `EmailRegisterPage` normally inside `LoginPage`:
```dart
Navigator.push(context, MaterialPageRoute(builder: (_) => EmailRegisterPage()));
``` 

`LoginPage` and `EmailRegisterPage` (everthing pushed from `LoginPage`) can access to `AuthenticationBloc` with:
```dart
Provider.of<AuthenticationBloc>(context);
```

**Comment by basketball-ico** [comment]
@UnoDeTantos Thanks,
But I want that `LoginPage` and `EmailRegisterPage` will pushed also with named routes also.
I want to use push named ever, but i am not sure if is a good practice. when use pushNamed and when use push? 🤔🤔

Thanks

**Comment by UnoDeTantos** [comment]
```dart
MaterialApp(
  routes: {
    '/': (context) => HomePage(),
    '/login': (context) => Provider<AuthenticationBloc>(
      builder: (context) => AuthenticationBloc(),
      dispose: (context, value) => value.dispose()
      child: LoginPage(),
    ),
    '/login/register': (context) => EmailRegisterPage(),
  }
)
```

Then in `LoginPage`:
```dart
Navigator.pushNamed(context, '/login/register');
```

Anything that is pushed from `LoginPage` has access to `AuthenticationBloc`

About `pushNamed` vs `push` I'm not the best to answer that question. I'm not an expert, I have been using flutter just a few weeks 😄 (And what I am answering here may be wrong or not the best way, test it!)

**Comment by w0nderb0y** [comment]
Hi, 

I have the same question as the op and tried the solution that is suggested here but it won't work. 

`import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', routes: {
      '/': (context) => MyHomePage(),
      '/detail': (context) => Provider<ViewModel>(
            create: (context) => ViewModel(),
            child: DetailScreen(),
          ),
      '/detail/edit': (context) => EditScreen(),
    });
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: RaisedButton(
          child: Text("DetailView"),
          onPressed: () => Navigator.pushNamed(context, "/detail")),
    ));
  }
}

class DetailScreen extends StatelessWidget {
  const DetailScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: RaisedButton(
        child: Text("EditScreen"),
        onPressed: () => Navigator.pushNamed(context, "/detail/edit"),
      ),
    ));
  }
}

class EditScreen extends StatelessWidget {
  const EditScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
            child: Text("Print"),
            onPressed: () =>
                Provider.of<ViewModel>(context, listen: false).printNumber()),
      ),
    );
  }
}

class ViewModel {
  printNumber() {
    print(2);
  }
}
`

Do I have a mistake in my code?

**Comment by rrousselGit** [comment]
The original problem lies in this statement:

> I don't want to provide this bloc like a parent of MaterialApp(Navigator) , because I only need this bloc in this pages,

While I understand the feeling, the benefit is very small.
Moving the provider above `MaterialApp` will fix all your problems for a very small inconvenience.
