### ISSUE TITLE
Closing sink of streamcontroller

### ISSUE THREAD

**Issue by bramvbilsen** [rrousselGit/provider#178]
Hi!
I'm uncertain about what the best way is to close the sink of `StreamController` when used with the `StreamProvider` class.
Imagine I have a class like this:
```dart
class Mockup {
  StreamController<int> controller = StreamController();

  Mockup() {
    OtherClass.streamFromAnotherPlace.listen(() {
      // transform data
      controller.sink.add(transformedData);
    });
  }
}
```
If I'd now use the `StreamProvider.controller` to listen to the `controller` of the `Mockup` class, then how would I best close the sink?

**Comment by rrousselGit** [comment]
Which sink are you talking about? Because `controller` will automatically be closed using `StreamProvider.controller`.

**Comment by bramvbilsen** [comment]
> Which sink are you talking about? Because `controller` will automatically be closed using `StreamProvider.controller`.

Alright, that is what I thought! But, the Dart Analyzer does not now that I will use it with a `StreamProvider.controller`? So in the Mockup class, I will keep getting a warning that I need to close the sink.
Any way to prevent this from happening?

**Comment by bramvbilsen** [comment]
I actually do not need to expose the `StreamController`, I'd rather just expose the stream coming from the controller. But the same warning from the analyzer would arise.

**Comment by rrousselGit** [comment]
If you don't expose the `StreamController`, then you should write a `dispose` method on your `Mockup` class, that closes the controller.

This should make the warning disappear.

**Comment by bramvbilsen** [comment]
> If you don't expose the `StreamController`, then you should write a `dispose` method on your `Mockup` class, that closes the controller.
> 
> This should make the warning disappear.

For sure it'd make the error go away, but that dispose method won't actually be used, if I understand you correctly. This isn't a functional problem, but is redundant code.

**Comment by bramvbilsen** [comment]
Also, if I only expose the `stream` of the `StreamController`, then how will the `sink` of the controller ever get closed? The provider does not have access to it right?

**Comment by rrousselGit** [comment]
Yeah, which why I said you should make a `dispose ` method on `MockUp`.

**Comment by bramvbilsen** [comment]
I still do not see how that answers it. The `StreamProvider` does not have access to the `Mockup` class, so how would it be able to close the `sink`? The `StreamProvider` would only have access to the `Stream` and the `StreamController` if used with `.controller`.

**Comment by rrousselGit** [comment]
Provider won't automatically dispose it, yes. But you can do it yourself

**Comment by bramvbilsen** [comment]
But didn't the `controller` automatically close using `StreamProvider.controller`? 
Apologies for the long thread, just trying to not have leaks in my code 😊

**Comment by zjiekai** [comment]
I'm sorry.  What is the `StreamProvider.controller`?  I can not find it in the documents.
