### ISSUE TITLE
Trouble rebuilding a StreamProvider to update its current data

### ISSUE THREAD

**Issue by madqueendany** [rrousselGit/provider#180]
Hi, so I have a`Consumer<NotificationProvider>` and in its builder function a `StreamProvider<List<Item>>`.

Please note that the latter widget builds perfectly on its initial load.

`NotificationProvider` contains a list of notifications from Firebase Cloud Messaging, ergo when I receive a notification, I push something into the class' List<Alert>` and then call `notifyListeners()`.

Please also note that my NotificationProvider is doing a good job because I have a counter at my `AppBar` and it's updating whenever I receive one.

Now on to the meat and potato.

I'm trying to rebuild the StreamProvider whenever `NotificationProvider.addAlert()` is called. But somehow it's not working?

I also added `updateShouldNotify: (prev, next) => true,` but it didn't help one bit.

Please help. Thanks!

Here's some code to help clarify things further.

```
return Consumer<NotificationProvider>(
  builder: (context, provider, child) {
    return StreamProvider<ItemsProvider>(
      builder: (_) async* {
        ItemsProvider _itemsProvider = Provider.of<ItemsProvider>(context);
        await _itemsProvider.getItems();
        yield _itemsProvider;
      },
      child:  LeContent(),
      updateShouldNotify: (prev, next) => true,
    );
  },
);
```

**Comment by madqueendany** [comment]
I solved my own issue by having a `StreamBuilder` in a `StatefulWidget`.

I have my fetcher as a separate `Future<T>` method which will be called on `initState` and on `didUpdateWidget()`.

Next, in my `StatefulWidget` class, I require something that will be used to validate on `didUpdateWidget()`'s `oldWidget.something != widget.something`.


In my case I used the length of the `NoticeProvider.notices` which will be incremented every time my FCM configuration triggers it.

in code:

```
  @override
  void didUpdateWidget(_Body oldWidget) {
    if (oldWidget.alertLength != widget.alertLength) _fetchData();
    super.didUpdateWidget(oldWidget);
  }
```

_fetchData, will then call the api, transform the JSON, and add it to the `stream` using a `StreamController` which, in turn, update the UI.

I hope someone will be helped by this answer in the `Future`!

____


I had a similar scenario but I had to put the `StreamController` in my provider so that the widgets down the tree will be able to determine if the `streamController` `hasData` and its `connectionState`. Is this approach `Bloc`-esque? I've read documentation about the pattern but haven't really used it.

**Comment by theochampion** [comment]
@madqueendany How did you manage to "typedef" your `StreamController<T>` to `ItemsProvider` in your example?

**Comment by madqueendany** [comment]
Can you say that differently?

Are you referring to the `StreamController<ItemProvider>`?

**Comment by theochampion** [comment]
@madqueendany I was just wondering how you defined `ItemsProvider` in your example

**Comment by madqueendany** [comment]
Well it's just your ordinary `class ItemsProvider with ChangeNotifier`. In that class I have a function called `getItems` that communicates with the api to get my items.

**Comment by theochampion** [comment]
But doesn't `StreamProvider` take a `Stream<T>` not a `ChangeNotifier` ?

**Comment by madqueendany** [comment]
It can take anything. I have a StreamController of type `ItemsProvider`

```
initState() {
  StreamController<ItemsProvider> _streamController= StreamController<ItemsProvider>();
}
...
then on my builder:

StreamBuilder(
  stream: _streamController.stream,
  builder: (context, AsyncSnapshot<ItemsProvider>) {
    if (snapshot.hasData) {
      ItemsProvider _provider = snapshot.data;

      // then build your tree
    }
  }
);
```

Does this help?

**Comment by theochampion** [comment]
And is `ItemsProvider` a custom class? I've been trying to a streamProvider with the type of a custom class like this:

```dart
class MyNavEvent {}
 
class _MainScreenState extends State<MainScreen> {
  final _navController = StreamController<MyNavEvent>.broadcast();

  @override
  void dispose() {
    _navController.close();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return StreamProvider.controller(
        builder: (BuildContext context) => _navController, child: TestWidget());
  }
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: Provider.of<StreamController<MyNavEvent>>(context).stream,
      builder: (context, snapshot) {
        return Text("text");
      },
    );
  }
}
```

But this always give me this error:

```Error: Could not find the correct Provider<StreamController<NAV_EVENT>> above this TestWidget Widget```

**Comment by madqueendany** [comment]
In your `StreamProvider` builder function, add this line, this may help:

``` 
// StreamProvider implementation
  builder: (BuildContext context) => _navController, 
  child: ChangeNotifierProvider(
    builder: (_) => _navController, 
    child: TestWidget(),
  ),
);
```

**Comment by theochampion** [comment]
Isn't it was `StreamProvider.controller()` is supposed to do already, expose the provided streamcontroller to all childs?

The issue I'm facing is using `StreamProvider<T>.controller()` with `T` being a custom class.

I created an issue for this here ;) https://github.com/rrousselGit/provider/issues/206

**Comment by madqueendany** [comment]
> Isn't it was StreamProvider.controller() is supposed to do already, expose the provided streamcontroller to all childs?

Hmm, I never found this to be the case. Whenever I use a StreamProvider I always have a Consumer below it. Like for example:

``` 
StreamProvider(
)

**Comment by rrousselGit** [comment]
StreamProvider.controller to not expose the StreamController.

It rarely make sense anyway, since we can't subclass StreamController easily. So we can't use it as a ChangeNotifier alternative

**Comment by theochampion** [comment]
@rrousselGit So the only way to access the `sink` of a stream is to expose a normal `Provider`?

**Comment by rrousselGit** [comment]
You can't do it with `StreamController` only, but you can use two providers together:

```dart
Provider(
  builder: (_) => StreamController<int>(),
  child: Consumer<StreamController<int>>(
    builder: (_, controller, __) =>
      StreamProvider.controller(
        builder: (_) => controller,
        child: <some child>,
      ),
  ),
)
```

**Comment by rrousselGit** [comment]
This previous snippet allow you to do: `Provider.of<StreamController<int>>(context)`
