### ISSUE TITLE
Providing a listenable from a future of listenable.

### ISSUE THREAD

**Issue by TannerYoung** [rrousselGit/provider#184]
I have a function which returns a Future<ValueListenable<T>> and want to access T via a consumer.

I've tried combining providers with FutureProvider, ProxyProvider<ValueListenable<T>> and ListenableProxyProvider but they don't seem to work.

Is this something which would require a dedicated FutureListenableProvider or could I acheive it with the existing ones?

**Comment by rrousselGit** [comment]
What do you want to access via Consumer?
The Future? The ValueListenable? Or the value of the ValueListenable?

**Comment by TannerYoung** [comment]
Apologies, it appears I mis-formatted my original post.

The value of the ValueListenable

**Comment by rrousselGit** [comment]
You can do FutureBuilder > ValueListenableBuilder > Provider.value
