### ISSUE TITLE
The versioning numbers are wrong

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#186]
`+1` after the version should only be used for pre-1.0.0 builds, so 3.0.0+1 shouldn't exist.

**Comment by uuttff8** [comment]
https://pub.dev/packages/sqflite really? sqlite have 1.1.6+3 version

**Comment by feinstein** [comment]
Also wrong.

**Comment by feinstein** [comment]
See more [here](https://dart.dev/tools/pub/version ING):

>Although semantic versioning doesn’t promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to **0.1.2+1 indicates a change that doesn’t affect the public API**.

**Comment by rrousselGit** [comment]
It doesn't matter.
The change was like explained by the doc : no impact on the public API.

**Comment by feinstein** [comment]
Yes, but this is only valid for pre-1.0.0.0, as the + has the build number, not something we expose after a release version.

**Comment by rrousselGit** [comment]
If this was valid only for <1.0.0, then the tooling would prevent it.

It's useful to differentiate between actual change in the code, and change in the documentation/readme.

**Comment by feinstein** [comment]
The tooling does prevent it, see the Travis check for the plugins repo.

**Comment by rrousselGit** [comment]
Do you have a link?
Because if the tooling prevented it, then this discussion wouldn't exist.

It really doesn't matter anyway.

**Comment by feinstein** [comment]
I think this is it, I got the error myself so I am sure it checks, just not sure that's the code that Travis uses. 


https://github.com/flutter/plugin_tools/blob/384d8ad7fcf41837be741ff8039fec9f05d944d5/lib/src/version_check_command.dart#L54-L85

**Comment by rrousselGit** [comment]
It's specific to their repository/ci.
