### ISSUE TITLE
Initializing ChangeNotifierProviders that depend on Futures more explicitly

### ISSUE THREAD

**Issue by MrMonotone** [rrousselGit/provider#189]
I have noticed that I have a large portion of my notifiers doing something like this:
```
class AsyncInitialize with ChangeNotifier {
int _value = 0;
int get value = _value;

  AsyncInitialize() {
    _loadAsyncThing();
  }

  Future<void> _loadAsyncThing() async {
    var asyncValue = await doAsyncThing();
    _value = asyncValue;
    notifyListeners();
  }
}
```
Is there someway that I could write this more explicitly? Is there someway that I could create a ChangeNotifierProxy that uses a future to seed its data without having to expose it to all of the widgets? You mentioned before that Consumer and FutureProvider.value can be used to expose a future. But I do not care about the result of that future after it seeds my changenotifier.

For example, lets say I have a shopping cart. I want to expose a ChangeNotifier that represents the list of shopping items. I have the list of shopping items saved in a database. I either need to do what I did above or create a consumer, FutureProvider.value, and a wrapper class so that a ProxyChangeNotifier can take the provider value and pass it to my changenotifier.

This seems like a pretty often used pattern. I do not know if it is in scope of this library but I would like a more explicit way to write this. Perhaps this would involve me writing my provider or there might already be functionality for this?

**Comment by rrousselGit** [comment]
If I understand correctly, you want a `ChangeNotifierProvider` where `builder` returns a `Future<ChangeNotifier>`?

**Comment by MrMonotone** [comment]
Maybe? I would like to write something like this.
```
        ChangeNotifierFutureProvider<AsyncAssetNotifier>(
          initialData: 0,
          future: Future.value(1),
          builder: (BuildContext context, int value, PortfolioAssetNotifier previous) {
            return AsyncAssetNotifier(value);
          },
        ),
```
So the change notifier would initally render with 0 as the value. it would then call change listeners when the future completed. I think there is probably some combination of functionality I can use. I am just not sure about what to compose with where. I do not want to crowd the provider type space.

**Comment by rrousselGit** [comment]
What about subclassing `ValueNotifier`?

```dart
abstract class AsyncNotifier<T> extends ValueNotifier<T>(
  AsyncNotifier(T initialData) : super(initialData) {
    loadAsync().then((v) => value = v);
  } 

  Future<T> loadAsync;
)
```

**Comment by rrousselGit** [comment]
The syntax you suggested will not work as you'd expect.
This would recreate the `ChangeNotifier`, which means it'd kill its state, if any.

Your best bet is to make a custom ChangeNotifier and/or a custom Provider adapted to your use-case. 

Fortunately, `provider` exposes everything needed to make your own provider.

**Comment by MrMonotone** [comment]
I was trying to avoid putting executing statements in a constructor. Is there anyway around it or is that just the way it has to be if I want that behaviour?

**Comment by rrousselGit** [comment]
You cannot avoid it.
But you can make an abstract class that does the job, and reuse that.

**Comment by MrMonotone** [comment]
Well thanks for your input. For others I decided to go with Remi's solution. For reference:
```
abstract class AsyncNotifier<T> extends ValueNotifier<T>{
  Future<T> get loadAsync;
  AsyncNotifier(T initialData) : super(initialData) {
    loadAsync.then((v) => value = v);
  } 
}

abstract class RepositoryNotifier<T> extends AsyncNotifier<T>{
  final AppRepository repository;
  RepositoryNotifier({AppRepository repository, T initialData}) : repository = repository, super(initialData);
}
```

**Comment by bt1159** [comment]
I know I'm very late here, but I am trying to follow along despite being very new to flutter.  Can someone explain whether @MrMonotone had a type in the above comment.  On line 4, he has:
`loadAsync.then((v) => value = v);`

Shouldn't it say:
`loadAsync().then((v) => value = v);`

?  I think I am following along, but just barely.  This answer would help me a lot.  Thanks!
