### ISSUE TITLE
Add documentation on using Provider inside initState()

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#190]
I was initializing a variable inside `initState()` and so I used `Provider` to inject a dependency, but then I got an Exception explaining that `inheritFromWidgetOfExactType(InheritedProvider<T>)` or `inheritFromElement()` can't be called before `initState()` completed.

This error exposes the inner workings of `Provider` and the docs here should explain that this shouldn't be done and a recommendation on how to proceed (or even better, throw an exception inside `Provider` with a message explaining how to fix this and why it's an error).

**Comment by madqueendany** [comment]
Yeah I encountered this behavior as well.

I worked around it by passing the provider to a stateful widget and accessing it on the `initState` via 

```
  dynamic myData = widget.myProvider.myData;
```

I'm curious to see your approach.
