### ISSUE TITLE
How to update FutureProvider?

### ISSUE THREAD

**Issue by PandaGeek1024** [rrousselGit/provider#194]
Im trying to use FutureProvider to wait for the result of a permission check. Everything seems fine for the first time. But I have this requirement to recheck the permission every time when I comes back from background (by call setState() in didChangeAppLifecycleState), but FutureProvider does nothing because builder only get called once.

How do I update the future so FutureProvider can provide the latest permission status? Thanks.

**Comment by Drakirus** [comment]
I'm having the same question.
In case of failure (for example), how do we re-call the future?

**Comment by madqueendany** [comment]
I don't think you can re-call a Future, let alone a FutureProvider, unless you setup your widget as a `StreamBuilder` that can accept a continuous stream (pun intended) of data.

I'd also use `StatefulWidget`'s function `didUpdateWidget` to check if my data has changed since some moments ago.

```
if (old.widget.myData != widget.myData) _getData()
```

**Comment by rrousselGit** [comment]
As stated by @madqueendany, you'll want to use StreamProvider instead.

**Comment by xujim** [comment]
how to use stream provider for updating the data source? could you add a specific example? Thanks

**Comment by uldall** [comment]
I am also interested in an example.
