### ISSUE TITLE
[Selector] about Selector,can Selector merge with Consumer?

### ISSUE THREAD

**Issue by fantasy525** [rrousselGit/provider#196]
Cousumer is useful but it can't  ignore changes.so can  add a parameter slector to the Consumer?
if so. Selector is redundant.All we need is Consumer.
like this:
```
Comsumer(
 selector: (_, list) => list.length,
builder: (_, a, child) {
      return Bar(a: a, child: child);
    },
    child: Baz(),
)
```

**Comment by rrousselGit** [comment]
It's not feasible due to language limitations.

The current version of Consumer has only one generic parameter:

```dart
Consumer<Foo>()
```

While Selector needs two:
```dart
Selector<Foo, Selected>() 
```

**Comment by fantasy525** [comment]
@rrousselGit  I have read this issue #169 , and I am very interested in it.
I like this:
```
Consumer<Foo>(
  shouldRebuild: (prev, current) => prev.value != current.value,
  builder: (_, Foo foo, __) => Text(foo.value),
)
```
