### ISSUE TITLE
Error: Could not find the correct Provider<StateRastram > above this Consumer<StateRastram > Widget

### ISSUE THREAD

**Issue by harifutures** [rrousselGit/provider#200]
@override
  Widget build(BuildContext context) {
    //return ChangeNotifierProvider (
    return MultiProvider (
      providers: [
        ChangeNotifierProvider.value(
          value: StatesProvider(),
        ),
       
      ],
      child: MaterialApp(
        title: 'Paripalan',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: NavigationPage(),
      )
    );
  }
====================
And using in one of the screens inside form dropdowns like below. 
Note: StateRastram class is just model class not a provider class but injecting some data to this model through constructor from provider.

final stateRastarmList = Provider.of<StatesProvider>(context);
final statesRastram = stateRastarmList.stateRastramList;

child: Form (
          child: ListView (
            children: <Widget>[
              Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: <Widget>[
                  Consumer<StateRastram> (
                    builder: (context, stateRastram, _) => FormField(
                      builder: (FormFieldState state) {
                        return InputDecorator(
                          decoration: InputDecoration(
                            icon: const Icon(Icons.color_lens),
                            labelText: 'State',
                          ),
                          child:  new DropdownButtonHideUnderline(
                            child: DropdownButton<StateRastram> (
                              items: statesRastram.map((StateRastram value) {
                                 return new DropdownMenuItem(
                                   value: value,
                                   child: new Text(value.stateName),
                                 );
                               }).toList(),

                              value: _stateRastram,
                              isDense: true,
                              onChanged: (StateRastram newValue) {
                                setState(() {
                                  //newContact.favoriteColor = newValue;
                                  _stateRastram = newValue;
                                  state.didChange(newValue);
                                });
                              }

                            ),
                          ),
                        );
                      }

                    ),

                  )

**Comment by hamidafghan** [comment]
I had the same error, then I wrapped the ``` scofald ``` with ``` ChangeNotifierProvider ```. See the code snippet bellow. 

``` return ChangeNotifierProvider(
      builder: (context) => TodosModel(),
      child: Scaffold(
      appBar: AppBar(
          title: Text('Todos'),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () {},
            ),
          ],
          bottom: TabBar(
            controller: controller,
            tabs: <Widget>[
              Tab(text: 'All'),
              Tab(text: 'Incomplete'),
              Tab(text: 'Complete'),
            ],
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: <Widget>[
            AllTasks(),
            IncompletedTasks(),
            CompletedTasks(),
          ],
        ),
      ),
    );
```

**Comment by hamidafghan** [comment]
I had the same error and I solve by wrapping the ``` Scaffold ``` with ``` ChangeNotifierProvider ```. See the below code snippet. 

``` 
return ChangeNotifierProvider(
      builder: (context) => TodosModel(),
      child: Scaffold(
      appBar: AppBar(
          title: Text('Todos'),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () {},
            ),
          ],
          bottom: TabBar(
            controller: controller,
            tabs: <Widget>[
              Tab(text: 'All'),
              Tab(text: 'Incomplete'),
              Tab(text: 'Complete'),
            ],
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: <Widget>[
            AllTasks(),
            IncompletedTasks(),
            CompletedTasks(),
          ],
        ),
      ),
    );
```

**Comment by harifutures** [comment]
Thanks hamidafghan, It was already wrapped around scaffold.

return Scaffold(
      appBar: AppBar(
        title: Text('Complaints Form')
      ),

      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form (
          child: ListView (
            children: <Widget>[
              Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: <Widget>[
                  Consumer<StateRastram> (
                    builder: (ctx, stateRastram, _) => FormField(
                      builder: (FormFieldState state) {
                        return Container(
                          // decoration: InputDecoration(
                          //   icon: const Icon(Icons.color_lens),
                          //   labelText: 'State',
                          // ),
                          child:  new DropdownButtonHideUnderline(
                            child: DropdownButton<StateRastram> (
                              hint: new Text("Select State"),
                              items: statesRastram.map((StateRastram value) {
                                 return new DropdownMenuItem(
                                   value: value,
                                   child: new Text(value.stateName),
                                 );
                               }).toList(),

                              value: _stateRastram,
                              isDense: true,
                              onChanged: (StateRastram newValue) {
                                _stateRastram = newValue;
                                setState(() =>                                   //newContact.favoriteColor = newValue;
                                  _stateRastram = newValue
                                 // state.didChange(newValue);
                                );
                              }

                            ),
                          ),
                        );
                      }

                    ),

                  )

==================
I extended Model class with ChangeNotifier and included in Main.dart  along with provider.
But i dont know is it an efficient way. Is there a better way?

return MultiProvider (

     // builder: (context) => Departments(),
      //builder: (context) => StatesProvider(),
      providers: [
        ChangeNotifierProvider.value(
          value: StatesProvider(),
        ),
ChangeNotifierProvider.value(
          value: StateRastram(),
        ),
])

**Comment by rrousselGit** [comment]
Hello!

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
