### ISSUE TITLE
How to Integrate flutter DropDown with consumer provider?

### ISSUE THREAD

**Issue by harifutures** [rrousselGit/provider#201]
Tried many ways to understand integrating DropDowns with Consumer Provider object. I could not set onchange value with out statefulwidget.
Please suggest.

**Comment by madqueendany** [comment]
```
class MyProvider with ChangeNotifier {
  List<String> _items = [
    // my items
  ];

  List<String> get items => _items;

  void setSelectedItem(String s) {
  }
}

**Comment by rrousselGit** [comment]
Hello!

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
