### ISSUE TITLE
How to avoid unnecessary rebuilds

### ISSUE THREAD

**Issue by muhammadwfa** [rrousselGit/provider#202]
I am using **[provider][1]** in my app, but I faced with unnecessary building.

Example

```
class AllWidget extends StatelessWidget{

  @override
  Widget build(BuildContext context){
    print('state build called');
    return ChangeNotifierProvider(
            builder: (_) => MyCounter(),
            child: Column(children: <Widget>[
                  MyCounterText(),
                  SizedBox(height: 10),
                  MyIncreaseButton(),
                  SizedBox(height: 10),
                  MyDecreaseButton(),
            ],
            mainAxisAlignment: MainAxisAlignment.center,
          ),
    );
  }
}

class MyCounterText extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    final myCounter = Provider.of<MyCounter>(context);
    print('MyCounterText');
    return Text(myCounter.num.toString());

  }
}

class MyIncreaseButton extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    final myCounter = Provider.of<MyCounter>(context);
    print('MyIncreaseButton');
    return RaisedButton(
      child: Text('Increase +'),
      onPressed: ()=> myCounter.increament(),
    );

  }
}


class MyDecreaseButton extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    final myCounter = Provider.of<MyCounter>(context);
    print('MyDecreaseButton');
    return RaisedButton(
      child: Text('Decrease -'),
      onPressed: ()=> myCounter.decreament(),
    );

  }
}
```

Now if I click on `MyIncreaseButton` widget, to inscrease the value, the `MyDecreaseButton` widget builds too, even when I dont click on it.

And vice versa, if I click on `MyDecreaseButton` widget, to descrease the value, the `MyIncreaseButton` widget builds too, even when I dont click on it.

My Expectation is:

**When clicking `MyIncreaseButton` widget, `MyDecreaseButton` widget should not build.**

  [1]: https://pub.dev/packages/provider

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/provider#my-widget-rebuilds-too-often-what-can-i-do

**Comment by muhammadwfa** [comment]
Thank you @rrousselGit,  It looks a little hard to me can you please show that solution with my above code?

**Comment by fantasy525** [comment]
@muhammadwfa this can help you [should_rebuild](https://github.com/fantasy525/should_rebuild)

**Comment by muhammadwfa** [comment]
@fantasy525 
Thank you, I will try and let you

**Comment by rrousselGit** [comment]
> Thank you @rrousselGit, It looks a little hard to me can you please show that solution with my above code?

What don't you understand there?

**Comment by fantasy525** [comment]
@rrousselGit why you reacted with thumbs downn emoj?

**Comment by rrousselGit** [comment]
That's built-in `provider`. There's no reason to use a 3rd party package.

**Comment by fantasy525** [comment]
@rrousselGit  Your provider package is great . but why do you think we have no reason to use a  third party package . I don't think there's any connection between them , their role is different . the provider is mainly used for state management , ShouldRebuild is just a Widget , It's just to determine whether you need rebuild widgets or not  . You should not restrict us to using your Provider for everything

**Comment by rrousselGit** [comment]
We're on provider repository here, and the problem described is something that provider tries to solve (Selector)

The answer should not be to use a 3rd party package. The issue should be used to determine what is lacking in the documentation/library to then improve provider.
