### ISSUE TITLE
Selector not working properly on lists.

### ISSUE THREAD

**Issue by mariogorki94** [rrousselGit/provider#205]
The Selector widget is not properly checking lists and iterables for equality. By default the selector uses the == operator which internally uses hashcode to check are two object the same. But when you remove objects from the iterable unless the internal size increases the hashcode is not changed. The proper way of checking are two iterables equal is  from the Dart foundations library

import 'package:flutter/foundation.dart';
listEquals(other.values, values)

**Comment by rrousselGit** [comment]
That's the expected behavior.
It is the developer job to use a List that has a proper `==`.

There are some implementations available on the pub, like `KList` from [kt_dart](https://pub.dev/packages/kt_dart)

**Comment by 2534290808** [comment]
Should selector add a method shouldUpdate that we can control ourselves, and if we don't implement it we'll still implement `selected! = value`, so we can control the List refresh, as follows:
```
@override
  Widget build(BuildContext context) {
    final selected = widget.selector(context);

    if (oldWidget != widget || shouldUpdate!=null ? shouldUpdate(selected,value) : selected != value ) {
//or 
      value = selected;
      oldWidget = widget;
      cache = widget.builder(
        context,
        selected,
        widget.child,
      );
    }
    return cache;
  }
```
```
Selector < < B > A, List > (
     selector (_, A) = > a. ist,
     builder: (_) = > SizedBox (),
     shouldUpdate: (newList, oldList) = > newList! = oldList | | newList length! = oldList. Length
)
```

**Comment by rrousselGit** [comment]
That's reasonable. Could you make this into a standalone issue?

**Comment by 2534290808** [comment]
ok 🆗

**Comment by rrousselGit** [comment]
As a comeback on this, I can see some arguments for having this instead of a "shouldUpdate":
`List`/`Map` are core, and it'll definitely prevent mistakes.

**Comment by rrousselGit** [comment]
This was changed
Selector deeply compares collections now.
