### ISSUE TITLE
FutureProvider docs uses non-standard language

### ISSUE THREAD

**Issue by jtlapp** [rrousselGit/provider#207]
The dartdoc for `FutureProvider` talks about futures in non-standard language. It refers to "subscribing" to and "listening" to futures. I'd never heard that language in Javascript `Promise` land, and it's not in the [Dart documentation](https://dart.dev/codelabs/async-await) for `Futures` either.

It wasn't clear to me whether `FutureProvider` provides the currently available value to the consumer or actually rebuilds the consumer when the `Future` completes. Either approach seems compatible with "subscribing" or "listening" to a `Future`; in both you get the value when it changes.

A quick test showed me that it asynchronously rebuilds the consumer when the `Future` completes. That's pretty cool, but the dartdoc could make that clear.

**Comment by jtlapp** [comment]
We might also look at creating generic language for describing all of the providers. For example, we could define "binding" as meaning tying a consumer to a change in a value. `FutureProvider` could then say it binds consumers to the value of the `Future`. The meaning of "binding" fills in the rest.

**Comment by rrousselGit** [comment]
> It wasn't clear to me whether FutureProvider provides the currently available value to the consumer or actually rebuilds the consumer when the Future completes

What's the difference?

**Comment by jtlapp** [comment]
> What's the difference?

One continues to return `initialData` until the Future completes. It's still a subscription because the value changes when the Future completes.

Even so, the "subscription" language makes more sense to me now that I finally understand how this package works.

**Comment by jtlapp** [comment]
I see now why you're using the subscription language in `FutureProvider`. You're also using it in `ListenableProvider` and `StreamProvider`. The `ChangeNotifierProvider` docs don't use this language, but `ChangeNotifierProvider` is a subclass of `ListenableProvider`.

The reason seems to be that there are two ways to source data: provide the data outright, or provide a publisher of the data. `ListenableProvider` isn't exactly a data source, but is a data publisher because it provides notices of change. Pub/sub language works for all of them.

In this case, I wasn't properly thinking of the future as the publisher; I was thinking of the provider as the publisher.

**Comment by jtlapp** [comment]
I'm closing this because I understand it now. I think my problem was just not having the right big picture for how provider works.
