### ISSUE TITLE
ChangeNotifier within field objects

### ISSUE THREAD

**Issue by febg11** [rrousselGit/provider#208]
Hi,
I have been using the provider for a while now and really like it but i have hit a problem. I have a field within my changeNotifier class (in this example ParentClass) that holds a list of objects say List<ChildClass> and within that ChildClass I have many fields. 

I want to be able to notifyListeners(); on changes in the ChildClass objects. The ChildClassimplements ChangeNotifier and I call the  notifyListeners(); when the fields are set.

The problem that this is not calling a build. 
I currently access each child using the ParentClass state, 
    parentState = Provider.of<ParentClass>(context);

parentState .THE_LIST[0].ChildClassField

Am i doing this incorrectly. I thought i may need to access the childstate using the provider.of but could not figure out a way to use the parentstate list position to get a specific object

Sorry if this is a simple problem
Thanks.

**Comment by madqueendany** [comment]
Let me get this straight, you have a `ParentClass` with ChangeNotifier, in it, a `ChildClass` (alsow with `ChangeNotifier` that's directly related to `ParentClass` and you want to be able to listen to the changes that happened in `ChildClass`? 

Also, can you share some code snippets on what you have?

**Comment by febg11** [comment]
Thanks for replying. Kind of yes. I wasnt really sure whether i needed a change notifier on the child class so I added one after it didnt work without one.

Here is an example of my first approach.

class ParentState with ChangeNotifier {
  List<ChildState> _list;

  String get list;=> _list;
}

class ChildState with ChangeNotifier {
   String _someField; 

   String get someField=> _someField;

   set someField(String newVal) {
    _someField = newVal;
    notifyListeners();
  }
}

I want to be able to display a listview of the ChildState (_list in the parent state) but be able to call methods within the child state objects .e.g. parentState.list[0].someField = "A new val" and have it reflect in the listview that there has been changes (display 'A new val').

Is there any way to call notifyListeners in the parent state from the child or is there a better approach that I am completely missing.

**Comment by madqueendany** [comment]
In my opinion, having two classes with `ChangeNotifier`s are a bit complicated. Making it simple would be better, I think.

Maybe this'll work... In your `ParentClass`, add this

```
void setChildValue(int index, dynamic value) {
  _list[index] = value;
  notifyListeners();
}
```

You want a `ListView` of `Provider.of<ParentClass>(context).list`, right? Maybe you can do

```
ListView.builder(
  itemBuilder: (context, index) {
    return ChildItem(
      onChange: (String newVal) {
        provider.setChildValue(index, newVal);
      }
    );
  }
);
```

**Comment by febg11** [comment]
I guess that would be a solution.. just seems a bit hacky and would become quite flawed if the data models were a lot more complex.. Is there definitely no better method of doing this?


My only other idea was the call the method on the child class to update a value and then call an method on the parent class that does mothing but notifyListeners(). This feels like a bad solution aswell.

**Comment by rrousselGit** [comment]
Hello! This is not directly related to `provider` (as it doesn't care about what you do with `ChangeNotifier`).

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
