### ISSUE TITLE
Deriving/providing a single value from 2 other providers

### ISSUE THREAD

**Issue by castaway** [rrousselGit/provider#211]
I'm attempting to refactor some code, so that instead of calling an update method, changes to the data just update the screen (y'know, the sane way)..

In the current case, the main screen is a map, and I have 2 ChangeNotifier classes: PointsOfInterest, and UserLocation, one generates a series of markers onto the map, the other adds a marker for the user position.. 

The extra item I need is "the single point thats closest to the user, currently", in my update-style code I have calculated it like this:

    var initialPoint = pois.points[0];
    setState(() {
        _closestPoint = pois.points.fold(initialPoint, (current, point) {
            return Distance().as(LengthUnit.Meter, newLocation, point.location) < Distance().as(LengthUnit.Meter, newLocation, current.location) ? point : current;
        });
    });

and the markers as:

    allMarkers = [
      userMarker,
      ...pois.points.where(
        (poi) => _mapController.ready ? _mapController.bounds.contains(poi.location) && !(poi.location == _closestPoint.location) : true
      ).map((poi) => poiMarker(poi, Theme.of(context).primaryColor))
      .toList(),
    ];
     if(_mapController.ready && _mapController.bounds.contains(_closestPoint.location)) {
      // print("Adding location in accentColor");
      allMarkers.add(poiMarker(_closestPoint, Theme.of(context).accentColor));
      
    }
  }

Can I generate that point using something like.. ?:

      providers: [
        ChangeNotifierProvider.value(
          value: PointsOfInterest(),
        ),
        ChangeNotifierProvider.value(
          value: UserLocation(),
        ),
        ProxyProvider2<PointsOfInterest, UserLocation, POI>(
          builder: (_, pois, userLoc, __) => pois.points.fold(
            initialPoint, (current, point) {
              return Distance().as(LengthUnit.Meter, newLocation, point.location) < Distance().as(LengthUnit.Meter, newLocation, current.location) ? point : current;
          }),
        ),
      ],

**Comment by castaway** [comment]
Hmm, how to I then catch/consume that single instance of POI?

**Comment by castaway** [comment]
`final closestPoint = Provider.of<POI>(context)` ?

**Comment by rrousselGit** [comment]
Hello!

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
