### ISSUE TITLE
Consider re-initializing delegate based on more than runtimeType (_DelegateWidgetState)

### ISSUE THREAD

**Issue by shyndman** [rrousselGit/provider#212]
Hello,

We ran into a problem where a `Provider.builder`'s widget was being recreated with a new builder, but that wasn't enough to trigger a change notification, or even change the `Provider`'s value. Tracing through the code, it looks like the `BuilderStateDelegate` is being replaced successfully in `_DelegateWidgetState`, but after a `runtimeType` check, the new builder assumes the old builder's value rather than building its own.

It sort of threw us for a loop. On the trickier side to debug, because we weren't sure where the stale value was coming from.

Might it be better to ask the delegate whether it should be re-initialized?

**Comment by rrousselGit** [comment]
Do you mind sharing an example of such situation, and your suggestions on how to call builder again? 

Because the current `builder` is explicitly called only once.

**Comment by shyndman** [comment]
Yeah, it's a little tricky. A reference check I guess? I realize this would be a breaking change, and has its own set of issues. 

We decided to wrap provider creation in a keyed stateful object, which is re-created entirely when we need it to. Closing this off unless you think it has value.

**Comment by rrousselGit** [comment]
Do you mind sharing a snippet of your approach?

**Comment by shyndman** [comment]
Sure. Here's the buggy version:
https://gist.github.com/shyndman/0f2cf5f9d12d7128809877b65ffca2cd

And the new version, without `Provider.builder`, and now relying on state lifecycle for disposal:
https://gist.github.com/shyndman/467e81617463c2c39b22d8a879c685b1

**Comment by shyndman** [comment]
We could have keyed the Provider.builder as an alternative, but we thought this was clearer.

**Comment by rrousselGit** [comment]
What you're saying is, you want a value that can change over time, but where the previous value is disposed when it changes?

**Comment by shyndman** [comment]
That's correct.

**Comment by rrousselGit** [comment]
That's something I've been considering for a *long* time.
I'd love to, but I have yet to find a solution that is flexible while type safe and mistake free.

Otherwise, there are some interesting approaches like the one taken by state_rebuilder
