### ISSUE TITLE
Getting subscription to the stream

### ISSUE THREAD

**Issue by shashikantdurge** [rrousselGit/provider#215]
How to get subscription to the stream provided in the StreamProvider?
So that we can pause and resume it whenever we want.

**Comment by rrousselGit** [comment]
It's not public. Why do you need it?

**Comment by shashikantdurge** [comment]
Provided Stream is created by me, I want it to pause producing events and
resume back in different situations.

In detail, I've implemented chat feature, where initially I'm getting *n *
messages from firestore. And on scroll I'm getting *m* messages into the
stream.
When m messages are loaded, I want it to pause, and resume it when the
scroll reaches top again.

**Comment by rrousselGit** [comment]
Instead of pausing the subscription, what about not emitting values?

**Comment by shashikantdurge** [comment]
I wanted the logic to be inside onPause, onResume, onListen & onCancel of the stream controller.

Anyway I have to work on other ways. 

Is there by any chance it's made public?

**Comment by rrousselGit** [comment]
It's not. In fact provider don't even have it right now, since it uses StreamBuilder

**Comment by shashikantdurge** [comment]
Thank you for your quick response.

I'll try working on not emitting events.
