### ISSUE TITLE
inject without BuildContext

### ISSUE THREAD

**Issue by soleverlee** [rrousselGit/provider#218]
Hi,
I want to do some initialization before I run the app, 
```java
void main() async {
  // call InitializeService here
  runApp(AppEntry(
    hasInitialized: true,
  ));
}
```
and this InitializeService depend on Sqlite Database, I'd like to get this from provider, however in there no build context is available. Is there any way to get a service without BuildContext, or I should not do like this?

Thanks:p

**Comment by jtlapp** [comment]
I was going to suggest moving the initialization to inside the app so you can properly dispose of the DB, but then I found [this issue](https://github.com/flutter/flutter/issues/28879), where `dispose()` isn't being called at the end of the app; or if it is being called, it's not waiting for a future to complete. [This comment](https://github.com/flutter/flutter/issues/28879#issuecomment-496020083) suggests the problem only occurs if the top widget is stateful.

**Comment by rrousselGit** [comment]
@soleverlee Why not call `InitializeService` in the constructor of your service?

**Comment by soleverlee** [comment]
Hi @jtlapp @rrousselGit thanks for your suggestion, I ended up using the following way: create the initService before put it into the providers. I'm not sure if it's a good way, but at least it works for my purpose.

I need to use this service before I run app to decide the route, that's the reason why I could not use it inside the constructor or somewhere.  Here is part of the code:

```dart
void main() async {
  final database =
      await SqliteFactory.createInstance("data.db", "assets/config/init.sql");
  final HeaderRepository headerRepository = SqliteHeaderRepository(database);
  final InitService initService = InitService(headerRepository);
  final bool hasInitialized = await initService.hasInitialized();

  final List<SingleChildCloneableWidget> providers = [
    // _independentServices,
    Provider.value(value: database),
    Provider.value(value: headerRepository),
    // _dependentServices,
    ProxyProvider<Database, SqliteItemRepository>(
      builder: (context, database, itemRepository) =>
          SqliteItemRepository(database),
    ),

    // _states
    ChangeNotifierProvider(builder: (context) => LoginViewModel()),
  ];

  runApp(AppEntry(
    providers: providers,
    hasInitialized: hasInitialized,
  ));
}

class AppEntry extends StatelessWidget {
  final bool hasInitialized;
  final List<SingleChildCloneableWidget> providers;

  const AppEntry({Key key, @required this.providers, this.hasInitialized})
      : super(key: key);


  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: providers,
      child: MaterialApp(
        title: 'ben',
        theme: ThemeData(
          primarySwatch: Colors.red,
        ),
        routes: {
          "/": (_) => hasInitialized ? new LoginPage() : new InitializePage(),
          "/login": (_) => new LoginPage(),
          "/home": (_) => new HomePage(),
        },
      ),
    );
  }
}
```

```
