### ISSUE TITLE
Help on creating an extension, dart type inference

### ISSUE THREAD

**Issue by matejthetree** [rrousselGit/provider#219]
Hello,

I was playing with the provider and I wanted to create a sort of extension for commands. 

Currently, I am maping typedefs and I provide those functions with the provider to be executed, but I had an idea to create commands.

Here is the code
https://gist.github.com/d02ef6662ca72df314df28ab86e3ce83

I thought that dart type inference would work when trying to execute commands.
`      command.execute(Provider.of(context), vo);`
but it is read as dynamic.
When I debug, the debugger knows that execute closure is taking `Bloc1` and `ExampleVO` params.

I would appreciate help or explanation on why it doesn't work.

Ty for your time.

**Comment by rrousselGit** [comment]
Hello!

It's likely because you're doing `is Command` instead of `is Command<Whatever>`.
Without specifying the type there, `is Command` is inferred as `is Command<dynamic>`
