### ISSUE TITLE
Could not find the correct provider <pipeprovider> above this LoginPage Widget

### ISSUE THREAD

**Issue by XamarinPOC** [rrousselGit/provider#226]

**Comment by rrousselGit** [comment]
Hello!

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
