### ISSUE TITLE
Could not find the correct provider <pipeprovider> above this LoginPage Widget

### ISSUE THREAD

**Issue by XamarinPOC** [rrousselGit/provider#227]
import 'package:flutter/material.dart';
import 'package:flutter_xmllayout_helpers/pipes/Pipe.dart';
import 'package:flutter_xmllayout_helpers/providers/PipeProvider.dart';
import 'package:provider/provider.dart';
import 'package:xmllayout/page/LoginPage/LoginPage.xml.dart';
// import 'pipes/translate.dart';
// import 'i18n/gen/delegate.dart';
// import 'package:flutter_localizations/flutter_localizations.dart';

void main() async {
  final RouteObserver<PageRoute> routeObserver = new RouteObserver<PageRoute>();
  runApp(
    MultiProvider(
      //
      // dependency injection
      //
      providers: [
        Provider<RouteObserver<Route>>.value(value: routeObserver),
        Provider<PipeProvider>(builder: _createPipeProvider)
      ],
      child: MyApp(routeObserver: routeObserver)
    )
  );
}

PipeProvider _createPipeProvider(BuildContext context)
 {
  final PipeProvider pipeProvider = PipeProvider();
  //
  // register pipes
  //
  pipeProvider.register(new MyTranslatePipe());

  return pipeProvider;
}

class MyTranslatePipe extends Pipe {
  String get name => 'translate'; // unique name
  dynamic transform(BuildContext context, value, args)
  {
    // write your own logic...

    // AppLocalizations class generated by this extension if you have JSON files inside lib/i18n folder.
    return AppLocalizations.of(context).getTranslation(value) ?? '';
  }
}

class MyApp extends StatelessWidget {
  const MyApp({
    Key key,
    this.routeObserver
  }) : super(key: key);

  final RouteObserver<PageRoute> routeObserver;

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorObservers: [routeObserver],
      title: 'MyAppTitle',

      //
      // theming
      //
      theme: ThemeData(primarySwatch: Colors.blue),
      
      // //
      // // localization
      // //
      // localizationsDelegates: [
      //   GlobalMaterialLocalizations.delegate,
      //   GlobalWidgetsLocalizations.delegate,
      //   AppLocalizationsDelegate()
      // ],
      // supportedLocales: [
      //   Locale("en")
      // ],
      // locale: Locale("en"),
      
      //
      // navigation
      //
      home: LoginPage(),
      onGenerateRoute: (RouteSettings settings) {
        switch (settings.name) {
          case '/':
            return MaterialPageRoute(builder: (context) => LoginPage());
        }
      }
    );
  }
}

**Comment by rrousselGit** [comment]
Hello!

Instead of an issue, consider posting this kind of question on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or [Gitter](https://gitter.im/flutter_provider/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
