### ISSUE TITLE
Where can I find the full licence agreement text?

### ISSUE THREAD

**Issue by APopatanasov** [rrousselGit/provider#230]
I have recently built a flutter application and used provider in it- the library is great by the way :). Due to some legal reasons (internal company policies) I cannot publish my application until I find the full licence text of the repository. Can somebody provide me the full licence agreement? Thanks in advance. 

P.S. I apologize if this is not the right place for asking this, but I am in a hurry.

**Comment by rrousselGit** [comment]
This file? https://github.com/rrousselGit/provider/blob/master/packages/provider/LICENSE

**Comment by APopatanasov** [comment]
Yes. Thank you very much. 🔝
