### ISSUE TITLE
ChangeNotifier is not selective for consumer

### ISSUE THREAD

**Issue by JoanSchi** [rrousselGit/provider#231]
I like to use multiple ChangeNotifierProviders and consumers to update only parts of my application, in the simplified app only the counter (CountText -> StatefulWidget).

provider: ^3.1.0
flutter 40.0.2

### Problem:
The problem is if I use the notifyListeners the complete app is rebuild and changenotifier is not selective for the consumer,

To reproduce the the issue I build a simple app below. If the  **Issue+** button is pressed the complete app is rebuild and prints: 
---- Scaffold rebuild? :( ----
--- DescriptionText rebuild? :( ---- (DescriptionText -> StatefulWidget)

The **Uggle+** button updates only CountText.

Expected:
I was aspected that only the Counter was rebuild like the uggle way with a function to setstate.

(Issue is also reported at: https://github.com/flutter/flutter/issues/35360)

### Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(providers: [
      ChangeNotifierProvider<_DescriptionNotifier>(
          builder: (_) =>
              _DescriptionNotifier()),
      ChangeNotifierProvider<_CountNotifier>(
          builder: (_) =>
              _CountNotifier()),
    ],

      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(

          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _incrementCounterIssue() {
    final nf = Provider.of<_CountNotifier>(context);
    nf.count++;
    nf.notifyListeners();
  }

  void _incrementCounterUggle() {
    final nf = Provider.of<_CountNotifier>(context);
    nf.count++;
    nf.updateSetState();
  }

  @override
  Widget build(BuildContext context) {
    print('----   Scaffold  rebuild? :( ----');
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            DescriptionText(),
            CountText(),
            RaisedButton(child: Text('Issue +'),onPressed: _incrementCounterIssue,),
            RaisedButton(child: Text('Uggle +'),onPressed: _incrementCounterUggle,)
          ],
        ),
      ),
    );
  }
}


class _DescriptionNotifier with ChangeNotifier {

  _DescriptionNotifier();
}

class DescriptionText extends StatefulWidget{
  @override
  State<StatefulWidget> createState() => DescriptionTextState();

}

class DescriptionTextState extends State<DescriptionText>{
  @override
  Widget build(BuildContext context) {
    return Consumer<_DescriptionNotifier>(
        builder: (context, value, child){
          print('----   DescriptionText  rebuild? :( ----');
          return Text('You have pushed the button this many times:');
        });

  }

}

class _CountNotifier with ChangeNotifier {
    int count = 0;
    var updateSetState;
  _CountNotifier();
}

class CountText extends StatefulWidget{
  @override
  State<StatefulWidget> createState() => CountTextState();

}

class CountTextState extends State<CountText>{



  @override
  Widget build(BuildContext context) {
    return Consumer<_CountNotifier>(
        builder: (context, value, child){
          return Text(
          '${value.count}',
          style: Theme.of(context).textTheme.display1,
        );}
        );

  }

  @override
  void didChangeDependencies() {
    Provider.of<_CountNotifier>(context).updateSetState = updateSetState;
  }

  //Uggle way
  updateSetState(){
    setState(() {

    });
  }

}
```
### Flutter doctor
[✓] Flutter (Channel dev, v1.10.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.6 at /home/joan/flutter
    • Framework revision cc3ca9a916 (7 days ago), 2019-09-25 10:57:58 -0400
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/joan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/joan/AppData/programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/joan/AppData/programs/android-studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by rrousselGit** [comment]
Hello!

I do not understand. What's the problem?

**Comment by JoanSchi** [comment]
If you call  notifyListeners of _CountNotifier or any other specific notifier and the complete app is rebuild equal to setstate at the basic/scaffold level, why even bother to implement provider. The purpose to implement providers is to update only parts of your program to prevent a complete build and to boost performance. 

Please look at the code.

**Comment by bleroux** [comment]
Hi,
the fact there is a full rebuild in your sample code doesn't mean that provider is not able to be selective :-)
Using Provider.of, the way you do, means you ask for a rebuild of _MyHomePageState each time you call notifyListeners on your instance of _CountNotifier ;-)

Have a look at Provider.of documentation https://pub.dev/documentation/provider/latest/provider/Provider/of.html
The second parameter is important. Try to update your code with this : 
final nf = Provider.of<_CountNotifier>(context, listen: false);

**Comment by JoanSchi** [comment]
Hi,

Thank you for reply, that a bummer that a full rebuild is normal (also with (context, listen: false)). From the google 1/0 presentation I assumed that the providers was a good way to update only parts of the app to boost performance :), unfortunately this is not the case and it can be a potential app killer for complex widgets on older phones. 

I think wrapping the builder function of the consumer into a Statefull Widget and implement the consumer in the widget with a listener to setState to prevent a full rebuild would be equal to the "uggle way" and will boost performance.

**Comment by bleroux** [comment]
JoanSchi, Provider IS a good way to update only parts of the app.
I didn't say a full rebuild is normal... I said it is expected to happen considering your code.
Try to find example of using it the right way.

Here is a very complete series of article to understand it : 
https://medium.com/flutter-community/understanding-provider-in-diagrams-part-1-providing-values-4379aa1e7fd5
In this series there is provider version of the counter sample, have a look to it.

**Comment by mono0926** [comment]
This should suppress the unwanted rebuild.

```dart
  void _incrementCounterIssue() {
    final nf = Provider.of<_CountNotifier>(context, listen: false); // set `listen` to false
    nf.count++;
    nf.notifyListeners();
  }
```

**Comment by JoanSchi** [comment]
@bleroux, mono0926: Thank you for your help.

**Comment by caustav** [comment]
> Hi,
> 
> Thank you for reply, that a bummer that a full rebuild is normal (also with (context, listen: false)). From the google 1/0 presentation I assumed that the providers was a good way to update only parts of the app to boost performance :), unfortunately this is not the case and it can be a potential app killer for complex widgets on older phones.
> 
> I think wrapping the builder function of the consumer into a Statefull Widget and implement the consumer in the widget with a listener to setState to prevent a full rebuild would be equal to the "uggle way" and will boost performance.

I don't think "a full rebuild is normal (also with (context, listen: false))." this is true. If you set  listen: false it ought not to rebuild the whole widget.
