### ISSUE TITLE
Consumer<Interface>

### ISSUE THREAD

**Issue by TannerYoung** [rrousselGit/provider#234]
How would one go about consuming an interface / abstract class / mixin? Is this something that's supported. I had suspected that since I am already providing the concrete implementation I could consume the interface, but that results in an exception that the type can't be found.

I had also thought I could use a proxy provider, but my concrete type extends change notifier and my interface doesn't, meaning I can't construct it with ChangeNotifierProxyProvider nor with the standard ProxyProvider.

Thoughts?

**Comment by rrousselGit** [comment]
It's based on the provider:

```dart
Provider<Concrete>(
  builder: (_) => Concrete(),
)
```

which is then consumed with `Consumer<Concrete>`

vs:

```dart
Provider<Interface>(
  builder: (_) => Concrete(),
)
```

which is consumed with `Consumer<Interface>`

**Comment by TannerYoung** [comment]
Hmm perhaps I wasn't clear.

I have an interface which does not extend ChangeNotifier, but a concrete implementation which does. The compile time checks mean I can't provide the interface via ChangeNotifierProvider, and the debug check means I can't provide it via Provider (as the concrete is a ChangeNotifier).

I've come up with the following solution, but it feels awfully hacky:

```
ChangeNotifierProvider<Concrete>(
  builder: ...
  child: Consumer<Concrete>(
    builder: (_, concrete, __) => InheritedProvider<Interface>.value(
      value: concrete, 
      updateShouldNotify: (_, __) => true)))
```

**Comment by rrousselGit** [comment]
That's not feasible. Consider making your interface implement ChangeNotifier.

**Comment by KieranCTaylor** [comment]
Hey @rrousselGit I had to do quite a bit of googling around to find this. Massive fan of this project and would be happy to contribute this to documentation if you could point me to somewhere appropriate to add.

**Comment by rrousselGit** [comment]
Hi, nice!

You could add it to the dartdoc of `Provider` and/or the Readme (the FAQ?)
