### ISSUE TITLE
Challenges structuring my data

### ISSUE THREAD

**Issue by Jomik** [rrousselGit/provider#238]
Hey,

So this is not an issue with Provider, but probably just with my understanding of Provider.
I am working on a small app for fitness logging, and I have decided I'll use Provider for injecting my BLoCs, which are simply `ChangeNotifierProvider`, currently.
My data looks something like below.
```
WorkoutSet: { name, reps, weight, time, distance, complete }
WorkoutSuperSet: { name, List<WorkoutSet> sets }
Workout: { name, List<WorkoutSuperSet> supersets }
```

So I wanted to create a `WorkoutBloc` for providing the Workout, so that I can get the name and the number of supersets, and the number of total sets, completed sets, etc.
But then I also want that Widget to be able to provide a `WorkoutSuperSetBloc` to each item in a list, and those items in turn then need to provide a `WorkoutSetBloc` to each item in a list inside them.
Does this make sense?
My issue is that I need a change in `WorkoutSetBloc` to reflect a change in `WorkoutBloc`, but I don't necessarily want to rebuild the whole tree just because some things are changed in a `WorkoutSet`.

**Comment by soleverlee** [comment]
is you question similar to mine  #247 ?

**Comment by rrousselGit** [comment]
Hello!

This question does not really fit github. Consider asking it on stackoverflow.com
