### ISSUE TITLE
Could not find the correct provider: providers for the childrens.

### ISSUE THREAD

**Issue by hektorjg** [rrousselGit/provider#245]
Hello, I'm trying to understand how `provider` works, but I still dont get it.

I have a simple example code, where I want one element to be provided to all the following routes called after that.

Page1 has a `Provider<bool>.value()`
Page2 reads that value, and could modify (extending ChangeNotifier) those needed Providers, but dont explicitly pass them to the next page.
Page3 tries to read Page1 provider, but fails. This Page should complete a process and pop back through Page2 and Page1 a value.

Think like a three-step screens to create something.

As I see in Flutter Inspector, the Page3 sits below MaterialApp and not below Page2.
![image](https://user-images.githubusercontent.com/22684537/66782373-db86cc80-eed5-11e9-80f1-61db1293434f.png)

So my question is: How to properly create and pass providers to descendant routes on the stack?

Example code:
```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class Page1 extends StatefulWidget {
  Page1();

  @override
  State<StatefulWidget> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Page1")),
        body: Column(
          children: <Widget>[
            ListTile(title: Text("No providers")),
            RaisedButton(
              child: Text("Next page"),
              onPressed: () => Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => Provider<bool>.value(value: true, child: Page2()))),
            ),
          ],
        ));
  }
}

class Page2 extends StatefulWidget {
  Page2();

  @override
  State<StatefulWidget> createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Page2")),
        body: Column(
          children: <Widget>[
            ListTile(title: Text("Provider value: ${Provider.of<bool>(context).toString()}")),
            RaisedButton(
              child: Text("Next page"),
              onPressed: () =>
                  Navigator.of(context).push(MaterialPageRoute(builder: (context) => Page3())),
            ),
          ],
        ));
  }
}

class Page3 extends StatefulWidget {
  Page3();

  @override
  State<StatefulWidget> createState() => _Page3State();
}

class _Page3State extends State<Page3> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Page3")),
        body: Column(
          children: <Widget>[
            ListTile(title: Text("Provider value: ${Provider.of<bool>(context).toString()}"))
          ],
        ));
  }
}

```

**Comment by jtlapp** [comment]
You need to put the Provider above all of the widgets that might need the value -- above ALL of the pages. That is, you need one Provider providing a single value to multiple pages below.

I think you're one of the people who could benefit from [this series of articles](https://medium.com/flutter-community/understanding-provider-in-diagrams-part-1-providing-values-4379aa1e7fd5) that I wrote about provider.

I may yet propose a revision of the README that should help clear up some of these issues.

**Comment by hektorjg** [comment]
Okey, so If I understood correctly:

- Once you push a new MaterialPageRoute, you lose all the current providers on the current Page and does not pass them into the new BuildContext unless re-defining again.
- If you want it so, then you should add the to the MaterialApp using the MultiProvider, and each of my Page1,Page2,Page3 should use it and/or modify it.
- In my example, I should modify in the runApp `Provider<bool>.value(value: true, child:MaterialApp())` and then Page1, Page2, and Page3 can see the Provider of this value.

Thank you very much for your help!!

**Comment by jtlapp** [comment]
That sounds about right. A few clarifications:

- The only thing Provider uses a BuildContext for is identifying where in the tree the dependent widget is, so that it can figure out which ancestor provider's value to retrieve.
- I assume you realize this, but you'll be replacing the `true` value with some useful variable.
- Be sure to [read up](https://medium.com/flutter-community/understanding-provider-in-diagrams-part-2-basic-providers-1a80fb74d4e7#d4e3) on when to use `.value` providers.

You're welcome!

**Comment by hektorjg** [comment]
Yup, that's it, thanks for your help!

Best regards
