### ISSUE TITLE
A question about provider

### ISSUE THREAD

**Issue by soleverlee** [rrousselGit/provider#247]
Hi, 
I 'm sorry for the issue name but I have a problem handling data with tab view,  let me first describe it. The app looks like this:
![image](https://user-images.githubusercontent.com/6427851/66890948-64a71c00-f01a-11e9-946c-6d0d29f415b5.png)

for each tab it contains a list with different type(let's say it's an integer, ie. 1, 2, 3), that means if you press the `+` button, it will also pop to different add page according to the type of current tab. So in order to keep the list data, now I have two thoughts:

* A: Use a `Map<int, List<String>>` to store different types of data, and provide this in `Scaffold` widget to make sure both the add button and tabbar view can access it
* B: Use `List<String>` to store the items per tab, and just provide it to each child of `TabBarView`

So if I choose solution A, the only problem is that when I add some data, all listeners(including the unselected tab) will rebuild, that's not what I want, because I just made change to the current tab, and I only want to rebuild this.

But if I use solution B, then it's a problem for refreshing the list after add, because the `+` button are not inside tabbar view, I cannot get the view model, and I have no idea how to refresh it.

So I'm quite struggle about this, could some one give me some suggestion? :p

**Comment by rrousselGit** [comment]
Hello!

This question does not fit github. Instead consider asking it on stackoverflow.com
