### ISSUE TITLE
Add an optional ifAbsent parameter to Provider.of 

### ISSUE THREAD

**Issue by ekarayel** [rrousselGit/provider#252]
The idea is that, `Provider.of<Foo>(context)` would still be returning a ProviderNotFoundError, while `Provider.of<Foo>(conext, ifAbsent: () => bar)` would return bar, in the case that Foo is not present in the tree.

Somewhat similar to the update method from darts Maps. https://api.flutter.dev/flutter/dart-core/Map/update.html 

Also related to https://github.com/rrousselGit/provider/issues/235.

**Comment by rrousselGit** [comment]
The idea is interesting, but it's still not practical with NNBD

We won't be able to do :
```dart
Foo? foo = Provider.of<Foo>(c, ifAbsent: () => null);

**Comment by ekarayel** [comment]
Do we know, how the [orNull](https://api.flutter.dev/flutter/quiver.core/Optional/orNull.html) function will be available with NNBD? They essentially have the same problem.

**Comment by rrousselGit** [comment]
I don't know. We can only wait and see I guess.

For now, I don't think it's reasonable to implement such a thing.

**Comment by RaviKavaiya** [comment]
@rrousselGit Any updates on this??

**Comment by rrousselGit** [comment]
As I mentioned before, an "orElse" /"if Absent" is impractical because of nnbd

**Comment by rrousselGit** [comment]
Closing since the 6.0.0 version should that care of this with `Provider.of<T>` vs `Provider.of<T?>`
