### ISSUE TITLE
QUESTION regarding - I use ChangeNotifier and I have an exception when I update it

### ISSUE THREAD

**Issue by frankrod** [rrousselGit/provider#254]
Hello!

I saw this in the documentation:

![Screen Shot 2019-10-29 at 12 10 00 PM](https://user-images.githubusercontent.com/5304641/67796333-7e4a5980-fa45-11e9-875d-b4f15a7e7f24.png)

Would it be good or better to use somethings like this:
ex. Named constructors
```
class MyNotifier extends ChangeNotifier {
  MyNotifier() {
    _fetchSomething();
  }
  MyNotifier.withOneParam(someValue) {
    _fetchSomethingWithParam(someValue);
  }

  Future<void> _fetchSomethingWithParam(someValue) async {}

  Future<void> _fetchSomething() async {}
}
```

is it better than using the `Future.microtask` approach?

**Comment by rrousselGit** [comment]
Yes, if you can avoid the microtask, do it. As for the named constructor thing, it doesn't really matter. It's up to your preferences
