### ISSUE TITLE
Non-standard package structure

### ISSUE THREAD

**Issue by dspicher** [rrousselGit/provider#256]
Is there a deeper reason for hosting the package in `packages/provider` subdirectory?

It makes tools like [`dart_dev`](https://pub.dev/packages/dart_dev) fail on the `provider` dependency.

I'm happy to submit a PR if you agree on making it conform to https://dart.dev/tools/pub/package-layout

**Comment by rrousselGit** [comment]
This is a standard package structure, for monorepo.

There are many examples available of packages using that structure, such as :
- https://github.com/flutter/flutter
- https://github.com/felangel/bloc

**Comment by rrousselGit** [comment]
It's not needed for provider yet, but I have some unpublished side packages that live next to it
