### ISSUE TITLE
Question about some code

### ISSUE THREAD

**Issue by mohammadne** [rrousselGit/provider#258]
I wrote an app but in hot reloads, the app will lost their properties in provider classes.
Any help is appreciated.
This is what I wrote in main.dart:

MultiProvider(
        providers: [
          ChangeNotifierProvider.value(
            value: Auth(),
          ),
          ChangeNotifierProvider.value(
            value: AlbumsProperties(),
          ),
          ChangeNotifierProvider.value(
            value: AlbumsData(),
          ),
          ChangeNotifierProvider.value(
            value: ArtistsProperties(),
          ),
          ChangeNotifierProvider.value(
            value: ArtistsData(),
          ),
          ChangeNotifierProvider.value(
            value: GeneralPlayer(),
          ),
          ChangeNotifierProvider.value(
            value: PlayerSubscription(),
          ),
          ChangeNotifierProvider.value(
            value: AnimationProvider(),
          ),
          ChangeNotifierProvider.value(
            value: AlbumData(),
          ),
          ChangeNotifierProvider.value(
            value: ArtistData(),
          ),
          ChangeNotifierProvider.value(
            value: CategoryData(),
          ),
          ChangeNotifierProvider.value(
            value: InstrumentalData(),
          ),
          ChangeNotifierProvider.value(
            value: MoodData(),
          ),
          ChangeNotifierProvider.value(
            value: GenreData(),
          ),
        ],
        child: MaterialApp(
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            FallbackCupertinoLocalisationsDelegate(),
            EasylocaLizationDelegate(
              locale: data.locale,
              path: 'resources/langs',
            ),
          ],
          supportedLocales: [
            Locale("en", "US"),
            Locale("fa", "IR"),
          ],
          locale: data.savedLocale,
          title: "Gerama",
          home: SplashPage(),
          routes: {
            '/Welcome': (ctx) => WelcomePage(),
            '/Login': (ctx) => LoginPage(),
            '/App': (ctx) => BottomPlayer(),
          },
        ),
      )

**Comment by mohammadne** [comment]
So after any change, I had to refresh the entire app

**Comment by rrousselGit** [comment]
The answer is on stackoverflow: https://stackoverflow.com/questions/56580988/flutter-state-is-lost-on-hot-reload-when-using-provider/56581738#56581738
