### ISSUE TITLE
Filtering Consumer updates

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/provider#26]
Having a way to filter updates at the consumer level may be useful to fine-grain builds.

For example, if we have a `ChangeNotifier` model with multiples properties,`notifyListeners` would be called each time a value of a property changed. If we have a `Consumer` for that model that only depends on one of the properties, it is updated even when an other property changes.

We could have a `bool shouldBuild(T previousValue, T newValue)` argument for `Consumer` for that purpose.

**Comment by rrousselGit** [comment]
How would that be implemented? From my understanding there's no way for widgets to cancel a rebuild

**Comment by rrousselGit** [comment]
I'm going to close this, as it's not doable.

Not only do widgets cannot cancel a rebuild, but there's also a bigger flaw:

In 99% of the situations with `ChangeNotifier`, `previousValue` & `newValue` are actually the same.

**Comment by fantasy525** [comment]
@rrousselGit  I also need this.
> notifyListeners would be called each time a value of a property changed. If we have a Consumer for that model that only depends on one of the properties, it is updated even when an other property changes.

for best performance,I don't think it need to rebuild the entire screen and also I don't want to write a ChangeNotifier  for every property.I just need write a ChangeNotifier with many properties.

**Comment by fantasy525** [comment]
@aloisdeniel  do you have any ideas?

**Comment by rrousselGit** [comment]
That's simply not possible with mutable objects like `ChangeNotifier`. You need to use an immutable architecture

**Comment by fantasy525** [comment]
@rrousselGit  can you provide me some examples?and your  example  is too simple.sorry. i'm confused

**Comment by fantasy525** [comment]
> I'm going to close this, as it's not doable.
> 
> Not only do widgets cannot cancel a rebuild, but there's also a bigger flaw:
> 
> In 99% of the situations with `ChangeNotifier`, `previousValue` & `newValue` are actually the same.

I think you can save last value,like Int ,String value.

**Comment by rrousselGit** [comment]
From a discussion on gitter:

Most of the time, the worry you have is just premature optimisation.

But if you really need that optimisation, you can ProxyProvider

```dart
class ManyMutableThings with ChangeNotifier {
  String foo;
  int bar;
}

class ImmutableCopyOfTheFewFieldsYouNeed {
  ImmutableCopyOfTheFewFieldsYouNeed({this.foo});

  final String foo;
}

Widget build(BuildContext context) {
  return ProxyProvider<ManyMutableThings, ImmutableCopyOfTheFewFieldsYouNeed>(
    builder: (_, model, __) => ImmutableCopyOfTheFewFieldsYouNeed(foo: model.foo);
    updateShouldNotify: (a, b) => a.foo == b.foo,
    child: Consumer<ImmutableCopyOfTheFewFieldsYouNeed>(
      builder: (_, data) {
        return Text(data.foo);
      },
  );
}
```
