### ISSUE TITLE
Consider options for making it easier to _not_ notify in ChangeNotifierProxyProvider

### ISSUE THREAD

**Issue by filiph** [rrousselGit/provider#260]
One issue I've repeatedly had in recent months is this: I'd love to update the value of a ChangeNotifierProvider without triggering rebuilds downstream.

Pseudocode example illustrating the problem, from memory:

```dart
class App extends StatelessWidget {
  build() {
    return ChangeNotifierProvider(
      builder: (_) => Tapper(),
      child: ...
    );
  }
}

class FooPage extends StatelessWidget {
  build() {
    return ChangeNotifierProxyProvider<...>(
      initial: (_) => Foo(),
      builder: (_, tapper, previous) {
        return previous.copyWith(tapper: tapper); // or something similar
      }
    );
  }
}
```

Imagine that Tapper is quite low level. In the particular case I have in mind, it's a way for a particular FloatingActionButton-alike to notify basically anyone in the app who cares to listen that it was tapped. The important part is that it gets a lot of updates, by design.

Foo, on the other hand, is not supposed to change too often. It might be the object responsible of loading data into a screen. Once they're loaded — sure, rebuild that screen. But don't do that every time someone taps a button.

So I guess the problem is that both `notifyListeners` _and_ rebuilding the value in ChangeNotifier will both do the same thing, but quite often I'd like to separate those types of "update".

I was reminded of this when I read https://github.com/rrousselGit/provider/issues/259. I don't have any solution, so this is just to gather thoughts at this point.

**Comment by rrousselGit** [comment]
Thanks for the issue!

Out of pure curiosity, why use "copyWith"? 
Because that's what cause the problem: the instance of the object changes, so it has to notify dependents somehow. 

I personally don't use ChangeNotifierProxyProvider this way, and instead do:

```dart
ChangeNotifierProxyProvider<...>(
  initialBuilder: (_) => Foo(),
  builder: (_, tapper, foo) => foo
     ..didChangeDependencies(tapper), 
)
```


This doesn't change the instance of the ChangeNotifier. 
Then we just have to _not_ call `notifyListeners` when it isn't needed.

**Comment by filiph** [comment]
Oh, therein lies the problem, probably. I thought that any time `builder` is called (because of some upstream dependency), `notifyListeners` gets called. E.g. I'm pretty sure I have code like this:

```dart
ChangeNotifierProxyProvider<...>(
  initialBuilder: (_) => Foo(),
  builder: (_, tapper, foo) { 
    foo.tapper = tapper;
    return foo; 
  }
)
```

... and it still notifies downstream listeners (Consumers) of `Foo`. Is that not the case?

**Comment by rrousselGit** [comment]
That is not the case (unless `foo` has a custom setter).

The only situation where builder triggers a rebuild of dependents is if it returns a new object.

Otherwise, nothing happens, and it is up to `builder` to call `notifyListeners`.

**Comment by rrousselGit** [comment]
@filiph Does this explanation solves your issue, or is there still a need for something here?

Alternatively, I'm joining you in your comment where you said you made your own ChangeNotifier.
I've been thinking of making a secondary package that'd expose a `Listenable`-like, but without the dependency on Flutter and with some small API changes.
