### ISSUE TITLE
Throw if Provider.of is called with dynamic

### ISSUE THREAD

**Issue by reachanil** [rrousselGit/provider#261]
My main.dart has this - 

void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<Athlete>(
        builder: (_) => Athlete(),
        child: MaterialApp(
_....<stuff cut out for brevity>.._. 
            home: MyHomePage()));

My home page file has - 

class MyHomePage extends StatelessWidget {
   Widget build(BuildContext context) {
    return Scaffold(
        body: new Stack(
      children: <Widget>[
        GestureDetector(
          onTap: () {
            bool tmp = Provider.of<Athlete>(context, listen: false).dummy;

When I run this I get - 

Error: Could not find the correct Provider<Athlete> above this MyHomePage Widget

To fix, please:

  * Ensure the Provider<Athlete> is an ancestor to this MyHomePage Widget

In my understanding, MaterialApp is the child of ChangeNotifierProvider<Athlete> and MyHomePage is a descendent of MaterialApp, then why is the error showing cannot find Provider<Athlete> above MyHomePage widget? What could be going wrong? 

Thanks,
-Anil

**Comment by rrousselGit** [comment]
You forgot to specify the generic type passed to `.of`:

`Provider.of<Athlete>(context)`, instead of just `Provider.of(context)`

**Comment by rrousselGit** [comment]
I'll keep this open as a reminder to throw if `Provider.of` is called with `dynamic`.

**Comment by reachanil** [comment]
Hi Remi,
I had put the <Athlete> in both the ChangeNotifierProvider<> and Provider.of<>
Somehow when I cut and paste this stuff into the comments here it doesn't show up, however when I try editing my original note in the bug report it does show up. So, in summary I do have the template argument passed correctly in both places. Otherwise the code is exactly like I showed in my note. I still have the error. The error is as below - 

The following ProviderNotFoundError was thrown while handling a gesture:
Error: Could not find the correct Provider<Athlete> above this MyHomePage Widget

To fix, please:

  * Ensure the Provider<Athlete> is an ancestor to this MyHomePage Widget
  * Provide types to Provider<Athlete>
  * Provide types to Consumer<Athlete>
  * Provide types to Provider.of<Athlete>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues

When the exception was thrown, this was the stack
#0      Provider.of 
package:provider/src/provider.dart:260
#1      MyHomePage.build.<anonymous closure> 
package:faster_fit/components/HomePage.dart:34
#2      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#3      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
#4      TapGestureRecognizer.handlePrimaryPointer

**Comment by reachanil** [comment]
<Athlete>

**Comment by reachanil** [comment]
I had to put an escape character around this to get it into the note section like above - \<Athlete\>

**Comment by reachanil** [comment]
One change got this to work - 

One of the errors shown was - 
Always use package imports. Ex: `import 'package:my_app/my_code.dart';

So, I modified my import which was using a relative path to my Model/Athlete.dart folder instead to  - import 'package:faster_fit/Model/Athlete.dart' and voila! everything works as expected... 

I should've spent more time looking at the error printed, but never expected this to cause some indirect issue and not prompt me right at the point where I did the import itself...

**Comment by martinpelli** [comment]
@rrousselGit there is no way to call a provider using dynamic? I have an escenario where I don't know which is the current provider or closest. For example I have an interceptor to catch if there is a backend error. I show an alert dialog there, but I need to call isLoading = false of the current provider because if not, the screen will keep spinning with the CircularProgressiveIndicator widget, so I need to do something like this:

```
 _dio.interceptors.add(InterceptorsWrapper(onError: (error, handler) {
      showDialog(
          barrierDismissible: false,
          context: navKey.currentContext!,
          builder: (context) => CustomAlertDialog(
              titleText: error.response?.data?.toString() ?? 'Error',
              bodyText: (error.response?.data?.toString() != null) ? null : error.error?.toString() ?? error.message ?? 'Server error',
              iconColor: Colors.red,
              iconData: Icons.error));

      if (navKey.currentContext == null) return;

      final currentProvider = navKey.currentContext!.watch();

      currentProvider?.clear();

      return;
    })); 
```
 Here, if the provider exists, then clear() function of that provider will call isLoading=false and other params that need to be reset. But I get `Tried to call Provider.of<dynamic>. This is likely a mistake and is therefore\nunsupported`
    The only way right now is to make a huge select or if and check the current route and then user Provider.of<T> so it's a mess.
