### ISSUE TITLE
StreamProvider behaves differently than StreamBuilder

### ISSUE THREAD

**Issue by BaranMichal25** [rrousselGit/provider#266]
I noticed that `StreamProvider` (with `Consumer`?) is behaving differently than `StreamBuilder`, in a way, that `StreamProvider` is ignoring object emitted by a stream, if it is the same object that was emitted before. Even if the `==` or `hashCode` return different values.

 🔴 Example with `StreamProvider` behaving differently than `StreamBuilder`:
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class ExamplePage extends StatelessWidget {
  final repository = Repository();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          StreamProvider<Holder>.value(
            initialData: Holder(0),
            value: repository.stream,
            child: Consumer<Holder>(
              builder: (context, number, _) {
                return Text("StreamProvider: ${number.value}");
              },
            ),
          ),
          StreamBuilder(
            initialData: Holder(0),
            stream: repository.stream,
            builder: (context, snapshot) {
              if (snapshot.data is Holder) {
                return Text("StreamBuilder: ${snapshot.data.value.toString()}");
              } else {
                return Text("empty");
              }
            },
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => repository.incrementAndEmit(),
        child: Icon(Icons.add),
      ),
    );
  }
}

class Repository {
  int counter = 0;
  Holder holder = Holder(0);
  final subject = StreamController<Holder>.broadcast();

  Stream<Holder> get stream => subject.stream;

  void incrementAndEmit() {
    counter++;
    holder.value = counter; // StreamProvider not working
    //holder = Holder(counter); // StreamProvider working
    subject.add(holder);
  }
}

class Holder {
  int value;

  Holder(this.value);
}
```

 🟢 Example with `StreamProvider` behaving same as `StreamBuilder`:
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class ExamplePage extends StatelessWidget {
  final repository = Repository();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          StreamProvider<Holder>.value(
            initialData: Holder(0),
            value: repository.stream,
            child: Consumer<Holder>(
              builder: (context, number, _) {
                return Text("StreamProvider: ${number.value}");
              },
            ),
          ),
          StreamBuilder(
            initialData: Holder(0),
            stream: repository.stream,
            builder: (context, snapshot) {
              if (snapshot.data is Holder) {
                return Text("StreamBuilder: ${snapshot.data.value.toString()}");
              } else {
                return Text("empty");
              }
            },
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => repository.incrementAndEmit(),
        child: Icon(Icons.add),
      ),
    );
  }
}

class Repository {
  int counter = 0;
  Holder holder = Holder(0);
  final subject = StreamController<Holder>.broadcast();

  Stream<Holder> get stream => subject.stream;

  void incrementAndEmit() {
    counter++;
    //holder.value = counter; // StreamProvider not working
    holder = Holder(counter); // StreamProvider working
    subject.add(holder);
  }
}

class Holder {
  int value;

  Holder(this.value);
}

```

Is this expected behaviour? 
If it is expected behaviour, then what can I do to keep emitting same instance of `Holder` (with different values) so that StreamProvider doesn't ignore it?

_Provider version: 3.1.0+1_
_Flutter version: 1.9.1+hotfix.6 • channel stable_

**Comment by rrousselGit** [comment]
This is expected. The data should be immutable. 

Either emit à new instance, or override StreamProvider's updateShouldNotify

**Comment by PavelPZ** [comment]
I am sorry to mix provider x flutter_hook questions:

Am I right that in case of flutter_hooks, ```useStream``` hook causes widget rebuild for every stream value (without checking equality with previous value)?

**Comment by BaranMichal25** [comment]
Thanks for the quick response. 

> This is expected. 
What do you think about adding a note about it to documentation of `StreamProvider`? 
I think many people during migration to `provider` will intuitively try to replace `StreamBuilder` with `StreamProvider` and find their code not working anymore, so probably a note like this would be very helpful.

**Comment by rrousselGit** [comment]
> I am sorry to mix provider x flutter_hook questions:
> 
> Am I right that in case of flutter_hooks, `useStream` hook causes widget rebuild for every stream value (without checking equality with previous value)?

You mean that?

```dart
final snapshot = useStream(myStream);

return Provider.value(
  value: snapshot.data,
  child: ...,
)
```

If so, then fear not! Dependents won't be updated unnecessarily when the stream updates.
`Provider.value` has an `updateShouldNotify` that filters == values.

**Comment by BaranMichal25** [comment]
Thanks for the quick response. 

> This is expected. The data should be immutable.

What do you think about adding a note about it to documentation of `StreamProvider`? 
I think many people during migration to `provider` will intuitively try to replace `StreamBuilder` with `StreamProvider` and find their code not working anymore, so probably a note like this would be very helpful.

**Comment by PavelPZ** [comment]
In following code, every tap in ```onTap: () => sc.add(m1)``` rebuilds MyWidget component. 

So:
- ```useStream``` means rebuilding on every StreamController.add
- ```StreamBuilder``` means rebuilding on every StreamController.add
-  ```StreamControllerProvider``` means rebuilding only when StreamController.add adds different object.

Am I right?

```
class Model {
  int value;
}
@widget
Widget app(BuildContext context) => Provider.value(
  value: StreamController<Model>.broadcast(),
  child: MyWidget()
);

@hwidget
Widget myWidget(BuildContext context) {
  final sc = Provider.of<StreamController<Model>>(context);
  final value = useStream(sc.stream, initialData: Model(0));
  final m1 = useMemoized(() => Model(1));
  return GestureDetector(
      onTap: () => sc.add(m1),
      child: Text(value.data.value.toString(), textDirection: TextDirection.ltr));
}

void main() => runApp(App());
```
