### ISSUE TITLE
ValueNotifier<ENUM> doesnt work right?

### ISSUE THREAD

**Issue by logemann** [rrousselGit/provider#268]
Just played around with ValueNotifier in combination with ChangeNotifierProvider. Am i correct that you cant use enums as a type for a ValueNotifier?

Its like the 10th time i am trying to use these very low-featured enums in Dart (Flutter) and now i am really giving up ;-) Just need a clarification thats its not a usage issue on my side here. 

Thanks

**Comment by logemann** [comment]
It does work. Imported that ENUM without the package: prefix. Man...  somehow painful that you can even make errors like these in dart.

**Comment by doodatales** [comment]
@logemann What do you mean when you say that you imported enum without the package prefix?  I wasn't able to get this to work either.
