### ISSUE TITLE
Hub: a convenient architecture with Provider

### ISSUE THREAD

**Issue by gloomie** [rrousselGit/provider#270]
@rrousselGit and the Provider community

Hi, this is not an issue, just a question/discussion about project architecture and Provider. It's just about to confirm that my planned 'convenient' architecture is viable and not dangerous, before implementing it:

I'm learning dart/flutter and I would like to use Provider as a 'DI' for Mobx and my other logic/flow classes. What I would love to do is having some class instances that I will register with Provider and distribute them for usage in the widget tree or even inside other logic/state classes. So far so good....

The **questionable part** is that I would like to use a central **Hub** class that is going to hold the instances as class fields and just register the Hub instance as an injectable Provider, usable from ui widgets and the flow/utility classes, like this:

**Hub: instances registration**
```dart
class Hub {
  MobxStore store;
  Network net;
  TapEvents taps;

  Hub() {
    this.store = MobxStore(this);
    this.net = Network(this);
    this.taps = TapEvents(this);
  }
}
```

**Provider: Hub injection**
```dart
void main() {
  runApp(Injector());
}

class Injector extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider(
      builder: (context) => Hub(),
      child: App(),
    );
  } 
}
```
**Usage - in widgets**
```dart
class MyColumn extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final hub = Provider.of<Hub>(context);
    return Column(
      children: <Widget>[
        for (int i = 0; i <= hub.store.articlesList.length - 1; i++)
          GestureDetector(
            onTap: hub.taps.onTapArticle(),
            child: MyTile(i),
          )
      ],
    );
  }
}
```

**Usage - in logic classes**
```dart
class MobxStore = _MobxStore with _$MobxStore;

abstract class _MobxStore with Store {
  Hub hub;

  @observable
  int userPref = 0;

  @action
  void savePrefs() {
    hub.storage.savePrefs(userPref);
    hub.network.syncPrefs(userPref);
  }

  _MobxStore(this.hub)
}
```

So, Hub holds instances for every helpfull class in the project (here they act like singletons, but Hub could easily support factory too) . Each class that wants some communication with other classes does this through the active instance of the Hub class , which is instantiated (and injected to the tree) with Provider. 

This seems to me like having the convenience of get_it, but designed around the healthier top-down setup of Provider. Is this actually the case? Do you see any major architectural flaws that I could repair? 

My intention is to use this setup for middle-level apps, working solo (no team) and having 'code convenience / do the damn work' at a very high ranking in my priorities. So, I'm not asking whether this is the healthiest setup, but rather if it seems to you healthy-enough.

Thanks for your time!

**Comment by rrousselGit** [comment]
Hi!

What's the purpose of that `hub` class? Can't you just pass each instance using providers?

**Comment by gloomie** [comment]
Some of the advantages I see:

- **Code clarity and convenience**: You just bring a hub reference into a widget's build and you can use any library class without additional provider.of calls. Just like the locator pattern, but without globals and always context-aware!
- **Single-point registration**: Each logic class is centrally instantiated from the Hub (not from other consumer classes). So, you can thoroughly inspect what's going on with your instances flow from a single point, instead of digging into deep code.
- **Single-point communications**: Each logic class holds a single reference ('this' hub) for communicating with the outter world. No need to mess with ad-hoc instance passes from class to class, which is extremely error-prone when dealing with many domain classes. For example, in the State domain, Hub substitutes the role of a central Root store that orchestrates the other stores, instead of letting them know about each other. Imagine this done for free with all your domain classes (network, storage, etc).
- **Forced abstractability**: You are  reminded to design your classes around abstract layers of the outter world, not specific implementations of functionality in other classes. For example, in my first post I have registered a TapEvents class inside Hub, which hides store.actions implementation from widgets and lets me initialize several domain-class calls in one pass, completely removing logic design from UI. Of course, you could implement this without a hub for the widget classes. Hub however, gives you only one Provider.of to play with, so you are reminded that everything should be instantiated from Hub - you are forced to consider potential abstractions. Moreover, you cannot call Provider.of without a context when dealing with domain/logic classes that are communicating with each other. You either have to use a locator with globals or an instances manager like Hub. The latter is designed to be instantiated and controlled from within Provider, so everything complies to the Flutter top-down paradigm.

**Comment by rrousselGit** [comment]
I personally doubt it is a good thing.
`provider` voluntarily doesn't have a _single global state_, and instead multiple small composable states.

This has many added benefits, such as:
- uni-directional data-flow for a good maintainability
- providers can be placed in the middle of the widget tree so that their object is disposed of when not needed anymore
- the upcoming 4.0.0 will include lazy-loading out of the box. Such a class would have to reimplement it 

Similarly, `provider` already is a "single-point registration" and "force abstraction".
And the "single-point communication" is _voluntarily_ not supported for health purpose and instead enforce uni-directional data-flow.
Such "Hub" is the opposite of uni-directional data-flow, which means that all objects are aware of all other objects. This can easily degrade the code quality.
