### ISSUE TITLE
Error: Could not find the correct Provider<Login> above this MyApp Widget

### ISSUE THREAD

**Issue by IgnacioCentola** [rrousselGit/provider#272]
I´m getting this error when using `ChangeNotifierProvider`:

> I/flutter (13888): Error: Could not find the correct Provider<Login> above this MyApp Widget
I/flutter (13888):
I/flutter (13888): To fix, please:
I/flutter (13888):
I/flutter (13888):   * Ensure the Provider<Login> is an ancestor to this MyApp Widget
I/flutter (13888):   * Provide types to Provider<Login>
I/flutter (13888):   * Provide types to Consumer<Login>
I/flutter (13888):   * Provide types to Provider.of<Login>()
I/flutter (13888):   * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
I/flutter (13888):   * Ensure the correct `context` is being used.

I´ve searched for a solution but I´m still clueless about what´s the bug, because there´s no way my `ChangeNotifierProvider` is not a parent of the `MaterialApp` widget. Here´s my `main.dart`:

`void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          builder: (ctx) => Login(),
        )
      ],
      child: MaterialApp(
        title: 'Spend-o-meter',
        theme: ThemeData(
          primarySwatch: Colors.blue, accentColor: Colors.blueAccent,
          // primaryIconTheme: IconThemeData(color: Colors.red)
        ),
        home: Provider.of<Login>(context).isLoggedIn()
            ? MyHomePage()
            : LoginScreen(),
        routes: {
          // MyHomePage.ROUTE_NAME: (ctx) => MyHomePage(),
          AddGastoScreen.ROUTE_NAME: (ctx) => AddGastoScreen(),
        },
      ),
    );
  }
}`

Here´s my Provider:

`class Login with ChangeNotifier {
  bool _loggedIn = false;

  bool isLoggedIn() => _loggedIn;

  void login() {
    _loggedIn = true;
    notifyListeners();
  }

  void logout() {
    _loggedIn = false;
    notifyListeners();
  }
}`

I tried many things, like using `MultiProvider`, `ChangeNotifierProvider.value()` or instantiating the Provider outside the `return` statement, but nothings works. 

I remember using the 3.0.0 version in a previous app and not getting this error, so i thought It could be dependecy-related, an internal issue.

Anyone know how to fix it? Thanks!

**Comment by BaranMichal25** [comment]
You used wrong build context - context of `MyApp`, which doesn't have any Providers above it. 
To fix this you can use `Builder` widget like this:
```dart
class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          builder: (ctx) => Login(),
        )
      ],
      child: MaterialApp(
        title: 'Spend-o-meter',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          accentColor: Colors.blueAccent,
        ),
        home: Builder(
          builder: (lowerContext) {
            return Provider.of<Login>(lowerContext).isLoggedIn()
                ? MyHomePage()
                : LoginScreen();
          },
        ),
      ),
    );
  }
}
```

or use Consumer class:
```dart
class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          builder: (ctx) => Login(),
        )
      ],
      child: MaterialApp(
        title: 'Spend-o-meter',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          accentColor: Colors.blueAccent,
        ),
        home: Consumer<Login>(
          builder: (lowerContext, login, _) {
            return login.isLoggedIn()
                ? MyHomePage()
                : LoginScreen();
          },
        ),
      ),
    );
  }
}
```

**Comment by IgnacioCentola** [comment]
@BaranMichal25 using the `Consumer` worked. Thank you very much!
