### ISSUE TITLE
Dynamically creating a MultiProvider

### ISSUE THREAD

**Issue by gmparker2000** [rrousselGit/provider#274]
I have a use case for dynamically creating a multi provider.  To illustrate my problem here is some code that doesn't work:

```
List<ChangeNotifierProvider> providers = List<ChangeNotifierProvider>();
providers.add(new ChangeNotifierProvider<AppProvider>(builder: (context) =>MyFirstProvider()));
providers.add(new ChangeNotifierProvider<AppProvider>(builder: (context) =>MySecondProvider()));

return MultiProvider(
      providers: providers,
      child: ...
```

So all my providers extend AppProvider.  The problem arises when I try to use a comsumer like this:

```
Consumer<MyFirstProvider>(
    builder: (context, provider, _) => ...
```

This fails because the type MyFirstProvider is not found.  Presumably this is because it only finds AppProvider up the hierarchy.

Is there a way to make this work?

**Comment by bitsydarel** [comment]
why dont you specify the concreate type of the dependency ?
not the super type.

**Comment by rrousselGit** [comment]
Instead of `ChangeNotifier<AppState>(create: (_) => MyFirstState())` do `ChangeNotifier<MyFirstState>(create: (_) => MyFirstState())`

**Comment by gmparker2000** [comment]
Sorry I guess I should have been more clear.  The example above was simplified for illustration purposes.  The architecture of the application we are creating is very modular.  When we create the MultiProvider we don't know the concrete types of the providers.  We have a service that returns a List of abstract AppProviders of various types.  So I can't do as mentioned above.

**Comment by rrousselGit** [comment]
You will still need to somehow statically make it clear that a given object is a specific subclass of AppState


Maybe you can do something like this:

```dart
List<AppState> appStates;

Widget appStateToProvider(AppState appState) {
  if (appState is MyFirstState) {
    return ChangeNotifierProvider<MyFirstState>(...)
  } else if (appState is MySecondState) {...} 
}


MultiProvider(
  providers: [
    for (appState in appStates)
      appStateToProvider(appState),
  ], 
)
```

**Comment by gmparker2000** [comment]
If I have to I will fallback to something like your example.   When I specify the consumer I supply the concrete type.  Was hoping that the algorithm that searches back up the hierarchy to find the provider would be smart enough to compare the concrete types and see that they are the same.  I don't know the Dart type system but in Java if you have an instance of AppProvider and you call getClass you would get back the derived type MyFirstProvider or MySecondProvider.  Then this could be compared to the type specified on the Consumer to see if they match.

**Comment by rrousselGit** [comment]
> Was hoping that the algorithm that searches back up the hierarchy to find the provider would be smart enough to compare the concrete types and see that they are the same

The thing is, there's no walking up the tree involved.

Inheritedwidgets are stored in a HashMap<Type, InheritedWidget>

The key being the generic type passed to Provider.of

As such, reading providers is O(1) as opposed to walking up the tree. 

But that means what you're asking for is not feasible.

**Comment by gmparker2000** [comment]
I don't suppose there is a way to use the concrete type as the map key?  Something like asking the AppProvider for it's runtime type to use as the key instead of just accepting AppProvider as the type?

**Comment by rrousselGit** [comment]
That would require overriding `runtimetype` of InheritedWidgets to be the value's type instead

This is simply a pretty bad idea and not feasible because sometimes the value is lazy loaded

**Comment by bitsydarel** [comment]
Introducing qualifiers or named providers would allow such use cases, @rrousselGit do you plan on introducing named providers or qualifiers ?
Like in dagger DI library.

**Comment by rrousselGit** [comment]
What do you mean @bitsydarel?
Do you mind sharing an example?

**Comment by gmparker2000** [comment]
I was thinking the same thing about using named providers.  So I would imagine creating a provider like this:

`
new ChangeNotifierProvider<AppProvider>(name: "myProvider", builder: (context) => MyProvider());
`

Then you could access the provider with the name:

`
Provider.of<MyProvider>("myProvider", context)
`
etc.  You wouldn't even really need the generics in this case.  Especially given that you are using a map, which in this case would use the name as the key.

Anyhow, I can get by without support but given that I am trying to use some modularity and good OO design principles in this application it would be nice if I could leverage them in the consumer/provider piece as well.

**Comment by rrousselGit** [comment]
Such named provider is not feasible. Inheritedwidgets do not allow that

The map is not from provider but Flutter framework. I do not have the ability to change what the keys are

**Comment by bitsydarel** [comment]
@rrousselGit So as far as i understand this map is keeped in the flutter framework ?
Can you share the link to class where flutter keep it?

I think named provider is achievable without touching flutter framework code.

Reading the implementation of [Providier.of()](https://github.com/rrousselGit/provider/blob/00d0f8f8020dcfe876bd7826f176e1ca2feeaac7/packages/provider/lib/src/provider.dart#L267), the most important line is the _value field.
If this field was a map with key (String) and the dependency as the value.

When returning the value for Provider.of<AppProvider>("myProvider", context)
You would check if there's a key matching the "myProvider"  if yes provide the value if not then null.

This behavior would only happen is someone provide different Provider with the same generic type.

**Comment by rrousselGit** [comment]
The Map is on the Element class of Flutter


Provider._value **cannot** be a  map. Your suggestion seem to forget that InheritedWidgets are _not_ global variables
They can be placed anywhere in the widget tree, and we can have multiple ones of the same type on purpose


Anyhow, I fail to understand the real use-case of a "scope" feature. 
The Readme is gives a much safer alternative: https://github.com/rrousselGit/provider#can-i-obtain-two-different-providers-using-the-same-type

**Comment by bitsydarel** [comment]
You can get the same InheritedWidgets instance the same way you currently do with the Provider.of.
inheritFromWidgetOfExactType(type) or ancestorInheritedElementForWidgetOfExactType(type)

Your suggestion is safer but it's does not allow dynamic value, your suggestion assume that we known the value at compile time.

**Comment by rrousselGit** [comment]
> You can get the same InheritedWidgets instance the same way you currently do with the Provider.of.

But Provider.of will always point to _that_ inherited widget even if the name is on another one

```dart
Provider.value(
  value: 0,
  name: 'foo'
  child: Provider.value(
    value: 1,
    name: 'bar'
    child: Builder(
      builder: (context) {
        Provider.of<int>(context, name: 'bar'); // 1
        Provider.of<int>(context, name: 'foo'); // impossible to find
      },
    ),
  ),
)
```

**Comment by rrousselGit** [comment]
The only potential solution to what you're suggesting would be to obtain all the ancestors InheritedWidgets of the same type when instantiating an InheritedWidget, and merge them by name


Something that would transform the previous example implicitly into:


```dart
Provider.value(
  value: { 'foo': 0 },
  name: 'foo'
  child: Builder(
    builder: (context) {
      return Provider.value(
        value: { ...Provider.of<Map<Object, int>, 'bar':  1,
        name: 'bar'
        child: Builder(
          builder: (context) {
            Provider.of<int>(context)['bar']; // 1
            Provider.of<int>(context)['foo']; // impossible to find
          },
        ),
      ),
    },
  ),
)
```


But that adds a relatively big overhead to _all_ provider users, even those that don't use this feature (so most people).

**Comment by bitsydarel** [comment]
I had in mind a different implementation, in every build method for the current provider.

```dart
class Provider ... {
...
@override
  Widget build(BuildContext context) {
    assert(() {
      Provider.debugCheckInvalidValueType?.call<T>(delegate.value);
      return true;
    }());
    final type = _typeOf<InheritedProvider<T>>();
    provider = context.ancestorInheritedElementForWidgetOfExactType(type)?.widget as InheritedProvider<T>;
    if (provider != null) {
        return provider..._value[specifiedKeyOrDefault] = delegate.value;
    } else {
       return InheritedProvider<T>(
          initialKey: specifiedKeyOrDefault,
          initialValue: delegate.value,
          ....
      );
    }

    return InheritedProvider<T>(
      value: delegate.value,
      updateShouldNotify: updateShouldNotify,
      child: child,
    );
  }
}
```

**Comment by rrousselGit** [comment]
Sorry for the late reply
If you're looking for a scope feature, then there's a WIP implementation on #296 

It adds a `scope` parameter to providers and `Provider.of`.

It should be what you're looking for. I'm still thinking about whether it's good for the API or not though.

**Comment by rrousselGit** [comment]
I'll close this.

I don't plan to work on this. Users are already very confused with `BuildContext`. Adding a "scope" would drastically increase the complexity.

**Comment by tafaust** [comment]
@rrousselGit Sorry for the necro bump but to me this is a very much needed feature. The issue that I have is the following:

```dart
ChangeNotifierProvider<FooProvider<BarDelegate>>.value(
  value: fooBarProvider,
),
```

with

```dart
class BaseDelegate { ... }

class BarDelegate extends BaseDelegate { ... }

class FooProvider<T extends BaseDelegate> { ... }
```

The provider won't recognize the correct generic type `BarDelegate` of my `FooProvider`. I understand that the scope parameter may be a valid workaround for my use case. Any ideas?
