### ISSUE TITLE
Provider can't pass data between two pages

### ISSUE THREAD

**Issue by asjqkkkk** [rrousselGit/provider#278]
Hello, I encountered this problem a few months ago.

When I use provider to pass data between two pages, provider will throw ``ProviderNotFoundError`

<img width="200" alt="WeChatd9f7f414b3898b141971ebece0be6f29" src="https://user-images.githubusercontent.com/30992818/70033144-cf6fdf00-15e9-11ea-8266-b7a00c95233b.gif">

**MainPage code**

```
void main() {
  runApp(
    ChangeNotifierProvider<MainModel>(
      create: (_) => MainModel(),
      child: MaterialApp(home: MyHomePage(title: "Main Page",)),
    ),
  );
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  void _goToNextPage(BuildContext context) {
    Navigator.of(context).push(new MaterialPageRoute(builder: (ctx) {
      return ChangeNotifierProvider<TwoModel>(
        child: MyHomePageTwo(
          title: "Second Page",
        ),
        create: (_) => TwoModel(),
      );
    }));
  }

  @override
  Widget build(BuildContext context) {
    final mainModel = Provider.of<MainModel>(context);
    
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _goToNextPage(context),
        child: Icon(Icons.chevron_right),
      ),
    );
  }
}
```

**SecondPage code**

```
class MyHomePageTwo extends StatelessWidget {
  final String title;
  MyHomePageTwo({@required this.title});

  void _goToNextPage(TwoModel model,BuildContext context,{MainModel mainModel}) {
    Navigator.of(context).push(new MaterialPageRoute(builder: (ctx) {
      return ChangeNotifierProvider<ThreeModel>(
        child: MyHomePageThree(
          title: "Third Page",
        ),
        create: (_) => ThreeModel(),
      );
    }));
  }

  @override
  Widget build(BuildContext context) {
    final mainModel = Provider.of<MainModel>(context);
    final twoModel = Provider.of<TwoModel>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _goToNextPage(twoModel,context,mainModel: mainModel,),
        child: Icon(Icons.chevron_right),
      ),
    );
  }
}
```

**ThirdPage code**

```
class MyHomePageThree extends StatelessWidget {

  final String title;
  
  MyHomePageThree({@required this.title});
  
  @override
  Widget build(BuildContext context) {
    final mainModel = Provider.of<MainModel>(context);
    final model = Provider.of<ThreeModel>(context);
    final twoModel = Provider.of<TwoModel>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
    );
  }
}
```

- In SecondPage I can get ``MainModel`` and ``TwoModel`` by  **Provider.of<T>()**;
- In ThirdPage I can get "MainModel" and "ThreeModel" by  **Provider.of<T>()**, but if I call ``final model = Provider.of<ThreeModel>(context)``, it will throw ``ProviderNotFoundError``

I have read a little source code, Is it due to InheritedWidget‘s problem? 
😄I don't know if this is compliant

**Comment by rrousselGit** [comment]
> In ThirdPage I can get "MainModel" and "ThreeModel" by Provider.of(), but if I call final model = Provider.of<ThreeModel>(context), it will throw ProviderNotFoundError

You mean `Provider.of<TwoModel>(context)` right?

Your `_goToNextPage` did insert `ThreeModel` but not `TwoModel` on the new page.

In the snippet you gave, your `_goToNextPage` receives `TwoModel` as parameter, but doesn't do anything with it. 

You should create another ChangeNotifierProvider next to the `ThreeModel` one, to insert `TwoModel` on the new page

**Comment by asjqkkkk** [comment]
> > In ThirdPage I can get "MainModel" and "ThreeModel" by Provider.of(), but if I call final model = Provider.of(context), it will throw ProviderNotFoundError
> 
> You mean `Provider.of<TwoModel>(context)` right?
> 
> Your `_goToNextPage` did insert `ThreeModel` but not `TwoModel` on the new page.
> 
> In the snippet you gave, your `_goToNextPage` receives `TwoModel` as parameter, but doesn't do anything with it.
> 
> You should create another ChangeNotifierProvider next to the `ThreeModel` one, to insert `TwoModel` on the new page


Maybe my description is not accurate enough

## MainPage

![image](https://user-images.githubusercontent.com/30992818/72624467-fc9e0400-3981-11ea-907a-c4f79bcdea9b.png)

![image](https://user-images.githubusercontent.com/30992818/72624382-ce202900-3981-11ea-90ac-d92066ea9bac.png)

## SecondPage

![image](https://user-images.githubusercontent.com/30992818/72624435-ee4fe800-3981-11ea-9b76-97a8f9d63e6a.png)

![image](https://user-images.githubusercontent.com/30992818/72624540-1c352c80-3982-11ea-9234-e75a2f1e4d8a.png)


## ThirdPage

![image](https://user-images.githubusercontent.com/30992818/72624571-2b1bdf00-3982-11ea-8f8d-56d29accb8c4.png)

![image](https://user-images.githubusercontent.com/30992818/72624588-3242ed00-3982-11ea-98c6-ac421d1c9375.png)

I mean, why I can use ``Provider.of<TwoModel>(context)`` to get ``TwoModel`` in SecondPage, but I can't get it in ThirdPage. At the same time, I can use ``Provider.of<MainModel>(context)`` to get  ``MainModel`` in ThirdPage. I don't konw why I can't ``TwoModel`` in ThirdPage just like how I get the ``MainModel``

😄Ask for help！

**Comment by rrousselGit** [comment]
The third page is not a descendant of the second page.

Providers are scoped. A provider located in one page is available only to that specific page.

If you want one provider to be available to all pages, put it above `MaterialApp`

**Comment by asjqkkkk** [comment]
oh,I konw.

Thank you!😄
