### ISSUE TITLE
Not able to import MultiProvider in the Project.

### ISSUE THREAD

**Issue by Shajeel-Afzal** [rrousselGit/provider#286]
I am trying to import `MultiProvider` and `ChangeNotifierProvider` in the project but it is importing the wrong file from the .pub-cache directory. 

<img width="887" alt="Screenshot 2019-12-14 at 9 56 10 PM" src="https://user-images.githubusercontent.com/3718283/70851895-059c4100-1ebd-11ea-8ec7-5cb38a72f70d.png">

I am using Provider version 3.2.0, I have also tried 3.0.0! 

Flutter version and OS details are: `Flutter (Channel master, v1.13.3-pre.23, on Mac OS X 10.14.3 18D109`

Any solution?

**Comment by rrousselGit** [comment]
That's unrelated to `provider` and is instead an issue with VScode

Consider raising an issue on https://github.com/Dart-Code/Dart-Code


For now, just add the import manually:

```dart
import 'package:provider/provider.dart';
```
