### ISSUE TITLE
How to use ProxyProvider with a Stream?

### ISSUE THREAD

**Issue by owais635** [rrousselGit/provider#287]
So I have a UserAuthService, which gives me the user's uid (UserAuthService.user.uid). And I'm able to successfully access the uid through out the app using `String userId = Provider.of<UserAuthService>(context).user.uid;`.
```
class UserAuthService with ChangeNotifier {
  FirebaseAuth _auth;
  FirebaseUser _user;

  UserAuthService.instance() : _auth = FirebaseAuth.instance {
    _auth.onAuthStateChanged.listen(_onAuthStateChanged);
  }

  FirebaseUser get user => _user;
....
```

I need the uid to look up the courses for the user (a Stream returned by Firestore's Collection Snapshot).
```
Stream<QuerySnapshot> getCoursesStream(String userId) {
  return Firestore.instance
      .collection('users')
      .document(userId)
      .collection('courses')
      .snapshots();
```

In my main file, I would like to access the uid from UserAuthService Provider, and pass it to my getCoursesStream(), and have the returned Stream<QuerySnapshot> available throughout the app.

This is what I'm doing currently but it gives me the following error `Tried to use Provider with a subtype of Listenable/Stream (Stream<QuerySnapshot>).
`
```
class MyApp extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<UserAuthService>.value(
            value: UserAuthService.instance()),

        ProxyProvider<UserAuthService, Stream<QuerySnapshot>>(
          update: (context, userAuthService, _) =>
              getCoursesStream(userAuthService.user.uid),
        )
      ],
      child: MaterialApp(
        title: 'MyApp',
        debugShowCheckedModeBanner: true,
        theme: appTheme,
        home: App(),
      ),
    );
  }
}
```

Note the reason I have `update: (context, userAuthService, _) =>` is because if *I don't have `update`*, dart lint gives the error `The parameter 'update' is required. .dart(missing_required_param)`.

When I try to use use `create: (context, userAuthService, _) => getCoursesStream(userAuthService.user.uid)`, the dart lint gives the error `The argument type 'Stream<QuerySnapshot> Function(BuildContext, dynamic, dynamic)' can't be assigned to the parameter type 'Stream<QuerySnapshot> Function(BuildContext)'.dart(argument_type_not_assignable)`

Also I have tried using `getCoursesStream(Provider.of<UserAuthService>(context).user.uid),` inside ProxyProvider but that doesn't work either.

Any help would be appreciated, Thanks.

**Comment by rrousselGit** [comment]
A "proxy" variant of StreamProvider doesn't exist at the moment. This is technically unsupported

Consider making a separate issue if you have a proposal on how to implement a StreamProxyProvider

**Comment by nomyzs** [comment]
Hello @rrousselGit .
Thanks for great work on this library!

I am wondering is there any workaround for this? Similar to one mentioned here https://github.com/rrousselGit/provider/issues/120#issuecomment-501165716 ?

It seems that this solution stopped working after updating to 4.0.x version. 

Appreciate any help on this!

**Comment by rrousselGit** [comment]
I'm not sure. What stopped working with the v4?

**Comment by nomyzs** [comment]
Well, I am not getting any updates on the stream anymore when I use stream provider
```
  StreamProvider<CurrentViewer>(
    create: (context) =>
        Provider.of<AuthenticationService>(context, listen: false)
            .currentViewer,
  ),
```

```
  @override
  void didChangeDependencies() {
    currentViewer = Provider.of<CurrentViewer>(context);
    super.didChangeDependencies();
  }
```

**Comment by rrousselGit** [comment]
Could you make a separate issue with a way to reproduce your problem?

**Comment by nomyzs** [comment]
Done, #340 .
Hope it helps, thank you!

**Comment by lukepighetti** [comment]
Can you explain to me why a proxy StreamProvider is technically unsupported?

Use case is as follows:

```
Stream<String> myUserId()
Stream<UserModel> myUserModel(String userId)
```

`myUserModel` depends on `myUserId`

We'd like to be able to have `myUserModel` `StreamProvider` active if `myUserId` `StreamProvider`'s last value was not null.

**Comment by rrousselGit** [comment]
The difficulty is in not calling `update` again when not necessary.

While a basic support for it should be doable, we'll likely want to support more advanced syntax such as `context.select`. It also needs extra care to handle GlobalKeys (or make them unsupported, which is probably saner)

Overall it requires quite a bit of work. And to be honest, I don't believe that Proxy* were the correct approach to the problem.

It may not be the answer you're looking for, but Riverpod solves this problem much better. You could do:


```dart
final userProvider = StreamProvider<User>((ref) => auth.authStateChanges());

final fbUserPublicInfoProvider = StreamProvider<FBUserPublicInfo>((ref) async* {
  final user = await ref.watch(userProvider.last);
  yield* user.service.myPublicInfo();
});
```
