### ISSUE TITLE
inheritFromWidgetOfExactType deprecated

### ISSUE THREAD

**Issue by masseelch** [rrousselGit/provider#289]
With the new stable release of flutter v1.12.1 a deprecation notice was added to `inheritFromWidgetOfExactType`. 

Instead `dependOnInheritedWidgetOfExactType` should be used. 

This is the issue on the flutter repo: https://github.com/flutter/flutter/pull/44189

**Comment by rrousselGit** [comment]
Yes, it's solved as part of https://github.com/rrousselGit/provider/pull/243
