### ISSUE TITLE
About MultiProvider tree structure

### ISSUE THREAD

**Issue by fantasy525** [rrousselGit/provider#292]
```dart
MultiProvider(
      providers: [
        Provider.value(value: Parent()),
        Provider.value(value: Child())
      ],
      child: MaterialApp(
        home: LoginPage(),
      ),
    );
```

Child can get parent's data, but Parent cannot get child's data.
Why not set it to a flat data structure？

**Comment by rrousselGit** [comment]
The fact that Parent cannot get Child's data is voluntary and will not be changed

That's called uni-directional data-flow and is a key component of the `provider` architecture
