### ISSUE TITLE
ChangeNotifierProxyProvider should provide on create

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#293]
I updated my `Provider` package to version `3.2.0` and I got some `deprecated` messages. I see now there's `create` and `update` on `ChangeNotifierProxyProvider2`, instead of the old `builder`.

The old `builder` provided all the proxies at the first creation, but the new `create` doesn't. My `ChangeNotifier` gets on its constructor some references that will never change and it can't be used without it. For example, my `ChangeNotifier` uses `FirebaseAuth` and `Crashlytics`, it needs it upon creation, the constructor enforces that it will never be used without it, that's why constructors are made in the first place, to enforce this kind of security. Now I have to make my `final` fields modifiable, which is something I don't like, as `final` is a documentation on itself.

I think `create` should be updated to provide all the proxies, the same way that `update` does, this way we can create our `ChangeNotifier` safely and avoid hard to track bugs.

**Comment by rrousselGit** [comment]
This was a simple rename of `builder` -> `update`. There's no behavior change involved.

**Comment by feinstein** [comment]
I still get a warning saying that `create` is a required field, besides I would like to use `create`, it's a good optimization for creating with things that don't change, is it there a reason to not also provide the values on `create`?

**Comment by rrousselGit** [comment]
>  is it there a reason to not also provide the values on create?

The values passed to `update` can change over time.

If you want to use `create`, do:

```dart
create: (context) {
  return MyNotifier(Provider.of<Something>(context, listen: false);
}
```

**Comment by feinstein** [comment]
Ok, I just thought the first call could be sent to `create` and if something changes than `update` is called, and it's up to us the users to know what to use on `create` and what to use on `update` as we know what is need at creation and what is not.

**Comment by anotherglitchinthematrix** [comment]
You can also use `create: null`.

**Comment by rrousselGit** [comment]
Well, it'd is generally un-safe to do so and would confuse people (especially considering all providers, not just proxy variants can do the same thing).

In the end, it's just a bunch of functions. You can make yourself a function that helps with the verbosity.

Like:

```dart
Provider<MyClass>(
  create: two((A a, B b) => MyClass(a, b)),
)
```

where `two` is:

```dart
T Function(BuildContext) two<T, A, B>(T cb(A a, B b)) {
  return (context) {
    return cb(
      Provider.of<A>(context, listen: false),
      Provider.of<B>(context, listen: false),
    );
  }
}
```

**Comment by feinstein** [comment]
Thanks, but that's not much readable, I will stick to calling 'Provider.of<>`.
