### ISSUE TITLE
Improvement: Simplify ChangeNotifierProxyProvider boilerplate ?

### ISSUE THREAD

**Issue by Thibault2ss** [rrousselGit/provider#294]
Hey,

thanks for the work you've done on Provider @rrousselGit. I'm getting more & more into flutter with full provider v3 state management, and I'm liking it a lot !

I have a question though: instead of using `ChangeNotifierProxyProvider`, I'm using the following method, which is less boilerplate code I think. I just want your confirmation that I'm not using anything wrongly, and that my method won't lead to any issues.

*to give you some context:*
- I'm creating a view (`OnboardingView` in **onboarding_view.dart**). It's a StatelessWidget, supposed to contain only the UI part.
- I also create a model to manage this view's state. (`OnboardingViewModel` in **onboarding_view_model.dart**). It's a ChangeNotifier. In this model, I create and manage other ChangeNotifiers extensions (in my case a `PageController` and several `TextEditingController`...).
- Now, of course, when the `PageController` or `TextEditingController` has some properties changing (eg. `page` or `text`), my `OnboardingViewModel` doesn't notify its Consumers inside `OnboardingView`, because we didn't swap out those controllers.
- There are several ways to deal with that, one of them being using the provider class you created `ChangeNotifierProxyProviderX` (X being 1, 2, 3... depending on the number of internal ChangeNotifiers).
- Now, me I'm actually still using a `ChangeNotifierProvider` in my view. My method is : in my `OnboardingViewModel`, in the constructor, I'm using the **`_bindOtherChangeNotifiers`** method below:

*onboarding_view.dart (simplified)*
```dart
class OnboardingView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<OnboardingViewModel>(
        create: (context) => OnboardingViewModel(),
        child: Container(
          child: ...
          ....
          ........ TextField(
                        controller: Provider.of<OnboardingViewModel>(context, listen: false).textController
                    )
          .......
          ....... Consumer<OnboardingViewModel>(
                         builder: (context, model, _) => Text(model.
                    )
        )
    );
  }
}
```

*onboarding_view_model.dart (simplified)*
```dart
class OnboardingViewModel extends ChangeNotifier {

   final pageController = PageController();
   final textController = TextEditingController();

   List<ChangeNotifier> get _notifiersToBound => [pageController, textController];

   OnboardingViewModel(){
      _notifiersToBound.forEach(_bindOtherChangeNotifiers);
   }

   void _bindOtherChangeNotifiers(ChangeNotifier notifier) {
       if (!notifier.hasListeners) {
         notifier.addListener(() => notifyListeners());
        }
   }
   ....
}
```

This works for me, so I'm thinking of creating a class **`BaseChangeNotifier`** containing the getter `_notifiersToBound` the contructor code, and the method `_bindOtherChangeNotifiers`, so that whenever I want to create a new `ChangeNotifier` extension with others `ChangeNotifiers` in it, I will instead extend `BaseChangeNotifier`, and @override the `_notifiersToBound` getter.

What do you think ??

**Comment by rrousselGit** [comment]
Well, if your goal is to have _less_ boilerplate, then this doesn't seem.

It's alright, but it misses the point of why we use `WhateverProxyProvider`. It's not about internal state, but about separate objects.

In your case `pageController` is owned by `OnboardingViewModel`, while with something like:

```dart
MultiProvider(
  providers: [
    Provider(create: (_) => Auth()),
    ChangeNotifierProxyProvider<Auth, User>(
      create: (_) => User(),
      update: (_, auth, user) => user..auth = auth.
    ),
  ]
)
```

then `Auth` and `User` are completely independent from each other.

**Comment by rrousselGit** [comment]
Closing this since I don't think further comments is needed
