### ISSUE TITLE
Feature Request: ValueListenableProxyProvider

### ISSUE THREAD

**Issue by wytesk133** [rrousselGit/provider#297]

**Comment by rrousselGit** [comment]
Sure, I don't mind it.
But first, do you mind explaining your use-case?

`ValueListenableProvider` is relatively unused nowadays, and I was even thinking of removing it.
If you have a good use-case, I'd love if you could share it

**Comment by wytesk133** [comment]
I would say my use-case is similar to #287 (but being a `ValueNotifier` rather than a `Stream`).

By the way, since you thought about removing `ValueListenableProvider`, what would you suggest instead of using that?

**Comment by rrousselGit** [comment]
> By the way, since you thought about removing ValueListenableProvider, what would you suggest instead of using that?

I'll first need to know what _you_ are doing with ValueListenableProvider

**Comment by rrousselGit** [comment]
Implementing a ValueListenableProxyProvider is very easy (as opposed to streams) 

The mean issue is: why do we want it?

**Comment by rrousselGit** [comment]
Closing this, as I still don't understand the use-case and received no answer

Feel free to reopen it if you still need it
