### ISSUE TITLE
Dooes Create really needs a BuildContext?

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#299]
`Create` looks like this:

```
typedef Create<T> = T Function(BuildContext context);
```

But I can't think of a case where any `Provider` will have `create:` called outside a `build()` method, so `context` will always be available, isn't this redundant?

**Comment by rrousselGit** [comment]
Keep in mind that a BuildContext points to a very specific location in the widget tree, and that widgets uses unidirectional dataflow.

The context of your custom widget may not have access to the same things that the provider's context does.

**Comment by feinstein** [comment]
Hmm, ok, I can't see where this would be useful, but I will close it then.
