### ISSUE TITLE
Error: The method 'didChangeDependencies' isn't defined for the class 'ProxyProvider<CategoriesRepository, CategoryBloc>'.

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/provider#301]
I updated Provider package now.. Now my code is not working..

> lib/screens/home/widgets/drawer.dart:297:15: Error: The method 'didChangeDependencies' isn't defined for the class 'ProxyProvider<CategoriesRepository, CategoryBloc>'.
>  - 'ProxyProvider' is from 'package:provider/src/proxy_provider.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.0.0/lib/src/proxy_provider.dart').
>  - 'CategoriesRepository' is from 'package:yellochat/repository/category_repository.dart' ('lib/repository/category_repository.dart').
>  - 'CategoryBloc' is from 'package:yellochat/screens/categories/category_bloc.dart' ('lib/screens/categories/category_bloc.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'didChangeDependencies'.
>             ).didChangeDependencies(context, categoryBloc).deleteEntry();

```
  ProxyProvider<CategoriesRepository, CategoryBloc>(
              update: (context, categoryRepo, categoryBloc) =>
                  CategoryBloc(categoryRepository: categoryRepo),
              dispose: (context, categoryBloc) => categoryBloc.dispose(),
            ).didChangeDependencies(context, categoryBloc).deleteEntry();
```

**Comment by rrousselGit** [comment]
Doing that was never supported and is anti pattern.

Just call your method directly inside `update`

**Comment by bhanuka96** [comment]
> Doing that was never supported and is anti pattern.
> 
> Just call your method directly inside `update`

Just like that:  ` update: (context, categoryRepo, categoryBloc) =>categoryBloc.deleteEntry(),` or ` update: (context, categoryRepo, categoryBloc) =>//categoryBloc.deleteEntry(),
                  CategoryBloc(categoryRepository: categoryRepo).deleteEntry(),`

**Comment by bhanuka96** [comment]
> > Doing that was never supported and is anti pattern.
> > Just call your method directly inside `update`
> 
> Just like that: ` update: (context, categoryRepo, categoryBloc) =>categoryBloc.deleteEntry(),` or ` update: (context, categoryRepo, categoryBloc) =>//categoryBloc.deleteEntry(), CategoryBloc(categoryRepository: categoryRepo).deleteEntry(),`?

**Comment by rrousselGit** [comment]
The second option should work
