### ISSUE TITLE
Error: 'SingleChildCloneableWidget' isn't a type. 

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/provider#302]
I updated Provider. Now it's not working

> lib/di/global_providers.dart:13:6: Error: Type 'SingleChildCloneableWidget' not found.
> List<SingleChildCloneableWidget> globalProviders = [
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/di/global_providers.dart:18:6: Error: Type 'SingleChildCloneableWidget' not found.
> List<SingleChildCloneableWidget> independentServices = [
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/di/global_providers.dart:23:6: Error: Type 'SingleChildCloneableWidget' not found.
> List<SingleChildCloneableWidget> dependentServices = [
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/main.dart:18:16: Error: The argument type 'List<invalid-type>' can't be assigned to the parameter type 'List<SingleChildWidget>'.
>  - 'List' is from 'dart:core'.
>  - 'SingleChildWidget' is from 'package:nested/nested.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/nested-0.0.4/lib/nested.dart').
>     providers: globalProviders,
>                ^
> lib/di/global_providers.dart:13:6: Error: 'SingleChildCloneableWidget' isn't a type.
> List<SingleChildCloneableWidget> globalProviders = [
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/di/global_providers.dart:18:6: Error: 'SingleChildCloneableWidget' isn't a type.
> List<SingleChildCloneableWidget> independentServices = [
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/di/global_providers.dart:23:6: Error: 'SingleChildCloneableWidget' isn't a type.
> List<SingleChildCloneableWidget> dependentServices = [

Code

```
List<SingleChildCloneableWidget> globalProviders = [
  ...independentServices,
  ...dependentServices,
];

List<SingleChildCloneableWidget> independentServices = [
  Provider.value(value: YelloChatDb()),
  Provider.value(value: YelloChatClient()),
];

List<SingleChildCloneableWidget> dependentServices = [
  ProxyProvider<YelloChatDb, CategoryDao>(
      update: (context, yelloChatDb, categoryDao) => CategoryDao(yelloChatDb)),

  ProxyProvider<YelloChatDb, SubCategoryDao>(
      update: (context, yelloChatDb,subCategoryDao) => SubCategoryDao(yelloChatDb)),

  ProxyProvider<YelloChatDb, UserDao>(
    update: (context, yelloChatDb, userdAO) => UserDao(yelloChatDb),
  ),

  ProxyProvider<YelloChatDb, EnquiriesDao>(
    update: (context, yelloChatDb, enquiriesDao) => EnquiriesDao(yelloChatDb),
  ),

  ProxyProvider<YelloChatClient, CategoryService>(
      update: (context, yelloChatClient, categoryService) =>
          CategoryService.create(yelloChatClient.chopperClient),
      dispose: (context, categoryService) => categoryService.client.dispose()),


  ProxyProvider2<CategoryDao, CategoryService, CategoriesRepository>(
      update: (context, categoryDao, categoryService, categoryRepository) =>
          CategoriesRepository(categoryDao: categoryDao, categoryService: categoryService)),

  ProxyProvider2<UserDao, CategoryService, UserRepository>(
      update: (context, userDao, categoryService, categoryRepository)=>
          UserRepository(userDao: userDao, categoryService: categoryService)
  ),

  ProxyProvider2<SubCategoryDao, CategoryService, SubCategoriesRepository>(
      update: (context, subCategoryDao, categoryService, subCategoryRepository) =>
          SubCategoriesRepository(categoryDao: subCategoryDao, categoryService: categoryService)),

  ProxyProvider2<EnquiriesDao, CategoryService, EnquiriesRepository>(
      update: (context, enquiriesDao, categoryService, enquiriesRepository) =>
          EnquiriesRepository(enquriesDao: enquiriesDao, categoryService: categoryService))
];
```

**Comment by rrousselGit** [comment]
To begin with, I would not recommend doing that. Consider creating this list directly inside your MultiProvider.

Doing what you're currently doing adds unnecessary complexity & ceremony for no real benefits. 
In fact you're actually decreasing testability. 


If you insist on doing that though, the Readme is pretty clear about it:

Replace SingleChildCloneableWidget by SingleChildWidget (from provider/single_child_widget.dart)

**Comment by bhanuka96** [comment]
> To begin with, I would not recommend doing that. Consider creating this list directly inside your MultiProvider.
> 
> Doing what you're currently doing adds unnecessary complexity & ceremony for no real benefits.
> In fact you're actually decreasing testability.
> 
> If you insist on doing that though, the Readme is pretty clear about it:
> 
> Replace SingleChildCloneableWidget by SingleChildWidget (from provider/single_child_widget.dart)

@rrousselGit thanks. I replaced it.
