### ISSUE TITLE
provider: ^4.0.0 Flutter Performance refreshing 

### ISSUE THREAD

**Issue by q876625596** [rrousselGit/provider#305]
After upgrading provider ^ 4.0.0, Flutter Performance keeps refreshing even without any operation.

**Comment by mono0926** [comment]
I also confirmed this problem.
It is reproduced at https://github.com/rrousselGit/provider/tree/master/packages/provider/example, and I suspect that all applications which uses provider 4.0.0 are affected this problem.

There were no problems at version 3.2.0:
https://github.com/rrousselGit/provider/tree/v3.2.0/packages/provider/example

**Comment by rrousselGit** [comment]
What are you talking about by performance keepks refreshing?

**Comment by mono0926** [comment]
@rrousselGit 

This refreshing started after upgrading to 4.0.0.

![a](https://user-images.githubusercontent.com/1255062/71436705-f5dcf200-2731-11ea-88af-f993c1b2cd5a.gif)

**Comment by q876625596** [comment]
> 您在谈论什么让性能刷新呢？

``` dart
ChangeNotifierProvider.value(
      value: value,
      child: Consumer(
        builder: (BuildContext context, S data, Widget child) {
          return Container();
        },
      ),
    )
```
I just added this code and did nothing.

**Comment by isanimu** [comment]
I also confirmed this.

Even with this simple code

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        StreamProvider<String>.value(
          value: Stream.empty(),
        ),
      ],
      child: MaterialApp(
        title: 'Kalpati',
        home: Container(),
      ),
    );
  }
}
```

High cpu usage from iOS Simulator.

<img width="272" alt="ss" src="https://user-images.githubusercontent.com/11643300/71440798-4273fd80-2731-11ea-8758-bd61c5f871c9.png">

**Comment by rrousselGit** [comment]
Ah that's actually a misuse of SchedulerBinding to infer if the `listen` flag of `Provider.of`

It's actually a fairly critical bug, and I'll have to disable that inference and make a hot-fix

**Comment by pqsky7** [comment]
I still have this issue after changing the .yaml file to 'provider: ^4.0.0-hotfix.1' , is this the proper way to get the updates?

**Comment by rrousselGit** [comment]
Make sure you ran `pub get` and that the lock file correctly says it uses the hot fix version

**Comment by pqsky7** [comment]
> Make sure you ran `pub get` and that the lock file correctly says it uses the hot fix version

it worked, many thx

**Comment by isanimu** [comment]
> I still have this issue after changing the .yaml file to 'provider: ^4.0.0-hotfix.1' , is this the proper way to get the updates?

Something like this should work. Once the newest version is released you can remove the overrides.

```
dependencies:
  provider: ^4.0.0

dependency_overrides:
  provider: 4.0.0-hotfix.1
```

**Comment by rrousselGit** [comment]
A 4.0.1 is coming in a matter of minutes.

Which means ^4.0.0 will properly get the new version

**Comment by eggzotic** [comment]
Great thx - was hunting down the cause of this issue for last few days also. Really killed my dev env when running 2 emulators. Provider had always behaved so well before this. Great to have it back to normal again :-)
