### ISSUE TITLE
Add description of `lazy` parameter to the documentation of `Provider` constructor

### ISSUE THREAD

**Issue by AlexanderArendar** [rrousselGit/provider#307]
In the release notes for 4.0.0 I've found this useful piece:

```
The new create/update callbacks are lazy-loaded, which means they are called the first time the value is read instead of the first time the provider is created.

If this is undesired, you can disable lazy-loading by passing lazy: false to the provider of your choice:

FutureProvider(
  create: (_) async => doSomeHttpRequest(),
  lazy: false,
  child: ...
)
```

Would be great to add it to documentation of the `Provider` constructor.

**Comment by rrousselGit** [comment]
There's already a mention to it:

> It is worth noting that the `create` callback is lazily called.
> It is called the first time the value is read, instead of the first time
> [Provider] is inserted in the widget tree.
>
> This behavior can be disabled by passing `lazy: false` to [Provider].

It that not enough in your opinion?

**Comment by AlexanderArendar** [comment]
Sure, it is enough. Just I started to look for info on the constructor parameter in the constructor documentation, naturally :) Only after I've checked the class level docs.
