### ISSUE TITLE
provider 4.0.0 unnecessary rebuilds

### ISSUE THREAD

**Issue by FisherWL** [rrousselGit/provider#308]
I notice this when my laptop gets overheated (both CPU and GPU) processing an uncomplicated app on Simulator. Dart DevTool performance overlay also shows flutter rebuilds every page -- including static pages -- all the time. 

The problem is solved by downgrading the package to 3.2.0.

I use the counter app example that the package provides to test, by Dart DevTool and temperature monitor, the problem recurs, and can also be solved by downgrading to 3.2.0.

**Comment by rrousselGit** [comment]
It's fixed as part of 4.0.0-hotfix.1
