### ISSUE TITLE
Error : Could not find the correct provider <CheckOut> above this cartPage widget ..

### ISSUE THREAD

**Issue by kwansion** [rrousselGit/provider#309]
Please advise us how to fix the above issue .. 
there are some suggestions : 
-Ensure the provider<Checkout> is an ancestor to this cartpage widget..
-Provide types to Provider<checkout> 
-Provides type to consumer<checkout>
-Provide.of<Checkout>()
-Always use package import. 
-ensure the correct 'context' is being used.

Simon,
Malaysia

**Comment by ggcsriram** [comment]
Have you wrapped your material app with Provider or MultiProvider??

**Comment by rrousselGit** [comment]
Consider asking this kind of question on StackOverflow instead

Github is only here for bug reports
