### ISSUE TITLE
Doubt with Provider.of

### ISSUE THREAD

**Issue by basketball-ico** [rrousselGit/provider#31]
Hello, nice library 😀.
can you explain me please what is the difference.

```dart
Provider.of<SomeClass>(context, listen: true)
```

```dart
Provider.of<SoomeClass>(context, listen: false)
```
I noticed that I can use in `initState()` of `StatefulWidget` when is `false`, and can't use when is `true`, but really I don't know why :(

Thanks

**Comment by rrousselGit** [comment]
`listen` determines if the widget that use the value wants to rebuild when the value change.

For example, if:

```dart
Provider<int>(
  value: 42,
 child: ...
)
```

is later replaced by:

```dart
Provider<int>(
  value: 24,
  child: ...
```

Then this will trigger a rebuild of all widgets that called `Provider.of(context)` with `listen` to `true`.

**Comment by wheel1992** [comment]
Hi @rrousselGit, is there a way to update the value in a stateful widget?
For example

```dart
Provider<int>(
  value: _value,
  child: ...
)

...
// Some widget calls (e.g. onClick event)
setState({
  _value = 1234,
})


```

**Comment by rrousselGit** [comment]
Yes, that's how you should do it.

**Comment by wheel1992** [comment]
I'm stuck with this for quite long. 

For example:
App init provider value as 123. 
In Screen A, a button update the provider value to 456.
However, in screen B, it return the provider value as 123 instead of 456.

**App:**

```dart
MultiProvider(
  providers: [
    Provider<int>(
      value: 123,
      child: Material
    ),
    ... // other providers
  ],
  child: MaterialApp(
  ...
  ),
)

```

**Screen A:**

```
Widget build(BuildContext context) {
  return Provider.of<int>(
    value: _value,
    child: Scaffold(
      ...
      Button(
        onPressed: ()  {
          setState({
            _value = 456,
          });
        }
      ),
    ),
  );
}

```

**Screen B:**

```
int _value;

Widget build(BuildContext context) {
  final _provider = Provider.of<int>(context);
  // when access _provider, the value still returns 123 instead of 456
}

```

**Comment by enetor** [comment]
It looks to me that you have two provides: one in the App and one in Screen A. The value you got in Screen B is from the App, which is a value literal of 123.

**Comment by wheel1992** [comment]
@enetor But Screen A is supposed to change the `value` in Provider by doing `setState({ value = 456 })`. 

@enetor @rrousselGit Do you have recommendation on how to update the `value` from Screen A?

**Comment by jasonlaw** [comment]
hi, what if we are using ChangedNotifierProvider? will it based on the notifiedListener, instead of value changed? and i suppose it will not rebuild if listen = false right?

**Comment by PandaGeek1024** [comment]
It seems listen parameter is not working in my example, whenever I call setState, it will just rebuild the child widget no matter listen is false or not. Am I doing something wrong? @rrousselGit 

```
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Provider<int>.value(
              value: _counter,
              child: Column(
                children: <Widget>[TestStatelessWidget()],
              ))),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class TestStatelessWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // result is updated anyway, listen = false does not work.
    int result = Provider.of<int>(context, listen: false);
    return Text("result: $result");
  }
}
```

**Comment by mono0926** [comment]
@PandaGeek1024 

This should work.
Without `const`, TestStatelessWidget is built by setState even though `listen = false`.
`listen = false` just suppresses rebuild triggered by Provider not State's setState.

```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Provider<int>.value(
              value: _counter,
              child: Column(
                // add `const`
                children: const <Widget>[TestStatelessWidget()],
              ))),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class TestStatelessWidget extends StatelessWidget {
  // add `const` constructor
  const TestStatelessWidget();
  @override
  Widget build(BuildContext context) {
    // result is updated anyway, listen = false does not work.
    int result = Provider.of<int>(context, listen: false);
    return Text("result: $result");
  }
}
```

**Comment by rrousselGit** [comment]
Exactly

Which is also why provider love const constructors/statelesswidgets

**Comment by Wes1324** [comment]
Hey @rrousselGit and @mono0926,

I am having a similar issue to @PandaGeek1024 except that my app (in the following attached document) uses only StatelessWidgets so there is no call to setState anywhere. 

[Listen doesn't work.txt](https://github.com/rrousselGit/provider/files/3688184/Listen.doesn.t.work.txt)

For that reason, I am not sure what is causing my text widgets to rebuild themselves.

I have been trying to figure this out for 2 days now so any insight you could give would be much appreciated.

**Comment by mono0926** [comment]
@Wes1324 

This should work.

```dart
TextField(
            onChanged: (newText) {
              Provider.of<Data>(context, listen: false).updateValue(newText);
            },
          )
```

**Comment by Wes1324** [comment]
@mono0926 
Please can you explain why this works?
Thank you

**Comment by mono0926** [comment]
@Wes1324 
 I wrote about that in this article. This is written in Japanese, sorry.
https://link.medium.com/7a5FrRXFw0

**Comment by rrousselGit** [comment]
I believe that the new syntax (`context.read`/`watch`) makes it clear enough for this issue to be closed.

Feel free to correct me if you disagree
