### ISSUE TITLE
[v4] ChangeNotifierProxyProvider update loop with async update method

### ISSUE THREAD

**Issue by moodstubos** [rrousselGit/provider#314]
It seems there is a behavior change between version 3 and 4. 

Please see this code which works like expected:

```
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(providers: [
      ChangeNotifierProvider<FrModel>(lazy: false, create: (_) => FrModel()),
      ChangeNotifierProxyProvider<FrModel, MtModel>(
        lazy: false,
        create: (_) => MtModel(),
        update: (_, frModel, mtModel) => mtModel..update(frModel.value),
      ),
    ], child: MyHomePage());
  }
}

class FrModel with ChangeNotifier {
  String value = "";

  FrModel();

  void setValue(String newValue) {
    value = newValue;
    notifyListeners();
  }
}

class MtModel with ChangeNotifier {
  String mtvalue = "";

  MtModel();

  void update(String frvalue) {
    // update values

    mtvalue = frvalue + " / foobar " + Random().nextInt(100).toString();

    notifyListeners();
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(Provider.of<MtModel>(context, listen: true).mtvalue),
            FlatButton(
              color: Colors.red,
              onPressed: () {
                Provider.of<FrModel>(context, listen: false).setValue("some value " + Random().nextInt(100).toString());
              },
              child: Icon(Icons.add),
            )
          ],
        )));
  }
}

```

now change the update method of second model to a async method:

 ```
void update(String frvalue) async {
    // update values

    // do http stuff
    await Future.delayed(Duration(seconds: 2));

    mtvalue = frvalue + " / foobar " + Random().nextInt(100).toString();

    // after fetch data from server
    notifyListeners();
  }
```

result: an update loop.
the async is necessary cause of server requests on value update.
I am pretty sure this worked in version 3

flutter version is 1.13.6

**Comment by rrousselGit** [comment]
what do you mean by update loop?

**Comment by moodstubos** [comment]
the update method of the ChangeNotifierProxyProvider is called over and over again

![device-2020-01-05-001616](https://user-images.githubusercontent.com/5072232/71772758-f73bc500-2f50-11ea-87b5-d2c20f07a13d.gif)

**Comment by rrousselGit** [comment]
Ah, yes.

You're not supposed to make unchecked side-effects inside your `update` method.

You need to change it to something like:

```dart
void update(String frvalue) {
  if (frvalue == this.frvalue) return;
  this.frvalue = frvalue;
  // do some requests
}
```

**Comment by moodstubos** [comment]
jup, I confirm this works. Maybe this could be added to the documentation (or I missed it).
 
thanks a lot for your work and your support :blue_heart: :blue_heart: :blue_heart:

**Comment by moodstubos** [comment]
hmmm, after some investigations the described behaviour change is very sad.

if the parameter of update method is a non-primitive we need a deep copy to compare with old value

see this example: 
it does not work, unless we create a new list (List.from()) which takes even more memory as the list is passed by reference:

void update(List<Foo> value ) {
  // (..) compare value with frvalue (e.g via ListEquality) does not work
  this.frvalue = value;
}

in v3 this was definitely not necessary

**Comment by rrousselGit** [comment]
It definitely was necessary before too.
It's just that it was harder to see. 

So people could _think_ that they didn't need it.

**Comment by rrousselGit** [comment]
Why would you need a deep copy though? I don't quite understand

**Comment by moodstubos** [comment]
> It definitely was necessary before too.

but it had a different behaviour.

see same code as above (with async update method):

```
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(providers: [
      ChangeNotifierProvider<FrModel>(create: (_) => FrModel()),
      ChangeNotifierProxyProvider<FrModel, MtModel>(
        create: (_) => MtModel(),
        update: (_, frModel, mtModel) => mtModel..update(frModel.value),
      ),
    ], child: MyHomePage());
  }
}

class FrModel with ChangeNotifier {
  String value = "";

  FrModel();

  void setValue(String newValue) {
    value = newValue;
    notifyListeners();
  }
}

class MtModel with ChangeNotifier {
  String mtvalue = "";

  MtModel();

  void update(String frvalue) async {
    // update values

    // do http stuff
    await Future.delayed(Duration(seconds: 2));

    mtvalue = frvalue + " / foobar " + Random().nextInt(100).toString();

    // after fetch data from server
    notifyListeners();
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(Provider.of<MtModel>(context, listen: true).mtvalue),
            FlatButton(
              color: Colors.red,
              onPressed: () {
                Provider.of<FrModel>(context, listen: false).setValue("some value " + Random().nextInt(100).toString());
              },
              child: Icon(Icons.add),
            )
          ],
        )));
  }
}
```

BUT with v3 instead of v4 like at the screenrecord above:
`provider: ^3.1.0`


result (no update loop):

![device-2020-01-06-161937](https://user-images.githubusercontent.com/5072232/71827464-93281680-30a0-11ea-9b61-a9002192f643.gif)

**Comment by moodstubos** [comment]
Another simplified example which worked in v3.2.0 but doesn't in v4.0.1

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  print("[main] runApp");
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(providers: [
      ChangeNotifierProvider<FirstModel>(lazy: false, create: (_) => FirstModel()),
      ChangeNotifierProxyProvider<FirstModel, SecondModel>(
        lazy: false,
        create: (_) => SecondModel(),
        update: (_, firstModel, secondModel) => secondModel..dependencyUpdated(),
      ),
    ], child: MyHomePage());
  }
}

class FirstModel with ChangeNotifier {
  void updateValue() {
    // do something

    print("[FirstModel] updated");

    notifyListeners();
  }
}

class SecondModel with ChangeNotifier {
  void dependencyUpdated() async {
    print("[SecondModel] updated");

    // isLoading = true;
    print("[SecondModel] notifyListeners");
    notifyListeners();

    // do http stuff
    await Future.delayed(Duration(seconds: 2));

    // isLoading = false;
    print("[SecondModel] notifyListeners");
    notifyListeners();
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
            child: RaisedButton(
          onPressed: () {
            Provider.of<FirstModel>(context, listen: false).updateValue();
          },
          child: Icon(Icons.add),
        )));
  }
}
```

### Output v3:

> I/flutter ( 2230): [main] runApp
> I/flutter ( 2230): [SecondModel] updated
> I/flutter ( 2230): [SecondModel] notifyListeners
> I/flutter ( 2230): [SecondModel] notifyListeners

### Output v4:

> I/flutter ( 1682): [main] runApp
> I/flutter ( 1682): [SecondModel] updated
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] updated
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] updated
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] updated
> I/flutter ( 1682): [SecondModel] notifyListeners
> I/flutter ( 1682): [SecondModel] notifyListeners
> ...

**Comment by rrousselGit** [comment]
> If we pass non-primitive values (like a List<>) to the update method, we will unable to simply compare the new value with old one. In this case we have to create a copy of current value.

Why? A == should be enough. 
You don't need a deep compare. Compare what you use

**Comment by rrousselGit** [comment]
The behavior is the same in the sense that such check was always necessary.

But it is called more often, which makes it more obvious that you need this check

**Comment by moodstubos** [comment]
> The behavior is the same in the sense that such check was always necessary.

okay

**Comment by khangly** [comment]
Has this been added to the documentation? It took me a lot of time yesterday figuring out this issue. I hope others don't have to go through this.

**Comment by mkhtradm01** [comment]
@rrousselGit in my case, I am updating ChangeNotifierProxyProvider list with a StreamProvider. But I have to reload the app first before getting the values, even after lazy is set to false on both providers
