### ISSUE TITLE
Provider.of bug on version >= 4.0.0

### ISSUE THREAD

**Issue by Underscore25** [rrousselGit/provider#325]
Hello,
I have a problem with Provider.of<...>(...) on version >= 4.0.0

**My class FooState:**
```
class FooState extends ChangeNotifier {
  User _user;
  User get user => _user;
  set user(User value) {
    _user = value;
  }
}
```

**On top of my app :**
```
ChangeNotifierProvider(
      create: (context) => FooState(),
      child: App(),
)
```
**In child App widget :**
`Provider.of<FooState>(context).user = user;`
=> Execution stop, no error

This is work in 3.0.0

Do you have an idea ?

**Comment by Underscore25** [comment]
I miss something : Provider.of<FooState>(context).user = user;

**Comment by Underscore25** [comment]
Correction : Provider.of\<FooState\>(context).user = user;

**Comment by rrousselGit** [comment]
I do not understand the problem.

Could you give an example that can be executed?

**Comment by Underscore25** [comment]
Arf sorry me bad, if i add `listen: false` it's work :
`Provider.of<FooState>(context,listen: false).user = user;`

**Comment by ruslanraupoff** [comment]
> Arf sorry me bad, if i add `listen: false` it's work :
> `Provider.of<FooState>(context,listen: false).user = user;`
which you version, i have such problem not working listen: false
