### ISSUE TITLE
Possible memory leak on StreamProvider

### ISSUE THREAD

**Issue by beljand** [rrousselGit/provider#326]
I'm using Provider with MultiProvider basically on all my views.

I use `StreamProvider` which returns a List of Models (Class instances), which are created while listening to a `Firebase` subscription (deserialization).

I've noticed a steady memory increase while navigating do different routes. Turns out that those Models are still inside the heap (according to DevTools). Even when forcing GC, they are not removed from the heap. As far as I can tell those Models are not used by any widget after navigating to a different View, also `maintainState` is set to `false`.

What am I missing here? Shouldn't StreamProvider dispose of all values emitted by the stream?

**Comment by rrousselGit** [comment]
It's unlikely StreamProvider, but instead your stream the issue

**Comment by beljand** [comment]
Not yet 100% sure but maybe I've discovered the issue...

in the same MultiProvider I have a `StreamProvider` (multiple providers in fact) which returns a stream (BehaviourSubject) from a class instance (let's call it `ProjectViewModel` which is, in fact, a `ChangeNotifier` class). In the same MultiProvider there is also a `ChangeNotifierProvider` which returns this whole class (`ProjectViewModel`).

Inside `ProjectViewModel` I manually cancel subscriptions and close all streams when `ProjectViewModel` is disposed of, but somehow all Objects that were emitted inside the stream, are still present inside the heap.

When I remove the `ChangeNotifierProvider` from the MultiProvider, this issue disappears (Objects are removed from memory).

Maybe I'm abusing the ChangeNotifierProvider to pass around / provide the class instance?

**Comment by rrousselGit** [comment]
Do you mind making a code snippet to reproduce your issue?
A description is too abstract to understand what is happening.

**Comment by beljand** [comment]
After extensive investigation, I came to the conclusion that the issue is not related directly to StreamProvider.

It was a case of not completed/closed streams and database connections (SQLite) inside ViewModel class, therefore there was still an existing reference to the emitted instances.
