### ISSUE TITLE
What's the complexity of dispatching updates in Provider?

### ISSUE THREAD

**Issue by BaranMichal25** [rrousselGit/provider#329]
What's the complexity of dispatching notifications to all consumers - in other words all Widgets calling `Provider.of<T>`, of a `Provider<T>` ?

So for example let's say we have one StreamProvider of String and N consumers of the String below it. What's then the complexity of dispatching updates to all consumers when there is a new value in a Stream?

```dart
class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<String>.value(
      value: someStream,
      child: Column(  // There is in total N consumers of String in the subtree of this Column
        children: [
          Consumer<String>(...),
          Consumer<String>(...),
          Row(
            children: [
              Consumer<String>(...),
              Selector<String, bool>(...),
            ],
          ),
          ...,
          ...,
          ...,
          ProxyProvider<String, int>(...),
          Selector<String, bool>(...),
        ],
      ),
    );
  }
}
```

For comparison [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) has a O(N²) complexity for this and I was curious what it is in case of Provider

**Comment by rrousselGit** [comment]
It's O(N), like with Inheritedwidget

And it's debounced. 
Calling `notifyListeners` multiple times within the same frame will notify dependents only once.

**Comment by BaranMichal25** [comment]
That's great, thank you!

**Comment by virgule-xyz** [comment]
Hi :)

So, is it best and simplier to have only one Provider for the whole app (instead of many for different features...) and only using Selector (instead of many Consumer or Provider.of) ?

**Comment by rrousselGit** [comment]
Having many providers is probably better
