### ISSUE TITLE
All consumers of all providers in multiprovider are notified rather than just those with same type

### ISSUE THREAD

**Issue by dannyboy424242** [rrousselGit/provider#330]
I suspect I have misunderstood documentation so apologies. I thought I understood that multiproviders would allow descendants access to distinct sets of data and that only the consumers citing the right type would be notified, but it seems that any call to notifyListeners() in any provider in the list will cause a rebuild on ALL widgets that consume any of the providers in the list.

If I have a top level of:
```
return MultiProvider(
      providers: [
        ChangeNotifierProvider<DannysInt>(create: (context) => DannysInt()),
        ChangeNotifierProvider<DannysString>(create: (context) => DannysString()),  ],
      child: MaterialApp(
```

Then lower in the tree are some distinct consumers, each only consuming one of those two:
```
Consumer<DannysInt>(
              builder: (context, value, child) {
                debugPrint('Doing Builder for the Int');
                return Text(value.myInteger.toString());
              },
```
......and another one that listens to the other provider
each of the classes looks like:
```
class DannysInt with ChangeNotifier {
   int myInteger = 5;
   void incrementMyInteger() {
     myInteger++;
     notifyListeners();
   }
}
```

......again the other is similar but with a string

When, within a button widget somewhere else in the tree I access the provider and call the little void functions that tweak the int or the string and call notifyListeners
`provider.of<DannysInt>(context, listen:false).incrementMyInteger()`

I expect that because notifyListeners is being called from within a specific class, only consumers which are listening to that particular class would have their builder methods called, but it seems that all consumers are being re-built.

Its almost certainly me being stupid, its probably expected behaviour or me misunderstanding so apologies and feel free to delete this and tell me to go re-read the documentation.

**Comment by rrousselGit** [comment]
> I thought I understood that multiproviders would allow descendants access to distinct sets of data and that only the consumers citing the right type would be notified

That's the case.

Your code doesn't give me enough information on where your undesired rebuild comes from, but that's unlikely to be `Consumer` rebuilding by itself and it may instead be one of its ancestors that rebuilt.

**Comment by dannyboy424242** [comment]
Hi,

Yes, it helped, because you were right, of course! Somehow I was inducing a build higher up, or perhaps better to say that some of my widgets were higher up than I thought. I slowly cut code out and simplified as much as I could so that I could paste in the whole code to ask again what I was doing, and eventually I managed to get rid of the bug. Just for completeness I include below my code (which WORKS as expected). i.e. the Build methods are only called when expected, when the notifyListeners from the correct class is called.
```

        import 'package:flutter/material.dart';
    import 'package:provider/provider.dart';
    
    void main() => runApp(MyApp());
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MultiProvider(
            providers: [
              ChangeNotifierProvider<DannysInt>(create: (context) => DannysInt()),
              ChangeNotifierProvider<DannysString>(create: (context) => DannysString()),
            ],
            child: MaterialApp(home: TheScreen()));
      }
    }
    
    
    class TheScreen extends StatelessWidget {
    
      @override
      Widget build(BuildContext context) {
        return Column(
          children: <Widget>[
            Consumer<DannysInt>(
                builder: (context, value, child) {
                  debugPrint('Doing Builder for the Int');
                  return Text(value.myInteger.toString());
                }),
            Consumer<DannysString>(
                builder: (context, value, child) {
              debugPrint('Doing Builder for the String');
              return Text(value.myString);
            }),
            FloatingActionButton(
                onPressed: () => {Provider.of<DannysString>(context, listen: false).addToMyString()},
                tooltip: 'Increment', child: Icon(Icons.text_fields) ),
            FloatingActionButton(
                onPressed: () => {Provider.of<DannysInt>(context, listen: false).incrementMyInteger()},
                tooltip: 'Increment', child: Icon(Icons.add) ),
    
          ],
        );
      }
    }
    
    class DannysInt with ChangeNotifier {
      int myInteger = 5;
      void incrementMyInteger() {
        myInteger++;
        notifyListeners();
      }
    
    }
    
    class DannysString with ChangeNotifier {
      String myString = 'danny';
      void addToMyString() {
        myString += ' blurp';
        notifyListeners();
      }
    }

```
Thanks again for your help and feel free to delete this thread if you feel best - I fully accept that this was a coding error on my part and nothing to do with your (excellent) plugin.

**Comment by rrousselGit** [comment]
Haha, no worries. Enjoy 😊
