### ISSUE TITLE
Why selected value must be immutable?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/provider#335]
when I use selector new value must be clone of old value.
in Notifier:
`List<bool> get items => List.from(item);` => rebuild normal.
but `List<bool> get items => item;` => not rebuild.
so items always copy from origin item when I call notifiListener();

**Comment by rrousselGit** [comment]
Selected values must be immutable because otherwise comparing the previous and new value returned by `selector` will always be equal to itself.

So `Selector`/`select` will never be able to know that something changed

**Comment by tbm98** [comment]
Is there any data structure that can check for changes as soon as we change the data inside it?
For example, an object can store a list and every time that list changes data, it marks a variable indicating that the data has changed or not?

**Comment by rrousselGit** [comment]
Yes, that's ChangeNotifier

**Comment by tbm98** [comment]
I just have write a class for handle/store list. It solved this problem without clone origin value.

my ChangeNotifiers class:
```
class MainNotifier extends ChangeNotifier {
  StoreList _storeList = StoreList<bool>();

  StoreList get storeList => _storeList;

  MainNotifier() {
    _initItems();
  }

  void _initItems() {
    // add some item to StoreList
    for (int i = 0; i < 10; i++) {
      _storeList.addItem(i % 2 == 0);
    }

    // every time add item, StoreList set status ro Status.changed
    // now must reset status to Status.nothing to avoid rebuild
    _storeList.resetStatus();
  }

  void clickItem(int i) {
    bool ii = _storeList.getItem(i);
    ii = !ii;
    _storeList.updateItem(i, ii);
    print('click on $i');
    notifyListeners();
  }

  void afterRebuild() {
    //afterRebuild called when shouldRebuild run
    //if shouldRebuild is true => rebuild listview then must resetStatus
    // to nothing to avoid rebuild next time
    _storeList.resetStatus();
  }

  void notifiOnly() {
    print('notified');
    notifyListeners();
  }
}
```
my custom class
```
enum Status{
  changed,nothing
}
class StoreList<T>{
  List<T> _items = [];
  Status _status = Status.nothing;


  T getItem(int index){
    return _items[index];
  }

  void addItem(T item){
    _items.add(item);
    _status = Status.changed;
  }

  void deleteItem(int index){
    _items.removeAt(index);
    _status = Status.changed;
  }

  void updateItem(int index,T newItem){
    if(_items[index] == newItem){
      return;
    }
    _status = Status.changed;
    _items[index] = newItem;
  }

  void setItems(List<T> newItems){
    //todo: check with deep equals
    _items = newItems;
    _status = Status.changed;
  }

  List<T> getItems(){
    return _items;
  }

  bool isChanged(){
    return _status == Status.changed;
  }

  Status getStatus(){
    return _status;
  }

  void resetStatus(){
    _status = Status.nothing;
  }
}
```
and my view:
```
                  Expanded(
                    child: Selector<MainNotifier, StoreList>(
                      builder: (context, data, child) {
                        print('rebuild listview');
                        return ListView.builder(
                            itemCount: data.getItems().length,
                            itemBuilder: (context, index) {
                              return ListTile(
                                selected: data.getItem(index),
                                title: Text(index.toString()),
                                subtitle: Text(index.toString()),
                                onTap: () {
                                  Provider.of<MainNotifier>(context,
                                          listen: false)
                                      .clickItem(index);
                                },
                              );
                            });
                      },
                      selector: (context, data) => data.storeList,
                      shouldRebuild: (pre, next) {
                        print('pre: ${pre.getStatus()} - next: ${next.getStatus()}');
                        final rebuild = next.isChanged();

                        Provider.of<MainNotifier>(context, listen: false)
                            .afterRebuild();
                        return rebuild;
                      },
                    ),
                  )
```
did I do anything wrong or any problems ?
and should I do that?

**Comment by smiLLe** [comment]
@tbm98 
> For example, an object can store a list and every time that list changes data, it marks a variable indicating that the data has changed or not?

If you want to use Selector, you must at least change your List. Create a new List as you mentioned here ```List<bool> get items => List.from(item);```
 Or even better, use one of the oss packages out there like equatable or built_value. they will help you implement ```==```and ```hashCode```, so Selector wont be an issue anymore :)

**Comment by tbm98** [comment]
@smiLLe
Is there a performance problem?  When each item changes, it returns a copy of the list and it costs O (n).

**Comment by smiLLe** [comment]
I don't know what you are exactly trying to achieve with your code, but to me, it looks way too spaghetti :) 

If you don't want to make your items immutable but still want to update the whole UI after an item has changed, try something like this:

```dart
class MyList extends ValueNotifier<List<Items>> {
  MyList(List<Items> initialList): super(initialList);

  void updateItem(item)  {
    List<Items> _list = value;
    // replace item in _list
    value = List.from(_list);
  }
}
```

Then you can provide MyList
``` dart
ValueNotifierProvider( ... );
````
and consume like:

```dart
Consumer<MyList>(builder: (_, list, __) => ListView.builder( ... ) );
```

Now whenever you call ```myList.updateItem(item)``` your ```Consumer``` will rebuild

**Comment by tbm98** [comment]
I will post to reddit because it is not the problem of provider :))

**Comment by 0921dma** [comment]
I work a lot with mutable state (Mostly models with sub classes) and came up with a very simple and central solution to this 'issue'. The following code or something similar allows selecting mutable objects by selecting the objects hash instead of the object itself.

`
// ----------------------------------------------------
// * Actual Logic
// ----------------------------------------------------

class SomeProvider extends ChangeNotifier {
  List<int> someMutableList = [];

  /// Adds a value to [someMutableList] and notifies listeners.
  void add() {
    someMutableList.add(1);
    notifyListeners();
  }
}

extension BuildContextExtensions2 on BuildContext {
  /// Shortcut to read [SomeProvider].
  SomeProvider get someProvider => read<SomeProvider>();

  /// Shortcut to select a value from [SomeProvider].
  ///
  /// f is pointing to the value to be selected from [SomeProvider].
  T someProviderSelect<T>(T Function(SomeProvider p) f) {
    /// Using deep collection quality to ensure unique hash for collections.
    select((SomeProvider p) => const DeepCollectionEquality().hash(f(p)));

    /// Get the actual value by reading [SomeProvider].
    return f(someProvider);
  }
}

// ----------------------------------------------------
// * Usage Example
// ----------------------------------------------------

class Screen extends StatelessWidget {
  const Screen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    /// Button to add a value to [SomeProvider.someMutableList].
    final addButton = ElevatedButton(
      onPressed: context.someProvider.add,
      child: const Text('Add value to list'),
    );

    /// Simple widget to display [SomeProvider.someMutableList].
    ///
    /// The list is selected from [SomeProvider] using vanilla [BuildContext.select].
    final vanilla = Builder(
      builder: (context) {
        final list = context.select((SomeProvider p) => p.someMutableList);
        return Column(
          children: [
            const Text('Vanilla: '),
            Text('[${list.join(', ')}]'),
          ],
        );
      },
    );

    /// Simple widget to display [SomeProvider.someMutableList].
    ///
    /// The list is selected from [SomeProvider] using the extension [BuildContext.someProviderSelect].
    final extension = Builder(
      builder: (context) {
        final list = context.someProviderSelect((p) => p.someMutableList);
        return Column(
          children: [
            const Text('Extension: '),
            Text('[${list.join(', ')}]'),
          ],
        );
      },
    );

    return Column(
      children: [
        vanilla,
        const SizedBox(height: 10),
        extension,
        const SizedBox(height: 10),
        addButton,
      ],
    );
  }
}

void main() {
  runApp(
    ChangeNotifierProvider(
      create: (_) => SomeProvider(),
      child: const MaterialApp(
        home: Scaffold(
          body: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Screen(),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}

`
