### ISSUE TITLE
Provider.of<bool>(context) fails where Consumer<bool>(builder) succeeds

### ISSUE THREAD

**Issue by maletor** [rrousselGit/provider#337]
Is that by design? I thought they were fairly interchangeable.

**Comment by smiLLe** [comment]
Please don't provide primitive values.
[recommended way](https://github.com/rrousselGit/provider#can-i-obtain-two-different-providers-using-the-same-type)

can you share some code :)?

**Comment by maletor** [comment]
My issue is invalid.
