### ISSUE TITLE
Error: Could not find the correct Provider<User> above this Wrapper Widget

### ISSUE THREAD

**Issue by SasinduJayashma** [rrousselGit/provider#342]
- main.dart file -

`class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return StreamProvider<User>.value(
      value: AuthService().user,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Wrapper(),
      ),
    );
  }
}`

- wrapper.dart -
`class Wrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final user = Provider.of<User>(context);
    print(user);

    return joinUI_1();
  }
}`

**Why I get this error?  I tried everything to fix this but still couldn't find a clue`**

**Comment by rrousselGit** [comment]
Could you share a way to reproduce this issue?

**Comment by Jinxishihenian** [comment]
I had a similar problem.
### 错误日志
```
Error: Could not find the correct Provider<QueryFunction> above this HomePage Widget 
To fix, please:

  * Ensure the Provider<QueryFunction> is an ancestor to this HomePage Widget
  * Provide types to Provider<QueryFunction>
  * Provide types to Consumer<QueryFunction>
  * Provide types to Provider.of<QueryFunction>()
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
```

### 重现步骤:
When I run my project, I may enter a certain page and report this error, and it will only happen once, so I won't get this error when I enter my app again.
### 代码片段:

```
MultiProvider(
      providers: [
        Provider<QueryFunction>(create:(_)=>QueryFunction()),
        ListenableProvider<QueryFunction>(create: (_) => QueryFunction()),
      ],
      child:MaterialApp(
        title: 'xxxx',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
            platform: TargetPlatform.android,
            primaryColor: Colors.white,
            scaffoldBackgroundColor: Color.fromRGBO(248, 248, 249, 1)
//        primarySwatch:Colors.white,
        ),
        localizationsDelegates: [
          RefreshLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        locale: Locale('zh'),
        supportedLocales: [
          const Locale('zh', 'CN'),
        ],
        routes: SptErpApp.initroutes(),
      ),
    );
```
This is where I configure my provider.

```
  var modules = Provider.of<QueryFunction>(context);
    modules.controlAuth(quickData, autoList);
    modulesView = modules.getModule;
```
I use this in the build method.

**Comment by vinothkumarmEzcliniq** [comment]
same issue here also, i spent more tome on it please give some idea

**Comment by vinothkumarmEzcliniq** [comment]
Same issue here also so i spent lot of time on it please give some idea.... thank you

**Comment by vinothkumarmEzcliniq** [comment]
> * main.dart file -
> 
> `class MyApp extends StatelessWidget { // This widget is the root of your application. @override Widget build(BuildContext context) { return StreamProvider<User>.value( value: AuthService().user, child: MaterialApp( debugShowCheckedModeBanner: false, home: Wrapper(), ), ); } }`
> 
> * wrapper.dart -
>   `class Wrapper extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>   final user = Provider.of(context);
>   print(user);
>   return joinUI_1();
>   }
>   }`
> 
> **Why I get this error? I tried everything to fix this but still couldn't find a clue`**

im facing same issue did u fixed it because i spent more time on it couldn't fix it, can u help me.. thank you

**Comment by luyang7415445** [comment]
im facing same issue,its my found, (class BKPresenter extends ChangeNotifier  import 'bkpresenter.dart'; this import is wrong,changed like this   import 'package:integralapp/list/HotBook_Knowledge/bkpresenter.dart'; )

**Comment by vinothkumarmEzcliniq** [comment]
till i couldn't fix it, i followed some youtube video so i got same issue,
if you fix this please help me, thank you.

**Comment by rrousselGit** [comment]
I believe the new error message of ProviderNotFoundException should help.
