### ISSUE TITLE
How to create my own provider on version >= 4.0.0

### ISSUE THREAD

**Issue by travispdev** [rrousselGit/provider#344]
This [sample](https://gist.github.com/rrousselGit/4910f3125e41600df3c2577e26967c91) works on version 3 but on 4.0.0 those classes were removed. Can you please provide an up-to-date sample?
Thanks for all your hard work 👍🏻

**Comment by rrousselGit** [comment]
I actually ported it yesterday during a PR for a sample app of ValueNotifier+freezed+provider

https://github.com/rrousselGit/flutter_architecture_samples/blob/freezed_sample/freezed_provider_value_notifier/lib/value_notifier_provider.dart

**Comment by travispdev** [comment]
Thanks man.
