### ISSUE TITLE
ProxyProvider doesn't let me create like update or old builder 

### ISSUE THREAD

**Issue by Migue28** [rrousselGit/provider#352]
I need authentication when creating the Widget, but create doesn't accept my arguments, update doesn;t have problems, but I need to create first.

![image](https://user-images.githubusercontent.com/17736149/74672122-996ae180-517a-11ea-974f-e549508adf56.png)

**Comment by rrousselGit** [comment]
`create` only receives a single `context` parameter.

You probably want to use `update` anyway since `Provider` doesn't provider any way to trigger updates besides `==`.
