### ISSUE TITLE
ChangeNotifierProxyProvider update method called when switching tabs

### ISSUE THREAD

**Issue by davidmartos96** [rrousselGit/provider#353]
Hi Remi,
my app uses an architecture with independent Navigators for each tab in the BottomNavigationBar.
When using `ChangeNotifierProxyProvider` in one of the tabs, I found out that the method `update` is called every time I switch tabs. Is this behavior intended in such a Widget Tree structure? The tree doesn't change when changing tab, so I don't really know why the `update` is being called.

Is this a bug or is it expected? If that is expected, what is the explanation to that behavior? 

Minimal example: https://gist.github.com/davidmartos96/5e8e4e0c807ee1c7ee4cb64597c1cb78

Thanks in advance!

Provider version 4.0.4

**Comment by davidmartos96** [comment]
Also, I would like to add that the very same code with provider version 3.2.0 doesn't trigger the `update` callback when switching tabs.

**Comment by davidmartos96** [comment]
@rrousselGit Do you have any insight into this issue? Should it be considered a regression bug from Provider v4?
From what I have debug, it seems that the `update` callback triggers because the flag `_isBuildFromExternalSources` is being set to true in https://github.com/rrousselGit/provider/blob/master/lib/src/inherited_provider.dart
but I do not have much knowledge on the internals of `provider` to see if that is right or wrong.

**Comment by rrousselGit** [comment]
This is expected.
The v4 has a slight behavior change on `update`, which calls the life-cycle again when the widget rebuilds.

This allows things like:

```dart
MyProvider(
  ...
  update: (_, model) {
    model.something = widget.something;
    return model;
  }
)
```

**Comment by davidmartos96** [comment]
Ok thanks. I opened the issue because I have some "fetch" operations that occur when the dependency of a ProxyProvider changes and it was constantly being called when switching tabs. In v4 I would have to handle if that dependency really has changed by myself, right? Something like the pretty common `didUpdateWidget` logic.

**Comment by rrousselGit** [comment]
> In v4 I would have to handle if that dependency really has changed by myself, right

Yes.
You had to do that before too. It's just that when you had a single dependency if was hard to notice that you had this issue.

v4 is instead more of a reveal of the weakness in your code than an actual break.

**Comment by davidmartos96** [comment]
> v4 is instead more of a reveal of the weakness in your code than an actual break.

Yes, that must be it.
Thanks for the info and help @rrousselGit !
