### ISSUE TITLE
Consumer not listening to changes in release mode

### ISSUE THREAD

**Issue by ggcsriram** [rrousselGit/provider#355]
Some consumers are not listening to changes in release mode while some are working fine in release mode

**Comment by rrousselGit** [comment]
I will need more information than that.

Provider doesn't do any debug-only thing, so I can't see any reason for that.

**Comment by ggcsriram** [comment]
I'm using Consumer for state management .The consumer i'm using in my application is not observing the changes in release mode. And when the  same piece of code is separated and placed in another project its working fine in release mode also.

Note:The other consumers were working good in the application in release mode as well as debug mode also but the consumer with which i'm facing issues is not listening to changes in release mode only and works fine in debug mode

**Comment by anticafe** [comment]
@ggcsriram At least you should provide a minimal app which can reproduce that issue if you really want people help you.

**Comment by ggcsriram** [comment]
![debug_mode](https://user-images.githubusercontent.com/49143516/75216564-677cff00-57ba-11ea-8570-f48822914cdf.gif)

This is how it works in debug mode
![release_mode](https://user-images.githubusercontent.com/49143516/75216575-7794de80-57ba-11ea-8bad-e585a8354b48.gif)

Here in release mode I am receiving the data from backend but consumer is not listening to the changes as it is in debug mode.

I have given the internet permissions as i was getting data to the ui as the list of names from the backend in the first screen

**Comment by nmhernandez10** [comment]
I have the same issue. In debug mode listeners rebuild correctly, but in release mode they don't.

**Comment by rrousselGit** [comment]
As said previously, without a way to reproduce the error I cannot help you.

**Comment by UttamPanchasara** [comment]
Hmmm, observed same issue .. have wrapped listview inside consumer to notify change whenever user tap the list item.

But the thing is, consumer not rebuilding the list when there is a change in provide and on calling notifyListener().

Issue only with release build and debug build is working fine.

**Comment by rrousselGit** [comment]
Again, as said previously, I can't reproduce it.

Please give me enough to reproduce the problem, otherwise I cannot help.

**Comment by AkioAlex0817** [comment]
I also same issue. The provider works well in the debug mode and release model. 
But not work in "Sony" and "Huawei" Phone in release mode. Please let me know how to fix it?

**Comment by rrousselGit** [comment]
Considering the issue is old and I don't have any way to reproduce the problem.

If you still have problem, feel free to say so!

**Comment by shivangg66** [comment]
Facing the same issue

**Comment by rrousselGit** [comment]
@shivangg66 Consider opening a new issue and including a way to reproduce the problem. Otherwise I cannot help

**Comment by shivangg66** [comment]
No need I found the soultion. Stream Provider was having problem with change notifier provider. So i just removed the stream provider and used a future function instead. Thanks

**Comment by savadmv** [comment]
I have the same issue found. 
_This is how I initialize the **provider**_ 
```
 runApp(
    MultiProvider(
      child: App(
        userRepository: userRepository,
        cartList: list,
      ),
      providers: [
        ChangeNotifierProvider<CartListModel>(
          create: (context) => CartListModel(),
        )
      ],
    ),
  );
```

I navigate from **FirstPage()** to **SecondPage()** to List the cart items and then navigate to **ThirdPage()**  to do something else 

_So I use_ 

```
Navigator.pushNamedAndRemoveUntil(
                context, MyRoutes.first, (route) => false);

```
to remove  **ThirdPage()**  and **SecondPage()** .

So there in some widget in **FirstPage()** that use the **Consume** widget . There its not updating . This works fine when i relaunch the application 

The weired part is that , Its working fine in debug build and not working in release widget

**Comment by rrousselGit** [comment]
It is possible that you have an exception is release mode before "notifyListeners" is called.

In any case, without a way to reproduce the issue, I can not help.

**Comment by joeyyy688** [comment]
Facing the same issue 
Anyone on how to fix it, please?

**Comment by savadmv** [comment]
> Facing the same issue
> Anyone on how to fix it, please?

I faced the issue when I use Provider with Bloc.Please paste your code here. So that it will be easy to find the solution

**Comment by skc18** [comment]
Truth to be told, this issue has happened quite a lot of times during me using flutter as a development tool. But I always forgot how it later on works fine. But I got issue today again, any help?

**Comment by rrousselGit** [comment]
As I mentioned a few times in this issue before, without a way to reproduce the problem, I cannot help.

If you have this problem, consider opening a new issue with clear steps on how to reproduce the problem
