### ISSUE TITLE
Integration testing for providers (Flutter driver)

### ISSUE THREAD

**Issue by Nicopla880** [rrousselGit/provider#358]
Hi! I am using providers for State Management.

While trying to write the integration test i noticed that providers widgets where not working and i couldnt catch any exceptions. 

documentation only show how create unit test and widgets test, i dont know if im missing something.

if it is possible how can i create the integration test?

Regards
Nico

**Comment by rrousselGit** [comment]
The same way as you'd do with unit tests

Add the necessary providers in the file that starts the app.

**Comment by rrousselGit** [comment]
Closing this since it seems to have answered your question
