### ISSUE TITLE
Problem with mixin ChangeNotifier

### ISSUE THREAD

**Issue by jasonlaw** [rrousselGit/provider#36]
Hi @rrousselGit , 

Suppose I already have a class A extends B, in order to use the ChangeNotifierProvider, I have to mixin the ChangeNotifier. Now, in my A.dispose, I expect the super.dispose to B.dispose, but it ends up with the ChangeNotifier.dispose. That will somehow ruin my logic. 
May I what is the alternative to the ChangeNotifierProvider if the class is not extends/mixin from ChangeNotifier?

Thanks in advance.

**Comment by rrousselGit** [comment]
`ChangeNotifier` is not designed to be used as a mixin.

Another solution is to _implement_ the interface

```dart
class A extends B implements ChangeNotifier {
  final _notifier = ChangeNotifier();

  void addListener(VoidCallback listener) => _notifier.addListener(listener);

  void removeListener(VoidCallback listener) => _notifier.removeListener(listener);

  void notifyListeners() => _notifier.notifyListeners();

  void dispose() {
    _notifier.dispose();
  }
}
```

**Comment by jasonlaw** [comment]
That works, many thanks!

**Comment by rrousselGit** [comment]
Closing this since the issue have been solved.
