### ISSUE TITLE
Eliminate `listen` property

### ISSUE THREAD

**Issue by lukepighetti** [rrousselGit/provider#361]
<img width="839" alt="Screen Shot 2020-02-24 at 7 04 33 PM" src="https://user-images.githubusercontent.com/666539/75202229-96eb2780-5738-11ea-9082-4853837b7e6b.png">

It seems to me this assertion is not necessary. If this assertion fails, `provider` can pass `listen: false` internally, if it succeeds, `provider` can pass `listen: true` internally.

**Comment by rrousselGit** [comment]
This is not possible. 

Some of the informations needed are available only in debug mode, while other informations are missing. 

Provider cannot reliably guess what to use.

**Comment by lukepighetti** [comment]
Thanks for the clarification
