### ISSUE TITLE
Rename SingleChildCloneableWidget

### ISSUE THREAD

**Issue by leisim** [rrousselGit/provider#37]
I really like this package. Especially the straightforward naming (coming from `scoped_model`)

Would it be possible to rename `SingleChildCloneableWidget` to something like `BaseProvider` or `AbstractProvider` to make it more readable?

I suppose most users don't ever use this class but my app is quite complex and I find it very useful...

**Comment by rrousselGit** [comment]
The interface described by `SingleChildCloneableWidget` is technically unrelated to the notion of "provider" (and so is `MultiProvider`).
In fact `SingleChildCloneableWidgt` could even be moved in the Flutter repository (that and a `Disposable` interface). 

So I dislike having "Provider" in the name. 

One solution is to rename it on your end, with a subclass (or with typedefs one available):


```dart
abstract class BaseProvider implements SingleChildCloneableChild {}
```

**Comment by leisim** [comment]
Okay thank you 👍
