### ISSUE TITLE
Providing multiple types for the same instance

### ISSUE THREAD

**Issue by szotp** [rrousselGit/provider#374]
I have an reusable abstract class and reusable widget that watches it:
```dart
abstract class Loading extends ChangeNotifier {
  bool get isLoading;
}

class AutoLoadingIndicator extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: context.select<Loading, bool>((x) => x.isLoading),
      child: CircularProgressIndicator(),
    );
  }
}
```

And then I have concrete class that implements the abstract class plus some page specific behavior:

```dart
class LoginController extends Loading {
  bool _isLoading = false;

  @override
  bool get isLoading => _isLoading;

  Future<void> login(String username, String password) async {
    _isLoading = true;
    notifyListeners();

    await Future.delayed(Duration(seconds: 1));

    _isLoading = false;
    if (hasListeners) {
      notifyListeners();
    }
  }
}

class LoginPage1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => LoginController(),
      builder: (context, _) => buildContent(context),
    );
  }

  Widget buildContent(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: <Widget>[
          AutoLoadingIndicator(),
          FlatButton(
            onPressed: () {
              context.read<LoginController>().login('x', 'x');
            },
            child: Text('Login'),
          )
        ],
      ),
    );
  }
}
```
But this will crash because only LoadingController was provided, where AutoLoadingIndicator watches for Loading.

What would be the best way of fixing this?

1. In onPressed, use `context.read<Loading>` and then force cast it into LoadingController?

Seems ugly, especially if I wanted publish Loading as package and expect users to do that everywhere Loading is involved.

2. Use MultiProvider with additional provider that converts the type?
I managed to write this helper:
```dart
class InterfaceProvider<Concrete extends Interface,
    Interface extends Listenable> extends SingleChildStatelessWidget {
  @override
  Widget buildWithChild(BuildContext context, Widget child) {
    return ListenableProvider<Interface>.value(
      value: context.read<Concrete>(),
      child: child,
    );
  }
}
```
it works, but destroys laziness and adds unnecessary listener.

3. Something else?

**Comment by rrousselGit** [comment]
Providers do not work with base classes. They are obtained by strictly comparing the searched type and the exposed type.

You should change the way you're consuming your providers instead. A generic widget/function should be enough.

For example, your `AutoLoadingIndicator` could become:

```dart
class AutoLoadingIndicator<T extends Loading> extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: context.select((T x) => x.isLoading),
      child: CircularProgressIndicator(),
    );
  }
}
```

**Comment by szotp** [comment]
Thanks for quick answer. Generic widget is not very practical - if I had another reusable widget that contains AutoLoadingIndicator, it would cause a cascade of generics.

But,  the ProxyProvider0 makes sense, at least for this example. Creating new object(snapshot) in the provider would allow me to filter updates at the root, instead of the select.

Anyway, I figured out a better InterfaceProvider implementation:
```dart
class InterfaceProvider<Concrete extends Interface,
    Interface> extends InheritedProvider<Interface> {
  InterfaceProvider()
      : super(
          update: (context, _) => context.watch<Concrete>(),
          updateShouldNotify: (_, __) => true,
        );
}
```
