### ISSUE TITLE
[4.1.0-dev+1] read() `!debugDoingBuild` assert is too strict

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/provider#377]
I noticed this commit(https://github.com/rrousselGit/provider/commit/874107f52bf12409bfd47413937e33655bd3e7ff), and this was released as `4.1.0-dev+1`.

I've tried that, but I feel `T read<T>()`'s `!debugDoingBuild` assert is too strict.
https://github.com/rrousselGit/provider/blob/739b7e50a7ea1276c24f5823ae00e68bd155b136/lib/src/provider.dart#L427

For example, I write this kind of code, and using `read` is intended.

```dart
floatingActionButton: FloatingActionButton(
    child: Icon(Icons.add),
    onPressed: context.read<_Notifier>().increment,
),
```

But after `4.1.0-dev+1`, this triggers error, and it forced to change to use `watch` or `() => context.read<_Notifier>().increment()` (closure, not tear-off).

<details><summary>Error log</summary>
Restarted application in 725ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building HomePage(dirty, dependencies:
flutter: [_InheritedProviderScope<_Notifier>, _LocalizationsScope-[GlobalKey#ee3ac], _InheritedTheme]):
flutter: 'package:provider/src/provider.dart': Failed assertion: line 427 pos 12: '!debugDoingBuild &&
flutter: !_debugIsInInheritedProviderUpdate': is not true.
flutter:
flutter: The relevant error-causing widget was:
flutter:   HomePage file:///Users/mono/Git/flutter_playground/lib/main_change_notifier.dart:18:22
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ReadContext.read (package:provider/src/provider.dart:427:12)
flutter: #3      HomePage.build (package:flutter_playground/main_change_notifier.dart:38:28)
flutter: #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #12     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:350:11)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
flutter: #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: ...     Normal element mounting (7 frames)
flutter: #22     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
flutter: ...     Normal element mounting (24 frames)
flutter: #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #47     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (119 frames)
flutter: #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #167    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (253 frames)
flutter: #420    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #421    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #422    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1142:16)
flutter: #423    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1113:5)
flutter: #424    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1055:17)
flutter: #425    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
flutter: #426    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1054:13)
flutter: #427    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:935:7)
flutter: #428    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomePage(dirty, dependencies: [_InheritedProviderScope<_Notifier>, _LocalizationsScope-[GlobalKey#ee3ac], _InheritedTheme]):
'package:provider/src/provider.dart': Failed assertion: line 427 pos 12: '!debugDoingBuild && !_debugIsInInheritedProviderUpdate': is not true.

The relevant error-causing widget was: 
  HomePage file:///Users/mono/Git/flutter_playground/lib/main_change_notifier.dart:18:22
When the exception was thrown, this was the stack: 
#2      ReadContext.read (package:provider/src/provider.dart:427:12)
#3      HomePage.build (package:flutter_playground/main_change_notifier.dart:38:28)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
</details>

Full code: 
https://github.com/mono0926/flutter_playground/blob/8dc362e83e67994ce13863b0ed888429c039ec23/lib/main_change_notifier.dart#L38

---

I understand that `!debugDoingBuild` suppress misuse, but for practical convenience, I think `!debugDoingBuild` assert should be removed from `T read<T>()`.

**Comment by rrousselGit** [comment]
That is desired and is one of the scenarios that this asserts fights against.

You should instead write:

```dart
onPressed: () => context.read<T>().increment()
```

**Comment by mono0926** [comment]
I noticed another situation.

What should I do if `lazy: true` about this code?

https://github.com/mono0926/flutter_playground/blob/054301b6eb8c86d3e850b22bc993f8605c5528e4/lib/main_change_notifier2.dart#L9-L17

**Comment by mono0926** [comment]
> That is desired and is one of the scenarios that this asserts fights against.

Okay, I understand your intention, and follows that about this kind of callback.

**Comment by mono0926** [comment]
If you missed it, I'm still in trouble with handling this:

> What should I do if I want to set lazy: false for this code?
> 
> https://github.com/mono0926/flutter_playground/blob/054301b6eb8c86d3e850b22bc993f8605c5528e4/lib/main_change_notifier2.dart#L9-L17



And, I noticed related another error when using `state_notifier`, and submit an issue: https://github.com/rrousselGit/state_notifier/issues/7.

**Comment by rrousselGit** [comment]
Yes, I saw these. Thanks for the reports ❤️ 

I will fix them asap.

**Comment by rrousselGit** [comment]
Thanks again for the reports!
It revealed quite a lot of weaknesses related to `_debugIsInInheritedProviderUpdate`

It took me the entire day to fix everything, but that should be fine now

**Comment by mono0926** [comment]
Thank you very much, https://github.com/rrousselGit/provider/issues/377#issuecomment-596334857 ando https://github.com/rrousselGit/state_notifier/issues/7 are perfactly fixed 👍 

I really appreciate your great packages and hard work 🙏 

I'm closing this because I understood strict assertion intension and related problems I noticed were fixed.
