### ISSUE TITLE
[>= 4.1.0-dev+1] Unavailable on stable

### ISSUE THREAD

**Issue by kaboc** [rrousselGit/provider#379]
I noticed newer versions of provider were up and decided to update from v4.1.0-dev to v4.1.0-dev+2 today, but `pub get` failed on the `stable` channel.

```
Because xxxxx depends on provider >=4.1.0-dev+1 which requires Flutter SDK version >=1.15.17-pre.5, version solving failed.
```

Is `flutter: '>= 1.15.17-pre.5'` in pubspec.yaml of provider not going to be removed until Flutter 1.15.17-pre.5 comes to stable, or is it just a temporary measure only during the pre-release phase of 4.x?

It is expected to take months before 1.15.17-pre.5 arrives in the stable channel. It'll be inconvenient for users if newer provider versions are not available for such a long time while attractive features are newly added in 4.x.

**Comment by rrousselGit** [comment]
That version constraint is here because it is needed. This version relies on a recent change made on Flutter.

I could technically remove the feature related to these change, but that would make introducing it later a breaking change. I prefer to keep 4.1.0 a dev release than having a 5.0.0 already.

**Comment by kaboc** [comment]
@rrousselGit 
I understand your intention, but it's a shame. Some new features in 4.1 is so useful that I was thinking I would use the dev version ahead of time and its release version would come before long. Now that I know it's not the case, I have to change my decision.

Will useful features like `context.select()` be added to 4.0.x? If not, do you think it is a reasonable idea for me or other users to keep using 4.1.0-dev without updating to 4.1.0-dev+2 until 1.15.17-pre.5 comes to the stable channel, or you recommend that we should use 4.0.x?

**Comment by rrousselGit** [comment]
Well, if you are fine with using the dev version of provider, why don't you use a different flutter channel that is up to date?

**Comment by kaboc** [comment]
I use 4.1.0 because I confirmed it works fine and I know your work is trustworthy. Even if some bug was found, it is expected that you rapidly deal with it.

On the other hand, Flutter's non-stable channels have so many commits added frequently that it is virtually impossible to track all of them. However, I'm thinking the dev channel may be fairly fine, which does not have 1.15.17-pre.5 yet though.

**Comment by rrousselGit** [comment]
4.1.0-dev should work fine. But if there's a bug, you'll get stuck as I don't plan to support both with and without the Flutter changes together.

It's your call

**Comment by kaboc** [comment]
OK. That's what I wanted to know. If it's not supported, I'll choose a different version with more support. Thanks.

IMHO, I think it would be better if it was documented somewhere.

**Comment by kaboc** [comment]
I mean it was one of the two things I wanted to know. How about the other one?

> Will useful features like context.select() be added to 4.0.x?

**Comment by rrousselGit** [comment]
No, that would be against semver, and it depends on the `'>= 1.15.17-pre.5'` too

**Comment by kaboc** [comment]
I can decide on the version I should use now. Thank you for all the info.

**Comment by AgboVincent** [comment]
downgrading from provider: ^4.1.3 to provider: ^3.1.0 fixed my problem

**Comment by rrousselGit** [comment]
Why did you need that?
4.1.x is compatible with stable.

**Comment by AgboVincent** [comment]
4.1.0 didnt work either

**Comment by rrousselGit** [comment]
Are you sure you didn't forget to update flutter?

**Comment by AgboVincent** [comment]
am using Flutter version 1.12, which is compatible with 3.1.0, 4.1.0
requires flutter version 1.15

**Comment by rrousselGit** [comment]
Flutter stable is currently on 1.17

**Comment by AgboVincent** [comment]
okay
I have to update my packages, and flutter version
