### ISSUE TITLE
Provider.of() without listen:false in onChanged outputs no error

### ISSUE THREAD

**Issue by kaboc** [rrousselGit/provider#380]
https://stackoverflow.com/questions/60636202/function-in-changenotifier-class-not-called/

As in this question, using `Provider.of()` without `listen: false` in `onChanged` fails.

```dart
class MyTextField extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField(
      onChanged: (value) {
        Provider.of<AmountManager>(context).changeAmount(value);  // changeAmount() is not called
      },
    );
  }
}
```

I think it is the correct behaviour as mentioned [here](https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart#L197-L204) as detailed information specified in `assert()`.

However, the misuse does not show any error message and just fails, which is why OP couldn't realise what the cause was. Is it a bug?

My environment:
* Flutter v1.12.13+hotfix.8 (Channel stable)
* provider v4.0.4

**Comment by rrousselGit** [comment]
There definitely is an error message, which is the one you mentioned: https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart#L197-L204

Maybe they actually have an exception but didn't see it because there's no red screen of death?

**Comment by kaboc** [comment]
I actually run the code and didn't see the exception. Here is the code:

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<AmountManager>(
      create: (_) => AmountManager(),
      child: MaterialApp(
        home: Scaffold(
          body: SafeArea(
            child: Padding(
              padding: const EdgeInsets.all(32.0),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  MyText(),
                  MyTextField(),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class AmountManager extends ChangeNotifier {
  String amount = '';
  void changeAmount(String newAmount) {
    amount = newAmount;
    notifyListeners();
  }
}

class MyTextField extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField(
      decoration: const InputDecoration(
        hintText: 'Input text here',
      ),
      onChanged: (String value) {
        Provider.of<AmountManager>(context).changeAmount(value);
      },
    );
  }
}

class MyText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      Provider.of<AmountManager>(context).amount,
    );
  }
}
```

**Comment by rrousselGit** [comment]
This looks like to be a bug in `TextField.onChanged`

If we replace the `TextField` with:

```dart
RaisedButton(
      child: Text('foo'),
      onPressed: () {
        Provider.of<AmountManager>(context).changeAmount('a');
      },
    );
```

Then we correctly see the exception in the console.


It sounds like `TextField` is silently catching the exception and not reporting it back to the framework.

**Comment by kaboc** [comment]
Oh, that's bad... Thanks for finding the cause anyway. I'll take this back to SO for other users' sake.

Shall I close this issue if you have any measure against it?

**Comment by rrousselGit** [comment]
I can't do anything about it.

I'd suggest making an issue on Flutter as it's a bug on their side 😊

**Comment by kaboc** [comment]
OK, I'll file the bug. Thanks you!
