### ISSUE TITLE
Error: Could not find the correct Provider above this Widget

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#387]
I am getting this error:

> Error: Could not find the correct `Provider<Trip>` above this `TravelTicketsScreen` Widget
> 
> To fix, please:
> 
>   * Ensure the `Provider<Trip>` is an ancestor to this `TravelTicketsScreen` Widget
>   * Provide types to `Provider<Trip>`
>   * Provide types to `Consumer<Trip>`
>   * Provide types to `Provider.of<Trip>()`
>   * Ensure the correct `context` is being used.
> 
> If none of these solutions work, please file a bug at:
> https://github.com/rrousselGit/provider/issues

Here are my Routes:

`MainScreen`>`TripScreen` > `TravelTicketsScreen`.

On the `MainScreen` the user selects a `Trip` and I push the new route, surrounded by a `Provider<Trip>`, so all future Routes will have access to this same `Trip` object:

```dart
() async {
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) {
        return Provider<Trip>.value(
          value: trip,
          child: TripScreen(),
        );
      },
      settings: RouteSettings(name: '/trip'),
    ),
  );
},
```

Then on the `TripScreen` I can get the `Trip` using `Provider.of<Trip>(context)`, there are no errors, it works fine. On `TripScreen` I show several buttons, each button leads to a new Route, I programmatically get what's the new Route with `createCategoryRoute` when a user clicks a button with this code:

```dart
() {
  Widget newRoute = createCategoryRoute(key, trip);
   if (newRoute != null) {
     Navigator.push(
       context,
       MaterialPageRoute(
         builder: (context) => newRoute,
         settings: RouteSettings(
           name: '/${newRoute.runtimeType}',
         ),
       ),
     );
   }
 }
```

This pushes me to the `TravelTicketsScreen`. On the `TravelTicketsScreen` I try to get the `Trip` as the first thing I do on `build`, like this:

```dart
@override
  Widget build(BuildContext context) {
    Trip trip = Provider.of<Trip>(context);
```

But then I get the error I showed on the begging of this Issue.

I am sure `Provider<Trip>` is an ancestor, as we can see it in to following image as an ancestor to `TripScreen`:

![image](https://user-images.githubusercontent.com/8120472/77015479-a898a700-6953-11ea-8624-1ccfc4e7dd74.png)

`CategoriesContainer` is where I push `TravelTicketsScreen`.

**Comment by feinstein** [comment]
Ok, I found out that when I push `TravelTicketsScreen` it's getting "parallel" to `TripScreen`, so `Provider<Trip>` isn't an ancestor, but how's this even possible?!

Before:

![image](https://user-images.githubusercontent.com/8120472/77018049-e816c180-695a-11ea-8fc5-f75b5b67b591.png)

After:

![image](https://user-images.githubusercontent.com/8120472/77018117-198f8d00-695b-11ea-92bf-133250b512d4.png)

**Comment by rrousselGit** [comment]
That's how navigator works.
Each route are in a different branch. 

You never have a situation where a route is "inside" another route.

**Comment by feinstein** [comment]
So how can I make the `Trip` object be provided to all routes navigated after `TripScreen`?

So far I was using `Provider` as a wrapper to my `MaterialApp`:

![image](https://user-images.githubusercontent.com/8120472/77019477-66756280-695f-11ea-95e6-217e48799f8f.png)

**Comment by rrousselGit** [comment]
Putting it above MaterialApp, or reinserting the provider on the new route everytime

**Comment by feinstein** [comment]
Is this the same for other `InheritedWidgets` like `Theme` or just `Provider`?

**Comment by rrousselGit** [comment]
It is the same for all InheritedWidgets

**Comment by rrousselGit** [comment]
That could be fixed through declarative overlays though https://github.com/flutter/flutter/issues/50961

As the overlay would be part of the main branch

**Comment by feinstein** [comment]
Oh that's great than.

To I leave this open or should I close it then?

**Comment by rrousselGit** [comment]
Let close it

It's not actionable as part of provider. It's either a modification on Flutter or a new package
