### ISSUE TITLE
how do I switch pages when the 401 api response is flutter ??

### ISSUE THREAD

**Issue by rakafajar** [rrousselGit/provider#388]
I want to try to resolve when the 401 response code status then he will switch the login page

**Class API :** 

    Future<EventArticleList> getEventArticleList(String token) async {
        Map<String, String> headers = {
          "Accept": "application/json",
          "Authorization": "Bearer $token"
        };
        var response = await client.get('$endpoint/mobile/news', headers: headers);
    
        if (response.statusCode == 200) {
          print(response.body);
          return eventArticleListFromJson(response.body);
        } else if (response.statusCode == 401) {
          throw Exception("Error");
        } else {
          throw Exception("Error");
        }
      }

**Widget** 

    import 'package:btn_survey/src/core/constants/app_constants.dart';
    import 'package:btn_survey/src/core/viewmodels/event_article/event_article_list_model.dart';
    import 'package:btn_survey/src/ui/utils/shimmer_widgets.dart';
    import 'package:btn_survey/src/ui/views/base_widget.dart';
    import 'package:btn_survey/src/ui/widgets/event_article/event_article_list_item_widget.dart';
    import 'package:flutter/material.dart';
    import 'package:provider/provider.dart';
    
    class EventArticleListWidget extends StatelessWidget {
      final String type;
      final Function onTap;
    
      const EventArticleListWidget({Key key, this.type, this.onTap})
          : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return BaseWidget<EventArticleListModel>(
          model: EventArticleListModel(api: Provider.of(context)),
          onModelReady: (model) => model.getEventArticleList(),
          builder: (context, model, child) => model.busy
              ? Container(
            margin: EdgeInsets.symmetric(vertical: 20),
            child: ShimmerWidgets.shimmerEventsArticle(),
          )
              : RefreshIndicator(
            onRefresh: () {
              model.getEventArticleList();
              return null;
            },
            child: Column(
              children: <Widget>[
                type == "full"
                    ? Container()
                    : Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: <Widget>[
                      Expanded(
                        child: Text(
                          'Events & Article',
                          style: TextStyle(
                              fontSize: 18,
                              color: Colors.black,
                              fontWeight: FontWeight.bold),
                        ),
                      ),
                      model.eventArticleList.data != null &&
                          model.eventArticleList.data.length == 0
                          ? Container()
                          : InkWell(
                        onTap: onTap,
                        child: Text(
                          'See all',
                          style:
                          TextStyle(color: Color(0xFF06377B)),
                        ),
                      ),
                    ],
                  ),
                ),
                Container(
                  margin: EdgeInsets.only(left: 16, right: 16, bottom: 16),
                  child: ListView.builder(
                    shrinkWrap: true,
                    physics: NeverScrollableScrollPhysics(),
                    itemCount: type == "full"
                        ? model.eventArticleList.data.length
                        : model.eventArticleList.data.length > 5
                        ? 5
                        : model.eventArticleList.data.length,
                    itemBuilder: (BuildContext context, int index) =>
                        EventArticleListItemWidget(
                          eventArticleListItem:
                          model.eventArticleList.data[index],
                          onTap: () {
                            Navigator.pushNamed(
                              context,
                              RoutePaths.EventArticleDetail,
                              arguments: model.eventArticleList.data[index],
    
                            );
                          },
                        ),
                  ),
                ),
              ],
            ),
          ),
        );
      }
    }

**Model :** 

    import 'package:btn_survey/src/core/models/event_article_list.dart';
    import 'package:btn_survey/src/core/services/api.dart';
    import 'package:btn_survey/src/core/utils/shared_pref_utils.dart';
    import 'package:btn_survey/src/core/viewmodels/base_model.dart';
    import 'package:flutter/cupertino.dart';
    
    class EventArticleListModel extends BaseModel {
      Api _api;
    
      EventArticleListModel({@required Api api}) : _api = api;
    
      EventArticleList eventArticleList;
    
      Future getEventArticleList() async {
        setBusy(true);
        String token = await getToken();
        eventArticleList = await _api.getEventArticleList(token);
        setBusy(false);
      }
    }

**Comment by virgule-xyz** [comment]
I'm working on it and after my first solution I've found an article of @boeledi where you can find that interesting feature :

https://www.didierboelens.com/2018/05/token-based-communication-with-server-part-1/

void _redirectToPage(BuildContext context, Widget page){
    WidgetsBinding.instance.addPostFrameCallback((_){
      MaterialPageRoute newRoute = MaterialPageRoute(
          builder: (BuildContext context) => page
        );

      Navigator.of(context).pushAndRemoveUntil(newRoute, ModalRoute.withName('/decision'));
    });
  }

**Comment by rrousselGit** [comment]
Hello!

This kind of questions belongs to StackOverflow instead
