### ISSUE TITLE
If I use Selector, can I put all ChangeNotifierProvider on MaterialApp? If not, why?

### ISSUE THREAD

**Issue by ddxl123** [rrousselGit/provider#391]
Does the selector cause the ChangeNotifier-widget to be built 1-to-1? If so, why not put all the ChangeNotifierProviders in the MaterialApp() or MyApp()?

**Comment by rrousselGit** [comment]
I do not understand the question

**Comment by ddxl123** [comment]
> I do not understand the question

Sorry, my English is not very good. I mean, can I write this:
`
void main () {
   runApp (MyApp ());
}
class MyApp extends StatelessWidget {
   @override
   Widget build (BuildContext context) {
     return MultiProvider (
       providers: [
         ChangeNotifierProvider (create: (_) => MainProvider ()),
         ChangeNotifierProvider (create: (_) => AProvider ()),
         ChangeNotifierProvider (create: (_) => BProvider ()),
         ChangeNotifierProvider (create: (_) => CProvider ()),
         ChangeNotifierProvider (create: (_) => DProvider ()),
         ChangeNotifierProvider (create: (_) => EProvider ()),
         ... // Can I put all the status on MaterialApp?
       ],
       child: MaterialApp (
         home: HomePage (),
       ),
     );
   }
}
// Can I put all the states in the entire app on MaterialApp?
`

**Comment by muj-programmer** [comment]
>  I mean, can I write this

Absolutely you can do this as it will expose all the provided values to child widgets.

**Comment by ddxl123** [comment]
> > I mean, can I write this
> 
> Absolutely you can do this as it will expose all the provided values to child widgets.

I know this. The difference between Selector and Consumer is that the Selector is more detailed. When using Consumers, you can't write like I did above, because there will be unnecessary rebuilds.
My main doubt is that when using Selector,
[Put AProvider and BProvider on MaterialApp, others on child]
[Put all providers on MaterialApp]
When using value, is the efficiency of the above two methods the same? Or is it more appropriate to use the second method?

**Comment by rrousselGit** [comment]
I'll close this as it is more appropriate to ask such question on StackOverflow
