### ISSUE TITLE
Feature Request: Add ability to know if a given Provider exists

### ISSUE THREAD

**Issue by frmatthew** [rrousselGit/provider#394]
`Provider.of<SomeClass>(context)` throws an exception if there is no Provider of `SomeClass` in the given context. This makes sense to me, as sometimes a provided object will be null. But I would like the ability to know if such a provider exists without resorting to exceptions.

The use case I am facing: I would like widgets deep below a Provider to build differently depending on whether they are in the context of a provided object, but at this point it's a little awkward to do so since I can't easily use nulls to indicate the absence of the provided object.

I am requesting a function on Provider that helps in this case without the need for exception handling. For example:

```
if (Provider.existsFor<SomeClass>(context)) {
  ...
}
```

Thanks for the consideration.

**Comment by frmatthew** [comment]
By the way, I think I can accomplish this by something like:
```
final provider = context.getElementForInheritedWidgetOfExactType<InheritedProvider<SomeClass>>()?.widget;
final hasProvider = provider != null;
```
...but maybe this logic would be helpful rolled into the package. Thanks.

**Comment by rrousselGit** [comment]
This is a reasonable request.

The difficulty is, a widget can technically be moved in the widget tree using GlobalKey. Which means the result of such check can change over time.
This is therefore tricky to do, as in such situation we need to rebuild our widget but it's not actually feasible to do so.

I'm not quite sure what would be the solution here.

**Comment by danielweil** [comment]
If I only need to check if the provider exists in the initState of a Statefull Widget, do you see any way to do it?

I tried the OP method, but was unsuccessful.

Thanks!

**Comment by rrousselGit** [comment]
As a comeback to this:
Now that we have non-nullable types, we could disable the `ProviderNotFoundException` and return `null` instead.

Then, checking whether the provider exists or not would be equivalent to comparing its value with `null`

**Comment by jamesblasco** [comment]
Could we implement some kind of `Provider.maybeOf(context)` that returns a nullable?
It won't be a breaking change and quite useful to check if a provider exists

**Comment by basketball-ico** [comment]
hi @rrousselGit 
I like the idea of `Provider.maybeOf(context)` that also can include
* `context.maybeRead()`;
*  `context.maybeWatch()`;

Currently i catch the exception to know if is null,.

I did this because i use a provider like a settings for a widget, but in case don't find the provider use a default settings.

**Comment by rrousselGit** [comment]
There is a pending PR that implements something similar.

Instead of:

```dart
context.watch<T>()
```

which throws if the provider is not found, you can do:

```dart
context.watch<T?>()
```

which will not throw and instead return `null`.

**Comment by rrousselGit** [comment]
Closing since the 6.0.0 version should that care of this with Provider.of<T> vs Provider.of<T?>
