### ISSUE TITLE
Using MultiProvider

### ISSUE THREAD

**Issue by MaxTenco** [rrousselGit/provider#396]
Hi, why do I have the following error when I use the MultiProvider?

I/flutter (12486): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12486): The following assertion was thrown building MyHomePage(dirty, dependencies:
I/flutter (12486): [_DefaultInheritedProviderScope<A>]):
I/flutter (12486): Tried to use Provider with a subtype of Listenable/Stream (A).
I/flutter (12486): 
I/flutter (12486): This is likely a mistake, as Provider will not automatically update dependents
I/flutter (12486): when A is updated. Instead, consider changing Provider for more specific
I/flutter (12486): implementation that handles the update mechanism, such as:
I/flutter (12486): 
I/flutter (12486): - ListenableProvider
I/flutter (12486): - ChangeNotifierProvider
I/flutter (12486): - ValueListenableProvider
I/flutter (12486): - StreamProvider
I/flutter (12486): 
I/flutter (12486): Alternatively, if you are making your own provider, consider using InheritedProvider.

`void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<A>(create: (_) => A()),
      ],
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final provider = Provider.of<A>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Text(
        'test',
      ),
    );
  }
}

class A with ChangeNotifier {}`

**Comment by Prathik-Jain** [comment]
+1
But I also see you missed the type.
`Type t = Provider.of<T>(context);`

**Comment by rrousselGit** [comment]
The exception clearly states what is happening.

You used `Provider` when you likely wanted to use `ChangeNotifierProvider`

**Comment by MaxTenco** [comment]
Sorry, but I don't understund.
If I insert single Provider like this:
`return ChangeNotifierProvider(
      create: (_) => A(),
      child: ...`

It works, but with MultiProvider, I have that message.
Why I have to use  `ChangeNotifierProvider`? The documentation tell me tu use `Provider`:
`MultiProvider(
  providers: [
    Provider<Something>(create: (_) => Something()),
    Provider<SomethingElse>(create: (_) => SomethingElse()),
    Provider<AnotherThing>(create: (_) => AnotherThing()),
  ],
  child: someWidget,
)`

**Comment by rrousselGit** [comment]
The type of provider that you want to use depends on what the object you want to provide is.

ChangeNotifiers uses ChangeNotifierProvider
Streams uses StreamProvider
And so on

**Comment by MaxTenco** [comment]
Thanks
