### ISSUE TITLE
Request for a good example using Provider and Mobx

### ISSUE THREAD

**Issue by talamaska** [rrousselGit/provider#398]
Hi, @rrousselGit 
I had an app perfectly working with both
https://bitbucket.org/talamaska/flutter_rss_reader/src/0eb601c85f89d1ddf29c91b263c99354acb8136b/?at=feature%2Fmobx
with mobx: ^0.3.9+3 and provider: ^3.2.0
Having an onInit function called in initState,

Now I have a new app and tried the same 
https://bitbucket.org/talamaska/sudoku_stats/src/master/
mobx: ^1.1.1 and provider: ^4.0.4
but I had errors with that approach.

I'm struggling to understand where I should make my action call to mobx to get data from sqlite using moor
Currently it is in the build function, but that doesn't seem right
Also I had to remove the Consumer from the screen, because for some reason it was passing multiple times and the last pass was loosing the data from mobx
I ended up having the consumer in the main.dart wrapping the whole Material app
This all looks incorrect, but I haven't found the proper way to do it.
What I am missing? Would you like to share your guidance on how to fix/xhange the structure in order to have a consumer in the page widget instead and where to make the action call.
After debugging, when I put the consumer in the records_list wrapping the observer, the property I look for is still an empty array, the action is called, I see there is a result from sqlite and the property recordsList in the store should have value, the place where I log item2
but widget receives an empty array, weird cause I see that the loading property is changing, I'm using Equatable in order to have a unique RecordsList object unique, any suggestion?
Greatly appreciate your opinion.

P.S I know my code is not perfect but still.

Edit: Eventually found this example 
https://github.com/zubairehman/flutter-boilerplate-project/blob/master/lib/ui/home/home.dart

Is it the right way to do it?

**Comment by rrousselGit** [comment]
Hello,

While this could be interesting to do, I do not have the time for it, and won't work on that.
Consider searching for community maintained examples instead.

**Comment by jonataswalker** [comment]
@talamaska take a look at https://github.com/jonataswalker/flutter-example
