### ISSUE TITLE
Is there any way to get an ancestor Provider by mixin

### ISSUE THREAD

**Issue by Vadaski** [rrousselGit/provider#400]
I want to get the provider through the mixin that the provider mixes in. Seems a little difficult to understand, please let me explain with the following code.

The general approach is that I provide AProvider in the ancestor node, and then get it through `Provider.of<AProvider>(context)`  in the lower widget.

But I want to remove the logic of a widget from its provider into its separate class, and then mix it into the provider of the current page through a mixin like this.
``` dart
class GoodsModel{
  //logic
}

class APageProvider with GoodsModel, ChangeNotifier{}

class APage extends StatelessWidget{

  final APageProvider provider = APageProvider();

  Widget build(BuildContext context){
    return ChangeNotifierProvider.value(
    value: provider,
    child: GoodsWidget(),
  )}
}

class GoodsWidget extends StatelessWidget{
  Widget build(BuildContext context){
    Provider.of<GoodsModel>(context);
    //...
  }
}
```

This way my widget has nothing to do with a page, but this will cause Provider.of (context) to find no ancestors.

The cause of this problem is the getElementForInheritedWidgetOfExactType that the Provider actually uses, which compares the `runtimeType` of the two widgets.

However in fact APageProvider is GoodsModel.

``` dart
void main() {
  var a = A();
  var b = B();
  print(a.runtimeType == b.runtimeType); //false
  print(a is B); // true
}

class A with B{}
class B{}
```

Any good suggestions？

**Comment by rrousselGit** [comment]
You can manually specify the generic argument to "downcast" the object:

```dart
class Interface {}
class Implementation implements Interface {}

...

Provider<Interface>( // << Interface instead of Implementation
  create: (_) => Implementation()
)

...

Provider.of<Interface>(context) // works
```

**Comment by Vadaski** [comment]
Thanks, it works. 
But this will cause another problem. If I want to use a ChageNotifier, I must mixin it in my Interface. 
This will cause my implementation class to override the ChangeNotifier method, which is obviously unreasonable.
``` dart
 class Interface with ChangeNotifier{}

class Implementation implements Interface {
// you must override ChangeNotifier
}
```
How can I solve that?

**Comment by rrousselGit** [comment]
Can't `Implementation` mix-in ChangeNotifier too?

**Comment by Vadaski** [comment]
Yes, you can check this demo. 
https://github.com/OpenFlutter/Flutter-Notebook/tree/master/mecury_project/example/provider_example

**Comment by Hu-Wentao** [comment]
Any update? @Vadaski @rrousselGit ?
