### ISSUE TITLE
Proposal for ListenableProvider with passing TickerProvider

### ISSUE THREAD

**Issue by cutzmf** [rrousselGit/provider#403]
Hi Remi!

I know about flutter_hooks, but could you make variant of ListenableProvider with passing TickerProvider in builder()?

For now I use following construction

`ListenableProvider<AnimationController>(
        create: (_) => AnimationController(
          vsync: TestVSync(),
          duration: Duration(seconds: 1),
        ),
        dispose: (_, controller) => controller.dispose(),
        child: child,
      )`

The main motivation - I don't want add more dependencies (hooks for example)

Thanks!

**Comment by rrousselGit** [comment]
This is not a good idea to expose animation controllers with providers, as it breaks multiple performance optimisations of Flutter (See [TickerMode](https://api.flutter.dev/flutter/widgets/TickerMode-class.html))

Hooks are the only solution that do not break such optimisation
