### ISSUE TITLE
ChangeNotifierProxyProvider that has a Future update/create method

### ISSUE THREAD

**Issue by Marek00Malik** [rrousselGit/provider#404]
Hi guys, 
The lib is one of the best in Flutter and the approach is something fantastic - great work!

I have a problem that gives me sleepless nights... 
In my app, I have to build a provider that calls an HTTP service, this provider is dependent on another provider that is set later in the app. Also, the result of the http call is a big deal and I need to know about it's status.
The best case would be to use ChangeNotifierProxyProvider with this second provider as an argument, but unfortunately, I need to call an async method and this is something that is not accepted currently in the lib. Do you guys have some idea how I could achieve this with the current state of the lib?

Any help much appreciated!

**Comment by Marek00Malik** [comment]
I think I managed to resolve my problem. I found one example that showed calling an update method that did some task async task, that task when finished calls notifyListeners(). All this with a ChangeNotifierProxyProvider managed to fix my problem :D I think I can now sleep :D

**Comment by kashishkhullar** [comment]
@Marek00Malik could you please share your code snippet. I am also struggling with the same problem. I need to use FutureProvider inside a ProxyProvider.

**Comment by banderberg** [comment]
Yes please share your code
