### ISSUE TITLE
StreamProvider returning null on flutter web

### ISSUE THREAD

**Issue by sondresorbye0111** [rrousselGit/provider#405]
StreamProvider Works fine on android and iOS, but always return null on flutter web

This is my StreamProvider: 
`StreamProvider<FirebaseUser>(
      create: (_) {
        return FirebaseAuth.instance.onAuthStateChanged.where((u) => u != null);
      },`

Get user:
`FirebaseUser user = Provider.of<FirebaseUser>(context);
`

**Comment by rrousselGit** [comment]
Are you sure that it's not because the stream doesnt emit anything?

**Comment by rrousselGit** [comment]
Closing this in the lack of any answer

**Comment by sondresorbye** [comment]
The problem was that I was under the impression that firebase auth would emit the user after updating the name. I had to do it manually
