### ISSUE TITLE
error happened when use provider inside init state

### ISSUE THREAD

**Issue by boucoding** [rrousselGit/provider#408]
I am using the provider package for state management and I am using it to set global variable to the incoming data from my api.

here is the error I get when I call inside init state:
`
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
E/flutter (23134): Receiver: null
E/flutter (23134): Tried calling: inheritFromWidgetOfExactType(InheritedProvider<PostsProvider>)
E/flutter (23134): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter (23134): #1      Provider.of 
package:provider/src/provider.dart:259
E/flutter (23134): #2      _NewsState.initState.<anonymous closure> 
package:joiny/screens/news.dart:123
E/flutter (23134): #3      EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.da
`

My code inside init state within future.delayed with zero duration: 
`
        Provider.of<PostsProvider>(context).updateOnNew(data);
`
full class:
```
import 'package:flutter/foundation.dart';
import 'package:joiny/models/post.dart';




class PostsProvider with ChangeNotifier {
  List _posts = [];

  void updatePosts(List newPostsArray) {
    _posts = newPostsArray;
    notifyListeners();
  }

  void updateOnNew(dynamic post) {
    _posts.add(post);
    notifyListeners();
  }

  void updateOnUpdate(dynamic post) {
    int index = _posts.indexWhere((_post) => _post['_id'].toString() == post['_id'].toString());
    _posts[index] = post;
    notifyListeners();
  }

  List get posts => _posts;
}
```

**Comment by rrousselGit** [comment]
It sounds like `context` that you passed to `Provider.of` was `null`

Your widget was likely removed from the widget tree at the time you made the call
