### ISSUE TITLE
search with provider

### ISSUE THREAD

**Issue by ashishkj93** [rrousselGit/provider#412]
import 'package:evil_icons_flutter/evil_icons_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_slidable/flutter_slidable.dart';

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:gls/DrawerMenuPages/JobDetailPage.dart';
import 'package:gls/Model/JobSearchListModel.dart';
import 'package:gls/Provider/JobListSearchProvider.dart';
import 'package:gls/Widgets/Apptheme.dart';
import 'package:gls/Widgets/SlidableNotDismiss/swipe_widget.dart';
import 'package:gls/Widgets/myStyles.dart';
import 'package:gls/Widgets/myWidgets.dart';
import 'package:provider/provider.dart';

class JobListPage extends StatefulWidget {
  @override
  _JobListPageState createState() => _JobListPageState();
}

class _JobListPageState extends State<JobListPage> {
 JobsearchListModel _jobsearchListModel;
 JobListSearchProvider jobsearch;
  String search;
bool _isvisiblesearch=false;
bool isdismiss=true;
bool isdismiss1=false;
bool isdismiss2=false;
SlidableController slidableController;
  @override
  void initState() {
    super.initState();
    initialise();
  }

  initialise() async {
    
    setState(() {
     
    });
    //print(a);
  }
   void _toggleLogin() {
    setState(() {
      _isvisiblesearch = !_isvisiblesearch;
    });
  }
 @override
  void didChangeDependencies() {
    super.didChangeDependencies();
     jobsearch = Provider.of<JobListSearchProvider>(context).allRefresh();
    _jobsearchListModel = jobsearch.jobsearchListModel;
    // _stage = videosState.stage;
    // _errorMessage = videosState.errorMessage;
  }

  void actionSearch() {
   // String text = _searchTextCtrl.value.text;
    Provider.of<JobListSearchProvider>(context, listen: false);
       
  }

  @override
  Widget build(BuildContext context) {
    return
        Scaffold(
            backgroundColor: Colors.white,
            appBar: AppBar(
              brightness: Brightness.light,
              title: Text(
                'Jobs',
                style: TextStyle(color: Colors.black),
              ),
              centerTitle: true,
              backgroundColor: Colors.white,
              iconTheme: IconThemeData(color: Colors.black),
              elevation: 0.0,
              actions: <Widget>[
                IconButton(
                  icon: Icon(EvilIcons.search, size: 32,),
                  onPressed: (){
                    _toggleLogin();
                  },
                ),
              ],
            ),
            body:
                     Column(
                      children: <Widget>[
                        Visibility(
                          visible: _isvisiblesearch,
                          child: Container(
                             
                            padding: EdgeInsets.all(8.0),
                            child: Row(
                              children: <Widget>[
                                Expanded(
                                  child: TextField(
                                     style:
                            new TextStyle( color: Colors.white),
                                    decoration: InputDecoration(
                                     
                                   contentPadding: const EdgeInsets.only(
                              left: 16.0, bottom: 0.0, top: 0.0, right: 7),
                             
                                      filled: true,
                                      fillColor:  Color(0xFF1A35E4),
                                      enabledBorder: OutlineInputBorder(
                            borderSide: new BorderSide(color: Color(0xFF1A35E4)),
                            borderRadius: new BorderRadius.circular(12.0),
                          ),
                                      border: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(12)
                                      ),
                                      hintText: "Search Jobs",
                                     
                                      hintStyle: TextStyle(color: Colors.white70),
                                      prefixIcon:  Padding(
                              padding: EdgeInsets.only(top: 3, bottom: 3),
                              child: RawMaterialButton(
                                constraints: BoxConstraints.tight(Size(60, 50)),
                                onPressed: null,
                                child: Icon(EvilIcons.search, size: 32,color:Colors.white),
                                
                              ))
                                    ),
                                    onChanged: (text) {
                                      Provider.of<JobListSearchProvider>(context, listen: false).allRefresh();
                                      setState(() {
                                         _jobsearchListModel.data.open = jobsearch.jobsearchListModel.data.open
                                    .where((r) => (r.organizationname
                                        .toLowerCase()
                                        .contains(text.trim().toLowerCase())))
                                    .toList();
                                      });
                                    },
                                  ),
                                )
                              ],
                            ),
                          ),
                        ),
                        Expanded(
                          child: ListView.builder(
                            padding: EdgeInsets.symmetric(horizontal: 6.0),
                            itemCount: _jobsearchListModel.data.open.length,
                            itemBuilder: (BuildContext context, int index) {
                              var joblist=_jobsearchListModel.data.open[index];
                               return  OnSlide(
                    items: <ActionItems>[
                       ActionItems(
                         text: Text("Add Timesheet",style: TextStyle(fontSize:8),),
                         icon:  IconButton(icon:  Icon(Icons.archive), onPressed: () {},color: Colors.green,
                      ), onPress: (){}, backgroudColor: Colors.white),
                       ActionItems(
                          text: Text("Add Timesheet",style: TextStyle(fontSize:8),),
                         icon:  IconButton(icon:  Icon(Icons.delete), onPressed: () {}, color: Colors.red,
                      ), onPress: (){},  backgroudColor: Colors.white),
                         ActionItems(
                             text: Text("Add Timesheet",style: TextStyle(fontSize:8),),
                           icon:  IconButton( icon:  Icon(Icons.save),  onPressed: () {},color: Colors.blue,
                      ), onPress: (){},  backgroudColor: Colors.white),
                         ActionItems(
                            text: Text("Add Timesheet",style: TextStyle(fontSize:8),),
                           icon:  IconButton(  icon:  Icon(Icons.bookmark),
                        onPressed: () {},color: Colors.orange,
                      ), onPress: (){},  backgroudColor: Colors.white),
                    ],
                                child: Container(
                                  margin: EdgeInsets.symmetric(horizontal: 6.0,vertical: 4.0),
                                   decoration: MyStyles.boxDecorationwithRoudedCorner(color:AppTheme.white, boxRadius: 12,shdowColor: Colors.grey[300]),
                                  child: ListTile(
                                    onTap: (){
                                       Navigator.pushAndRemoveUntil(
    context,
    MaterialPageRoute(builder: (BuildContext context) => JobDetailPage()),
    ModalRoute.withName('/joblist'),);
                                    },
                                    
                                    title: Text(joblist.organizationname,style: TextStyle(fontSize:15, fontWeight:FontWeight.bold),),
                                    subtitle: Text(joblist.jobtypename+" -"+joblist.targetenddate,style: TextStyle(fontWeight:FontWeight.w500, fontSize:13),),
                                    trailing: Icon(Icons.star,size: 30, color: Colors.amber,),
                                  ),
                                ),
                              
                              );
                            },
                          ),
                        )
                      ],
                    ),
                
          );
  }
}

**Comment by ashishkj93** [comment]
Error: Could not find the correct Provider<JobListSearchProvider> above this JobListPage Widget

To fix, please:

  * Ensure the Provider<JobListSearchProvider> is an ancestor to this JobListPage Widget
  * Provide types to Provider<JobListSearchProvider>
  * Provide types to Consumer<JobListSearchProvider>
  * Provide types to Provider.of<JobListSearchProvider>()
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues

**Comment by rrousselGit** [comment]
The new error message about ProviderNotFoundException should help
