### ISSUE TITLE
What if I use the provider as Singleton?

### ISSUE THREAD

**Issue by realcarlos** [rrousselGit/provider#415]
void main() => runApp(MyApp());

class Counter with ChangeNotifier {
  static final shared = Counter_internal();
  Counter._internal(){
   _count = 0
  }
  int _count;
  int get count => _count;

  void increment() {
    _count++;
    notifyListeners();
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Counter.shared.increment();
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => Counter.shared,
      ],
      child: Consumer<Counter>(
        builder: (context, counter, _) {
          return MaterialApp(
            supportedLocales: const [Locale('en')],
            localizationsDelegates: [
              DefaultMaterialLocalizations.delegate,
              DefaultWidgetsLocalizations.delegate,
              _ExampleLocalizationsDelegate(counter.count),
            ],
            home: const MyHomePage(),
          );
        },
      ),
    );
  }
}

so that we could use the `Counter.shared` outside Tree nature, is there any issue about this way?

**Comment by rrousselGit** [comment]
If that works for you, then it's fine
