### ISSUE TITLE
How to use a ChangeNotifierProvider in a sliver

### ISSUE THREAD

**Issue by vanlooverenkoen** [rrousselGit/provider#416]
I have a vertical CustomScrollView. with 4 lists. I want every list to be updated only when the ChangeNotifier calls notify listeners. 

I could place the ChangeNotifierProvider over the CustomScrollView but then all lists will be updated every time. This is not what I want How can I achieve this?

**Comment by rrousselGit** [comment]
Hello!

Github is not the right place to ask for help.
If you still have a problem, consider asking your question on StackOverflow/twitter/reddit/slack
