### ISSUE TITLE
How to dispose a ChangeNotifier which is also provided with a ChangeNotifierProvider.value?

### ISSUE THREAD

**Issue by letsar** [rrousselGit/provider#426]
I have the following use case :
In a `StatefulWidget` I have a property. When this property changes, I have to dispose an older `ChangeNotifier` and create a new one with the new value of this property.
The `ChangeNotifier` is provided to the subtree with a `ChangeNotifierProvider.value`.
The issue is that the `ChangeNotifier` is disposed before the call to `willUpdateDelegate` and therefore, the `removeListener` on the previous `ChangeNotifier` is throwing an error because it's already disposed.

I'm not sure my explanation is very good, but this is an example of what I'm talking about; when we click on the increment button, there is a crash in Provider because the `ChangeNotifier` has been disposed before the call to `removeListener`.

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const IssuePage(),
    );
  }
}

class IssuePage extends StatefulWidget {
  const IssuePage({
    Key key,
  }) : super(key: key);

  @override
  _IssuePageState createState() => _IssuePageState();
}

class _IssuePageState extends State<IssuePage> {
  int _value = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: Column(
            children: <Widget>[
              ValueHolder(value: _value),
              RaisedButton(
                child: Text('increment'),
                onPressed: () {
                  setState(() {
                    _value++;
                  });
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ValueHolder extends StatefulWidget {
  const ValueHolder({
    Key key,
    this.value,
  }) : super(key: key);

  final int value;

  @override
  _ValueHolderState createState() => _ValueHolderState();
}

class _ValueHolderState extends State<ValueHolder> {
  ValueNotifier<int> _valueNotifier;

  @override
  void initState() {
    super.initState();
    _valueNotifier = ValueNotifier<int>(widget.value);
  }

  @override
  void didUpdateWidget(ValueHolder oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.value != widget.value) {
      _valueNotifier.dispose();
      _valueNotifier = ValueNotifier<int>(widget.value);
    }
  }

  @override
  void dispose() {
    _valueNotifier.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
      value: _valueNotifier,
      builder: (context, child) {
        final int value = context.watch<ValueNotifier<int>>().value;
        return Container(
            color: Colors.red,
            width: 200,
            height: 200,
            child: Center(child: Text(value.toString())));
      },
    );
  }
}
```

How can we prevent that?

**Comment by smiLLe** [comment]
why do you dispose the VN in ```didUpdateWidget```. Instead, you can set the ```_valueNotifier.value = widget.value```

**Comment by smiLLe** [comment]
Mh, why don't you use ```Provider.value```. 
```dart
/// IssuePage

@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: Column(
            children: <Widget>[
              Provider.value(value: _value, child: SomeThingElse()),
              RaisedButton(
                child: Text('increment'),
                onPressed: () {
                  setState(() {
                    _value++;
                  });
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
```

**Comment by letsar** [comment]
This is just an example to repro the issue. The code is more complex than
that but the issue is the same

**Comment by rrousselGit** [comment]
ChangeNotifierProvider.value will not dispose the ChangeNotifier

It is your job to do so (with a typical StatefulWidget?), as using the `.value` constructor, it is impossible for provider to know if the object is no longer used.

**Comment by letsar** [comment]
Yes I understood that, the issue is when I dispose my object, an error is thrown because provider try to remove its listener from an already disposed object.

**Comment by rrousselGit** [comment]
Oh I see what you're doing

That's an interesting case. Do you really need to create a new ValueNotifier?

Can't you instead do:

```dart
  @override
  void didUpdateWidget(ValueHolder oldWidget) {
    super.didUpdateWidget(oldWidget);
    // The previous oldWidget.value != newWidget.value is done by ValueNotifier itself
    _valueNotifier.value = widget.value;
  }
```

**Comment by letsar** [comment]
The ValueNotifier here is just to simply reproduce the issue. My case involves a ChangeNotifier which holds other ChangeNotifiers and needs to dispose them in its dispose method.

**Comment by rrousselGit** [comment]
I would suggest queueing the dispose to the end of the frame with
addPostFrameCallback

**Comment by Okiring** [comment]
@rrousselGit , can u kindly let the developers know about this behaviour via the package landing page "ChangeNotifierProvider.value will not dispose the ChangeNotifier". I just noticed this today and double checked and wondered how on earth had missed that, however the package says nothing about this. I read thru the USAGE etc but nothing talks about this behaviour. I previously thought the @dispose override worked for all **ChangeNotifierProviders**.
