### ISSUE TITLE
Is there any way we can inject provider dependancy to normal class in flutter?

### ISSUE THREAD

**Issue by iavsm** [rrousselGit/provider#429]
I have one normal dart class in which I want to provide two provider dependency.

So I can access that class though out of my application. I can pass that dependency from the build method of the widget and then I can use this class but I don't want to do that, like 100 times I have to pass that dependency if I used that class 100 times.

I also want to use this class from every lifecycle of flutter as it's generating different types of events for application.

I also want to initialize genrateUserProerties() method only once when the dependency is ready and when the user opens the application.

This is initialized before any provider initializes and it's not always used from the method where we have context available.

I need a way to provide that dependency in a way we can initialize genrateUserProerties() only once.

User _user; and BrandCofiguration _activeBrand; I need these two be pass here when it's ready.

User _user; and BrandCofiguration _activeBrand; both are coming from two different Providers when I received a valid response from the server.

`class FireBaseAnalyticsBase {
  static FirebaseAnalytics _analytics;
  static FirebaseAnalyticsObserver _observer;
  **User _user;**
  BuildContext _context;
  **BrandCofiguration _activeBrand;**
  int _seconds;
  Stopwatch _stopwatch;
  String _eventName;
  Map<String, dynamic> _userProperties = {};
  bool _isTimeTrackEvent;

  FireBaseAnalyticsBase(BuildContext context, UserProvider userProvider,
      BrandSelectionProvider brandSelectionProvider) { 
    this._context = context;
    _analytics = FirebaseAnalytics();
    _observer = FirebaseAnalyticsObserver(analytics: _analytics);
    _activeBrand = brandSelectionProvider.activeBrand;
    _user = userProvider.authenticatedUser;
    if (_user != null) {
      genrateUserProerties();
    }
  }

  void startFirebaseEventWithoutTime(String eventName) {
    this._eventName = eventName;
    _isTimeTrackEvent = false;
    logFirebaseEvent();
  }

  void startFireBaseEventWithTime(String eventName) {
    _stopwatch = Stopwatch();
    _stopwatch.start();
    _isTimeTrackEvent = true;
    _eventName = eventName;
  }

  void stopFireBaseTimeEvent() {
    _stopwatch.stop();
    _seconds = (_stopwatch.elapsedMilliseconds / 1000) as int;
    _stopwatch.reset();
    logFirebaseEvent();
  }

  Future<void> logFirebaseEvent() async {
    if (_isTimeTrackEvent) {
      _userProperties
          .addAll({FirebaseAnalyticsEnum.time_spent.value: _seconds});
    }
    print("firebase test");
    await _analytics.logEvent(
      name: _eventName,
      parameters: _userProperties,
    );
  }

  Future<void> genrateUserProerties() async {
    print("firebase properties initilize");
    var _packageInfo = await PackageInfo.fromPlatform();
    _userProperties = {
      FirebaseAnalyticsEnum.user_id.value: _user.id.toString(),
      FirebaseAnalyticsEnum.platform.value: Platform.operatingSystem,
      FirebaseAnalyticsEnum.device_language.value:
          Localizations.localeOf(_context).languageCode,
      FirebaseAnalyticsEnum.application.value: _packageInfo.appName,
      FirebaseAnalyticsEnum.current_api.value: Config.CURRENT_API,
      FirebaseAnalyticsEnum.device_type.value: _user.id.toString(),
      FirebaseAnalyticsEnum.app_version.value: Config.CURRENT_VERSION,
      FirebaseAnalyticsEnum.is_admin.value: _user.isAdmin,
      FirebaseAnalyticsEnum.is_educator.value: _user.educator,
      FirebaseAnalyticsEnum.is_brand_ambassador.value: _user.brandAmbassador,
      FirebaseAnalyticsEnum.salon_role.value: _user.salongroup,
      FirebaseAnalyticsEnum.brand.value: _activeBrand.brandName,
      FirebaseAnalyticsEnum.school_role.value: _user.schoolgroup,
    };
  }
}`

**Comment by smiLLe** [comment]
And now you expect everyone to format your code in order to understand what you are trying to do, right?

**Comment by iavsm** [comment]
It will be good if you suggest some example or pattern in flutter.

**Comment by rrousselGit** [comment]
You can watch my last talk at the Flutter europe, which mentions a solution near the end https://www.youtube.com/watch?v=BulIREvHBWg
