### ISSUE TITLE
How can acess provider data from normal class

### ISSUE THREAD

**Issue by akhilprogrammer** [rrousselGit/provider#430]
I want to acesa provider data from normal class. But in normal Class buildcontext not available, then how it is possible. I dont like to pass into constructor.

**Comment by smiLLe** [comment]
What's the problem with that?
> I dont like to pass into constructor.

**Comment by hsul4n** [comment]
> What's the problem with that?
> 
> > I dont like to pass into constructor.

Will.. 

The main question here is can we access any data from provider without using context or build context..

The answer is truly nope because provider depends on context to find the exact data.

**Comment by rrousselGit** [comment]
There's an alternative offered at the end of my last talk https://www.youtube.com/watch?v=BulIREvHBWg
