### ISSUE TITLE
Accessing provider from pages without wrapping root widget

### ISSUE THREAD

**Issue by hsul4n** [rrousselGit/provider#432]
It will be good feature that we can pass provider with all nested routes.

I don’t know that this can be applied because I think that the main idea of provider is passing data between nested widgets not nested routes or pages.

Here is an example:
```dart
main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FooPage(),
    );
  }
}

class FooPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<MyProvider>(
      create: (_) => MyProvider(),
      child: RaisedButton(
        child: Text("Go to bar"),
        onPressed: ()=> Navigator.of(context).push(
          MaterialPageRoute(
            builder: (_) => BarPage(),
          )
        ),
      ),
    );
  }
}

class BarPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<MyProvider>(
      builder: (context, provider, child) {
        ...
      },
    );
  }
}
```

**Comment by rrousselGit** [comment]
That is not feasible, not with InheritedWidgets at the very least.

I have some plans that solves this problem (and many others), but that won't be available inside `provider` in the beginning.
I'll make an announcement about it relatively soon

**Comment by rrousselGit** [comment]
Closing this for now, this it's not feasible

**Comment by awhitford** [comment]
I am running into this problem now.  Provider works great for child widgets, but as soon as the user navigates to a new screen, the provider is no longer part of the context.  I must admit that I did not expect this.  An explanation in the FAQ would be great, along with some advice or recommendations for a workaround.

**Comment by rrousselGit** [comment]
Why do you want to place your provider inside a route?

**Comment by feinstein** [comment]
@rrousselGit consider this scenario:

The App has a login screen, once the user logs in it navigates to a new screen, that shows the user data. 

For that new screen we have a `ChangeNotifier`, acting as a `ViewModel`, to configure the screen for that particular user. For example, it could have a `isAdmin` that changes the screen if the user is an admin for the App or not.

Now there are several buttons that navigate to new screens, like "Show My Tasks" opens a `Tasks` screen. This screen also changes if the user is an admin (he can create and delete tasks) or not (can only visualize tasks created for him by an admin).

Being able to pass to each route the same `ViewModel` or some sort of class that configures the screens is very valuable.

With Redux there's a whole App state, but with Provider is hard to pass around information that's useful for many different screens/routes.

**Comment by rrousselGit** [comment]
@feinstein why not just place the provider above MaterialApp?

**Comment by feinstein** [comment]
Because that complicate things a lot.

I don't have that information when the app starts, only after the user login. So I will have to create an empty representation, or a null. I will need a mechanism for mutating that information, so I can't just pass a simple object, it will need to be something like a ViewModel or a wrapper.

Redux has a whole architecture for this, and it's a pretty complicated one IMHO, with App State, Reducers, Middleware, all that logic spread all over the place in several files. I rather keep things simple if possible.

**Comment by xsahil03x** [comment]
@rrousselGit any suggestions on the comment made by @feinstein? We are also facing similar usecase.

**Comment by rrousselGit** [comment]
@xsahil03x the official recommendation is to place a provider above everything.

There isn't another solution

**Comment by xsahil03x** [comment]
Thanks @rrousselGit 😃
