### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by ghost** [rrousselGit/provider#435]
Hi,

the following line redirects the reader to the same page.

"To read more about provider, see the **documentation**."
https://pub.dev/documentation/provider/latest/

Regards,
Yasser

**Comment by rrousselGit** [comment]
Hello

What's wrong with that? This is the correct link

**Comment by yasser-kfupm** [comment]
it is not meaningful to redirect the reader to the same page

**Comment by rrousselGit** [comment]
What else do you expect?

**Comment by yasser-kfupm** [comment]
the reader should not be redirected to the same page

**Comment by rrousselGit** [comment]
Could you give me the link of the page you'd expect people to be redirected to?

**Comment by apiep** [comment]
Maybe point the link to the "Usage" part of the document?
