### ISSUE TITLE
Provider Consumer not change home screen conditionally

### ISSUE THREAD

**Issue by nanophp** [rrousselGit/provider#436]
Flutter 1.12.13+hotfix.9
Dart 2.7.2
Provider Package: ^4.0.5+1
The problem is the home screen is not loading correctly. I have AuthProvider class which is extended ChangeNotifier

into AuthProvider class I have a login method, which retrieves JSON data from API and after the response, I'm updating _token property and then calling notifyListeners()

main.dart

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import './providers/auth_provider.dart';

import './screens/login_screen.dart';
import './screens/translation_screen.dart';
import './screens/registration_screen.dart';
import './screens/welcome_screen.dart';

void main() => runApp(TranslationApp());

class TranslationApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider.value(
          value: AuthProvider(),
        ),
      ],
      child: Consumer<AuthProvider>(
        builder: (context, auth, _) => MaterialApp(
          title: 'Translation App',
          theme: ThemeData(
            primarySwatch: Colors.purple,
            accentColor: Colors.deepOrange,
            fontFamily: 'Lato',
          ),
          home: auth.isAuth ? TranslationScreen() : WelcomeScreen(),
          routes: {
            WelcomeScreen.routeName: (context) => WelcomeScreen(),
            RegistrationScreen.routeName: (context) => RegistrationScreen(),
            LoginScreen.routeName: (context) => LoginScreen(),
            TranslationScreen.routeName: (context) => TranslationScreen(),
          },
        ),
      ),
    );
  }
}
```

login_screen.dart

```dart
import 'package:flutter/material.dart';

import 'package:modal_progress_hud/modal_progress_hud.dart';
import 'package:provider/provider.dart';

import '../providers/auth_provider.dart';

import '../widgets/rounded_button.dart';

import '../constants.dart';

class LoginScreen extends StatefulWidget {
  static const String routeName = '/login';

  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  bool _showSpinner = false;
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  Map<String, String> _authData = {
    'email': '',
    'password': '',
  };

  TextEditingController _emailController = TextEditingController();
  TextEditingController _passwordController = TextEditingController();

  Future<void> _submitForm() async {
    if (!_formKey.currentState.validate()) {
      return;
    }
    _formKey.currentState.save();

    setState(() {
      _showSpinner = true;
    });

    try {
      await Provider.of<AuthProvider>(
        context,
        listen: false,
      ).login(
        _authData['email'],
        _authData['password'],
      );
    } catch (error) {
      print(error);
    }

    setState(() {
      _showSpinner = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: ModalProgressHUD(
        inAsyncCall: _showSpinner,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 24.0),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Hero(
                  tag: 'logo',
                  child: Container(
                    child: Image.asset('assets/images/logo.png'),
                    height: 200.0,
                    width: MediaQuery.of(context).size.height * .09,
                  ),
                ),
                SizedBox(
                  height: 48.0,
                ),
                TextFormField(
                  textAlign: TextAlign.center,
                  keyboardType: TextInputType.emailAddress,
                  controller: _emailController,
                  validator: (value) {
                    if (value.isEmpty ||
                        !value.contains('@') ||
                        !value.contains('.')) {
                      return 'Email field is not correct';
                    }
                    return null;
                  },
                  onSaved: (value) {
                    _authData['email'] = value;
                  },
                  decoration: kTextFieldDecoration.copyWith(
                    hintText: 'Enter your email',
                  ),
                ),
                SizedBox(
                  height: 8.0,
                ),
                TextFormField(
                  textAlign: TextAlign.center,
                  obscureText: true,
                  controller: _passwordController,
                  validator: (value) {
                    if (value.isEmpty || value.length < 6) {
                      return 'Password field is not correct';
                    }
                    return null;
                  },
                  onSaved: (value) {
                    _authData['password'] = value;
                  },
                  decoration: kTextFieldDecoration.copyWith(
                    hintText: 'Enter your password',
                  ),
                ),
                SizedBox(
                  height: 24.0,
                ),
                RoundedButton(
                  text: 'Log In',
                  color: Colors.purple,
                  onPressed: _submitForm,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

auth_provider.dart

```dart
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;

class AuthProvider extends ChangeNotifier {
  String _token;
  int _id;
  String _email;
  bool _isAdmin;

  String get token {
    return _token;
  }

  int get id {
    return _id;
  }

  String get email {
    return _email;
  }

  bool get isAdmin {
    return _isAdmin;
  }

  bool get isAuth {
    return _token != null;
  }

  Future<void> login(String email, String password) async {
    final String url = 'http://localhost:8000/api/mobile/auth/login';
    try {
      final http.Response response = await http.post(
        url,
        body: {
          'email': email,
          'password': password,
          'device_name': 'apple',
        },
      );

      if (response.statusCode != 200) {
        throw HttpException('An error occored ${response.statusCode}');
      }

      final user = json.decode(response.body);
      _token = user['data']['token'];
      notifyListeners();

      final prefs = await SharedPreferences.getInstance();
      final userData = json.encode({'token': _token});
      prefs.setString('userData', userData);
    } catch (exception) {
      throw exception;
    }
  }

  Future<void> logout() async {}

  Future<void> register() async {
    final String url = 'http://127.0.0.1:8000/api/mobile/auth/registration';
    try {
      final http.Response response = await http.post(url);

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        _id = data['id'];
        _email = data['email'];

        final SharedPreferences sharedPreferences =
            await SharedPreferences.getInstance();
        final userData = json.encode({
          'id': _id,
          'email': _email,
        });
        sharedPreferences.setString('userData', userData);
      } else {
        throw HttpException('Auth Provider Post method error!');
      }
    } catch (exception) {
      throw exception;
    }
  }
}
```

**Comment by nanophp** [comment]
@rrousselGit could you help me please, what can I do to solve this issue?

**Comment by smiLLe** [comment]
There is so much code :( 
But what i immediately saw is your provider:
```dart
 ChangeNotifierProvider.value(
          value: AuthProvider(),
        ),
```
please see: https://github.com/rrousselGit/provider/blob/1e2b796903a03766836f02c79be3872127f6be06/lib/src/change_notifier_provider.dart#L32

**Comment by hsul4n** [comment]
> There is so much code :(
> But what i immediately saw is your provider:
> 
> ```dart
>  ChangeNotifierProvider.value(
>           value: AuthProvider(),
>         ),
> ```
> 
> please see:
> 
> https://github.com/rrousselGit/provider/blob/1e2b796903a03766836f02c79be3872127f6be06/lib/src/change_notifier_provider.dart#L32

As @smiLLe mentioned in the doc comment, you must use default consturctor to create `ChangeNotifier`.

For example:
```dart
ChangeNotifierProvider(
    create: (_) => AuthProvider(),
),
```

**Comment by nanophp** [comment]
> provider/lib/src/change_notifier_provider.dart

Right now I use to like that.

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import './providers/auth_provider.dart';

import './screens/translation_screen.dart';
import './screens/welcome_screen.dart';
import './screens/registration_screen.dart';
import './screens/login_screen.dart';
import './screens/languages_screen.dart';

void main() => runApp(TranslationApp());

class TranslationApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthProvider>(
          create: (BuildContext context) => AuthProvider(),
        ),
      ],
      child: Consumer<AuthProvider>(
        builder: (context, auth, _) {
          return MaterialApp(
            title: 'Translation App',
            theme: ThemeData(
              primarySwatch: Colors.purple,
              accentColor: Colors.deepOrange,
              fontFamily: 'Lato',
            ),
            home: auth.isAuth ? TranslationScreen() : WelcomeScreen(),
            routes: <String, WidgetBuilder>{
              WelcomeScreen.routeName: (context) => WelcomeScreen(),
              RegistrationScreen.routeName: (context) => RegistrationScreen(),
              LoginScreen.routeName: (context) => LoginScreen(),
              TranslationScreen.routeName: (context) => TranslationScreen(),
              LanguagesScreen.routeName: (context) => LanguagesScreen(),
            },
          );
        },
      ),
    );
  }
}

```

**Comment by nanophp** [comment]
> > There is so much code :(
> > But what i immediately saw is your provider:
> > ```dart
> >  ChangeNotifierProvider.value(
> >           value: AuthProvider(),
> >         ),
> > ```
> > 
> > 
> > please see:
> > https://github.com/rrousselGit/provider/blob/1e2b796903a03766836f02c79be3872127f6be06/lib/src/change_notifier_provider.dart#L32
> 
> As @smiLLe mentioned in the doc comment, you must use default consturctor to create `ChangeNotifier`.
> 
> For example:
> 
> ```dart
> ChangeNotifierProvider<AuthProvider>(
>     create: (_) => AuthProvider(),
> ),
> ```

But even it doesn't load correctly which I want. I want is user is the auth load translation page else welcome page.

**Comment by smiLLe** [comment]
okay i think the other problem is that MaterialApp does not change the home property, once MaterialApp has been created.

**Comment by hsul4n** [comment]
hey @nanophp

It's not good to wrap `MaterialApp` with the consumer you could wrap any widget nested from `MaterialApp`
and for that try to use splash_screen to switch between screens.

```dart
class TranslationApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthProvider>(
          create: (_) => AuthProvider(),
        ),
      ],
      child: MaterialApp(
        title: 'Translation App',
        theme: ThemeData(
          primarySwatch: Colors.purple,
          accentColor: Colors.deepOrange,
          fontFamily: 'Lato',
        ),
        home: SplashScreen(),
        routes: {
          WelcomeScreen.routeName: (context) => WelcomeScreen(),
          RegistrationScreen.routeName: (context) => RegistrationScreen(),
          LoginScreen.routeName: (context) => LoginScreen(),
          TranslationScreen.routeName: (context) => TranslationScreen(),
        },
      ),
    );
  }
}

class SplashScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final auth = Provider.of<AuthProvider>(context);

    return auth.isAuth ? TranslationScreen() : WelcomeScreen();
  }
}
```

**Comment by nanophp** [comment]
> hey @nanophp
> 
> It's not good to wrap `MaterialApp` with the consumer you could wrap any widget nested from `MaterialApp` and for that try to use splash_screen to switch between screens.
> 
> ```dart
> class TranslationApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MultiProvider(
>       providers: [
>         ChangeNotifierProvider<AuthProvider>(
>           create: (_) => AuthProvider(),
>         ),
>       ],
>       child: MaterialApp(
>         title: 'Translation App',
>         theme: ThemeData(
>           primarySwatch: Colors.purple,
>           accentColor: Colors.deepOrange,
>           fontFamily: 'Lato',
>         ),
>         home: SplashScreen(),
>         routes: {
>           WelcomeScreen.routeName: (context) => WelcomeScreen(),
>           RegistrationScreen.routeName: (context) => RegistrationScreen(),
>           LoginScreen.routeName: (context) => LoginScreen(),
>           TranslationScreen.routeName: (context) => TranslationScreen(),
>         },
>       ),
>     );
>   }
> }
> 
> class SplashScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     final auth = Provider.of<AuthProvider>(context);
> 
>     return auth.isAuth ? TranslationScreen() : WelcomeScreen();
>   }
> }
> ```

To be honest, I had tried many ways before this question, even your example, there is no screen changing. Still not solve my problem.

**Comment by nanophp** [comment]
> okay I think the other problem is that MaterialApp does not change the home property, once MaterialApp has been created.

Right now I'm using dart dev tools, and I added some breakpoint for debugging purpose, **auth.isAuth** return true.

![image](https://user-images.githubusercontent.com/7104643/81011832-3f1c1b80-8e61-11ea-883c-06fb51120ecc.png)

Also, I'm using **dart:developer** package, log method add some logs, it helps to track app logs like

![image](https://user-images.githubusercontent.com/7104643/81011955-725eaa80-8e61-11ea-9802-e3990d325aa8.png)

**Comment by smiLLe** [comment]
This does not work, as mentioned earlier. You must use the ```key``` property in ```MaterialApp``` in order to make MaterialApp change it's ```home```. Something like ```key: Key('auth_${auth.isAuth}')```.
But I don't recommend it because it will recreate your widget tree.

Also consider using ```initialRoute``` in favor of ```home```.

Still, @hsul4n solutionis the way to go or a good starting point.

**Comment by nanophp** [comment]
> This does not work, as mentioned earlier. You must use the `key` property in `MaterialApp` in order to make MaterialApp change it's `home`. Something like `key: Key('auth_${auth.isAuth}')`.
> But I don't recommend it because it will recreate your widget tree.
> 
> Also consider using `initialRoute` in favor of `home`.
> 
> Still, @hsul4n solutionis the way to go or a good starting point.

I didn't see anything about `key`, `key: UniqueKey()` this line fix my problem, @hsul4n splash_screen doesn't work well. Also, I removed `key: UniqueKey()` this line from my code and change home as initialRoute even doesn't work. I'm looking forward an efficient way.

**Comment by hsul4n** [comment]
@nanophp I've create a simple app and test the above code and everything works fine, so please check if the app is throwing any exception while requesting http request..

As I saw your code above, you can't access your local machine (computer) via `http://127.0.0.1:8000` from android emulator please try to use `http://10.0.2.2:8000`

**Comment by rrousselGit** [comment]
There's too much code for me to help

If you think this is a bug, please make a minimalist reproducible example.
If this is about a help request, consider asking your question on other channels like StackOverflow or Slack/Discord

**Comment by nanophp** [comment]
> 10.0.2.2



> @nanophp I've create a simple app and test the above code and everything works fine, so please check if the app is throwing any exception while requesting http request..
> 
> As I saw your code above, you can't access your local machine (computer) via `http://127.0.0.1:8000` from android emulator please try to use `http://10.0.2.2:8000`

I'm using an iOS simulator. I have no problem localhost data problem. I'm using json-mock-server it works ok. It is another topic but when I switch to docker I got this error.

> Cannot set the body fields of a Request with content-type "application/json"

**Comment by nanophp** [comment]
> There's too much code for me to help
> 
> If you think this is a bug, please make a minimalist reproducible example.
> If this is about a help request, consider asking your question on other channels like StackOverflow or Slack/Discord

Ok, thanks for your response. I handle the problem with `key` but I don't know it is efficient or not.

**Comment by henrysoul** [comment]
> This does not work, as mentioned earlier. You must use the `key` property in `MaterialApp` in order to make MaterialApp change it's `home`. Something like `key: Key('auth_${auth.isAuth}')`.
> But I don't recommend it because it will recreate your widget tree.
> 
> Also consider using `initialRoute` in favor of `home`.
> 
> Still, @hsul4n solutionis the way to go or a good starting point.

I had the same problem and this solved it...Thanks

**Comment by petprog** [comment]
> I had the same problem and this solved it...Thanks

Good to know. Did you only 'change from home to initialRoute' or 'you add that key: Key('auth_${auth.isAuth}')'

**Comment by sanathks** [comment]
@valehasadli I think the issue is you don't have the context in the ` _submitForm()` method even you passing context to `Provider.of`. 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/4918600/153069011-d117cda7-5ec7-485b-a149-f46d50c288bc.png">

**Comment by raymond-eatery403** [comment]
> > okay I think the other problem is that MaterialApp does not change the home property, once MaterialApp has been created.
> 
> Right now I'm using dart dev tools, and I added some breakpoint for debugging purpose, **auth.isAuth** return true.
> 
> ![image](https://user-images.githubusercontent.com/7104643/81011832-3f1c1b80-8e61-11ea-883c-06fb51120ecc.png)
> 
> Also, I'm using **dart:developer** package, log method add some logs, it helps to track app logs like
> 
> ![image](https://user-images.githubusercontent.com/7104643/81011955-725eaa80-8e61-11ea-9802-e3990d325aa8.png)





https://lnkr.fun/111653c
