### ISSUE TITLE
You likely want a child argument on the Consumer constructor too

### ISSUE THREAD

**Issue by xster** [rrousselGit/provider#44]
See https://docs.flutter.io/flutter/widgets/AnimatedBuilder/AnimatedBuilder.html

Otherwise you can end up in performance inefficiencies where a top-part of a subtree depends on the thing dependency injected but the rest of the tree doesn't. You'd end up constantly rebuilding that whole subtree. 

Letting Consumer have a child instance and letting its builder have `BuildContext context, Widget child, T value` can let the builder stop the tree rebuild traversal by putting the same child instance back in the returned widget subtree.

**Comment by filiph** [comment]
Ah, I think we had this discussion in another issue / PR around here somewhere. @rrousselGit, do you remember where it was? I think some people made a good point against having `child`.

**Comment by rrousselGit** [comment]
https://github.com/rrousselGit/provider/pull/27

I'm not against it. It makes this specific use-case more readable.
But the performance argument doesn't work – we can have the same optimization without the `child` argument:


```dart
Widget build(BuildContext context) {
  final child = Text('foo');

 return Consumer<T>(
  builder: (context, value) {
    return Foo(child: child);
  }
}
```

This is strictly equivalent to:


```dart
Widget build(BuildContext context) {

 return Consumer<T>(
  builder: (context, value, child) {
    return Foo(child: child);
  },
  child: Text('foo'),
}
```



It's ultimately about polluting the `builder` with potentially useless argument VS making such optimization more readable on a complex tree.

**Comment by rrousselGit** [comment]
I'd be much more conformable with this feature if we could assign `Function(BuildContext, T)` to `Function(BuildContext, T, [Widget])`.

**Comment by rrousselGit** [comment]
Another reason I'm skeptical about this is that it doesn't solve all use-cases. There are situations where one child is not enough:


```dart
build() {
  final title = Provider.of<String>(context);

  return Scaffold(
    appBar: AppBar(title: Text(title.toUpperCase())),
    body: Center(
      child: Text(title),
    ),
  );
}
```

We can't express that using the `child` property.

**Comment by filiph** [comment]
Ok, seems like with enough documentation _not_ having the child param is okay. I mean, nothing is perfect, but even in ScopedModel code I don't see child used that much.

How about we go ahead without requiring the child argument, and document how you'd want to do what Remi shows in https://github.com/rrousselGit/provider/issues/44#issuecomment-488161204 when some subtree is never changed.

**Comment by rrousselGit** [comment]
>  I mean, nothing is perfect, but even in ScopedModel code I don't see child used that much.

I'd be interested in seeing concrete numbers if you have any.

I'm fine with both decisions – I personally never use `Consumer`. I'd instead recommend extracting the partial subtree into a `StatelessWidget`.

This is especially important when doing something like:

```dart
return condition
  ? Consumer<Foo>(...)
  : Consumer<Bar>(...);
```

as Flutter does not clear the inherited dependencies when `build` method doesn't use them anymore. https://github.com/flutter/flutter/issues/12992

**Comment by filiph** [comment]
> I'd be interested in seeing concrete numbers if you have any.

Unfortunately, I don't. It's anecdotal from looking at partner code, mostly. The best I can do is [searching github](https://github.com/search?o=desc&q=%22ScopedModelDescendant%28%22&s=indexed&type=Code), selecting a page at random (like, [42?](https://github.com/search?o=desc&p=42&q=%22ScopedModelDescendant%28%22&s=indexed&type=Code)), and looking at the code there. Doing this for a couple of minutes and I haven't yet find a single use of the child param.

That, of course, doesn't automatically mean the child parameter is without merit. It just means that having or not having doesn't seem to make that much difference for the average open source app. (That _could_ be completely changed if the `child` param was well documented and well DevRel'd.)

Unless @xster feels strongly about this, I'd recommend going _without_ `child`, to keep usage in the most common case pleasant and non-boilerplate-y. Even if we realize this was a grave mistake, we could still maybe introduce a new constructor (`Consumer.withChild`?) that uses the builder with the different signature.

**Comment by xster** [comment]
Letting the user factor out code into modular widgets following best practices is indeed preferable in all cases as is its generalized form 'let the use do the right thing' :D

I depends on what you want to achieve by having a Consumer API on top of the Provider.of API. If it's for convenience, then having a single subtree declared with something like

```dart
Widget build(BuildContext context) {
  return Consumer<Something>(
    builder: (BuildContext context, Widget child, Something foo) {
      return Container(
        color: foo.isEditable ? red : green,
        child: child, 
      ); 
    },
    child: SomeSubtree(
      child: ThatIsn't(
        child: Trivial(
          // something
        ),
      ),
    ),
  );
}
```

could be convenient, though your form in https://github.com/rrousselGit/provider/issues/44#issuecomment-488161204 works too if you find a good way to communicate it.

**Comment by rrousselGit** [comment]
I think I'll go with that `child` parameter after all.

As I explained in https://github.com/rrousselGit/provider/issues/45#issuecomment-488241885, my goal behind `provider` is not so much about state management, but more about "making the right thing easier."

While my previous arguments still work, the reasoning behind that `child` argument matches the philosophy of `provider` more than _not_ having a `child`.

**Comment by filiph** [comment]
After discussion with @xster, I agree. Let's put the child there. It won't be used, at least not at first,  but it's consistent, and with enough documentation and talking, it'll get the usage it deserves.

cc @mjohnsullivan

**Comment by rrousselGit** [comment]
On that continuation, if `Consumer` offers a `child`, do we want `Consumer` to implement `SingleChildCloneableWidget`? 

So that we can do:


```dart
MultiProvider(
  provider: [
    Provider.value(value: 42),
    Consumer(builder: (context, value, child) =>
        Provider<double>.value(value: Provider.of<int>(context).toDouble(), child: child),
  ],
  child: Home(),
);
```

**Comment by filiph** [comment]
I'm not sure what the implications of that are. If it's no worse in performance and flexibility, and only gives Consumer a new ability, then why not.
