### ISSUE TITLE
Using builder in ChangeNotifierProvider's constructor throws an exception

### ISSUE THREAD

**Issue by wangzhiming8916** [rrousselGit/provider#442]
```Dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Goods List Page')),
      body: ChangeNotifierProvider(
        create: (_) => GoodsListModel(),
        builder: _buildGoodsListView,
      ),
    );
  }

  Widget _buildGoodsListView(BuildContext context, _) {
    final model = Provider.of<GoodsListModel>(context, listen: false);
    return ListView.builder(
      itemCount: model.goodList.length,
      itemBuilder: (context, index) => Builder(builder: (context) => _buildGoodsItem(context, index)),
    );
  }
```

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building ChangeNotifierProvider<GoodsListModel>(dirty, message: 'package:provider/src/inherited_provider.dart': Failed assertion: line 126 pos 12: 'child != null': ChangeNotifierProvider<GoodsListModel> used outside of MultiProvider must specify a child\nSee also: https://flutter.dev/docs/testing/errors, dirty, renderObject: RenderErrorBox#ee35f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE):
ChangeNotifierProvider<GoodsListModel> used outside of MultiProvider must specify a child
'package:provider/src/inherited_provider.dart':
Failed assertion: line 126 pos 12: 'child != null'

The relevant error-causing widget was: 
  ChangeNotifierProvider<GoodsListModel> file:///Users/wangzhiming26/Desktop/jd-projects/%E6%B1%AA%E5%B8%88%E5%82%85/flutter_engineer_wang/example/lib/main.dart:90:13
When the exception was thrown, this was the stack: 
#2      InheritedProvider.buildWithChild (package:provider/src/inherited_provider.dart:126:12)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by smiLLe** [comment]
> ChangeNotifierProvider used outside of MultiProvider must specify a child

So you basically want to add child to your ```ChangeNotifierProvider```

**Comment by smiLLe** [comment]
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Goods List Page')),
      body: ChangeNotifierProvider(
        create: (_) => GoodsListModel(),
        child: GoodsListView()
      ),
    );
  }

class GoodsListView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final model = Provider.of<GoodsListModel>(context, listen: false);
    return ListView.builder(
      itemCount: model.goodList.length,
      itemBuilder: (context, index) =>
          Builder(builder: (context) => _buildGoodsItem(context, index)),
    );
  }
}

```

**Comment by passsy** [comment]
Also ran into this. I don't understand why a `builder` doesn't work here. AFAIK `builder` is the equivalent for `child: Builder(...)` - which works.

```dart
// works
ChangeNotifierProvider(
  create: (_) => GoodsListModel(),
  child: Builder(
    builder: _buildGoodsListView,
  )
),
```

```dart
// doesn't work
ChangeNotifierProvider(
  create: (_) => GoodsListModel(),
  builder: _buildGoodsListView,
),
```
