### ISSUE TITLE
Re-using and resetting the fields of an existing ChangeNotifier object

### ISSUE THREAD

**Issue by abayomiAkanji** [rrousselGit/provider#444]
I have a `ChangeNotifier` object which I'm using to manage the state of a view. When I `pop` the view and later return to it, the old states (values) of the data are still retained.
How do I reset the values/states in order to have them all return to their default values? I understand that the `ChangeNotifier` Classes are prepared at the point of running the app, so calling `Provider.of<Class>(context);` to access the object does not mean the object is just being created (at that point).

How to I reset the values without having to manually update all the fields that I created in the Notifier Class?

**Comment by EdwynZN** [comment]
> I understand that the ChangeNotifier Classes are prepared at the point of running the app

If that is the point when you need them yeah, but if you are in another route and your app doesn't need it until you create the route/view perhaps you would want to create that ChangeNotifierProvider after the model route. I'll suppose you have a big class with some state parameters called A and you need some special parameters at the beginning of your app but at the same time when you open a route or view you want to start fresh, that could be another class called B inside A

```
class A with ChangeNotifier{
 bool favorite;
 bool darkMode;
...
 B _b;

  set updateB(B b){
  _b = b;
  notifyListeners();
}
...

  @override
  void notifyListeners() {
    super.notifyListeners();
  }
}

class B {
  List<String> order = <String>[];
  bool isOpen = false;

 B({bool newValue}) : this.isOpen = newValue ?? this.isOpen;

  ....
}


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
  /* 
  ///You created it here but if you're not going to use it at the beginning
  /// there is no point to create it here in the first place
  return ChangeNotifierProvider<A>(
    create: (_) => A(),
    child: MaterialApp(home: Scaffold(body: Center(child: TestWidget())))
  );
  */
    return MaterialApp(home: Scaffold(body: Center(child: TestWidget())));
  }
}

class TestWidgetextends StatelessWidget {
  @override
  Widget build(BuildContext context) {
   return RaisedButton(
        child: Text("Create B Object"),
        onPressed: () async {
          B myObject = await await Navigator.push(context, new MaterialPageRoute<B>(
             builder: (BuildContext context) {
              return Provider<B>(
                create: (_) => B(newValue: true),
                child: ViewWidget()
        );
       }
     )
    },
   )
  }
}


class ViewWidget extends StatefulWidget {
  ViewWidget State createState() => ViewWidget State();
}

class ViewWidget State extends State<ViewWidget > {
  @override
  Widget build(BuildContext context) {
    B b = Provider.of<B>(context);
    B bObject = Provider.of<B>(context, listen: false);
    return Scaffold(body: Center(
                  child: GestureDetector(
                    child: new Text('My Value is ${b.isOpen}'),
                     onTap: () => Navigator.pop(context, bObject); //just to be sure because after popping the provider will be disposed
                     onDoubleTap: () =>setState(() =>  b.isOpen = !b.isOpen),
                  ),
               )
            );
  }
}

```

You start your app with your object B within A, then when you push a route or dialog you want to show all B defaults parameters, not the one currently being used, so you made a new B provider class inside that route, after poping you can decide if you want to use the changes the user made. I don't know how else I can help you without a current example of what are you trying to do

**Comment by abayomiAkanji** [comment]
Hi @EdwynZN Many thanks for your response.

Here is my example:

```
class MyScreen extends StatefulWidget {
  
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {

  MyViewModel viewModel;

  @override
  Widget build(BuildContext context) {

    viewModel = Provider.of<QuestionPostingViewModel>(context);
    viewModel.question = getQuestion();

    return Scaffold();

    );

  }

}
```

Every time I `pushNamed` that `routeName` of this widget, it still holds the old values of the `viewModel` (which is a `ChangeNotifier` object). The goal is to reset the values of the `viewModel`.

**Comment by abayomiAkanji** [comment]
Hi @EdwynZN Many thanks for your response.

Here is my example:

```
class MyScreen extends StatefulWidget {
  
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {

  MyViewModel viewModel;

  @override
  Widget build(BuildContext context) {

    viewModel = Provider.of<MyViewModel>(context);
    viewModel.question = getQuestion();

    return Scaffold();

  }

}
```

Every time I `pushNamed` that `routeName` of this widget, it still holds the old values of the `viewModel` (which is a `ChangeNotifier` object). The goal is to reset the values of the `viewModel`.

**Comment by EdwynZN** [comment]
Hi, I suppose your MyViewModel is holding some values to make a FormField or survey questions and you need to reset them everytime they open the route. But as I understand if you open a route the widget tree is different from your main and it should give you an error (not finding the proper  MyViewModel on the widget subtree) when using `Provider.of<MyViewModel>(context);` because there is no MyViewModel on top of MyScreen (where it's supposed to start the new pushNamedRoute). When you use pushNamed are you passing as argument the MyViewModel to the new route? Do you use MyViewModel outside of this route?

Anyway you could try something like this to have a fresh new MyModelView everytime you push the the route

```
class MyScreen extends StatefulWidget {
  
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {

  MyViewModel viewModel;

  @override
  Widget build(BuildContext context) {

    return MultiProvider(
       providers: [
            ChangeNotifierProvider(
                create: (_) => MyViewModel()
             ),
           Consumer<MyViewModel>(
                builder: (context, model, _){
                     model.question = getQuestion(); //if you only need this the first time maybe you should do it in the create of the provider or the builder method MyViewModel() : question = getQuestion();
                     return Scaffold();
                }
           )
        ],
   );

  }

}

I suppose you pop the route after finishing so then when you push again this route it creates the changeNotifier anew
```

**Comment by abayomiAkanji** [comment]
Hi @EdwynZN 

Many thanks for your detailed response.

**Comment by kurisLei** [comment]
@abayomiAkanji Hey bro, i met the same question about this, could you please tell me how to solved.

**Comment by abayomiAkanji** [comment]
Hi @kurisLei The viewModel in my use-case is being initialized in the Build method. As a result, the object gets re-initialized every time the framework rebuilt the screen (by calling the build method). At the moment, I'm doing a manual clean-up of the fields whenever I open the screen and I only initialize the viewModel if it's null.

I hope that helps.

**Comment by kurisLei** [comment]
@abayomiAkanji Well, I also deal with this, I will manually initialize the parameters in the model during page initialization, such as the product details page, it should be a separate state management, so I give up using Provider to manage the state, but use the state management of the page itself, thank you for your reply.

**Comment by rrousselGit** [comment]
Provider does not have any built-in way to "automatically" reset the state of an object.

If you need to have a reset mechanism, you'll have to implement it manually (a StatefulWidget & dispose seems all indicated)

**Comment by neiljaywarner** [comment]
@rrousselGit  can you give any details on this? a lot of people want this i think...  eg a cart reset or viewmodel reset.

vm.reset() 
or cart.reset()
which then has the provider provide a new object () or deep copy the values with () or something

**Comment by notandyvee** [comment]
@neiljaywarner

> If you need to have a reset mechanism, you'll have to implement it manually

````
class MyModel extends ChangeNotifier {
/// Fancy logic
void reset() {
    // Reset all your instance variables here.
}
/// More fancy logic
}
````

Then whenever you need to reset any models, just access it with `Provider.of`, call reset, and update your app state however makes sense for your situation. 

If you have a specific use case you still need help with, it would be useful to know what it is to give you a push in the right direction.

**Comment by DeleMike** [comment]
Over 2 years since this issue was raised and no new update?
Time to switch to Riverpod.

**Comment by tjbaba** [comment]
Use riverpod now, it has autodispos function which is best suitable for these kind of situations
