### ISSUE TITLE
ValueListenableProvider not updating

### ISSUE THREAD

**Issue by EdwynZN** [rrousselGit/provider#445]
I don't know if  I understood correctly the purpose of ValueListenableProvider 

> Listen to a ValueListenable and only expose ValueListenable.value

```
ValueListenableProvider<bool>(
    create: (context) => ValueNotifier<bool>(false),
    child: Consumer<bool>(
         builder: (context, color, child){
              return IconButton(
                 icon: Icon(Icons.home, color: color ? Colors.white : Colors.black),
                   onPressed: () => color= !color, //doesn't call for rebuild
                  );
          },
     ),
),
```

ValueListenable has a T get value and ValueNotifier overrides it with T get value => _value;. What I don't fully understand is if when I change that value doesn't it supposed to use the setter from ValueNotifier which have a notifyListeners(); (calling it if the value is different from the previous) ? or the provider just copy the ValueNotifier.value to another object making it useless to notify using the setter?

**Comment by smiLLe** [comment]
You can use a ChangeNotifierProvider and update it's value  prop :)

```dart
class MyColor extends ValueNotifier<Color> {
  MyColor(Color value) : super(value);
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<MyColor>(
      create: (_) => MyColor(Colors.red),
      builder: (context, _) {
        final myColor = Provider.of<MyColor>(context);
        return MaterialApp(
            home: Container(
          color: myColor.value,
          height: 300,
          width: 300,
          child: Center(
            child: RaisedButton(
              onPressed: () => myColor.value = Colors.blue,
              child: Text('change'),
            ),
          ),
        ));
      },
    );
  }
}
```

**Comment by EdwynZN** [comment]
HI @smiLLe I understand I can use the ChangeNotifier for this problem, but considering I wanted a to change a primitive value (boolean) I wanted to just use a ValueNotifier instead of creating a class with a ChangeNotifier

class MyClass extends ChangeNotifier{
     bool value;
       
      MyClass(this.value);

      set update(bool newValue) {
        if(value == newValue) return;
         value = newValue;
         notifylisteners();
     }

}

considering this class it's remarkable the same as a ValueNotifier which impplements ChangeNotifier and Listenable I thought it was easy to just create a ValueNotifier<bool>(false) and work with that, but it doesn't update, does the ValueListenableProvider have a different way of work or is used for a different purpose? I though just like ValueNotifier was a simple use case of ChangeNotifier the ValueListenableProvider was homologue to ChangeNotifierProvider

**Comment by rrousselGit** [comment]
The problem is, you are not modifying the content of `ValueNotifier`, but the variable you obtained from `Provider.of`. 

So the setter of `ValueNotifier` which internally calls notifyListeners is never called.

A custom class instead of `ValueNotifier` is the proper solution.
