### ISSUE TITLE
New assertions & itemBuilder

### ISSUE THREAD

**Issue by szotp** [rrousselGit/provider#447]
```dart
    return ListView.builder(
      itemBuilder: (context, i) {
        print(context.debugDoingBuild);
        final provided = context.watch<String>(); // assertion failure
        return Text('Hello there, $provided');
      },
    );
```
`context.debugDoingBuild` is false inside itemBuilder and crashes on context.watch.

Perhaps this is not a bug, because itemBuilder is not a build method, but it feels like one tbh. Perhaps the assertion logic should check this and print extra message on how to fix, which is to use a Builder or custom widget.

**Comment by rrousselGit** [comment]
Eh, debugDoingBuild should be true

It sounds like it's a bug in the flag. I can see a few reasons why that is
happening. It also likely happens with LayoutBuilder.
