### ISSUE TITLE
Build fails on beta channel

### ISSUE THREAD

**Issue by prasadsunny1** [rrousselGit/provider#448]
This is what happened when I ran a workflow with codemagic.
`== Initializing code signing for Android ==

== Install Flutter dependencies ==
> /usr/local/bin/flutter packages pub get
Resolving dependencies...
The current Flutter SDK version is 1.17.0-3.4.pre.

Because provider 4.1.1 requires Flutter SDK version >=1.17.0 and no versions of provider match >4.1.1 <5.0.0, provider ^4.1.1 is forbidden.
So, because banksia depends on provider ^4.1.1, version solving failed.
pub finished with exit code 1

Build failed :|
Failed to install dependencies`

**Comment by prasadsunny1** [comment]
![Screenshot from 2020-05-12 12-09-33](https://user-images.githubusercontent.com/11705392/81646933-c2cd9d80-9449-11ea-8b07-c2b4c9c14239.png)

**Comment by arnoutvandervorst** [comment]
Same for me on beta channel, reversed to flutter stable for now...

**Comment by rrousselGit** [comment]
You can upgrade to stable

**Comment by atoka93** [comment]
Not if you're developing for web 🤔

**Comment by rrousselGit** [comment]
I see. I'll loosen the constraint in a second

**Comment by atoka93** [comment]
Thank you! 😃
