### ISSUE TITLE
ChangeNotifier performance

### ISSUE THREAD

**Issue by dnfield** [rrousselGit/provider#45]
ChangeNotifier is O(N^2) for notify listeners.  It has to make a copy of the list of listeners, iterate that copy, and during the iteration do another iteration of the original list to see if the listener is still registered.

This seems particularly troubling for the MultiProvider case (which would get to O(N^3)), but could be a problem anywhere you have lots of widgets listening to the same provider.

A possible optimization here is to see if we can stuff the callbacks into a set or map, e.g. by having `addListener` and `removeListener` (or the equivalent wrappers of them) using integer handles instead of the actual callback - or just using a set if that works for callbacks (I'm not sure how `hashCode` is handled on a var that is a closure), which should get this back to O(N).

**Comment by dnfield** [comment]
Doing this would be a break from the existing contract for ChangeNotifier, which guarantees that callbacks are fired in the order they were added including if they were added multiple times.  

I'm not sure that's important for this application.

**Comment by rrousselGit** [comment]
Interesting feedback, but I'm not sure if this is in the scope of `provider`.

This library is not opinionated on state management. It aims mostly at fixing the errors that the community make when working with inherited widgets.

In that sense, it is totally reasonable to use `provider` without using the `Listenable` architecture at all.
There is in fact an agreement with the Mobx team to use `provider` as their official dependency injection system — to stop the disparities.

**Comment by dnfield** [comment]
My concern here is that the ChangeNotifier providers (and particularly the MultiProvider version of that) make it easy to do something that won't scale.  Provider could have n opportunity to make that better here, unless it's critical that it follow exactly the same contract and semantics as the Flutter version of ChangeNotifier.

My main concern is people will more easily ignore a doc burried in ChangeNotifier here.

I think this is a great package overall, and I think this particular pattern could work a bit better here because of it.

**Comment by filiph** [comment]
I agree this is a concern, but I don't think this is in scope of 2.0.0.

Remi is right that this package is mostly about providing, and you can provide anything, including what Dan suggests. I think whether or not something like a Map/Set-based notifier is included in `pkg:provider` itself is a good question to ask. But again, not for 2.0.0, I think.

**Comment by rrousselGit** [comment]
In fact I'm not sure if this is really problematic.

The listening is done by the provider, not the consumer. So in most situations there will be only one listener. 

The issue could arise if peoples pass around the instance of a ChangeNotifier itself — but then that means they are not using ChangeNotifierProvider.
And in that case there's nothing we can do about it.

**Comment by dnfield** [comment]
Ahh I think I see.

So this problem should only arise if, for example, a someone creates a bunch of providers that listen to the same `ChangeNotifier`?

**Comment by rrousselGit** [comment]
Yes. But the use-case is extremely rare.

The only situation I can think of where we'll want to have more than one provider on the same `ChangeNotifier` is:

```dart
ChangeNotifier notifier;

Widget build(BuildContext context) {
  return Row(
    children: [
      ChangeNotifierProvider.fromValue(notifier: notifier, child:  Foo()),
      Bar(),
      ChangeNotifierProvider.fromValue(notifier: notifier, child:  Baz()),
    ],
  );
}
```

Where `Bar` is explicitly unable to read from the `ChangeNotifier.`. 
And even then, the number of listeners should be reasonably small.

**Comment by dnfield** [comment]
Maybe it's just worth documenting this somewhere on `ChangeNotifierProvider` and/or `MultiProvider`?

**Comment by rrousselGit** [comment]
What would you add on `MultiProvider`?

**Comment by dnfield** [comment]
Probably the example you just gave as something that should be avoided if possible, particularly if you start extending it to multiple items in a row/column/list/grid/etc.

**Comment by rrousselGit** [comment]
This was added to the readme of the 4.1.0 version (which will get merged as soon as Flutter makes a stable release)
