### ISSUE TITLE
How to best share dynamic Providers across Screens?

### ISSUE THREAD

**Issue by awhitford** [rrousselGit/provider#451]
I'm running into the issue already explained in #432 and #387.  Because each Navigation route is in its own branch, we cannot easily pass Providers to subsequent Screens -- unless those Providers are wrapping the `MaterialApp`.

So I need a workaround...  In my case, I really like the idea of using Provider because my data may change over time, and so it needs to refresh occasionally.  My data set is really like a collection that can grow and shrink over time; each element can change, or get updated.  You can think of it as a `Map<_key_, StreamProvider>` -- sort of like a _dynamic `MultiProvider`_.

Is there a Provider that I can wrap `MaterialApp` with, so that it is available to all Screens, that can dynamically grow/shrink/update like I described?

**Comment by rrousselGit** [comment]
StreamProvider<Map<_key>, Something> should work.

**Comment by rrousselGit** [comment]
Closing this in the lack of further comment
