### ISSUE TITLE
How to handle side-effects?

### ISSUE THREAD

**Issue by eddiesTime** [rrousselGit/provider#452]
Hi Rémi,

what would be your personal approach to handle **side-effects** with ChangeNotifierProvider?

In flutter_bloc the recommended place to handle side-effects is a _BlocListener_, for states_rebuilder is a _OnSetStateListener_ and MobX uses _reactions_.

This led me to the question of how to handle side-effects with provider. Currently there is no recommendation in the documentation and I was wondering if you have thought about it.

Some examples of how to handle side-effects with ChangeNotifierProvider can be found on [stackoverflow](https://stackoverflow.com/questions/58685074/how-to-show-errors-from-changenotifier-using-provider-in-flutter).

**Comment by rrousselGit** [comment]
There is no recommendation because provider and ChangeNotifier are two
completely independent entities.

It is not the role of provider to explain how to use ChangeNotifier, but
the role of Flutter instead.
I cannot say "this is how you should do it", as this is not in the scope of
the project.

**Comment by eddiesTime** [comment]
Thank you for your fast response.

Yeah, you are right. As you emphasised during your talk at Flutter Europe provider is a tool for dependency injection. 

Thanks for your time!
