### ISSUE TITLE
Provider with AnimatedListView best practice

### ISSUE THREAD

**Issue by claudeHasler** [rrousselGit/provider#453]
I have model which implements ChangeNotifier
```
class DataModel with ChangeNotifier{
   List<Data> data = List<Data>();

   void addData(Data data){
      data.add(data);
      notifyListeners();
   }
}
```
and a ListView which listens to those changes:

```
class DataListView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<DataModel>(
      builder: (context, model, child) {
        return ListView.builder(
          itemCount: model.data.length,
          itemBuilder: (context, index) {
            return Text(model.data[index].value);
          },
        );
      },
    );
  }
}
```

so far so good, when an item is added to the list in the model, the change notification triggers a rebuild of the Listview and I see the new data. But I cant wrap my head around using this with a AnimatedList instead of a ListView. Preferably id like to keep my model as it is, seeing as the animation is a concern of the ui and not of my logic.

The changenotifier always gives me a uptodate version of my data, but what i really need is a "item added" or "item removed" notification.

Is there a best practice way of doing this?

**Comment by rrousselGit** [comment]
Hello!

For help request, consider asking your question on Stackoverflow instead. 
Github is for bug reports and feature requests.
