### ISSUE TITLE
context.read<MyModel>()  : The method 'read' isn't defined for the type 'BuildContext'.

### ISSUE THREAD

**Issue by ThePredators** [rrousselGit/provider#454]
Hello,

I need some help i dont underdstand why the method read cant be called !

Error : The method 'read' isn't defined for the type 'BuildContext'.

I followed the sample here [provider sample](https://github.com/rrousselGit/provider/blob/master/example/lib/main.dart) but in my code it gives me the error shown.

Thanks.

**Comment by rrousselGit** [comment]
You need to use provider 4.1.0 and import provider

**Comment by ThePredators** [comment]
Awesome and thansk for replying so fast ! u are awesome bro and thanks for the library it is an amazing tool !!

**Comment by zhangKunUserGit** [comment]
need import 

`import 'package:provider/provider.dart';`

**Comment by FarhanSyedain** [comment]
I have provider imported yet sometimes it doesnt recofnise context.

**Comment by rohitmandiwal** [comment]
wow! it worked

**Comment by itbrunoms** [comment]
wow! it worked

**Comment by indrajeetcodonnier-jpg** [comment]
Hello i am new beginner with flutter BLoC and facing a issue can anyone help me out .
I am also facing the same issue 

https://stackoverflow.com/questions/79758830/the-block-is-not-getting-recognized-error-the-method-read-isnt-defined-for-t
