### ISSUE TITLE
Hey, I don’t know if it ’s a good idea to manage APIs in ORM？

### ISSUE THREAD

**Issue by medz** [rrousselGit/provider#455]
Provider I do n’t know if there is a best practice. I tried to use the built_value to model the data requested from the network.

For example, my API for a list of articles, the data structure after Models is:

```json5
[
   {
     "title": "Post One",
     "user": {...}
   }
]
```

The Post and User should be shared. I try to do ORM work on Provider. but failed. I need to manually extract the deep model to the top and insert it into a different Provider state. And every time you update an Item content will trigger the reconstruction of the entire App UI!

I think my way is wrong, I am still a Flutter rookie coder.

I need references to complex applications such as related references.

Thanks.

**Comment by rrousselGit** [comment]
Hello

If you need help, github is not the right place
Consider twitter/stackoverflow/reddit/slack
