### ISSUE TITLE
Why is it unsafe to use `context.read` inside `build`?

### ISSUE THREAD

**Issue by uesaiso** [rrousselGit/provider#456]
When I used `context.read` in `build` method, Provider said
```
Tried to use `context.read<AuthState>` inside either a `build` method or the `update` callback of a provider.
```

Why is it unsafe, while using `Provider.of<T>(context, listen: false)` in `build` method is allowed?

**Comment by rrousselGit** [comment]
Not listening to an Inheritedwidget inside build is an anti-pattern that
could lead to very hard to debug issues.

context.read prevents it for correctness. Provider.of allows it for
flexibility.

But there's always a different and better way of doing it.

**Comment by userCodingGabriel** [comment]
@rrousselGit I'm rather confused as to why this is an antipattern. It is something that I use quite frequently. The biggest example is:
- Getting Global Key values from a service whether it be a Form Key or a Navigation Key that my view models use.

I'm confused why if Provider.of allows it then why doesn't context.read allow it. It was my understanding context.read was just a wrapper for Provider.of. Now really the only time I would use context.read I'm forced to use Provider.of.

There is lots of times where the value you are reading won't change, and even if it does you don't care for that widget. This is what I thought the purpose of both context.read and Provider.of(context, listen: false) was supposed to take care of. Thanks for your time.

**Comment by rrousselGit** [comment]
If the value doesn't change, it shouldn't bother you to use watch instead
or read

Why do you refuse to do context.watch instead?

**Comment by userCodingGabriel** [comment]
@rrousselGit I guess the main reason is preformance. For example if I have a complex widget tree, I don't want the whole tree to be rebuilt everytime notifyListeners is called. I just want the areas wrapped with Consumers to be rebuilt. So for my example above, I know the formKey is going to stay the same, so why should the whole screen be rebuilt when notifyListeners is called just updating 1 variable is all.

**Comment by uesaiso** [comment]
@rrousselGit 
So you mean calling `Provider.of<T>(context, listening: false)` in build method should be avoided too, though it is allowed?

**Comment by rrousselGit** [comment]
> @rrousselGit
> So you mean calling `Provider.of<T>(context, listening: false)` in build method should be avoided too, though it is allowed?

Yes.
It is allowed for the edge cases. But that's it

**Comment by rrousselGit** [comment]
> @rrousselGit I guess the main reason is preformance. For example if I have a complex widget tree, I don't want the whole tree to be rebuilt everytime notifyListeners is called. I just want the areas wrapped with Consumers to be rebuilt. So for my example above, I know the formKey is going to stay the same, so why should the whole screen be rebuilt when notifyListeners is called just updating 1 variable is all.

That's why we have things like select, initiate, or ProxyProvider 

You have many possibilities to watch only what you need

**Comment by junca38** [comment]
I am more confused after reading. 
Context.watch<T>(), will listen on T
Context.select<T>() will listen on T only the parts that we need.
These two, I understand and know how to use. 

But Then, when and how to use Context.read?
Another thing with Provider.of, we can use listen:false, in the case that a widget only need the value once and never need to listen again. Is there an equivalent way of doing it with Context.watch<T>?

**Comment by rrousselGit** [comment]
> Another thing with Provider.of, we can use listen:false, in the case that a widget only need the value once and never need to listen again

Provider.of was not intended to be used this way. That's only possible because at the time `listen` was added, the assert done by `context.read` was not possible to implement.

`Provider.of` doesn't get the new assert because that would be a breaking change, and for flexibility for those who want to play around.

You can use `context.read` anywhere but inside `build`.

That includes:

initState:
```dart
initState() {
  context.read<T>();
}
``

and event handlers:

```dart
RaisedButton(
  onPressed: () {
    context.read<T>();
  },
)
```

**Comment by waniwang** [comment]
hi @rrousselGit, I'm also kind of confused here, could you please help explain more why `listening to an Inheritedwidget inside build is an anti-pattern`? I would be grateful if you can provide some reference links.

And as a user of the Provider, when I was reading the explanation of `context.read`, it mentions nothing about `avoid using it in build method`, which leads me to use it when I need the value but don't want to listen to the changes.
I know you want to provide both correctness (`context.read`) and flexibility(`Provider.of(context, listen: false)`), but it really creates inconsistency and ambiguity as far as I concerned.

**Comment by rrousselGit** [comment]
The doc does mention that read cannot be used inside build https://github.com/rrousselGit/provider/blob/4d96e24db6c1bd4b940b3e0746f3d8bed478f4ea/lib/src/provider.dart#L364

Not listening to an object as a performance optimisation is very brittle.
It could heavily lead to bugs that will be invisible during code reviews and normal development flows.

Instead, listen to only what you care about, with select.
That does the same thing. But that is drastically more resilient.
It'll survive refactoring and be readable.

Since we have select, there is no reason to allow read inside build

**Comment by userCodingGabriel** [comment]
@rrousselGit I now understand where you are coming from, I was slightly confused about the purpose of selector. I would like to add though that having the two kinds of read: Provider.of and context.read behaving differently is confusing. But using selector does make sense, even if it is a little longer to type everything than just context.read
