### ISSUE TITLE
StreamProvider and types

### ISSUE THREAD

**Issue by subzero911** [rrousselGit/provider#457]
Let's imagine we have some repository with 2 streams of int

```dart
class Repo {
	StreamController<int> booksCounter = StreamController();
	StreamController<int> dogsCounter = StreamController();

	// some logic with adding data to it
}
```

We declare providers:

```dart
MultiProvider(
	providers: [
		StreamProvider<int>.value(
			value: repo.booksCounter
		),
		StreamProvider<int>.value(
			value: repo.dogsCounter
		),
		...	// other providers
	]
        child: ...,
)
```

And trying to get a stream value in UI

```dart
@override
Widget build(BuildContext context) {
	var booksCounter = Provider.of<int>(context);  // !!!
}
```

How will provider solve which counter to choose?
It uses Type system to decide. But both counters are type of int!

**Comment by rrousselGit** [comment]
See the Readme about that part https://github.com/rrousselGit/provider#can-i-obtain-two-different-providers-using-the-same-type
