### ISSUE TITLE
StreamProxyProvider / FutureProxyProvider

### ISSUE THREAD

**Issue by subzero911** [rrousselGit/provider#458]
Consider adding StreamProxyProvider class.
What if we have a stream that we want to expose, located inside of some repository?
StreamProvider() constructor is not suitable, because we do not create a stream but expose existing stream (it's basically almost useless because I can't imagine the situation where we create a stream "on a fly" inside of 'create:' parameter)
StreamProvider.value() is good but how do we manage to access an instance of this repository?
The only way I can see, is to create it at the higher level and consume it in a child widget.
```dart
MultiProvider(
	providers: [
		ChangeNotifierProvider<Auth>(
                        //Auth is some repo containing all the authentication business logic
			create: (ctx) => Auth(),
		)
		...	// other providers
	]
	child: Consumer<Auth>(
		builder: (ctx, auth, child) {
			MultiProvider(
				providers: [
					StreamProvider<FirebaseUser>.value(
						value: auth.onAuthStateChanged
					),
					StreamProvider<int>.value(
						value: auth.secondStream,
					),
				]
			)
		}
	)
)
```
Pretty ugly. Now imagine what if we have StreamProxyProvider. The code will look much cleaner:
```dart
MultiProvider(
	providers: [
		ChangeNotifierProvider<Auth>(
			create: (ctx) => Auth(),
		),
		...	// other providers
		StreamProxyProvider<Auth, FirebaseUser>.value(
			value: (ctx, auth) => auth.onAuthStateChanged
		),
	]
)
```

**Comment by rrousselGit** [comment]
This has been requested multiple times, but as I've said previously: this
is not feasible.

At least, I am not aware of an easy solution for it.
If you have any suggestion, I am open to ideas.

**Comment by rrousselGit** [comment]
In the lack of suggestion, I'll close this as this cannot be worked on.

**Comment by kornha** [comment]
Is it not possible to expose a listenable function in the StreamProvider widget that can update based on changes in the context?

**Comment by lukepighetti** [comment]
Is there a recommended way to make a StreamProvider that depends on an ancestor StreamProvider? <img width="761" alt="Screenshot 2023-06-30 at 5 07 18 PM" src="https://github.com/rrousselGit/provider/assets/666539/27b36a6b-174b-4348-801b-349f51cd77bb">

**Comment by rrousselGit** [comment]
You could use a Consumer + StreamProvider.value

```dart
MultiProvider(
  providers: [
    ...,
    Consumer<User?>(
      builder: (context, user, child) => StreamProvider<Settings>.value(
        user == null
          ? const Stream.empty()
          : FirebaseFirestore.instance.getUserSetttings(user.userId),
      ),
    ),
  ],
)
```
