### ISSUE TITLE
Add multi childing to Consumer

### ISSUE THREAD

**Issue by egprojects** [rrousselGit/provider#461]
In some cases you need to 2 or more immutable widgets inside your Consumer.
For example, in this code I have 2 immutable widgets: poster preview and Container with gradient:
`Consumer<AnimeDetailsModel>(
      builder: (_, model, preview) => Hero(
        tag: '${model.animeId}_poster',
        child: Stack(
          fit: StackFit.expand,
          children: [
            model.posterUrl == null
                ? preview
                : CachedShikimoriImage(
                    imageUrl: model.posterUrl,
                    fadeInDuration: Duration.zero,
                    placeholder: (_, __) => preview,
                  ),
            Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.black54,
                    Colors.black.withOpacity(.0),
                    Colors.black.withOpacity(.0),
                    Colors.black54,
                  ],
                  stops: [0, .25, .5, 1],
                ),
              ),
            ),
          ],
        ),
      ),
      child: CachedShikimoriImage(
        imageUrl: Provider.of<AnimeDetailsModel>(context, listen: false)
            .posterPreviewUrl,
        fadeOutDuration: Duration.zero,
      ),
    )`
I can't just put Consumer into Stack and move Container outside of it because Consumer works not correctly when there is Hero over it.

So, that would be great if you add something like 'MultiChildConsumer' that will have a Map of widgets instead of just single Widget.

**Comment by rrousselGit** [comment]
That child parameter is optional.

You could do:

```dart
final child = Container();

return Consumer(
  builder: (_, value, __) {
    return Example(value: value, child: child);
 } 
)
```

So considering your request is a breaking change, I don't think it's worth the trouble.
