### ISSUE TITLE
context.read<T>() docs say its unsafe to use inside build, but it doesn't explain why

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#462]
The `context.read<T>()` docs say its unsafe to use it inside `build()`, but it doesn't explain why. Reading that something is `unsafe` bring a lot of red flags so this matter just be explained in depth. Unsafe operations are usually related to memory leaks, data corruption, security issues and etc.

If by `unsafe` the docs mean "the object is not being watched so build() won't be called again if the object changes" than the docs should include this and maybe use some wording that's not so strong as `unsafe`, like `can lead to bugs that are hard to find`.

**Comment by HackinoSelov** [comment]
I would add this from what I've just tried in flutter :
- the use of ```context.read<T>()``` inside ```build()``` throw an exception
- But the use of ```Provider.of<T>(context, listen: false)```inside ```build()```does not.
So now this is unclear to me. What is to best option in order to only get the provider without listening to it ?
