### ISSUE TITLE
Provider in initState

### ISSUE THREAD

**Issue by vishalchauhanAP** [rrousselGit/provider#463]
Hi, 

Requirement is, i need to call one provider init() function in initState, just to initiate few 2-3 values
But i want it outside of microtask, if i put it inside microstask, then it has crashes as init values are null.

This init function **has no notifyListners**.

So is it safe to call **Provider.of<SomeProvider>(**context**, listen: false)..init();** ?
as it uses context, context is not null when above line gets control.
But initState has not completed.

Not getting any error, but is it 100% safe to use Provider.of<SomeProvider>(context, listen: false)..init(); outside microtask?

  @override
  void initState() {
    super.initState();

    final SomeProvider provider = 
               Provider.of<SomeProvider>(context, listen: false)..init();
    Future<void>.microtask(() async {
      await provider.getSomeDetails();
    });
  }

**Comment by rrousselGit** [comment]
No, this is not safe.
You could have weird problems if another widget tries to read `SomeProvider` before `init` was called.

Consider moving the `init` call inside the constructor of `SomeProvider`

**Comment by vishalchauhanAP** [comment]
Actually, putting  init() inside constructor does not solve problem
As we have used mutiprovider, and they gets intialized once, so init is called once in constructor
But as we move screen back and forth, want this init function to run.  (other wise some intial values are wrong, not reset)

Per screen there is one provider, and prvoider is used in EachScreen().
All other widgets who are using this SomeProvider are children of EachScreen()

Context is not null here.
Provider.of(...) is not complaining.

**Comment by rrousselGit** [comment]
That doesn't change the fact that what you asked is unsafe

You're free to do it if you want to. But it's not a good pattern

**Comment by vishalchauhanAP** [comment]
Thanks!!
