### ISSUE TITLE
context.watch in didChangeDependencies result in exception

### ISSUE THREAD

**Issue by japborst** [rrousselGit/provider#464]
Pre v4.1 I had the following in place:

```dart
  CurrentUser _currentUser;

  @override
  didChangeDependencies() {
    super.didChangeDependencies();
    final currentUser = Provider.of<CurrentUser>(context);
    if (currentUser != _currentUser) {
      _currentUser = currentUser;
    }
  }
```

I loved the new extensions and per the [docs](https://github.com/rrousselGit/provider#i-have-an-exception-when-obtaining-providers-inside-initstate-what-can-i-do), changed this to
```dart
  CurrentUser _currentUser;

  @override
  didChangeDependencies() {
    super.didChangeDependencies();
    final currentUser = context.watch<CurrentUser>();
    if (currentUser != _currentUser) {
      _currentUser = currentUser;
    }
  }
```

However, that returns the following error. It suggests to use `context.read`, however that will disable updates and is the opposite of what I'm trying to achieve. One difference I see with the docs refer to a value of the object, instead of the whole object.
```
Tried to use `context.watch<CurrentUser>` ouside of the `build` method or `update` callback of a provider.

This is likely a mistake, as it doesn't make sense to rebuild a widget when the value
obtained changes, if that value is not used to build other widgets.

Consider using `context.read<CurrentUser> instead.
'package:provider/src/provider.dart':
Failed assertion: line 463 pos 12: 'debugDoingBuild || debugIsInInheritedProviderUpdate'
```

Why is `context.watch` not allowed here?

**Comment by rrousselGit** [comment]
It "should" be allowed, but that'd require removing the assert that
prevents watch from being used badly

You can simply move the code that you did inside didChangeDependencies to
build, that will work.

**Comment by japborst** [comment]
Thanks for the quick response! Moving to the build and wrapping it in a separate function indeed works as well.

Thinking about it more: is there still a use for keeping the `if` logic (as I copied from the docs) when considering the entire object? `watch` implies only rebuilds are triggered upon changes in the object.

**Comment by rrousselGit** [comment]
The code you showed doesn't do anything special in that if, so yeah you can
remove it

If you are doing special work inside, you may want to preserve the if

**Comment by rrousselGit** [comment]
Closing since this was answered
