### ISSUE TITLE
React to model change

### ISSUE THREAD

**Issue by bogdanmarinescu** [rrousselGit/provider#465]
Basically I need a way to call a method in a widget when a provider propriety changes its value.

**Comment by rrousselGit** [comment]
Assuming you are using a ChangeNotifier, you can normally listen to the notifier with addListener.

**Comment by bogdanmarinescu** [comment]
`
class _MySecondPageState extends State<MySecondPage> {
@override
  void initState() {
    super.initState();
    context.read<Counter>().addListener(_counterListener);
  }

  @override
  void dispose() {
    context.read<Counter>().removeListener(_counterListener); // can't call here
    super.dispose();
  }

  _counterListener() {
    if (context.read<Counter>().count % 2 == 0) {
      print("${context.read<Counter>().count}");
    }
  }`

Is this the right way? If so, how do I remove the listener when I want pop MySecondPage?

**Comment by rrousselGit** [comment]
That's fine

**Comment by b1acKr0se** [comment]
@rrousselGit I'm having a similar problem, how do we remove listener? If I put the `removeListener` method in `dispose`, Flutter throws the following error message:

> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by rrousselGit** [comment]
Call context.read only once, and save it's result inside the State class.
Then use that variable inside dispose.

**Comment by b1acKr0se** [comment]
@rrousselGit I'm reading the Provider source code for `ChangeNotifierProvider`, and it seems it automatically calls `dispose` on the ChangeNotifier, is it correct? If that's the case, then I don't think we need to call `removeListener`.

**Comment by rrousselGit** [comment]
It does, yes. But that depends on where you listener is added.
You may want to remove the listener before provider destroys the state of the notifier

**Comment by b1acKr0se** [comment]
That makes sense. Thank you.
