### ISSUE TITLE
Await for ProxyProvider update to finish

### ISSUE THREAD

**Issue by DriftingShadows** [rrousselGit/provider#474]
I encountered an issue and I'll copy/paste it from here:
https://stackoverflow.com/questions/62356921/changenotifierproxyprovider-notifylisteners-throwing-object-was-used-after-b

I currently have set up some providers like so: 

    providers: [
        ChangeNotifierProvider.value(
          value: Sites(),
        ),
        ChangeNotifierProxyProvider<Sites, Vehicles>(
            update: (_, sites, previousVehicles) {
              return Vehicles(sites.selectedSite,
                  previousVehicles == null ? {} : previousVehicles.vehicles);
            }),

And then on my home screen I need to fetch the sites and then the vehicles that belong to that site. A snippet of my home screen looks like so:

        Provider.of<Sites>(context, listen: false).fetchAndSetSites().then((_) {
          Provider.of<Vehicles>(context, listen: false)
              .fetchAndSetVehicles()
              .then((_) {
            setState(() {
              _isLoading = false;
            });
          });
        });
These provider calls are in the didChangeDependencies method in order to load this data the first time loading that page. At the end of the Vehicles provider is notifyListeners() which throws the error:

    Unhandled Exception: A Vehicles was used after being disposed. Once you have called dispose() on a Vehicles, it can no longer be used.

I figured out that I was running into this problem because my call to Provider.of<Vehicles> was being run before the update method in the ProxyProvider finished running for Provider.of<Sites> (therefore notifyListeners() was being called on a disposed object). Is there a way to wait for the update method to finish before initiating another method that depends on the first provider?

**Comment by rrousselGit** [comment]
You are creating your ChangeNotifier inside `update`. The documentation explicitly says that you shouldn't https://pub.dev/documentation/provider/latest/provider/ChangeNotifierProxyProvider-class.html


So instead, create your ChangeNotifier inside `create`

**Comment by DriftingShadows** [comment]
Ah, I think you're right. Thanks for the help! I've been following a course and it might be outdated or employing not the best practices. I have changed it to:

```        
ChangeNotifierProxyProvider<Sites, Vehicles>(
            create: (_) => Vehicles(null, sampleVehicles),
            update: (_, sites, previousVehicles) {
              previousVehicles.setSelectedSite(sites.selectedSite);
              return previousVehicles;
            }),
```
And it seems to have worked. 

One side note from the documentation you linked, is it suggested or NOT suggested to do this (taken from the link)
```
ChangeNotifierProxyProvider<MyModel, MyChangeNotifier>(
  // may cause the state to be destroyed involuntarily
  update: (_, myModel, myNotifier) => MyChangeNotifier(myModel: myModel),
  child: ...
);
```
I was thinking this was you warned me against (creating the notifier in the update) but the wording on the page suggests its how you should do it because it comes straight after saying 
`Instead reuse the previous instance, and update some properties or call some methods.`
Just wanted to clarify, thanks again!
