### ISSUE TITLE
SliverConsumer

### ISSUE THREAD

**Issue by superakabo** [rrousselGit/provider#478]
**Is your feature request related to a problem? Please describe.**
It would be convenient to make a SliverList a child of a Consumer widget at times when using a CustomScrollView. 

Doing so now (Provider: ^4.1.3) throws this exception:
'A RenderViewport expected a child of type RenderSliver but received a child of type RenderLimitedBox.'

**Describe the solution you'd like**
```dart
SliverConsumer<T>(
            builder: (_, value, __) {
              return SliverList(
                delegate: SliverChildBuilderDelegate(
                  (_, int index) => SomeRow(),
                  childCount: 10,
                ),
              );
            },
          ),
```
**Describe alternatives you've considered**
 I use a Scaffold and make the Consumer widget the child of its body and return a CustomScrollView for the Consumer widget's builder function.

**Comment by rrousselGit** [comment]
The problem you are facing is unrelated to Consumer.

Consumer doesn't create Renderobjects and is therefore compatible with Slivers. 

It is a different widget that causes your exception

**Comment by superakabo** [comment]
> The problem you are facing is unrelated to Consumer.
> 
> Consumer doesn't create Renderobjects and is therefore compatible with Slivers.
> 
> It is a different widget that causes your exception

You are right. Thank you.
