### ISSUE TITLE
Add dependencies to the create argument in ChangeNotifierProxyProvider.

### ISSUE THREAD

**Issue by gabrielmcreynolds** [rrousselGit/provider#481]
When you create a `ChangeNotifierProxyProvider`  and want to depend on certain dependencies, then you must first construct an empty model, and then one with the dependencies like the following:

 ```
ChangeNotifierProxyProvider2<DatabaseService,
                    AuthenticationService, ViewReservationViewModel>(
                  child: EditReservationView(),
                  create: (_) => EditReservationViewModel(),
                  update: (BuildContext context,
                          DatabaseService databaseService,
                          AuthenticationService authenticationService,
                          ViewReservationViewModel previous) =>
                      EditReservationViewModel(
                          databaseService: databaseService,
                          reservation: myReservation,
                          authenticationService: authenticationService),
                )
```

But if in this model's constructor you need the dependencies to setup some data, i.e. I need to access `databaseService` in my constructor, then my model will error out because when it tries to access it the first time it will be null. I'm not sure if this is possible, but it would be really nice to be able to inject the dependencies in the create argument so the above could look like the following:

```
ChangeNotifierProxyProvider2<DatabaseService,
                    AuthenticationService, ViewReservationViewModel>(
                  child: ViewReservationView(),
                  create: (BuildContext context,
                          DatabaseService databaseService,
                          AuthenticationService authenticationService) => ViewReservationViewModel(
                          databaseService: databaseService,
                          reservation: reservation,
                          authenticationService: authenticationService),
                  update: (BuildContext context,
                          DatabaseService databaseService,
                          AuthenticationService authenticationService,
                          ViewReservationViewModel previous) =>
                      ViewReservationViewModel(
                          databaseService: databaseService,
                          reservation: reservation,
                          authenticationService: authenticationService),
                )
```

Like I said I'm not sure how hard this would be but it would be very nice. I know some people will add a `addApis` where they call 
`previous..addApis(...)` and basically construct their model through that method, but for unit testing I feel like being able to add the dependencies through the constructor is just a lot easier and cleaner. Thanks!

-------

Note: As a  workaround, currently I just return `null` to the `create` argument and do all of the constructing on the update call, but this feels a bit hacky.

**Comment by rrousselGit** [comment]
You can call "context.read" inside create.

The provider doesn't promote it because this is not reactive, but you can.

**Comment by gabrielmcreynolds** [comment]
Yes, but in many cases context is not available. For example, If I declare the ChangeNotifierProxyProvider in my router which looks like the following:

```
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    FirebaseAnalytics().setCurrentScreen(screenName: settings.name);
    switch (settings.name) {

      case RoutePaths.ViewReservation:
        final reservation = settings.arguments as Reservation;
        return FadeRoute(
            builder: (_) => ChangeNotifierProxyProvider2<DatabaseService,
                    AuthenticationService, ViewReservationViewModel>(
                  child: ViewReservationView(),
                  create: (_) => null,
                  update: (BuildContext context,
                          DatabaseService databaseService,
                          AuthenticationService authenticationService,
                          ViewReservationViewModel previous) =>
                      ViewReservationViewModel(
                          databaseService: databaseService,
                          reservation: reservation,
                          authenticationService: authenticationService),
                ));

      default:
        return MaterialPageRoute(
            builder: (_) => Scaffold(
                  body: Center(
                    child: Text('No route defined for ${settings.name}'),
                  ),
                ));
    }
  }
}
```

context is not defined so it would be nice to have this feature. Like I said, it's not a big deal, just something that would be nice...

**Comment by rrousselGit** [comment]
The parameter of "create" is a BuildContext, so you can use that

**Comment by gabrielmcreynolds** [comment]
I didn't think of that... 🤦 If I were to do this, and I had a very intensive task that got ran on construction, would the ProxyProvider construct my model twice, repeating the processs?

**Comment by rrousselGit** [comment]
You shouldn't construct your object inside the `update` method, but instead
reuse the object created in `create` and update it.

**Comment by gabrielmcreynolds** [comment]
Thanks for all your help, I'll close the issue now.
