### ISSUE TITLE
Documentation - Can I make my own Provider? section might need to be updated

### ISSUE THREAD

**Issue by dev-aentgs** [rrousselGit/provider#483]
In the [documentation for provider](https://pub.dev/packages/provider),  _Can I make my own Provider?_ section has mentions of v3.x.0 `Widgets`. It might be better to update it for v4.0.0 or add a link to the [migration-from-v3x0-to-v400](https://pub.dev/packages/provider#migration-from-v3x0-to-v400) section. 

> ### Can I make my own Provider?
> Yes. provider exposes all the small components that make a fully-fledged provider.
> 
> This includes:
> 
>` SingleChildCloneableWidget`, to make any widget works with `MultiProvider`.
> `InheritedProvider`, the generic `InheritedWidget `obtained when doing `Provider.of`.
> `DelegateWidget`/`BuilderDelegate`/`ValueDelegate `to help handle the logic of "`MyProvider()` that creates an object" vs "`MyProvider.value() `that can update over time".
> Here's an example of a custom provider to use `ValueNotifier `as state: https://gist.github.com/rrousselGit/4910f3125e41600df3c2577e26967c91

**Comment by rrousselGit** [comment]
Oops good catch!

**Comment by rrousselGit** [comment]
I've updated the gist and the readme
