### ISSUE TITLE
How handle hot reload?

### ISSUE THREAD

**Issue by nikitadol** [rrousselGit/provider#484]
**Is your feature request related to a problem? Please describe.**
I have a provider that depends on the assets in the project.
When 'Hot Reload' occurs, Flutter reloads the assets.
How can I catch this in my provider?

**Describe the solution you'd like**
```dart
mixin ReassembleMixin {
  void reassemble();
}
```
And in the element do something like this
```dart
if (provider is ReassembleMixin) {
  provider.reassemble();
}
```

**Additional context**
https://github.com/flutter/flutter/issues/7302
https://github.com/flutter/flutter/blob/1ad9baa8b9/packages/flutter/lib/src/widgets/framework.dart#L2988

**Comment by rrousselGit** [comment]
Sounds reasonable.
Fancy making a pull request?

**Comment by nikitadol** [comment]
Most likely yes, but later

**Comment by larssn** [comment]
I'm seeing some yanky behavior since this PR; namely after hot reloading Provider has started complaining about not using `listen: false` in the widget tree (not click handlers). I'll create an issue later as my time is limited right now, but rolling back to 4.2.0 makes it go away.

**Comment by rrousselGit** [comment]
I've deployed a fix

**Comment by larssn** [comment]
Perfect, thank you
