### ISSUE TITLE
ChangeNotifierProxyProvider cannot propagate notifyListeners() without making deep copies of consumed Providers

### ISSUE THREAD

**Issue by raywhiteside** [rrousselGit/provider#486]
**Preamble**

I don't think this qualifies as a bug exactly, but seems to be a failing example of best practices as I understand them. It is closely related to https://github.com/rrousselGit/provider/issues/314, and specifically this comment in that issue:

> If we pass non-primitive values (like a List<>) to the update method, we will unable to simply compare the new value with old one. In this case we have to create a copy of current value.

Why? A == should be enough. 
You don't need a deep compare. Compare what you use

_Originally posted by @rrousselGit in https://github.com/rrousselGit/provider/issues/314#issuecomment-571573854_

**Describe the bug**

The issue is when providing an object to a ChangeNotifierProxyProvider, checking for equality without doing a deep copy is flawed. If you simply assign the provided object inside the child ChangeNotifier, that passes a references to the provided object. Then when the provided object is updated, the provided object in the child ChangeNotifier appears to have been updated before the update() function of the ChangeNotifierProxyProvider is called because the provided object is merely a pointer to the original object. 

In beginning of the linked issue, there is an infinite loop because there is no filter looking for a meaningful change before actually updating the provided object in the child ChangeNotifier. However with the suggested comparison, the update in the child ChangeNotifier doesn't actually execute because the reference to the object already matches the reference to the object. The value of the provided object in the child is updated as desired, but the update function where you would logically put the notifyListeners() call after filtering useless updates won't fire when desired.

**To Reproduce**

I made this small repo to illustrate the issue as simply as possible:

https://github.com/raywhiteside/provider_architecture_experiment/commits/master

The second to last commit (0f04d487a316e98f6ddca799cc9c07802acd79a3) demonstrates the failing case using the suggested best practices as I understand them. This is the output of this commit:

```
I/flutter (25520): starting to fetch settings from backend
I/flutter (25520): considering updating settings in PageModel
I/flutter (25520): new settings are {first_setting: UNINITIALIZED, second_setting: UNINITIALIZED}
I/flutter (25520): actually updating settings in PageModel
I/flutter (25520): finished fetching settings from backend
I/flutter (25520): notifying listeners of settings update
I/flutter (25520): considering updating settings in PageModel
I/flutter (25520): new settings are {first_setting: UPDATED_TO_INTERESTING_VALUE, second_setting: UPDATED_TO_INTERESTING_VALUE}
I/flutter (25520): current settings are {first_setting: UPDATED_TO_INTERESTING_VALUE, second_setting: UPDATED_TO_INTERESTING_VALUE}
```

Note that the PageModel update function is called (prints "considering updating"), but it never generates a notifyListeners() call (prints "actually updating settings") because the new setting and current settings are the same. The screen is not updated, reading "first setting is UNINITIALIZED".

The final commit (fd4b8b80eaaa4dff7c97f278d09da6d68bc58f41) adds a deep copy to illustrate how this fixes the issue. This is the output of this commit:

```
I/flutter (25520): starting to fetch settings from backend
I/flutter (25520): considering updating settings in PageModel
I/flutter (25520): new settings are {first_setting: UNINITIALIZED, second_setting: UNINITIALIZED}
I/flutter (25520): actually updating settings in PageModel
I/flutter (25520): finished fetching settings from backend
I/flutter (25520): notifying listeners of settings update
I/flutter (25520): considering updating settings in PageModel
I/flutter (25520): new settings are {first_setting: UPDATED_TO_INTERESTING_VALUE, second_setting: UPDATED_TO_INTERESTING_VALUE}
I/flutter (25520): current settings are {first_setting: UNINITIALIZED, second_setting: UNINITIALIZED}
I/flutter (25520): actually updating settings in PageModel
```
Here current settings and new settings are different values as expected, so it generates a call to notifyListeners (prints "actually updating settings") and the screen is updated, reading "first setting is UPDATED_TO_INTERESTING_VALUE".

**Expected behavior**

The proposed solution without any package changes:

Make deep copies of all provided objects in the child ChangeNotifier. This wastes resources, though I would guess not a substantial amount in most cases. The bigger issue with this method to me is having to support clone constructors all the way down the stack. This is not incredibly complicated, but does seem error-prone and could result in difficult bugs. It is also difficult when working with objects from third-party packages that likely don't have a clone function already.

Potential package changes:

Can the previous state be kept around in any way besides a reference to compare it with the new state when deciding whether or not to update? It seems there are lifecycle functions doing similar things to this in other widgets, but it's unclear to me if they would ultimately suffer this same issue. 

**Postamble**

I could easily be simply thinking about this the wrong way, a better architecture suggestion would be a superb outcome in this case. It seems reasonable to me to want to pass complex objects down the tree, but perhaps that's not the intent of the package. I am quite happy with the architecture I have come up with using this package with the exception of this issue, it seems to be a good balance of simplicity and functionality. In that respect thanks for your work on this package, regardless of outcome.

**Comment by rrousselGit** [comment]
This is more of an architectural issue than a provider issue.
Your problem is that you are using a mutable class, ChangeNotifier.

My personal recommendation is to use something like state_notifier, which is basically a split of ChangeNotifier into Controller+Model, where Model is immutable.

**Comment by raywhiteside** [comment]
Perfect, that solution makes sense to me. I updated my experimental repo for posterity and/or code review here:

https://github.com/raywhiteside/provider_architecture_experiment/commit/7ec2723f7f636a352acdd46bd744b78859fc4a98

This is now the output, which makes a lot of sense.

```
I/flutter ( 5584): starting to fetch settings from backend
I/flutter ( 5584): rebuilding widget tree due to change of state
I/flutter ( 5584): finished fetching settings from backend
I/flutter ( 5584): controller state updated
I/flutter ( 5584): rebuilding widget tree due to change of state
```

I love that all the downstream widgets became immutable, rather than having cascading update methods.

I don't love how I have the provider/builder/model/view squished together in a tight tree, primarily because I need to pass context through the builders. I think this is personal failings in Dart/Flutter, the same thing can probably be rewritten in a more readable way.

On the topic of Provider itself however, it seems like a pretty big caveat that you can't (or at least shouldn't) be using mutatable classes through a ProxyProvider. Doubly so if it actually does happen to work with primitives and only fails when passing objects. Is this documented somewhere that I missed, or is it an implied logical leap I should have made? A "HEY DUMMY, DON'T USE MUTABLE OBJECTS FOR THIS" disclaimer in the API docs probably would have saved me a lot of time. Perhaps with a link to state_notifier/flutter_state_notifier.

In any case the immediate issue is solved, you can close whenever you want. Thanks for your time.

**Comment by rrousselGit** [comment]
The "avoid mutable data" is just a personal preference.
Many people use it, it's just more complex imo
