### ISSUE TITLE
Provider hot reload removes previous instance

### ISSUE THREAD

**Issue by darkwolf91** [rrousselGit/provider#490]
Hi, 

I recently adopted provider into my project and I am having a strange behavior when it does hot reload.
Essentially, I am trying to display Sign in/ Sign out button depending on a user has logged in or not.

However, what I noticed is that whenever a hot reload is triggered, the create function under Provider gets called every single time.

Since a new instance is created, it breaks the check in child widgets where I check the current user.

I am wondering if the create function on Provider is expected to behave this way?

**main.dart**
`
void main() {
  runApp(MultiProvider(providers: [
    Provider(create: (context) {
      print("called multiple times");
      return FirebaseAuthService();
    }),
    StreamProvider<User>(
        create: (context) =>
            context.read<FirebaseAuthService>().onAuthStatechanged),
  ], child: ModularApp(module: AppModule())));
}
`

**firebase_service.dart**
`class FirebaseAuthService implements ReassembleHandler {
  FirebaseAuth _firebaseAuth;
  GoogleSignIn _googleSignIn;

  FirebaseAuthService({FirebaseAuth firebaseAuth, GoogleSignIn googleSignIn}) {
    _firebaseAuth = firebaseAuth ?? FirebaseAuth.instance;
    _googleSignIn = googleSignIn ?? GoogleSignIn();
  }
`

**Comment by rrousselGit** [comment]
It sounds like "initState" of MultiProvider is called all the time

Your snippets don't give a reason as to why, but you should explore further and look at why initState is called again. 
It's likely that you are doing something weird in your widget tree, like changing a Key all the time or always pushing a new route

**Comment by rrousselGit** [comment]
Do you still have this issue?

**Comment by rrousselGit** [comment]
In the lack of answer, I will close this for now. Feel free to go on StackOverflow or open a new issue if you still have a problem
