### ISSUE TITLE
Understanding ChangeNotifierProxyProvider behavior

### ISSUE THREAD

**Issue by davidmartos96** [rrousselGit/provider#491]
Hello @rrousselGit , I'm trying to understand why the following error is triggered inside the `ChangeNotifierProxyProvider` update callback. I'm aware that this error occurs when calling `notifyListeners` inside a Widget `build` method, but I wasn't aware that it could trigger in the following setup.
My setup consists in 2 `ChangeNotifiers`, one that depends on the other (child and parent). Sometimes the child needs to communicate with the parent so that the child can get fresh data with the Proxy provider. 

Here is the sequence of operations when the action starts and when the error triggers.
```
Start async work in child model:
    Some work...
    NOTIFYING CHILD MODEL LISTENERS 2020-07-14 15:43:07.336938

    Call parent model async method from within this child model method:
        Some work....
        NOTIFYING PARENT MODEL LISTENERS 2020-07-14 15:43:07.385428
---------
Inside ChangeNotifierProxyProvider<ParentModel, ChildModel> update callback:
    NOTIFYING CHILD MODEL LISTENERS 2020-07-14 15:43:07.401075

ERROR IS THROWN:
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for DeckCardsTabModel:
setState() or markNeedsBuild() called during build.
```

Here is how the ProxyProvider is created. I'm returning the same `ChildModel` instance because I would like
to preserve its state. I listen to some streams inside the child model, so this way they are not reinitialized.
`onParentModelUpdated` could notifyListeners and that is when I get the above error.

```dart
        ChangeNotifierProxyProvider<ParentModel, ChildModel>(
          create: (context) {
            return ChildModel();
          },
          update: (context, parentModel, childModel) {
            childModel.onParentModelUpdated(parentModel);
            return childModel;
          },
        ),
```

I would like to understand why this happens. If I schedule the `notifyListeners` inside the `onParentModelUpdated` method for the next frame, everything works correctly, but I don't know if that is the best solution. Maybe there is a better way to structure the providers for the Parent - Child communication? 

My understanding was that calling `notifyListeners` inside the ProxyProvider update callback was safe, but it looks like not necessarily.

Thanks!

**Comment by rrousselGit** [comment]
It sounds like your ChildModel is modifying a ParentModel – which is not good.

ParentModel can modify ChildModel, but ChildModel is not allowed to modify ParentModel.

**Comment by davidmartos96** [comment]
Do you know any alternative or pattern on how to handle this child to parent communication? Basically the child knows that the parent needs to update (fetch some data and return to the child via the proxy provider).
If not, feel free to close it 😄

**Comment by rrousselGit** [comment]
Child to parent update should not happen
You should restructure your communication such that it is reversed

**Comment by davidmartos96** [comment]
@rrousselGit 
Thanks Remi!
After some more investigation I've discovered that the issue is not related to the Child - Parent communication.
It has to do with injecting providers to a different route (on my case, a bottom sheet).
Here is a minimal example (no child - parent communication whatsoever). ¿Could it be an edge case in Provider? I could file a different issue if this is in fact a bug.

https://gist.github.com/davidmartos96/5bd829c1c43b124fb4c98f32267bfdb8

I haven't find any issues injecting existing providers to other routes for a long time, until now, hence my confusion.
