### ISSUE TITLE
Understanding how to debug the provider.

### ISSUE THREAD

**Issue by zommerberg** [rrousselGit/provider#493]
I am using Flutter Provider with a DiagnosticableTreeMixin in order to keep track of my state in the debugger.

However I need to set up the DiagnosticableTreeMixin to work with a List, not with plain strings or booleans.

## My Setup :
1) Class Setup
```
class MyClass with DiagnosticableTreeMixin {
  MyClass({this.value1, this.value2});

  final String value1;
  final String value2;


  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(StringProperty('value1', value1));
    properties.add(StringProperty('value2', value2));
  }
}
```
2)Provider Setup

```
class MyClassProvider with ChangeNotifier, DiagnosticableTreeMixin {
  List<MyClass> _listOfMyClass = [];
  List<MyClass> get listOfClass => _listOfMyClass;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);

    properties.add(DiagnosticsProperty<List<MyClass>>(
        'ListOfMyClass', _listOfMyClass));
  }
}
```
In this case when I open the debugger i see the following:
```
ListOfMyClass:[MyClass#0bb46(value1:"123",value2:"345),MyClass#0b546(value1:"123",value2:"456"),MyClass#01b46(value1:"1
```
This is an example with 3 instances, it is always cut into one line. This is problematic when trying to track multiple values since they will be not shown at all, and it is not an expandable structure so it is messy to track anything this way.

How is it possible to turn them into readable values in the debugger just like it would work with a normal console.log in the web?

Something like the example below while every item can be expanded:
```
ListOfMyClass:
[
 MyClass#0bb46(value1:"123",value2:"345),
 MyClass#0bb46(value1:"123",value2:"345),
 MyClass#0bb46(value1:"123",value2:"345),
 MyClass#0bb46(value1:"123",value2:"345),
 MyClass#0bb46(value1:"123",value2:"345),
 MyClass#0bb46(value1:"123",value2:"345)
]
``

**Comment by rrousselGit** [comment]
It's a bug I reported some time ago in the devtool https://github.com/flutter/devtools/issues/1679

Provider can't do anything about it, nor is your code wrong. It's just the devtool that doesn't render this nicely
So I'd suggest upvoting that issue.
