### ISSUE TITLE
StreamProvider ConnectionState.waiting

### ISSUE THREAD

**Issue by andrefedev** [rrousselGit/provider#494]
I have been looking for more documentation for StreamProvider including I think more documentation is missing. For example how can I know if the stream has completely resolved or is loading. With StreamBuilder it can be done easily according to the documentation, can I combine StreamBuilder with Provider?

**Comment by rrousselGit** [comment]
Could you expand more on your use case? Why do you need to know when the stream finished? 🙂

**Comment by andrefedev** [comment]
I would like to intercept new change while applying show progress circle. Firebase internally makes network calls and will take some time to respond, for that I want to allow to block buttons or any action while the stream ends.
    
    class AuthService {
      final FirebaseAuth _auth = FirebaseAuth.instance;

      // Firebase user a realtime stream
      Stream<FirebaseUser> get onAuthStateChanged => _auth.onAuthStateChanged;

      // Firebase user one-time fetch
      Future<FirebaseUser> get currentUser => _auth.currentUser();
    }

    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return Provider<AuthService>(
          create: (_) => AuthService(),
          child: MaterialApp(
            // ....
            home: LadingScreen(),
          ),
        );
      }
    }

    class LadingScreen extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return StreamProvider<FirebaseUser>(
          create: (_) => context.read<AuthService>().onAuthStateChanged,
          child: Consumer<FirebaseUser>(
             builder: () //.....
          ) ,
        );
      }
    }

**Comment by rrousselGit** [comment]
My recommendation would be to use a union type instead, possibly generated by github.com/rrousselgit/freezed

Such as writing:

```dart
@freezed
abstract class AsyncValue<T> with _$AsyncValue<T> {
  const factory AsyncValue.data(@nullable T value) = AsyncData<T>;
  const factory AsyncValue.loading() = AsyncLoading<T>;
  factory AsyncValue.error(Object error, [StackTrace stackTrace]) =
      AsyncError<T>;
}
```

Then using `StreamProvider` like so:


```dart
StreamProvider<AsyncValue<User>>(
  create: (ref) => auth.onAuthStateChanged.map($AsyncValue.data),
  initialValue: const AsyncValue.loading(),
  onError: $AsyncValue.error,
)
```

Then listened:

```dart
Widget build(context) {
  final user = context.watch<AsyncValue<User>>();

  return user.when(
    loading: () => const CircularProgressIndicator(),
    error: (err, stack) => Text('error'),
    data: (user) => Text('Hello ${user.name}'),
  );
}
```
