### ISSUE TITLE
How to apply ChangeNotifierProxyProvider without exposing this relationship

### ISSUE THREAD

**Issue by w1874** [rrousselGit/provider#495]
Here is what I learned about _ChangeNotifierProxyProvider_: 

**it defines the relationship between 'parent' and 'child', and when child changed, it will 'notify' parent. We also can directly change/update child from parent.** 

This is a simple example:
![display](https://user-images.githubusercontent.com/26924433/87933150-49909d80-cabf-11ea-8dbe-c23e9143c23c.gif)

https://github.com/w1874/provider_test/blob/master/lib/main.dart

This relationship is defined in the parent widget:

```dart
class ParentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ChildModel(1)),
        ChangeNotifierProxyProvider<ChildModel, ParentModel>(
          create: (_) => ParentModel(1),
          update: (_, childModel, parentModel) => parentModel..childModel = childModel,
        ),
      ],
      child: ...
```

BUT, **when i defined a super parent widget, how can i controll parent, without exposing anything about ChildModel?**

For example, the following is not ...

```dart
class SuperWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ChildModel(1)),
        ChangeNotifierProxyProvider<ChildModel, ParentModel>(
          create: (_) => ParentModel(1),
          update: (_, childModel, parentModel) => parentModel..childModel = childModel,
        ChangeNotifierProxyProvider<ParentModel, SuperModel>(
          create: (_) => SuperModel(),
          update: (_, parentModel, superModel) => superModel..parentModel = parentModel,
        ),
      ],
      child: ...
```

**Comment by rrousselGit** [comment]
I don't really understand what you're trying to do.
What is wrong in your last snippet?

**Comment by w1874** [comment]
> I don't really understand what you're trying to do.
> What is wrong in your last snippet?

The problem of last snippet is: if I design parentwidget as an isolated library/package, it can be called anywhere. And I think the **suitable** usage is:
```dart
class SuperWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ParentModel(1)),
        ChangeNotifierProxyProvider<ParentModel, SuperModel>(
          create: (_) => SuperModel(),
          update: (_, parentModel, superModel) => superModel..parentModel = parentModel,
        ),
      ],
      child: ...
```

It works like as a linked list...

**Comment by rrousselGit** [comment]
How would ParentModel know what is ChildModel?

**Comment by w1874** [comment]
> How would ParentModel know what is ChildModel?

I mean this relationship of ParentModel and ChildModel is intergrated into ParentWidget, the caller (SuperWidget) only need maintain the dependency relationship with ParentModel.

**Comment by rrousselGit** [comment]
You could pass context.read to the constructor of your class.

Provider exposes a typedef for it: Locator

```dart
Locator read = context.read;

read<Foo>();
read<Bar>()
```
