### ISSUE TITLE
provider notice will reset pageview index

### ISSUE THREAD

**Issue by leetomlee123** [rrousselGit/provider#497]
**Describe the bug**

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by rrousselGit** [comment]
Please fill in the form about what the problem is and how to reproduce it.

**Comment by leetomlee123** [comment]
it is diffcult to description
u can download apk observe 
![Screenshot_20200723-112834](https://user-images.githubusercontent.com/19498940/88249663-a2fdf580-cc94-11ea-890b-019501abdc0a.jpg)
 scroll page and switch app theme .
u will see it
 tks

**Comment by rrousselGit** [comment]
No, I _need_ a way to reproduce the issue and a good description.

**Comment by leetomlee123** [comment]
ok later  i will writer demo for this
