### ISSUE TITLE
UI is not refreshed when an update is made in the viewmodel

### ISSUE THREAD

**Issue by chilex111** [rrousselGit/provider#498]
In my app release version, the UI is not updated when i select an image from either my camera or gallery. But i can select and display image on my screen with the debug version of my app.
```
void _pickImage(HouseViewModel vm, ImageSource source) async {
   var selected = await picker.getImage(source: source);
    vm.setSavedImage = File(selected.path);
    Navigator.pop(context);
    print(vm.savedImage.file);
  }
```
Inside my viewmodel class I have 

```
set setSavedImage(File value) {
    _savedImage = value.toString().isNotEmpty
        ? FileValidationModel(value, null)
        : FileValidationModel(null, errorMsg);
    notifyListeners();
  }

```
The UI should refresh once an update has been made on the release version just like it does on the debug version of the app

**Comment by rrousselGit** [comment]
This issue does not respect the bug report template.
Please stick to the template

Futhermore, you gave too much code. 
Please remove all the code unrelated to the issue, and provide only the least amount of code necessary to reproduce the problem

**Comment by rrousselGit** [comment]
Thanks for clarifying a bit the issue
I still need a reliable way to reproduce the problem. It's hard to say just looking at the code.

Could you create a separate Flutter app, that contains just enough code to reproduce the issue, with step by step explanation on how to reach the problem?

**Comment by rrousselGit** [comment]
Do you still have the problem?

**Comment by rrousselGit** [comment]
Closing this is this unanswered
