### ISSUE TITLE
Please remove political banners from Readme.

### ISSUE THREAD

**Issue by gladkikhartem** [rrousselGit/provider#500]
**Describe the bug**
There's a political statement in first line of Readme that has nothing to do with the repository or code.

**To Reproduce**

**Expected behavior**
No politics in repositories. It's really disturbing.
And it's not like i'm against the statement - it's just code repository is not the right place for it.

**Comment by rrousselGit** [comment]
What's wrong with it, and what else would you suggest?

**Comment by RaviKavaiya** [comment]
@rrousselGit Here's my proposal:
Can you put this banner at bottom of the page?
(Note: I am not against this thing, just want to make the pub.dev page look more cleaner and to the topic)

**Comment by rrousselGit** [comment]
Putting it at the bottom of the page decreases the efficiency of the banner.

There is little value in having a banner if it isn't visible

**Comment by PavelPZ** [comment]
I'm a little older than you boys. And I have a different political experience than you: I spent half of my life under the dictatorship of the Soviet Union (in Czechoslovakia). Based on my experience, I don't trust political movements like BLM, Greta, Me too, etc. 

On the other hand, I trust tools such as Flutter, Provider, etc. So let's not mix dirty policy with the beauty of Flutter cross-platform develompent.

**Comment by rrousselGit** [comment]
You're over exaggerating.
There is no "if you use provider, you have to agree with Rémi Rousselet's political opinions" in the license.
You can use provider while disagreeing with this line.

That's just a single line with hypertext, that many OS projects includes too (like React and Flutter) about an issue that I care about

**Comment by filiph** [comment]
> I'm a little older than you boys. And I have a different political experience than you: I spent half of my life under the dictatorship of the Soviet Union (in Czechoslovakia). Based on my experience, I don't trust political movements like BLM, Greta, Me too, etc.

For what it's worth, I spent my early life in communist Czechoslovakia as well, and I think that comparing grassroots protests (like BLM, Me too, and students' environmental activism) to a hateful, corrupt, 40-year-long totalitarian regime is... exaggeration. I understand where it comes from (communism also started as a grassroots movement).

In my view, @rrousselGit's support of a protest movement in the README of his own open source project is fair. Of course, there is a balance. Nothing is absolute. If @rrousselGit put a political statement on every dartdoc comment in the whole repo, then yeah, that's too much. If he was asking for a bloody revolution or seize of power, yeah. But adding two sentences at the top of the README that support protests against racism and police brutality — I'd say that's totally fine. I'd understand if he agreed to make the font smaller if he wanted. But that's about the extent of modification I'd expect.

**Comment by gladkikhartem** [comment]
> What's wrong with it, and what else would you suggest?
What is wrong is that Engineering and Politics get mixed. This is wrong for efficiency reasons. For example:
I was doing programming  just fine and because of your banner - now I'm into politics, wasting my time writing arguments.
We could both use our time more productively, if the banner was not there.
What's next - we'll include political statements in the comments and start naming variables using political views? 

There are lots of other ways to advertise your political views - social networks and etc... You a free to use them as you wish.
You are also free to do whatever you want in your repo and keep the banner. My obligation is to remind you are bringing politics into engineering and this is distracting developers from their work.

At the end of the day - we can disagree politically, but we can write code together. :) I like that.
And the only way to continue working together with different political views is to keep our work and politics separate.
If all developers will start putting political banners in READMEs - the Github will soon become Facebook, which is not good for everyone.

**Comment by rrousselGit** [comment]
I don't understand the efficiency argument.
If you feel that this discussion is a waste of time, you are free not to spend more time answering.
You were the one creating this issue, after all. Nobody forced you to afaik.

Engineering and Politics are mixed.
This can go from your "other" choice when asking for the gender of a user, to "Is it fair for Apple/Play stores to take a 30% cut on the payments?", to groups like Flutteristas or Women tech makers

It's not like only Provider is including such banner either. A large number of projects do so:
- https://reactjs.org/
- https://vuejs.org/
- https://redux.js.org/
- https://flutter.dev/
...

Not to mention that as opposed to some of these sites, as soon as you scroll in Provider's readme, you won't see the banner anymore. In React's documentation, the banner will follow you everywhere you go.

**Comment by gladkikhartem** [comment]
`It's not like only Provider is including such banner either. A large number of projects do so:`

Putting banner on website != putting banner in README.  Website is for public, README is for developers.
And "others also do that" is not a valid justification for any action.

`Engineering and Politics are mixed.`

Your examples are not about Engineering, but about tech companies.  

`You were the one creating this issue, after all. Nobody forced you to afaik.`
You had put this banner - you brought politics to this repo - not me. 
I've just showed this fact. And the fact that I don't like politics in repositories.

`If you feel that this discussion is a waste of time, you are free not to spend more time answering.`

**Silence means consent**

**Comment by rrousselGit** [comment]
> Putting banner on website != putting banner in README. Website is for public, README is for developers.

These websites are for developers. They the documentation of open-source projects.
Provider's readme is the equivalent since afaik there is no way to edit the Dartdoc hosted by pub.

> Silence means consent

That is exactly why this banner was added

**Comment by gladkikhartem** [comment]
You have you vision and you are not planning to have a conversation or change/remove the banner. That's what I understood.

We can close this issue and of course you can do what you think is necessary.

I at least tried to show you why it's wrong to mix Politics with Engineering. Hope you'll understand this at some point.
Have a good luck and thanks for the peaceful discussion! :)

**Comment by rrousselGit** [comment]
Thank you too!

Not that the banner will be removed in the future. It is not a permanent addition. I'm not sure on _when_ though.
