### ISSUE TITLE
Consumers don't refresh from ChangeNotifiers when deploying app to web

### ISSUE THREAD

**Issue by tonyjchong** [rrousselGit/provider#503]
**Describe the bug**
Hi,

I know this Flutter for web is in the beta channel so if its not supported in provider, thanks anyway!
I have a Consumer that rebuilds a widget when the value of my ChangeNotifierProvider is updated. Works fine in iOS Simulator, and real mobile devices. When deploying to web, I can see the right things in the console, but the widget in the browser doesn't rebuild. 

**To Reproduce**
* Setup a Provider / Consumer that rebuilds the widget on a change
* Deploy to web
* Test the functionality

I'm pretty new to flutter so my code is all over the place. Happy to paste in some snippets if you can give me some guidance. 

**Expected behavior**
I would expect the widget to rebuild when the provider is updated.

**Comment by rrousselGit** [comment]
It is likely that you have an exception.

Try overriding FlutterError.onError to print errors to the console

**Comment by tonyjchong** [comment]
Thanks! I will give that a go and report back.

**Comment by tonyjchong** [comment]
Thank you for the tip. Looks like there is something else wrong and I won't have time to look into this for a while. I'm going to close for now while I refactor some stuff. If I can reproduce this with a less complex example, I'll open another ticket.

**Comment by wtfiwtz** [comment]
I have the same issue, based on the example code here, testing it with Flutter Web:

https://medium.com/flutter/testable-flutter-and-cloud-firestore-1cf2fbbce97b
https://github.com/craiglabenz/flutter-firestore-counter

It seems that the first two expectations in the test are successful, but the listener is not yet registered - `CounterManager.hasListeners` returns `false` in `increment()`. Hence, the third expectation fails because the count is never rebuilt after the `tap` event.

I'm still looking into it... 

`flutter doctor` gives `Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-AU)`
`provider` version is `4.3.2+4`

**Comment by wtfiwtz** [comment]
If I change the main code to use the `TestDependencyProvider` directly instead...

```
void main() {
  runApp(
      TestDependenciesProvider(child: MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: MyHomePage(title: 'My title')))
      // DependenciesProvider(child: MyApp())
  );
}
```

... then I get exceptions unless I update the following: 

```
Text(
              '${widget.manager != null ? widget.manager.state.count : '(loading)'}',
              style: Theme.of(context).textTheme.headline4,
            )
```

Then I constantly get `(loading)` on the page and the console shows the error `Another exception was thrown: NoSuchMethodError: invalid member on null:
'increment'`.

So I think the current setup of the test is not correct and some exception is occurring on the initial setup, causing problems with the setup of the listener.

**Comment by wtfiwtz** [comment]
I think I've worked it out... in my version of the code, the test is missing the `Consumer` here:
https://github.com/craiglabenz/flutter-firestore-counter/blob/main/test/widget_test.dart#L21
