### ISSUE TITLE
A way to not register a widget or something as a listener

### ISSUE THREAD

**Issue by millionhz** [rrousselGit/provider#508]
**Is your feature request related to a problem? Please describe.**

So the Provider.of(context) only exists for backwards comparability reasons and we should not use Provider.of(context, listen: false)  in our flutter app. context.read() cannot be used in build methods either so there is not way to create something use provider and not register it as a listener.

**Describe the solution you'd like**

A functionality in the package to register something as not a listener or detailed way to do it in the docs.

**Describe alternatives you've considered**

One way to do this have a variable in my model that will not change and use context.watch() to access it. At the end of the session, right before the widget is destroyed ,update that variable through a function.

Like mentioned in [this](https://stackoverflow.com/questions/63230323/getting-context-read-functionality-inside-build)

**Comment by rrousselGit** [comment]
The whole point of not allowing context.read inside build is that you should not do that.

Call context.read inside initState/didUpdateWidget instead

**Comment by millionhz** [comment]
I can imagine how context.read can be used in initState to set a variable that will not change but will change when the widget is reinitialized. 

I will try to submit a pull requests to the readme with sample code that will show how to implement this.

Thanks for this amazing package btw 😊.
