### ISSUE TITLE
Unhandled Exception: A EmrProvider was used after being disposed.

### ISSUE THREAD

**Issue by rakakhrl** [rrousselGit/provider#509]
**Describe the bug**
I got this error `Unhandled Exception: A EmrProvider was used after being disposed.` in my EmrProvider when i modify FilterProvider to call methods on its constructor.

Before i modify FilterProvider to call methods from its constructor everything works fine.

**To Reproduce**

app.dart
```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<EmrProvider>(
          create: (_) => EmrProvider(),
        ),
        ChangeNotifierProvider<FilterProvider>(
          create: (_) => FilterProvider(),
        ),
        ChangeNotifierProxyProvider<FilterProvider, EmrProvider>(
          create: (_) => EmrProvider(),
          update: (_, filter, __) => EmrProvider(
            filter: filter.inpatientListFilter,
          ),
        ),
      ],
      child: MaterialApp(),
    );
  }
}
```

FilterProvider
```dart
class FilterProvider extends ChangeNotifier {
  FilterProvider() {
    getListRoom();
    getListRoomClass();
    getListGuarantor();
  }

  List<RoomData> _listRoom;
  List<RoomClassData> _listRoomClass;
  List<GuarantorData> _listGuarantor;

  List<RoomData> get listRoom => _listRoom;
  List<RoomClassData> get listRoomClass => _listRoomClass;
  List<GuarantorData> get listGuarantor => _listGuarantor;

  set setListRoom(List<RoomData> val) {
      _listRoom = val;
      notifyListeners();
  }

  set setListRoomClass(List<RoomClassData> val) {
      _listRoomClass = val;
      notifyListeners();
  }

  set setListGuarantor(List<GuarantorData> val) {
      _listGuarantor = val;
      notifyListeners();
  }

  Future getListRoom() async {...}

  Future getListRoomClass() async {..}

  Future getListGuarantor() async {...}
}
```
EmrProvider
```dart
class EmrProvider extends ChangeNotifier {
  final InpatientListFilter filter;

  EmrProvider({this.filter});

  List<InpatientData> _inpatientList = [];
  bool _isFetchingInpatient = false;

  List<InpatientData> get inpatientList => _inpatientList;
  bool get isFetchingInpatient => _isFetchingInpatient;

  set inpatientList(List<InpatientData> val) {
    _inpatientList = val;
    notifyListeners();
  }

  set isFetchingInpatient(bool val) {
    _isFetchingInpatient = val;
    notifyListeners();
  }

  Future getActiveInpatientList(String doctorId) async {...}
}
```

Some code is remove to make it shorter

**Expected behavior**
My widget can access data stored in EmrProvider without getting any error

**Comment by rrousselGit** [comment]
filter.inpatientListFilter likely changed before getActiveInpatientList completed, in which case a new ChangeNotifier was created and the previous one was disposed.

**Comment by rakakhrl** [comment]
> 
> 
> filter.inpatientListFilter likely changed before getActiveInpatientList completed, in which case a new ChangeNotifier was created and the previous one was disposed.

But the method call only updates listRoom, listRoomClass and listGuarantor and not inpatientListFilter. How do I listen only if inpatientListFilter changed and not the others?

**Comment by rrousselGit** [comment]
You probably want something like:

```dart
        ChangeNotifierProxyProvider<FilterProvider, EmrProvider>(
          create: (_) => EmrProvider(),
          update: (_, filter, emr) {
            emr.filter = filter.inpatientListFilter;
            return emr;
          }
        ),
```

**Comment by rakakhrl** [comment]
> 
> 
> You probably want something like:
> 
> ```dart
>         ChangeNotifierProxyProvider<FilterProvider, EmrProvider>(
>           create: (_) => EmrProvider(),
>           update: (_, filter, emr) {
>             emr.filter = filter.inpatientListFilter;
>             return emr;
>           }
>         ),
> ```

Thank you for the help this works like intended. Can you explain what the difference between this and my implementation?

**Comment by rakakhrl** [comment]
Closing this because this is no longer an issue
