### ISSUE TITLE
ChangeNotifierProvider example

### ISSUE THREAD

**Issue by stocksp** [rrousselGit/provider#51]
Is the example code show by @brianegan in "Merge provider and scoped_model" 
 https://github.com/brianegan/scoped_model/issues/61  the "correct" way to use this provider?

Simple examples of the existing providers would help a lot for users of "scoped_model".  Your only example of the 'simple' provider seems to me to be the least useful as it isn't 'reactive' (if I'm reading the docs correctly) 

thanks for all your work!

**Comment by rrousselGit** [comment]
All providers are reactive. `ChangeNotifierProvider` is built on the top of the one in the example.

Improving the documentation and making great examples is definitely needed. But note that, as opposed to `scoped_model`, there's not a single possible architecture using `provider`.

`provider` is a mean, not the end.

**Comment by stocksp** [comment]
"This is perfect for exposing a complex object that **_never changes over time_** without writing a StatefulWidget"
never change .. is where I got the 'non reactive' thought.
In Scoped_model we extend out model from the included Model class and call 'notifyListeners' to get reactivity.  Which is the source of my confusion.

**Comment by rrousselGit** [comment]
> never changes over time

That's for the default constructor.
`Provider.value` constructor properly updates dependents when the value changes.


The mean to achieve the update is different though. Instead of a `Listenable`/`ChangeNotifer`, you'll need a stateful widget and call `setState` to update the passed value.

**Comment by stocksp** [comment]
Ahhh ...
"The mean to achieve the update is different though. Instead of a Listenable/ChangeNotifer, you'll need a stateful widget and call setState to update the passed value."

thanks, got it now!
