### ISSUE TITLE
Provider to change element in StreamBuilder ListView

### ISSUE THREAD

**Issue by GiacomoK** [rrousselGit/provider#511]
Hi,  
I am not able to use a Provider that changes element in StreamBuilder ListView (when something happens).

My model uses the function `notifyListeners()`.  

My StreamBuilder is:

    return StreamBuilder<List<MyItem>>(
      stream: _listStream,
      builder: (context, snapshot) {
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return CircularProgressIndicator(strokeWidth: 3.0);
            break;
          default:
            if (snapshot.hasData && snapshot.data.length > 0) {
              return ListView.builder(
                controller: _controller,
                itemCount: snapshot.data.length + 1,
                itemBuilder: (context, index) {
                  return index >= snapshot.data.length
                      ? CircularProgressIndicator(strokeWidth: 3.0)
                      : ChangeNotifierProvider<MyItem>(
                    create: (context) => snapshot.data[index],
                    update: (_, item) => item,
                    child: Consumer<Email>(
                      builder: (_, value, __) {
                        return _buildRow(value);
                      },
                    ),
                  );
                },
              );
            } else {
              return Container();
            }
        }
      },
    );

I tried everything, but the element in the ListView does not change.  
I noticed than when MyItem executes `notifyListeners()` function, it does have 0 listeners.  

Since my model is already instantiated, I also tried with `ChangeNotifierProvider<MyItem>.value` without success.

**Comment by rrousselGit** [comment]
You should definitely use the `.value` constructor. 
What do you mean by "without success"?

**Comment by GiacomoK** [comment]
I do not get any error, but the element seems not to be rebuilded.  
Even if I put a breakpoint (in debug) in the builder function of the consumer, the `builder` function itself is not executed after the model called `notifyListeners()` function.  
And with a breakpoint in the model, I see that it does have 0 listeners.

**Comment by rrousselGit** [comment]
It's hard to say just like that.

Could you make a minimalist app to reproduce the problem? Something without business logic, just enough code to run into the issue

**Comment by GiacomoK** [comment]
I will try

**Comment by GiacomoK** [comment]
I found the error.
I navigate from the list screen to another screen, and in the other screen I change the value of the element of the first screen.

The error was that in the second screen I reloaded the element from a server, so it was NOT the same element of the first screen.
Now I pass the element from the first screen to the second screen (without reloading it), and it works.
