### ISSUE TITLE
Document the builder parameter

### ISSUE THREAD

**Issue by davystrong** [rrousselGit/provider#512]
I may just be missing something but I have been using Provider (4.x) for a while and using the builder parameter like this:
```
Provider<MyClass>(
  create: (context) => MyClass(),
  builder: (context, child) {
    (...)
  },
)
```
Instead of explicitly creating a Builder widget:
```
Provider<MyClass>(
  create: (context) => MyClass(),
  child: Builder {
    builder: (context) => (...),
  },
)
```
This is very handy because it avoids extra boilerplate by providing a `context` where the provider value can be accessed and after I discovered this, I've really used Provider more frequently as a replacement for StatefulWidget.

However, I was reading the pub.dev page and discovered and it says "The parameters builder and initialBuilder of providers are removed.". I also couldn't find any explanation of this builder parameter in the details for any of the providers. Is this a mistake in the docs? Or maybe I'm using it wrongly/missed something?

Edit: I notice this is actually mentioned in the classic `ProviderNotFoundException` error message, so it seems to be correct.

**Comment by rrousselGit** [comment]
What the doc is referring to is the previous usage of `builder`.
Before, `create` was named `builder`. But it was renamed as part of 4.0.0

Then, a new _different_ `builder` was introduced, that is more in line with what "builder" means in the context of Flutter.
