### ISSUE TITLE
ios browser white screen

### ISSUE THREAD

**Issue by lcn1988** [rrousselGit/provider#521]
**Describe the bug**
This flutter demo,ios browser(Chrome Safari ) white screen，other platform browsers are normal,
provider: ^4.3.2+1
ios:13.6.1
flutter 1.21.0-10.0.pre.95,

**To Reproduce**
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
 // runApp(MyApp());
  runApp( MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => AmountPro()),
    ],
    child: MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor:Colors.white,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home:  MyHomePage(title: 'Flutter Demo Home Page'),
    ),
  ),);
}
class AmountPro with ChangeNotifier {
  int _amount;

  get amount => _amount;

}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,

        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
            routes:<String, WidgetBuilder>{

        '/home':(BuildContext context)=>new MyHomePage(),

      },
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

**Expected behavior**

**Comment by rrousselGit** [comment]
Grey screens appears when there is an exception in your application in release mode.

Override FlutterError.onError to print the errors to help you understand what happen. 

In any case, it is unlikely to be related to provider itself.

**Comment by rrousselGit** [comment]
Closing since there is nothing provider can do afaik. It is Flutter that makes the error silent, and Provider cannot do anything to make it more obvious what is happening.

Feel free to create a new issue if you have a suggestion on how we could improve the current situation.
