### ISSUE TITLE
Could not find the correct Provider<ListProvider> above this ListWidget Widget.

### ISSUE THREAD

**Issue by icodetheworld** [rrousselGit/provider#522]
I'm running into this issue all the time. I've been working on this for an entire week. I'm not seeing any possibility to get this error. 

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ProviderNotFoundException was thrown building ListWidget(dirty):
Error: Could not find the correct Provider<ListProvider> above this ListWidget Widget
This likely happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:
- The provider you are trying to read is in a different route.
  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.
- You used a `BuildContext` that is an ancestor of the provider you are trying to read.
  Make sure that ListWidget is under your MultiProvider/Provider<ListProvider>.
  This usually happen when you are creating a provider and trying to read it immediately.

Here's my code

```
import 'package:db_example/Views/controller/provider/list_provider.dart';
import 'package:provider/provider.dart';

class ListWidget extends StatefulWidget {
  @override
  _ListWidgetState createState() => _ListWidgetState();
}

class _ListWidgetState extends State<ListWidget> {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: Provider.of<ListProvider>(context, listen: false).fetchData(),
        builder: null,
        );
  }
}
```
```
import 'package:flutter/foundation.dart';

class ListProvider with ChangeNotifier {
  List<ListMdl> _items = [];
  List<ListMdl> get items {
    return [..._items];
  }

  Future<void> fetchData() async {
    final dataList = await DBHelper.getData('lists');
    _items = dataList
        .map((item) => ListMdl(name: item['name'], age: item['age']))
        .toList();
    print(_items);
  }
}
```

**Comment by rrousselGit** [comment]
Did you make sure that your Provider is above in the widget tree?

**Comment by jmcalibuso27** [comment]
If you want your provider to be accessible on all routes, set your MaterialApp as a child of Provider/MultiProvider.

**Comment by chinkysight** [comment]
Your `ListProvider` is not on the top of your `ListWidget`, that why you were not able to your `ChangeNotifierProvider`. Do as @jmcalibuso27 stated.

**Comment by rrousselGit** [comment]
Closing due to the lack of answer. If you still have the problem, make sure to try what was suggested here :smile:
