### ISSUE TITLE
ChageNotifierProxyProvider - make 

### ISSUE THREAD

**Issue by chris-rutkowski** [rrousselGit/provider#523]
I'd like to easily initialise `ChangeNotifierProvider` that has a dependency delivered from other Provider.

At this moment it's extremely simple to be done with `ProxyProvider`, as it doesn't require `create` argument:

```
MultiProvider(
  providers: [
    Provider<A>(create: (_) => A()),
    ProxyProvider<A, B>(update: (_, a, b) => a ?? A(b)),
  ]
)

class B {
  B(A a) {
    // do initialisation
  }
}
```

However, with `ChangeNotifierProxyProvider` it's not so easy...

```
MultiProvider(
  providers: [
    Provider<A>(create: (_) => A()),
    ChangeNotifierProxyProvider<A, B>(
      create: (_) => B(),
      update: (_, a, b) => a..set(b)
    ),
  ]
)

class B with ChangeNotifier{
   A _a;
   
   void set(A a) {
     if (_a != null) return;
     _a = a;
     // do initialisation
   }
}
```

Is there any reason why ChangeNotifierProxyProvider needs to have create method required?

Kind regards
Chris

**Comment by rrousselGit** [comment]
ProxyProvider is useful mainly for cases when one of the dependency can change over time

In that case, we usually don't want to recreate the ChangeNotifier, as we would lose the state

If you don't care about updates, you can use the normal ChangeNotifierProvider and use the context parameter to read other providers

**Comment by chris-rutkowski** [comment]
But in order to get provider from context the other providers cannot be created in the same context. I would need to create some dummy widgets or use Builder, correct me if I'm wrong?

**Comment by rrousselGit** [comment]
Each provider has its own context, so it's fine

**Comment by chris-rutkowski** [comment]
I don't think so, this code:

```
MultiProvider(
  providers: [
    Provider<A>(create: (_) => A()),
    ChangeNotifierProvider<B>(
      create: (_) => B(
        Provider<A>.of(context, listen: false),
      ),
    ),
  ]
)
```

complains it cannot find the provider A. That's what I meant by nesting into dummy widgets - easy but tedious walkaround.

**Comment by rrousselGit** [comment]
The way to do it is:

```dart
MultiProvider(
  providers: [
    Provider<A>(create: (_) => A()),
    ChangeNotifierProvider<B>(
      create: (context) => B(
        Provider<A>.of(context, listen: false),
      ),
    ),
  ]
)
```

**Comment by chris-rutkowski** [comment]
@rrousselGit omg, thank you so much, why I was so blind.
