### ISSUE TITLE
Minimum Flutter version update is missing in changelog

### ISSUE THREAD

**Issue by totalerex** [rrousselGit/provider#524]
Currently Provider requires Flutter 1.16+ or so, but this requirement/dependency change is missing in chagelog.

Could you please add to changelog in the appropriate version description changes of Flutter version minimum required?

On existing projects which cannot be simply upgraded, sometimes it is really not easy to find right dependency version combination.

Thank you.

**Comment by rrousselGit** [comment]
versions < 4.1.0 should be fine
