### ISSUE TITLE
Error: Could not find the correct Provider<List<Prescriptions>> above this AddPrescription Widget

### ISSUE THREAD

**Issue by guneet446** [rrousselGit/provider#525]
**Describe the bug**
According to me, the Provider<List<Prescriptions>> is an ancestor to the AddPrescription Widget. However, it's not working

**To Reproduce**
This is my Stream Provider in Prescriptions on main page

class _PrescriptionsState extends State<Prescriptions> {

  @override
  Widget build(BuildContext context) {

    return StreamProvider<List<Prescription>>.value(
      value: DatabaseService().prescription,
      child: Scaffold(
        body: AddPrescription(),
      ),
    );
  }
}

This is my AddPrescriptions:

class _AddPrescriptionState extends State<AddPrescription> {

  File _image;

  @override
  Widget build(BuildContext context) {

    final prescriptions = Provider.of<List<Prescriptions>>(context);
    prescriptions.forEach((prescription) {
      print('prescription: $prescription');
    });

    return Scaffold(
      appBar: AppBar(title: Text('Prescriptions')),
      body: Column(
        children: <Widget>[
          RaisedButton.icon(
            label: _image == null ? Text('Add a new prescription') : Text(
                'Prescription added'),
            icon: Icon(Icons.add_a_photo),
            onPressed: _getImage,
          ),
          Container(
            child: Image.file(
              _image,
              height: 300,
              width: 300,
            ),
          ),
        ],
      ),
      drawer: Drawer(
        // Add a ListView to the drawer. This ensures the user can scroll
        // through the options in the drawer if there isn't enough vertical
        // space to fit everything.
        child: ListView(
          // Important: Remove any padding from the ListView.
          padding: EdgeInsets.zero,
          children: <Widget>[
            Container(
              height: 100.0,
              child: DrawerHeader(
                child: Text(
                  'At your service',
                  style: TextStyle(fontSize: 40.0),
                ),
                decoration: BoxDecoration(
                  color: Colors.blue,
                ),
              ),
            ),
            ListTile(
              title: Text('Home'),
              onTap: () {
                Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => MyHomePage()));
              },
            ),
            ListTile(
              title: Text('Medicines'),
              onTap: () {
                Navigator.of(context)
                    .push(MaterialPageRoute(builder: (context) => Medicines()));
              },
            ),
            ListTile(
              title: Text('Reminders'),
              onTap: () {
                Navigator.of(context)
                    .push(MaterialPageRoute(builder: (context) => Reminders()));
              },
            ),
            ListTile(
              title: Text('Blood Pressure'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => BloodPressure()));
              },
            ),
            ListTile(
              title: Text('Sugar'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.of(context)
                    .push(MaterialPageRoute(builder: (context) => Sugar()));
              },
            ),
            ListTile(
              title: Text('Contacts'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer

                Navigator.pop(context);
              },
            ),
            ListTile(
              title: Text('House Help'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.pop(context);
              },
            ),
            ListTile(
              title: Text('My Account'),
              onTap: () {
                Navigator.of(context)
                    .push(MaterialPageRoute(builder: (context) => MyAccount()));
              },
            ),
          ],
        ),
      ),
    );
  }

    Future _getImage() async {
      //PickedFile image = await _picker.getImage(source: ImageSource.gallery);
      File image = await ImagePicker.pickImage(source: ImageSource.gallery);

      setState(() {
        _image = image;
        print('_image: $_image');
      });
    }
}

**Expected behavior**
I expect that Prescriptions is the ancestor of AddPrescriptions

**Comment by rrousselGit** [comment]
Have you tried moving your StreamProvider above MaterialApp

**Comment by rrousselGit** [comment]
I'll close this in the lack of a reply
