### ISSUE TITLE
Question about future

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [rrousselGit/provider#528]
Sorry for the dumb question, but whats the difference between using FutureProvider, and just a normal FutureBuilder?

**Comment by rrousselGit** [comment]
It's purely a syntax difference

**Comment by diego-lipinski-de-castro** [comment]
Oh ok, I was quite dumbfounded, because future builder still has the feature that it knows when it is loading, has error, and was successful, so I found myself in a situation where using it was better than using the FutureProvider, thanks for the answer
