### ISSUE TITLE
The name 'BuildContext' is defined in the libraries 'package:flutter/src/widgets/framework.dart' and 'package:provider/src/provider.dart

### ISSUE THREAD

**Issue by denis-taranenko-windmill** [rrousselGit/provider#529]
I updated the version of the provider package to ^4.3.2+1. After that, I see the linter exception, which says "The name 'BuildContext' is defined in the libraries 'package:flutter/src/widgets/framework.dart' and 'package:provider/src/provider.dart (via package:provider/provider.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports."

Can you help me to understand where I made a mistake?

Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by denis-taranenko-windmill** [comment]
The problem was in linter, sorry.

**Comment by divan** [comment]
@denis-taranenko-windmill  can you give more information on the linter problem? I started to see this error message as well and not sure how to handle that.
