### ISSUE TITLE
dispose keyword provided in Provider but not in FutureProvider

### ISSUE THREAD

**Issue by Gerrel** [rrousselGit/provider#530]
My problem is that I need to be able to dispose a FutureProvider.

In Provider we can use an argument dispose, but it is not available in FutureProvider.
This can be added?

**Comment by Gerrel** [comment]
Just adding the parameter PR is enough?

**Comment by rrousselGit** [comment]
I don't mind, but are you sure that this will satisfy your need?

**Comment by Gerrel** [comment]
Will check next week if it works like I expect it will... and will add a test for it.

**Comment by Gerrel** [comment]
Indeed I just need a ChangeNotifier class
