### ISSUE TITLE
A builder variant that support the re-use of a list of children?

### ISSUE THREAD

**Issue by znjameswu** [rrousselGit/provider#533]
Currently this package employed the design pattern of providing `child` parameter within `builder` function to reuse the child widget that doesn't depend on the state.

This design pattern is sufficient for the most of Flutter widgets. However, I believe Provider package faces different use cases compared to them. Sometimes the widgets that we want to reuse are more than one, so they can't fit into one `child` parameter.

## Proposal
Add apis to enable `Consumer`/`Selector` variant that use a different type of `builder` signature. Something like
```dart
ConsumerReuseList<A>(
  children: [Text('A')],
  builder: (context, value, children) => ...,
),
```

The implementation may be as simple to just provide `ConsumerReuseList` as a function wrapper over `Consumer`, wrap the `children` parameter inside a `Column`, and unwrap `Column` in the `builder`.

This proposal might be too trivial to merge, but it may be beneficial for a new design pattern.

**Comment by rrousselGit** [comment]
You don't really need a new widget for this.

You can do:

```dart
final first = Text("foo");
final second = Text("bar");

return Consumer<A>(
  builder: (context, a, _) {
    // todo: use first and second here
 } 
)

**Comment by znjameswu** [comment]
> You don't really need a new widget for this.
> 
> You can do:
> 
> ```dart
> final first = Text("foo");
> final second = Text("bar");
> 
> return Consumer<A>(
>   builder: (context, a, _) {
>     // todo: use first and second here
>  } 
> ) 
> ```

In this way you still need to rebuild the Widget instance inside the `build` function every time. What I suggest is a sort of api parity between re-use a single widget and a list of widgets to support the same level of re-use.

**Comment by rrousselGit** [comment]
I don't understand what you mean.

This:

```dart
final first = Text("foo");

return Consumer<A>(
  builder: (context, a, _) {
    return first;
 } 
)  
```

Is strictly identical to:

```dart
return Consumer<A>(
  builder: (context, a, child) {
    return child;
  }, 
  child: Text('foo'), 
) 
```

**Comment by znjameswu** [comment]
> I don't understand what you mean.
> 
> This:
> 
> ```dart
> final first = Text("foo");
> 
> return Consumer<A>(
>   builder: (context, a, _) {
>     return first;
>  } 
> )  
> ```
> 
> Is strictly identical to:
> 
> ```dart
> return Consumer<A>(
>   builder: (context, a, child) {
>     return child;
>   }, 
>   child: Text('foo'), 
> ) 
> ```

Oh, my mistake. Yeah, they are indeed equivalent. I'll close this issue for now.
