### ISSUE TITLE
SelectorListener: provide a listener instead of a builder 

### ISSUE THREAD

**Issue by oussama-reguez** [rrousselGit/provider#537]
**Is your feature request related to a problem? Please describe.**
 I have a progress variable of type int stored in a viewModel(ChangeNotifier)  
 i use a Selector in a Statesless Widget. My problem is that i want to listen to the value change without returning a widget, i want for example to move to next page or display a toast.
    My current workaround is that i return an empty container but it's not right:

     Selector<RegistrationViewModel, int>(
      builder: (context, data, child) {
        pagerController.animateToPage(data ?? 0,
            curve: Curves.easeIn, duration: Duration(seconds: 1));

        return Container();
      },
      selector: (buildContext, registrationViewModel) =>
          registrationViewModel.progress,
    );

I cant use ProviderListener<RegistrationViewModel> because i want to listen for only the progress value change 
also i could have used stream but i wanted to use Selector approach ( i wanted to use the same viewmodel by many widgets and each widgets may listen to one particular variable)

**Describe the solution you'd like**
Provide a listener instead of a builder

**Comment by kira1752** [comment]
> **Is your feature request related to a problem? Please describe.**
> I have a progress variable of type int stored in a viewModel(ChangeNotifier)
> i use a Selector in a Statesless Widget. My problem is that i want to listen to the value change without returning a widget, i want for example to move to next page or display a toast.
> My current workaround is that i return an empty container but it's not right:
> 
> ```
>  Selector<RegistrationViewModel, int>(
>   builder: (context, data, child) {
>     pagerController.animateToPage(data ?? 0,
>         curve: Curves.easeIn, duration: Duration(seconds: 1));
> 
>     return Container();
>   },
>   selector: (buildContext, registrationViewModel) =>
>       registrationViewModel.progress,
> );
> ```
> 
> I cant use ProviderListener because i want to listen for only the progress value change
> also i could have used stream but i wanted to use Selector approach ( i wanted to use the same viewmodel by many widgets and each widgets may listen to one particular variable)
> 
> **Describe the solution you'd like**
> Provide a listener instead of a builder

Just use `context.read<MyProvider>()` or in your case:
```dart
pagerController.animateToPage(
  context.read<RegistrationViewModel>().progress ?? 0,
  curve: Curves.easeIn, duration: Duration(seconds: 1
));
```

**Comment by rrousselGit** [comment]
This issue is a broader "I want to react to changes on a provider to show modals/snackbars"

This is sadly not feasible.
