### ISSUE TITLE
Consider adding back StatefulProvider

### ISSUE THREAD

**Issue by bizz84** [rrousselGit/provider#54]
# Consider adding back `StatefulProvider`

Version 2.0.0 merges `StatefulProvider` into `Provider` and leads to a nicer API.

However, with this change some use cases are no longer supported.

For example, I have an email & password sign in form where the user can switch between 3 different modes: _sign in_, _register_, _reset password_:

![example](https://user-images.githubusercontent.com/153167/57452551-0cdeda80-725c-11e9-9ab6-db5f746106f3.png)

The logic for updating the state is handled inside a bloc, and I use a `StreamBuilder` to update the UI.

When the system keyboard appears, the entire page is rebuilt.

And with `StatefulProvider` everything works fine, because the bloc is not created again when the keyboard appears (this is expected, as a `StatefulWidget`'s state is preserved when the parent is rebuilt).

However, this doesn't work with `provider: 2.0.0`, because when the keyboard appears the entire bloc is rebuilt and the UI is rebuilt with the **initial** state rather than the **previous** state.

This leads to some unexpected behaviour where the form state changes when I start typing on a text field:

![email-password-provider](https://user-images.githubusercontent.com/153167/57452570-15371580-725c-11e9-9c76-fa7900cefbfe.gif)

This is just an example, but I have a more complex app with a lot of nested `StatefulProvider`s. And I can see how rebuilds in parent widgets would cause a lot of problems, as my blocs would be re-created and their state reset.

Ultimately the problem is that we need a `Provider` that inherits from `StatefulWidget` rather than `InheritedWidget`, so that the value/bloc is created in `initState()` and the state is preserved when a parent widget is rebuilt.

**Comment by bizz84** [comment]
Some more context.

I instrumented my example code to track what gets rebuilt. I have two versions for comparison.
### Version 1. Creating bloc inside my widget's `initState()` - `Provider` not used

This works correctly:

Console log:

```
-- Initial page load
flutter: EmailPasswordSignInBloc build
flutter: EmailPasswordSignInPage build
-- when keyboard appears
flutter: EmailPasswordSignInPage build
```

### Version 2. Creating bloc with `Provider`

```
  static Widget create(BuildContext context) {
    final AuthService auth = Provider.of<AuthService>(context, listen: false);
    final EmailPasswordSignInBloc bloc = EmailPasswordSignInBloc(auth: auth);
    return Provider<EmailPasswordSignInBloc>(
      builder: (BuildContext context) => bloc,
      dispose: (BuildContext context, EmailPasswordSignInBloc bloc) => bloc.dispose(),
      child: EmailPasswordSignInPage._(bloc: bloc),
    );
  }
```

Console log:

```
-- Initial page load
flutter: EmailPasswordSignInBloc build
flutter: EmailPasswordSignInPage build
-- when keyboard appears
flutter: EmailPasswordSignInBloc build
flutter: EmailPasswordSignInPage build
```

The provider version causes my bloc to be recreated, which is the problem.

**Comment by bizz84** [comment]
Clarified that I was setting this up incorrectly. The correct way of passing in blocs is to use `Consumer`:

```dart
  static Widget create(BuildContext context) {
    final AuthService auth = Provider.of<AuthService>(context, listen: false);
    return Provider<EmailPasswordSignInBloc>(
      builder: (BuildContext context) => EmailPasswordSignInBloc(auth: auth),
      dispose: (BuildContext context, EmailPasswordSignInBloc bloc) => bloc.dispose(),
      child: Consumer<EmailPasswordSignInBloc>(
        builder: (BuildContext context, EmailPasswordSignInBloc bloc, _) => EmailPasswordSignInPage._(bloc: bloc),
      ),
    );
  }
```

**Comment by rdehouss** [comment]
I'm facing the same issue (keyboard causing rebuild) but can't get it work with what @bizz84 said with the Consumer.
Later I use a FutureBuilder using a Future from my Bloc. If I don't use the FutureBuilder, the keyboard does not cause a rebuild. Same if I don't use a Provider but only a FutureBuilder.
I'm kinda lost, could you explain how to use Provider for Bloc to avoid a rebuild when the keyboard appears?
I'm in a StatefulWidget but instantiate everything in the build method. Thanks!
