### ISSUE TITLE
[Documentation] Add StateNotifier and StateNotifierProvider in Provider documentation

### ISSUE THREAD

**Issue by kira1752** [rrousselGit/provider#540]
We need to add/mention `StateNotifier` and `StateNotifierProvider` in Provider documentation so people know there is an alternative to `ChangeNotifier` and `ValueNotifier` that have better **Time Complexity**.

**Comment by rrousselGit** [comment]
ChangeNotifier is no-longer O(N^2) so it doesn't really matter

Considering `state_notifier` requires is a different take on managing state, I think it is fine not to mention it (as it could otherwise confuse people).
