### ISSUE TITLE
Cannot use Provider with named routes 

### ISSUE THREAD

**Issue by Slava96** [rrousselGit/provider#544]
**Describe the bug**
Create provider on root.
On MaterialApp use initialRoute with another routes.
And when i try to use this provider on one of the routes - i see an error that provider cannot be found.

**To Reproduce**

main.dart
`return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => Wishes(),
        )
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: appTheme(),
        initialRoute: "/",
        routes: appRoutes(),
      ),`

Root of one of routes - use provider inside Body component
`return Scaffold(
        appBar: MainAppBar(),
        body: Scrollbar(
          child: Padding(
            padding: EdgeInsets.symmetric(vertical: 10, horizontal: 15),
            child: SingleChildScrollView(
              child: Body(),
            ),
          ),
        ));
`

**Comment by rrousselGit** [comment]
What's the exception, and what is the code that triggers this exception?

Have you tried doing what the exception suggests?

**Comment by Slava96** [comment]
Error: Could not find the correct Provider<Wishes> above this Body Widget

This likely happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that Body is under your MultiProvider/Provider<Wishes>.
  This usually happen when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```

**Comment by rrousselGit** [comment]
What's the code that throw this exception?

**Comment by Slava96** [comment]
When the exception was thrown, this was the stack:
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:269:7)
#1      Provider.of (package:provider/src/provider.dart:221:30)
#2      Body.build (package:wishes_app/screens/wish_screen/components/body.dart:11:35)

This is line
var wishesProvider = Provider.of<Wishes>(context);

**Comment by rrousselGit** [comment]
I need the code that threw this exception.

**Comment by Slava96** [comment]
var wishesProvider = Provider.of<Wishes>(context)

This is code that threw an exception

**Comment by rrousselGit** [comment]
You need to specify the type of the value you want to obtain:

```dart
var wishes = Provider.of<Wishes>(context)
```

**Comment by Slava96** [comment]
OK, already done, but problem still stands

**Comment by rrousselGit** [comment]
I need more code.

**Comment by Slava96** [comment]
This is my main.dart
`
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => Wishes(),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: appTheme(),
        initialRoute: "/",
        routes: appRoutes(),
      ),
    );
  }
}`

This is my routes:
`Map<String, Widget Function(BuildContext)> appRoutes() {
  return {
    "/": (_) => ResultTestScreen(),
    "/home": (_) => HomeScreen(),
    "/wishes": (_) => WishScreen()
  };
}`

**Comment by Slava96** [comment]
This is my WishScreen:

```class WishScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: MainAppBar(),
      body: Padding(
        padding: EdgeInsets.symmetric(vertical: 10, horizontal: 15),
        child: Body(),
      ),
    );
  }
}```

**Comment by rrousselGit** [comment]
I need the code of Body

**Comment by Slava96** [comment]
```var textTheme = Theme.of(context).textTheme;

    var wishesProvider = Provider.of<Wishes>(context);
    var wishes = wishesProvider.wishes;

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
...

**Comment by Slava96** [comment]
When re-write code on main.dart - it works. 
Cannot find root of problem.

Thank you! Close this issue.
