### ISSUE TITLE
getting issue

### ISSUE THREAD

**Issue by RanaMusab** [rrousselGit/provider#548]
**Describe the bug**
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following ProviderNotFoundError was thrown building Consumer<dynamic>(dirty):
Error: Could not find the correct Provider<dynamic> above this Consumer<dynamic> Widget

To fix, please:

  * Ensure the Provider<dynamic> is an ancestor to this Consumer<dynamic> Widget
  * Provide types to Provider<dynamic>
  * Provide types to Consumer<dynamic>
  * Provide types to Provider.of<dynamic>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

If none of these solutions work, please file a bug at:
https://github.com/rrousselGit/provider/issues

The relevant error-causing widget was: 
  Consumer<dynamic> file:///C:/Users/Rana%20Musab/AndroidStudioProjects/flutter_app/theme_app/lib/main.dart:19:14
When the exception was thrown, this was the stack: 
#0      Provider.of (package:provider/src/provider.dart:264:7)
#1      Consumer.build (package:provider/src/consumer.dart:182:16)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
...
**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by rrousselGit** [comment]
Hello

Please complete the full template about how to reproduce the issue, otherwise I cannot help you.

**Comment by rrousselGit** [comment]
In the lack of an answer, I'll close this for now. Feel free to open a new issue with more information if you still have a problem

**Comment by RanaMusab** [comment]
How can i solve this issue?? Or how can i manage the csv file using Android
studio

**Comment by rrousselGit** [comment]
As said before, please fill the issue template correctly. Otherwise I cannot help you

**Comment by RanaMusab** [comment]
Ok i will fill it later Thanks for help me
