### ISSUE TITLE
Need ChangeNotifier performance Explanation

### ISSUE THREAD

**Issue by Tharindu-dart** [rrousselGit/provider#553]
Hello roussel , I using provider package for my flutter projects more than a year. And its working without any performance issue.
But recently ,I saw that getx readme says below statement. And I think above statement is like misunderstanding about ChangeNotifier.

> There are currently several state managers for Flutter. However, most of them involve using ChangeNotifier to update widgets and this is a bad and very bad approach to performance of medium or large applications. You can check in the official Flutter documentation that ChangeNotifier should be used with 1 or a maximum of 2 listeners, making it practically unusable for any application medium or large.

Can you give an explanation on that topic. ( ChangeNotifier can be used for both medium and large scale applications) .

Great work! Thanks!

**Comment by rrousselGit** [comment]
That statement is invalid.

You can use ChangeNotifier for large scale apps.

**Comment by Tharindu-dart** [comment]
@rrousselGit Thnx for your reply..
