### ISSUE TITLE
ProviderNotFoundException errernous toString() help?

### ISSUE THREAD

**Issue by Mereep** [rrousselGit/provider#554]
Hello,

I was getting hit by the `ProviderNotFoundException` when trying to do some `context.watch`. The last tip of the exceptions' message seemed to be the root of the problem:
```dart
  You used a `BuildContext` that is an ancestor of the provider you are trying to read.
  Make sure that $widgetType is under your MultiProvider/Provider<$valueType>.
  This usually happen when you are creating a provider and trying to read it immediately.
  For example, instead of:
  
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  
  consider using `builder` like so:
  
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
```

However, the `builder` argument is defined as `TransitionBuilder` which itself is of `typedef TransitionBuilder = Widget Function(BuildContext context, Widget child);`, i.e., doing like descriped in the help message throws type errors.

Also, even after replacing the snippet to
```dart
builder: (context, _) => ...
```
Provider thrown me that my watches are not inside build-Methods. (Oh, yes surely I tried also whatever other builders I found in and out and around the snippet).

The final solution was NOT to use `watch` and `builder` but rather wrap the `child` into a `Consumer` providing the Provider directly. What a journey. Maybe I really picked it up wrong. Its my first time using the package. But the error messages seemed only partially helpful ;)

**Comment by rrousselGit** [comment]
Closing this as it appears that your issue was resolved

**Comment by Mereep** [comment]
Is it? 

- When I search here in the repository, the `builder` argument is always defined as `TransitionBuilder`: https://github.com/rrousselGit/provider/search?q=transitionBuilder
-`TransitionBuilder` is defined as `typedef TransitionBuilder = Widget Function(BuildContext context, Widget child)`: https://github.com/rrousselGit/provider/search?q=transitionBuilder
- The error message still states using builder as `builder: (context) {` https://github.com/rrousselGit/provider/blob/c61ac2097619abbdc42debaa4f95b4c18c40b041/lib/src/provider.dart#L457

Can remember that hitting me these days. Did some commit fix that somehow else?
