### ISSUE TITLE
Provider is returning NULL in another page using Flutter

### ISSUE THREAD

**Issue by astrO1** [rrousselGit/provider#555]
I have a delivery app that in start have this, if the company has 2 restaurants, it will show buttons to the user select the restaurant that he wants to connect and if don't have 2 restaurants he goes directly to the page and connects to the first restaurant that he gets from API.

My provider only works on the screen to choose the restaurant and in my another don't I will show now:

This is the code from my **SPLASH SCREEN** to start the APP

      @override
      void initState() {
        super.initState();
        loadData();
      }
    
      void loadData() {
        int counter = 0;
        _con.progress.addListener(() {
          double progress = 0;
          _con.progress.value.values.forEach((_progress) {
            progress += _progress;
          });
          if (progress == 100) {
            try {
              counter++;
              if(counter == 2) {
                _con.iniApp();
              }
            } catch (e) {}
          }
        });
      }

And this Screen run this in the controller, that is simply calling the function by company

      iniApp() {
        if(ConfigApp.instance.data['company_id'] != '1') {
          listenForListOfRestaurants();
        } else {
          Navigator.of(context).pushReplacementNamed('/Restaurants');
        }
      }

Now I will talk about my screen that is working the **Navigator.of(context).pushReplacementNamed('/Restaurants');**. When the user goes to this Screen he chooses which restaurant he wants to connect and this is the widget that I build to show the then:

    _con.listOfRestaurant.length > 0
                    ? Column(
                        children: List.generate(_con.listOfRestaurant.length, (i) {
                          return Container(
                            width: double.infinity,
                            child: Center(
                              child: Container(
                                width: screenWidth * 0.8,
                                child: Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: <Widget>[
                                    Container(
                                      width: screenWidth * 0.8,
                                      child: RaisedButton(
                                        onPressed: () => _con.chooseRestaurant(
                                            _con.listOfRestaurant[i]),
                                        child: Text(
                                          _con.listOfRestaurant[i].name,
                                          style: TextStyle(
                                            fontSize: 16,
                                            letterSpacing: 1.3,
                                            color: ThemeColor.kYellow600,
                                          ),
                                        ),
                                        padding: EdgeInsets.symmetric(
                                          horizontal: 10.0,
                                          vertical: 12.0,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(30.0),
                                        ),
                                        color: ThemeColor.AppSecundaryColor,
                                        textColor: Colors.white,
                                        elevation: 5,
                                      ),
                                    ),
                                    SizedBox(
                                      height: screenHeight * 0.12,
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          );
                        }),
                      )

See this function **_con.chooseRestaurant** ? When the user press it I call this function:

    class RestaurantController extends ControllerMVC {
      Restaurant restaurant;
      RestaurantService restaurantService = new RestaurantService();
      List<Restaurant> listOfRestaurant = <Restaurant>[];
      List<Gallery> galleries = <Gallery>[];
      List<Food> foods = <Food>[];
      List<Food> trendingFoods = <Food>[];
      List<Food> featuredFoods = <Food>[];
      List<Review> reviews = <Review>[];
      GlobalKey<ScaffoldState> scaffoldKey;
    
      RestaurantController() {
        this.scaffoldKey = new GlobalKey<ScaffoldState>();
      }
    
      void chooseRestaurant(Restaurant restaurant) {
        restaurantService = Provider.of<RestaurantService>(context, listen: false);
        restaurantService.selectRestaurant(restaurant);
        Navigator.of(context).pushReplacementNamed('/Pages', arguments: 2);
      }

And this is working fine and on the other page, I have a test line to see if I get this variable restaurant and he gets the value with no problem.

The problem is now when the user doesn't need to choose which restaurant he wants to connect, that is **this listenForListOfRestaurants();** 

      listenForListOfRestaurants() async {    
        final restaurantService = Provider.of<RestaurantService>(context, listen: false);
        final Stream<List<Restaurant>> stream = await getAllRestaurants();
        await for (List<Restaurant> _restaurantList in stream) {
          restaurantService.selectRestaurant(_restaurantList[0]);
        }
        print(restaurantService.getRestaurant().name);
        Navigator.of(context).pushReplacementNamed('/Pages', arguments: 2);
      }

It is like the other but with a little difference that does a Stream to get the first restaurant and set directly on my provider and change the page.

When I do this, I ALWAYS get the value here **print(restaurantService.getRestaurant().name);** but in the new page I GET NULL in my test function from the other page, that is this:

    class HomeController extends ControllerMVC {
      RouteArgument routeArgument;
      RestaurantService restaurantService = new RestaurantService();
      List<Category> categories = <Category>[];
      List<Restaurant> topRestaurants = <Restaurant>[];
      List<Restaurant> popularRestaurants = <Restaurant>[];
      List<Review> recentReviews = <Review>[];
      List<Food> trendingFoods = <Food>[];
      List<Food> featuredFoods = <Food>[];
    
      HomeController();
    
      void iniHome() {    
        listenForFeaturedFoods();
        // listenForTopRestaurants();
        listenForTrendingFoods();
        listenForCategories();
        listenForPopularRestaurants();
        listenForRecentReviews();
      }
    
      Future<void> listenForFeaturedFoods() async {   
        restaurantService = Provider.of<RestaurantService>(context, listen: false);
        print(restaurantService.getRestaurant().name);
        /*
        final Stream<Food> stream = await getFeaturedFoodsOfRestaurant(
            restaurantService.getRestaurant().id);
        stream.listen((Food _food) {
          setState(() => featuredFoods.add(_food));
        }, onError: (a) {
          print(a);
        }, onDone: () {
          print(featuredFoods);
        });
        */
      }

Why in approach i get the value and in another don't? Can someone explain to me

**Comment by rrousselGit** [comment]
Sorry for the late reply

I'll close this as this sort of question does not belong to Github
Consider asking this on StackOverflow or a Slack group
