### ISSUE TITLE
Hiding Center Docked Floating Action Button using Consumer causes Bottom Navigation Bar to break

### ISSUE THREAD

**Issue by jtmuller5** [rrousselGit/provider#557]
**Describe the bug**
When I try to use a Consumer to determine the visibility of my center-docked Floating Action Button, I cannot hide it by returning null. The error says to use Container() instead but when I do that I get a craxy looking bottom nav bar.

<img width="173" alt="2020-10-18 14_13_29-Your Phone" src="https://user-images.githubusercontent.com/47997351/96376320-36d44600-114c-11eb-87d2-e1cc04096ea7.png">

**To Reproduce**
 floatingActionButton: Consumer<global.MapState>(
        builder: (context, map, child) => map.mapMode
            ? FloatingActionButton(
                backgroundColor: Theme.of(context).accentColor,
                onPressed: () {
                 // Stuff
                },
                tooltip: 'Increment',
                child: FaIcon(FontAwesomeIcons.eye),
              )
            : Container(),
      ),

**Expected behavior**
I would expect returning null here to just hide the Floating Action Button. Instead, I have to change the location of the Fab and show an invisible widget so it doesn't display.

**Comment by rrousselGit** [comment]
Consider moving the Consumer such that it wraps the Scaffold instead, then pass "null"

**Comment by rrousselGit** [comment]
In the lack of an answer, I'll close this for now. Feel free to open a new issue with more information if you still have a problem
