### ISSUE TITLE
MultiProvider have one Provider listen to another Provider?

### ISSUE THREAD

**Issue by dakamojo** [rrousselGit/provider#56]
What would be the best pattern for breaking a large Provider into two Providers, but still have one of them listen to changes on the other.  For example I want to have two Providers, one named User and one named Favorites.  If the User changes then the Favorites needs to reload and notify its own listeners.

**Comment by rrousselGit** [comment]
That's one of the use-cases this RFC is trying to solve https://github.com/rrousselGit/provider/issues/46

Go ahead and give your opinion!

**Comment by MarcinusX** [comment]
@rrousselGit
Would you recommend ProxyProvider (as soon as it gets merged and published) as a way to create business-logic components? I mean, does it make sense to create Provider with States, and then Proxy Provider which can do some network requests and business logic and change the State?

If not, could you propose some recommended workflow of such things like creating network calls using Providers? I know it's rather a vague question but I just can't understand where to put business logic when using provider... Or maybe just to the state object that is being provided?

**Comment by rrousselGit** [comment]
There's no guarantee that it gets merged.

ProxyProvider is not meant to **directly** do data fetching.
But it can definitely be used to trigger some events, which leads to data fetching. 


There's an example in the opened PR for ProxyProvider in the example folder using 'ChangeNotifier`.
A similar logic can be done with both BLoC and Mobx relatively easily.


Is this what you had in mind?

**Comment by MarcinusX** [comment]
Thanks. Kind of that's what I meant but I looked again on your examples and find your initial example marked as `not good` as a point where I should start (assuming I have non-disposable state objects):
```
Configuration configuration;

Widget build(BuildContext context) {
  return MultiProvider(
    providers: [
      Provider.value(value: configuration),
      Provider(builder: (_) => AuthentificationService(configuration)),
    ],
    child: MaterialApp(...),
  );
}
```
Or am I wrong and I should never ever do it like this?

**Comment by rrousselGit** [comment]
That's exactly what you should _not_ do.

Instead with ProxyProvider you can:

```dart
MultiProvider(
  providers: [
    Provider(builder: (_) => Configuration()), 
    ProxyProvider<Configuration, Auth>(builder: (_, confs, _) => Auth(confs)), 
  ]
  child:... 
)
```


This makes each provider independent from each other without ever using `listen: false`

**Comment by MarcinusX** [comment]
The thing is I need to start it now and as you said, there is no guarantee that it gets merged. :(

**Comment by rrousselGit** [comment]
Definitely, go ahead!
The current implementation has quite a bit of tests, it shouldn't break that easily. 

Also feel free to comment on #46, by explaining your use case and why you think ProxyProvider helps. 


I'll test the current implementation further by making more complex examples using it.

**Comment by MarcinusX** [comment]
Thank you! I will play with it and share any thoughts :)
