### ISSUE TITLE
what is real meaning of listen on provider?

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/provider#563]
what is this meaning of these two?

**listen false** `ValueNotifier<Book> bookNotifier = Provider.of<ValueNotifier<Book>>(context,listen: false);`  and  

 **listen: true** `ValueNotifier<Book> bookNotifier = Provider.of<ValueNotifier<Book>>(context, listen: true);`

Both are changing (rebuild UI) when I am changing the value. (I didn't use together)
` bookNotifier.value = bookModel;`

**Comment by rrousselGit** [comment]
`listen: false` will not cause widgets to rebuild when the value changes.

If your widgets still rebuild with `listen: false`, then it is likely that even without the call to `Provider.of`, your widget would still rebuild.
This can happen if the parent of your widget rebuilds too
