### ISSUE TITLE
ValueNotifier not listen when change object element

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/provider#565]
I try to change the object element. but the valueNotifier is not changing. It's changing when I hot reload my page.

**Page A** 

**onMyBuild**
 `   ValueNotifier<AddressBook> addressBookNotifier = Provider.of<ValueNotifier<AddressBook>>(context, listen: true);
`

**Page B**
**onPressed event**

```
addressBookNotifier.value.deliveryMobileNo = mobileNoController.text;
addressBookNotifier.value.deliveryUserName = '${firstNameController.text} ${lastNameController.text}';
//addressBookNotifier.value = addressBookNotifier.value; - I added this, no luck
Navigator.pop(context);//back to Page A
```

currently, I am using setState after changing values.

```
addressBookNotifier.value.deliveryMobileNo = mobileNoController.text;
addressBookNotifier.value.deliveryUserName = '${firstNameController.text} ${lastNameController.text}';
//addressBookNotifier.value = addressBookNotifier.value;
widget.refreshFunction();
Navigator.pop(context);//back to Page A

```

Refresh Function on Page A

```
void refreshFunction(){
setState(({}));
}
```

**Comment by rrousselGit** [comment]
Could you give an example that can be executed? 

It is really hard to understand what is happening from these small broken down snippets

**Comment by rrousselGit** [comment]
I will close this in the lack of an answer.
