### ISSUE TITLE
Incorrect exception reported when using `context.watch` inside an IIF

### ISSUE THREAD

**Issue by narcodico** [rrousselGit/provider#572]
**Describe the bug**
An incorrect exception is thrown when calling `context.watch`/`context.select` using an Immediately Invoked Function inside `build` methods. The exception is pointing out incorrect usage of `context.watch`/`context.select` and is advising to replace it with `context.read`.

**Expected behavior**
`context.watch`/`context.select` should both work inside an IIF.

**Comment by rrousselGit** [comment]
Sorry for the delay

Could you share some code to reproduce the error?

**Comment by rrousselGit** [comment]
Closing as this was most likely "fixed" when asserts inside watch/select/read got removed
