### ISSUE TITLE
Please optimize the document

### ISSUE THREAD

**Issue by tmxdyf** [rrousselGit/provider#575]
This usage document is raw and difficult to understand

**Comment by rrousselGit** [comment]
Do you have any specific recommendation and pain point?

**Comment by bogdanmarinescu** [comment]
@tmxdyf Don't get your hopes up. You either read the whole provider code in order to understand this library, or you blunder your way into a pseudo working result.

**Comment by rrousselGit** [comment]
Rather than being overly negative about something you get for free, make suggestions on how to improve the doc or open pull requests.

**Comment by bogdanmarinescu** [comment]
A lot of beginners pick-up provider right away, most of them don't really know how flutter works. Maybe the community should write the provider docs as tutorial, with real world examples, pitfalls, tips and references to the official documentation. I don't want to be negative, I really appreciate your work.

**Comment by tmxdyf** [comment]
I'm sorry.I have learned Provider, It's really great.

**Comment by tmxdyf** [comment]
I'm sorry, I have learned Provider, It's really great. Thanks to the developers.
