### ISSUE TITLE
Description on https://pub.dev/packages/provider/example should be corrected

### ISSUE THREAD

**Issue by asavchuk** [rrousselGit/provider#578]
**Describe the bug**
In the example on [https://pub.dev/packages/provider/example](https://pub.dev/packages/provider/example) the description should be corrected. 
It was written
/// Calls `context.watch` to make [MyHomePage] rebuild when [Counter] changes.

**Expected behavior**
Should be corrected like
/// Calls `context.watch` to make [**Count**] rebuild when [Counter] changes.

_p.s. didn't find how to correct labels here for the issue_

**Comment by Abhishek01039** [comment]
It has been resolved.
