### ISSUE TITLE
pub get failed (server unavailable)

### ISSUE THREAD

**Issue by 3rigx** [rrousselGit/provider#580]
Got socket error trying to find package provider at https://pub.dartlang.org.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by Abhishek01039** [comment]
@3rigx 
how you import provider in `pubspec` file?
Thanks

**Comment by rrousselGit** [comment]
This is likely you not having a stable connection at that time, or maybe a VPN preventing the connection

In any case, this isn't something I can fix. If you still have a problem, consider raising an issue on Dart's repository instead
