### ISSUE TITLE
Remove the assertions related to context.watch/context.read

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/provider#585]
It appears that the assertions in `context.watch`/`context.read` are a source of frustration for many, and of little help

Instead of asserts, what we could do is implement a custom linter. That means using `read` inside `build` and the other things prevented by the asserts would "work", but if you are using the linter, you would get a warning

This is probably a better compromise as it allows people to opt-in/opt-out of this behavior

**Comment by DanMossa** [comment]
I was curious what kind of linter suggest in order to let me know when I'm not using `watch`/`read` the "intended" way?

**Comment by rrousselGit** [comment]
The custom linter doesn't exists yet
