### ISSUE TITLE
Weird ProviderNotFoundException

### ISSUE THREAD

**Issue by rvit34** [rrousselGit/provider#586]
**Describe the bug**
I've created a tiny example of code using providers according to your official example but got ProviderNotFoundException.
Actually, I've no clue it's a bug or my fault. So I decided to post it here.

**To Reproduce**

Just run the code below:
```
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => ColorProvider())
    ],
    child: AnimatedPage(),
  )
);

class AnimatedPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(
              "Homework provider",
               style: TextStyle(color: context.watch<ColorProvider>().color),
          ),
          centerTitle: true,
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              AnimatedContainer(
                width: 100,
                height: 100,
                duration: Duration(seconds: 5),
                color: context.watch<ColorProvider>().color,
              ),
              Switch(value: false, onChanged: (_) => context.read<ColorProvider>().tougleSwitch()),
            ],
          ),
        ),
      ),
    );
  }
}

class ColorProvider with ChangeNotifier {
  
  static final random = Random(); 
  
  var _color = Colors.black;
  
  Color get color => _color;
  
  void tougleSwitch() {
    _color = Color(random.nextInt(255));
    notifyListeners();
  }
}

```

What I get is:

Error: Could not find the correct Provider<ColorHolder> above this AnimatedPage Widget

```
When the exception was thrown, this was the stack: 
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:329:7)
#1      Provider.of (package:provider/src/provider.dart:281:30)
#2      WatchContext.watch (package:provider/src/provider.dart:653:21)
#3      AnimatedPage.build (package:layout/AnimatedContainer.dart:23:48)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
```

**Versions**
Dart 2.10.4
Flutter 1.22.4
Provider 4.3.2+3

**Expected behavior**
In my opinion, the provider should be found.

**Comment by rrousselGit** [comment]
Are you by any change using non-nullable types?

**Comment by rrousselGit** [comment]
Oops ignore my previous comment, I didn't see that you posted the versions you use

**Comment by rrousselGit** [comment]
I tried your example and it works for me.

Are you sure that your example throws an exception for you, or are you running a slightly modified version?

**Comment by rvit34** [comment]
I use exactly the same version which is provided in the first comment. I've recorded a screencast. See below:

![bug](https://user-images.githubusercontent.com/20579813/102021620-65604d00-3d9a-11eb-9908-12a634efc201.gif)

**Comment by rrousselGit** [comment]
That's problematic as I still fail to reproduce it, so I'm not sure how to help.

Maybe something is wrong with your environment? Are you sure you didn't edit the source code of Flutter or your local download of Provider by mistake?

**Comment by rrousselGit** [comment]
Closing as the issue appears to be stale
