### ISSUE TITLE
Could not find the correct provider

### ISSUE THREAD

**Issue by bambinoua** [rrousselGit/provider#588]
I have a simple code:
```dart
ValueNotifier<Controller> controllerNotifier;

@override
void initState() {
  super.initState();
  controllerNotifier = ValueNotifier(_getController());
}

@override
void build(BuildContext context) {
  return ValueListenableProvider.value(
    value: controllerNotifier,
    builder: (_, controller, __) {
      return controller != null ? _controllerBuilder() : IconizedMessage();
    }
  );
}
```
This code worked find using version 4.3.2+2 until I updated the provider to latest version 4.3.2+3 where `ValueListenableProvider` marked as deprecated. It is naturally that I changed deprecated `ValueListenableProvider` to `ChangeNotifierProvider.value` and now I get the error:

`Could not find correct Provider<Controller> above this Consumer<Controller>`

I changed `ChangeNotifierProvider.value` to `ListenableProvider.value` and nothing changed. So now I have a crash in my app and it looks like a bug...

**Comment by bambinoua** [comment]
If I restore version `4.3.2+2` the above written code become working. So... this is a bug.

**Comment by rrousselGit** [comment]
There is no difference between +3 and +2 besides the `@deprecated` annotation


But you can keep using `ValueListenableProvider.value`. I will remove the depreciation notice and keep it only for the default constructor

**Comment by bambinoua** [comment]
> There is no difference between +3 and +2 besides the `@deprecated` annotation
> 
I understand but the question is why when I change `ValueListenableProvider.value` to `ListenableProvider.value` or `ChangeNotifierProvider.value` I will get crash (provider is not found)? As I understant `ValueListenableProvider.value` is a partial case of `ListenableProvider.value`

**Comment by rrousselGit** [comment]
With `ListenableProvider`/`ChangeNotifierProvider`, when exposing a `ValueNotifier<int>`, you have to watch it with `context.watch<ValueNotifier<int>>`. With `ValueListenableProvider`, you have instead `context.watch<int>`

**Comment by bambinoua** [comment]
This is the case why `ValueListenableProvider` is still required.

**Comment by bambinoua** [comment]
> But you can keep using ValueListenableProvider.value. I will remove the depreciation notice and keep it only for the default constructor.

Is it possible to remove `@deprecated` from `ValueListenableProvider` (as promissed) for version 4.3.x?
