### ISSUE TITLE
Portuguese translation doesn't match the original

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/provider#590]
The portuguese translation starts with:

```
Uma mistura entre injeção de dependência (ID) e gerenciamento de estado, feito com widgets para widgets.

O seu propósito é usar widgets para ID/gerenciamento de estado ao invés de somente classes do Dart como Stream. A razão é que, widgets são muito simples mas ainda assim robustos e escaláveis.
 ```

Which translates to:

```
A mixture between dependency injection (DI) and state management, made with widgets for widgets.

Its purpose is to use widgets for DI/state management, instead of just Dart classes such as Stream. The reason being widgets are a lot simpler, but still robust and scalable.
```

As far as I know Provider is a package for DI, while state management is a plus, but not the core function of this library. I remember reading Remi saying this multiple times, so the Portuguese translation should match the english one word by word as much as possible.

**Comment by rrousselGit** [comment]
The portugese translation is out of date. Unfortunately I do not speak portugese.

**Comment by idkq** [comment]
https://github.com/rrousselGit/provider/pull/609
