### ISSUE TITLE
The name 'BuildContext' is defined in the libraries

### ISSUE THREAD

**Issue by SugyoIn-LBSTech** [rrousselGit/provider#593]
**Describe the bug**
After upgrade provider to v4.3.2+3. I got syntax error below.

The name 'BuildContext' is defined in the libraries 'package:flutter/src/widgets/framework.dart' and 'package:provider/src/provider.dart (via package:provider/provider.dart)'.

It can be solved 'hide' or 'as' but I think it's weird to do that.

```
flutter --version
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by rrousselGit** [comment]
It may be that your dart version is outdated and does not support extension methods yet

**Comment by Faiizii** [comment]
facing the same issue and also unable to resolve `context.watch...` and `context.read...`. I followed the example program from pub.dev

**Comment by SugyoIn-LBSTech** [comment]
I don't know why but it solved. No version changes for flutter, dart, provider and pubspec sdk.
I think this bug comes from VSCode or dart extension.

**Comment by Faiizii** [comment]
I am using android studio

**Comment by rrousselGit** [comment]
@Faiizii make sure to import provider and have a Dart version that supports extension and the latest provider version possible.

**Comment by Faiizii** [comment]
I am using the latest provider version `4.3.2+3`, and dart support extension since 2.7. I am using stable version of flutter with dart version 2.10.

**Comment by wujek-srujek** [comment]
I've seen this error many times. What fixes it for me is: `flutter clean`, `flutter pub get` and reload/restart the IDE.

**Comment by GanongLS** [comment]
it should be closed then
