### ISSUE TITLE
StreamProvider does not call `create` on builder

### ISSUE THREAD

**Issue by erf** [rrousselGit/provider#594]
**Describe the bug**

I use a `StreamProvider` which builds a `StreamProivder` with the value from it, but the child `StreamProvider` won't rebuild, even if i set `updateShouldNotify`. (My original code was much more complex but i simplified it down to this)

**To Reproduce**

Example:

``` Dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  runApp(MyApp());
}

class Item {}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<User>(
      create: (context) => FirebaseAuth.instance.userChanges(),
      builder: (context, widget) {
        final user = context.watch<User>();
        print('User changed -> ${user?.uid ?? 'null'}');
        return StreamProvider<List<Item>>(
          updateShouldNotify: (prev, curr) => true,
          create: (context) {
            // THIS IS NOT CALLED !!!
            print('Create StreamProvider<List<Item>> -> ${user?.uid ?? 'null'}');
            return Stream.value([]);
          },
          child: Builder(
            builder: (context) {
              return MaterialApp(
                home: Builder(
                  builder: (context) {
                    final user = context.watch<User>();
                    final items = context.watch<List<Item>>();
                    return Container(color: Colors.blue);
                  },
                ),
              );
            },
          ),
        );
      },
    );
  }
}

```

This is the output:

```
flutter: User changed -> null
flutter: Create StreamProvider<List<Item>> -> null
2 flutter: User changed -> N56hgBxA75O1GQbKXXufY27cOLBx
```

**Expected behavior**

I would expect `StreamProvider<List<Item>>`s `create` method to be called on new `User` values, so i can return a new Stream based on the user Id, but this is never called. If i add a unique key to the child `StreamProvider`, it is rebuild as i want, but then i experienced "flashing" as the whole app was rebuilt it seemed.

NOTE 1: In my original example, i had alot more state and was nesting multiple MultiProviders with StreamProivders in it.

NOTE 2: I'm looking into River  Pod now, maybe it is easier to solve this there?

Thanks for any help on this!

**Comment by rrousselGit** [comment]
`create` is called only once. It doesn't know that the value created depends on the user and needs to be rebuilt when the user changes.

> NOTE 2: I'm looking into River Pod now, maybe it is easier to solve this there?


It'd definitely be easier.

You could have:

```dart
final userProvider = StreamProvider<User>(...);

final itemsProvider = StreamProvider<List<Item>>((ref) {
  final user = ref.watch(userProvider);

  return Stream.value([]);
});
```

this would automatically recreate the items list whenever the user changes

**Comment by erf** [comment]
Ah, i see! I will definitely switch to "River Pod" now. Thank you for making it, looks awesome.

Out of curiosity, if you have time, how would you solve this using Provider?

Feel free to close this.

**Comment by rrousselGit** [comment]
Using StreamProvider to solve this in provider is difficult.

At the moment Provider doesn't support nicely such use-case.
