### ISSUE TITLE
Logout after data consumed in dashboard page issue

### ISSUE THREAD

**Issue by ashishoffice** [rrousselGit/provider#601]
I have decleared in multiprovider and added dashboardprovider . I have invoked  in multiprovider. 
Logout after data consumed issue .. 
 I have disposed all provider. Then again issue conumed the data after logout.

**Comment by rrousselGit** [comment]
Hello!

For help request, I would suggest asking on stackoverflow or on Riverpod's Discord, as Github is not the proper place.
