### ISSUE TITLE
Provider.of<SomeProvider>(context, listen: false).SomeAPICall()

### ISSUE THREAD

**Issue by codememory101** [rrousselGit/provider#61]
Good Day Remi,

Could you please explain how to use the provider in initState, i have tried many way and all have failed except doing below

 #`  Future.delayed(Duration.zero, () {
      Provider.of<PrincipalProvider>(context, listen: false).fetchPrincipals();
    });`

Is there a better way to implement it?

Also, the code worked perfectly in the scoped_model 

`ScopedModel.of<PrincipalProvider>(context).fetchPrincipals();`

I want to fully embrace the provider model, but I just need some clarity.

**Comment by rrousselGit** [comment]
the following is enough:

```dart
Provider.of<PrincipalProvider>(context, listen: false).fetchPrincipals();
```

**Comment by codememory101** [comment]
Just tried, however, I get the error below,



`flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for ProductProvider:
flutter: setState() or markNeedsBuild() called during build.
flutter: This ChangeNotifierProvider<ProductProvider> widget cannot be marked as needing to build because the
flutter: framework is already in the process of building widgets. A widget can be marked as needing to be
flutter: built during the build phase only if one of its ancestors is currently building. This exception is
flutter: allowed because the framework builds parent widgets before children, which means a dirty descendant
flutter: will always be built. Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   ChangeNotifierProvider<ProductProvider>(state: _ListenableProviderState<ProductProvider>#d5b44)
flutter: The widget which was currently being built when the offending call was made was:
flutter:   Builder`


Also, this is code for fetchPrincipal... when it throw the error.

`  Future fetchProducts() async {
    _isLoading = true;
    notifyListeners();

    await ProductDbHelper.fetchProducts().then((products) {
      _products = products;
      _initProducts = _products.map((product) => product).toList();
    });
    _isLoading = false;
    notifyListeners();
  }`

However when using below, no error. Can you explain why? N.B there is only one notifyListeners

` Future fetchProducts() async {
    _isLoading = true;
    // notifyListeners();

    await ProductDbHelper.fetchProducts().then((products) {
      _products = products;
      _initProducts = _products.map((product) => product).toList();
    });
    _isLoading = false;
    notifyListeners();
  }`

**Comment by rrousselGit** [comment]
It seems that you are synchronously modifying the provided value from its descendant. 
That is a no-go.

Your application must work such that your `initState` does not call a `notifyListener`.

**Comment by Klerith** [comment]
@rrousselGit You are a genius man, Thank you so much, I was having some issue similar to this one. I figure out my mistake.
