### ISSUE TITLE
initialData must be optional in StreamProvider

### ISSUE THREAD

**Issue by Sameerkash** [rrousselGit/provider#611]
**Describe the bug**
StreamProvider API now includes `initalData` as a `required` argument, this wasn't the case before. 
Also thinking about this doesn't seem like the best thing as the user should be allowed to decide if the `initalData` needs to be given or not. 

That's what the docs say too
```
/// `initialData` determines the value exposed until the [Stream] emits a value.
/// If omitted, defaults to `null`.
```

**To Reproduce**
Use `StreamProvider`,
```
StreamProvider<ThemeModel>(
        lazy: false,
        initialData: , // Expected an identifier.dart(missing_identifier)
        create: (context) => themeManager.themesStream,
)
```

**Expected behavior**
`initialData`  in `StreamProvider` must be nullable.

**Comment by rrousselGit** [comment]
The doc is just outdated

Making it optional is not feasible.
`null` is not a valid value for `ThemeModel`.
