### ISSUE TITLE
Error: Could not find the correct Provider<CategoryMeal> above this CategoryMealItem Widget

### ISSUE THREAD

**Issue by Zulqarnain97** [rrousselGit/provider#613]
Error: Could not find the correct Provider<CategoryMeal> above this CategoryMealItem Widget

Can AnyOne Please help in solving this error?
[categoryMeal.txt](https://github.com/rrousselGit/provider/files/6067077/categoryMeal.txt)
[categoryMealItem.txt](https://github.com/rrousselGit/provider/files/6067078/categoryMealItem.txt)
[categoryMeals.txt](https://github.com/rrousselGit/provider/files/6067079/categoryMeals.txt)
[categoryMealScreen.txt](https://github.com/rrousselGit/provider/files/6067080/categoryMealScreen.txt)
[main.txt](https://github.com/rrousselGit/provider/files/6067081/main.txt)

**Comment by nikitadol** [comment]
Hi @Zulqarnain97 
I would like to help you, but your code won't run

**Comment by Zulqarnain97** [comment]
I found the solution, This error occurred due to a missing import.
