### ISSUE TITLE
Unhandled Exception: Error: Could not find the correct Provider<Database> above this SliverList Widget

### ISSUE THREAD

**Issue by Fernando555** [rrousselGit/provider#615]
so i have a question i got that error when i try to acces another page,i underatsn it have to do with the context but i do now know how to fix it.so what im trying to do is im trying to get to another page using the ontap widget, i can move just fine to antoher page i have created but when i try to move to this job entries it give me this error which i do not know how to resolve please help

here the first page: 
Widget _buildContents(BuildContext context) {
    final database = Provider.of<Database>(context, listen: false);
    return StreamBuilder<List<Job>>(
      stream: database.jobsStream(),
      builder: (context, snapshot) {
        return ListItemsBuilder<Job>(
          snapshot: snapshot,
          itemBuilder: (context, job) => Dismissible(
            key: Key('job-${job.id}'),
            background: Container(color: Colors.red),
            direction: DismissDirection.endToStart,
            onDismissed: (direction) => _delete(context, job),
            child: JobListTile(
              job: job,
              onTap: () => JobEntriesPage.show(context, job), //bisa buat JobEntriesPage.show(context, job); cuman masi error
            ),
          ),
        );
      },
    );
  }

here's the second page i want to go to(the job entries page) from the ontap:

class JobEntriesPage extends StatelessWidget {
  const JobEntriesPage({@required this.database, @required this.job});
  final Database database;
  final Job job;

  static Future<void> show(BuildContext context, Job job) async {
    final database = Provider.of<Database>(context, listen: false);
    await Navigator.of(context).push(
      MaterialPageRoute(
        fullscreenDialog: false,
        builder: (context) => JobEntriesPage(database: database, job: job),
      ),
    );
  }

  Future<void> _deleteEntry(BuildContext context, Entry entry) async {
    try {
      await database.deleteEntry(entry);
    } on FirebaseException catch (e) {
      showExceptionAlertDialog(
        context,
        title: 'Operation failed',
        exception: e,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 2.0,
        title: Text(job.name),
        actions: <Widget>[
          FlatButton(
            child: Text(
              'Edit',
              style: TextStyle(fontSize: 18.0, color: Colors.white),
            ),
            onPressed: () => EditJobPage.show(context, job: job),
          ),
        ],
      ),
      body: _buildContent(context, job),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () =>
            EntryPage.show(context: context, database: database, job: job),
      ),
    );
  }

  Widget _buildContent(BuildContext context, Job job) {
    return StreamBuilder<List<Entry>>(
      stream: database.entriesStream(job: job),
      builder: (context, snapshot) {
        return ListItemsBuilder<Entry>(
          snapshot: snapshot,
          itemBuilder: (context, entry) {
            return DismissibleEntryListItem(
              key: Key('entry-${entry.id}'),
              entry: entry,
              job: job,
              onDismissed: () => _deleteEntry(context, entry),
              onTap: () => EntryPage.show(
                context: context,
                database: database,
                job: job,
                entry: entry,
              ),
            );
          },
        );
      },
    );
  }
}

**Comment by miriam-z** [comment]
Hello is the similar to issue #620

**Comment by rrousselGit** [comment]
> so i have a question i got that error when i try to acces another page,i underatsn it have to do with the context but i do now know how to fix it.so what im trying to do is im trying to get to another page using the ontap widget, i can move just fine to antoher page i have created but when i try to move to this job entries it give me this error which i do not know how to resolve please help



It looks like your provider is scoped within a page, hence why other pages cannot access this provider.

Try moving the provider above MaterialApp.

In any case, the error message should explain what is going wrong. If there's something that you do not explain with the error message, please mentioned it so that we can improve it.

**Comment by NamanShergill** [comment]
> > so i have a question i got that error when i try to acces another page,i underatsn it have to do with the context but i do now know how to fix it.so what im trying to do is im trying to get to another page using the ontap widget, i can move just fine to antoher page i have created but when i try to move to this job entries it give me this error which i do not know how to resolve please help
> 
> It looks like your provider is scoped within a page, hence why other pages cannot access this provider.
> 
> Try moving the provider above MaterialApp.
> 
> In any case, the error message should explain what is going wrong. If there's something that you do not explain with the error message, please mentioned it so that we can improve it.

I'm just curious, if one were to want to have a provider specific to a page, like a user profile screen having its own provider for having multiple instances at a time of that widget with different profile data being stored in their providers, how would one go about it, because it's not possible to move the provider above materialapp in that scenario?

**Comment by rrousselGit** [comment]
I would never place a provider within a page, and always place them above MaterialApp.

I don't see a reason why you wouldn't be able to place them above MaterialApp.

**Comment by NamanShergill** [comment]
> I would never place a provider within a page, and always place them above MaterialApp.
> 
> I don't see a reason why you wouldn't be able to place them above MaterialApp.

As I mentioned in my example, if there could be multiple user profile pages opened in an app, all of them would require different providers, no? 

Let's say if there's one user profile page opened, you go to their followers/friends, and open a new page from there, a new screen will get pushed for the new profile. If one uses a single provider above materialapp for both the screens, wouldn't the original screen's data get changed as well, and when the user pops back to it, he'll see the new user instead of the original one?
