### ISSUE TITLE
Dispose() getting called on hot reload

### ISSUE THREAD

**Issue by dmvvilela** [rrousselGit/provider#616]
Why app works fine until i hot reload it. Then i get the message:

E/flutter ( 1678): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Cannot add new events after calling close

This is because i use old scholl bloc pattern with rxdart and streams. They are closed on dispose method.

I checked and the dispose method is really getting called! I am using Provider for my repository (api call) and ProxyProvider2 (with access to the repository) for my blocs.

I don´t think they should be disposed on hot reload. I am getting errors for this. Don´t fully understand why.

**Comment by rrousselGit** [comment]
That's difficult to say without seeing some code

Could you share a minimalist way of reproducing the issue? (not your entire project, just a few lines to reproduce the problem_

**Comment by dmvvilela** [comment]
Here is the code.. dispose method was commented cause it was throwing on hot reload.

`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        //
        // --- Repositórios ---
        //
        Provider<UserRepositoryBase>(
          create: (_) => UserRepository(),
          dispose: (_, userRepository) => userRepository?.dispose(),
        ),
        Provider<FeedRepositoryBase>(
          create: (_) => FeedRepository(),
          dispose: (_, feedRepository) => feedRepository?.dispose(),
        ),
        Provider<PlaceRepositoryBase>(
          create: (_) => PlaceRepository(),
          dispose: (_, placeRepository) => placeRepository?.dispose(),
        ),
        Provider<BalanceRepositoryBase>(
          create: (_) => BalanceRepository(),
          // dispose: (_, balanceRepository) => balanceRepository?.dispose(),
        ),
        Provider<PromotionRepositoryBase>(
          create: (_) => PromotionRepository(),
          dispose: (_, promotionRepository) => promotionRepository?.dispose(),
        ),
        //
        // --- BLoCs ---
        //
        ProxyProvider<PlaceRepositoryBase, FilterPlaceBloc>(
          update: (_, placeRepository, __) => FilterPlaceBloc(placeRepository),
          dispose: (_, placeCategoryBloc) => placeCategoryBloc.dispose(),
        ),
        ProxyProvider2<UserRepositoryBase, BalanceRepositoryBase, UserBloc>(
          update: (_, userRepository, balanceRepository, __) => UserBloc(
            userRepository,
            balanceRepository,
          ),
          // dispose: (_, userBloc) => userBloc?.dispose(),
        ),
        ProxyProvider<UserRepositoryBase, AuthBloc>(
          update: (_, userRepository, __) => AuthBloc(userRepository),
          dispose: (_, authBloc) => authBloc?.dispose(),
        ),
        ProxyProvider2<UserRepositoryBase, FeedRepositoryBase, CouponsBloc>(
          update: (_, userRepository, feedRepository, __) => CouponsBloc(
            userRepository,
            feedRepository,
          ),
          dispose: (_, couponsBloc) => couponsBloc?.dispose(),
        ),
        ProxyProvider3<UserRepositoryBase, FeedRepositoryBase, FilterPlaceBloc,
            HomeBloc>(
          update: (_, userRepository, feedRepository, filterPlaceBloc, __) =>
              HomeBloc(
            userRepository,
            feedRepository,
            filterPlaceBloc,
          ),
          dispose: (_, homeBloc) => homeBloc?.dispose(),
        ),
        ProxyProvider2<UserRepositoryBase, FeedRepositoryBase, OffersBloc>(
          update: (_, userRepository, feedRepository, __) => OffersBloc(
            userRepository,
            feedRepository,
          ),
          dispose: (_, offersBloc) => offersBloc?.dispose(),
        ),
        ProxyProvider2<UserRepositoryBase, BalanceRepositoryBase, PartnerBloc>(
          update: (_, userRepository, balanceRepository, __) => PartnerBloc(
            userRepository,
            balanceRepository,
          ),
          dispose: (_, partnerBloc) => partnerBloc?.dispose(),
        ),
        ProxyProvider2<UserRepositoryBase, BalanceRepositoryBase,
            BuyPointsBloc>(
          update: (_, userRepository, balanceRepository, __) => BuyPointsBloc(
            userRepository,
            balanceRepository,
          ),
          dispose: (_, buyPointsBloc) => buyPointsBloc?.dispose(),
        ),
        ProxyProvider2<PlaceRepositoryBase, PromotionRepositoryBase,
            SearchBloc>(
          update: (_, placeRepository, promotionRepository, __) => SearchBloc(
            placeRepository,
            promotionRepository,
          ),
          dispose: (_, searchBloc) => searchBloc?.dispose(),
        ),
      ],
      child: MaterialApp()...`

**Comment by rrousselGit** [comment]
What is getting disposed in your case exactly?

**Comment by dmvvilela** [comment]
@rrousselGit here:

'''dart
dispose: (_, userBloc) => userBloc?.dispose(),
'''

When i hot reload any file/widget this gets disposed. I don´t understand why.

(This is the only place in my code that i call this dispose() function.

I had to comment it so i wouldn't get errors on hot reload.

**Comment by rrousselGit** [comment]
That sounds logical for me:

hot-reload rebuilds all widgets, which creates a new `UserBloc` and disposes of the previous one.

What I don't understand is where your exception is coming from. It appears that your application somehow depends on the previous UserBloc instance.

**Comment by dmvvilela** [comment]
Hmm my understanding of hot reload might be wrong then.. I thought it would just rebuild the part of the widget tree that had changed.

What i don't understand is why before Flutter 2.0 this wasn't happening. I never had problem with this before. I just changed all this ProxyProviders for Get It so i could get rid of the problem.

I will close the issue than. But i truly don't understand what is happening.

My exception is coming because i am closing my streams on the dispose method. And thena fetch function somewhere try to populate that stream. Since it is already closed, i got the problem.

Maybe then hot reload always worked this way and with Flutter 2.0 the streams are behaving different. I really dont know.

Anyway thanks for your time.

**Comment by dmvvilela** [comment]
Actually i just updated Provider from version 3. I had to change my provider to use the "listen: false" thing.

This might be the problem right?
