### ISSUE TITLE
[Question] on refactoring in VSCode

### ISSUE THREAD

**Issue by miriam-z** [rrousselGit/provider#619]
How to make MultiProvider appear in the cmd . list of widgets to make it easier to refactor to.

i.e in VSCode don't see MultiProvider in list: 

![Screenshot 2021-03-12 at 13 01 48](https://user-images.githubusercontent.com/19760229/110943441-1d1de000-8333-11eb-9abe-d31fdf63a5b7.png)

provider: ^5.0.0

**Comment by rrousselGit** [comment]
Hello!

Sorry to say that, but there is no such thing
