### ISSUE TITLE
The method 'xyz' isn't defined for the type 'LoginProvider'.

### ISSUE THREAD

**Issue by aatikakhan** [rrousselGit/provider#623]
version  provider: ^4.3.3
  sdk: '>=2.12.0 <3.0.0'
 this is my code
` FutureBuilder(
      future: Firebase.initializeApp(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        return MultiProvider(
          providers: [
            ChangeNotifierProvider<LoginProvider>(
              create: (context) {
                return LoginProvider();
              },
            )
          ],
          builder: (context, child) {
            print(Provider.of<LoginProvider>(context));
            return KnightApp();
          },
        );
      },
    ),
  );`

**Comment by rrousselGit** [comment]
Could you expand on the issue?

Like adding the exception, properly formatting the code, and adding a way to reproduce it?

As `LoginProvider` is not from `provider`, nor is there an `xyz` method in provider either

**Comment by aatikakhan** [comment]
xyz is a function in LoginProvider and whenever I'm using functions from LoginProvider it's giving error as 'method isn't defined for LoginProvider'

**Comment by aatikakhan** [comment]
solved it by deleting the old sdk 1.22.5 from the system and downloading the new 2.0.2 sdk. Thank you.
