### ISSUE TITLE
The named parameter 'providers' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'providers'

### ISSUE THREAD

**Issue by aatikakhan** [rrousselGit/provider#624]
getting error that The named parameter 'providers' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'providers'

> provider: ^5.0.0  doing migration to nullsafety.

` FutureBuilder(
      future: Firebase.initializeApp(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        return MultiProvider(
          providers: [
            ChangeNotifierProvider<LoginProvider>(
              create: (context) {
                return LoginProvider();
              },
            )
          ],
          builder: (context, child) {
            print(Provider.of<LoginProvider>(context));
            return KnightApp();
          },
        );
      },
    ),`

**Expected behavior**
it should not give error at providers: and create: named parmeters

**Comment by rrousselGit** [comment]
Did you forget to run `pub get` or import provider?

**Comment by aatikakhan** [comment]
Nope.

**Comment by vityas-off** [comment]
`flutter clean` resolved this issue for me

**Comment by aatikakhan** [comment]
doesn't work

**Comment by aatikakhan** [comment]
solved it by deleting the old sdk 1.22.5 from the system and downloading the new 2.0.2 sdk
