### ISSUE TITLE
Provide last value in selector

### ISSUE THREAD

**Issue by masseelch** [rrousselGit/provider#628]
**Is your feature request related to a problem? Please describe.**
I have a stream of messages (websocket) which is provided to the Widget-Tree by a `StreamBuilder`. I then use `Selector` to filter out the message i need for the subwidgets. 

Now Selector-A gets a Message, decides it doesn't need it and should therefore provide the old value. I cannot do that for now. In the past I returned null in that case, but sometimes even null is a valid new value. 

**Describe the solution you'd like**
Have the old value provided to `Selector`s `selector` function so I can return that when there is no new value.
```dart
Selector<Message>(
  selector: (context, prev, current) {
    if (current.isForMe) return current;
    return prev;
  },
)
```

**Describe alternatives you've considered**

- Use `Provider.of` with listen and build the logic myself
- Returned null and interpreted that in a custom `shouldRebuild` as "Do not rebuild"
- Have an overly complicated (and unpure) `shouldRebuild` function.
- Do all the logic in the `builder` of a `Consumer`

**Comment by rrousselGit** [comment]
That would make the selectors "impure", meaning that the number of selector calls matters, which will prevent optimizations.

I would instead suggest changing how you structure your state, such that you keep a reference on both the current and previous message.

**Comment by masseelch** [comment]
Ah well, yes. I get that. 

I think i missunderstood the intended use of a `Selector` in the first place. I though it was meant to filter out emitted values. But it really is to just take a portion of each data sent (like taking a nested field only). 

What i wanted instead is filtering the stream. So I created two new widgets `FilterConsumer` and `FilterSelector`. They do what was my initial purpose. 

Are you interessted in extending `provider`-package to include those? If yes I can provide a PR

**Comment by rrousselGit** [comment]
Selector is the filtering mechanism of provider.

It is a filter by selecting only the properties that you care about instead
of the entire object.

This makes the filter mechanism significantly more resilient, because it is
independent from rebuilds and what the builder uses.

**Comment by masseelch** [comment]
So my first impression was right! I am still confused though. Say I have a stream of messages: 

```dart
abstract class Message<T> {
  Message(this.message);

  T message;
}

class StringMessage extends Message<String> {
  StringMessage(String message) : super(message);
}

class IntMessage extends Message<int> {
  IntMessage(int message) : super(message);
}
```

I provide a `Stream<Message>` with `StreamProvider<Message>()` and my `StringWidget` listens to that stream. How can I use `Selector` to prevent rebuild on `StringWidget` when an `IntMessage` is received?

```dart
class StringWidget extends StatelessWidget {
  @override
  Widget build(BuildCotext context) {
    return Selector<Message, String>(
      selector: (context, msg) {
        // I only want StringMessages, I do not care about IntMessage.
      },
      builder: [...] // I do not want a rebuild when I received an IntMessage
    );
  }
}

I do not know how Selector is able to filter the events / data provided by the `StreamProvider` above. Where is my mistake here?
```

**Comment by rrousselGit** [comment]
You could do:

```dart
StringMessage msg = context.select((Message msg) => msg is StringMessage ? msg : null);
```

**Comment by masseelch** [comment]
But in that case the `builder` will be called with `null` everytime an `IntMessage` is emitted, am I right? So this does not prevent a rebuild, does it?

**Comment by masseelch** [comment]
Well, you seem to think there is no issue while I am still not sure there is not. But I guess you will neither change the behaviour nor accept a PR. I will use my custom Widgets which do filter the events so for me it works. 

Thanks for your time and explanations :+1: .
