### ISSUE TITLE
Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.

### ISSUE THREAD

**Issue by nilotpalkapri** [rrousselGit/provider#629]
**Describe the bug**
it was working fine but for last two days getting the error below.
Performing hot restart...                                               
Restarted application in 72,998ms.
W/DynamiteModule(12543): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
W/ConnectivityManager.CallbackHandler(12543): callback not found for CALLBACK_AVAILABLE message
I/com.mcd.twb(12543): Waiting for a blocking GC ProfileSaver
I/DynamiteModule(12543): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(12543): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/ConnectivityManager.CallbackHandler(12543): callback not found for CALLBACK_AVAILABLE message

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by rrousselGit** [comment]
Could you please properly fill the issue template? Otherwise there's hardly anything I can do to help.

But this doesn't seem related to provider
