### ISSUE TITLE
Tried to call Provider.of<dynamic>. This is likely a mistake and is therefore unsupported.

### ISSUE THREAD

**Issue by seyaobey** [rrousselGit/provider#630]
**Describe the bug**
I've been using `Provider` without problem. Then suddenly I'm getting the above error.
First I have created an object notifier:
```
class GroupsProvider extends ChangeNotifier {
  List<Map> _groups = [];

  List<Map> get groups => _groups;

  void setGroups(List<Map> value) {
    _groups = value;
    notifyListeners();
  }
}
```
Second, at some point in my code, I initialise the notifier value:
`context.read<GroupsProvider>().setGroups(groups);`

Then third, in a different widget, I attempt to read this value (and I get the above error):
`final groups = context.watch()<GroupsProvider>().groups;`
![image](https://user-images.githubusercontent.com/2738569/112407464-6b10eb80-8d16-11eb-96b9-e2d37198950b.png)

**Expected behavior**
I should be able to read the notifier value (in fact, it was working until today...).

**Comment by meet30997** [comment]
Yes I am facing this error to I am using
`var response = await context
        .read()<ApiService>()
        .someAPICall();`

**Comment by rrousselGit** [comment]
`context.watch()<T>()` is not a valid syntax

Instead do `context.watch<T>()`
