### ISSUE TITLE
I get error after updating provider to v.5.0.0

### ISSUE THREAD

**Issue by frederik0312** [rrousselGit/provider#632]
**i get error even though 'listen:false' is added (see error below post)**

here is the part of my code that produces the error:

` 
void onModeSelected(String mode) async {
    List<Rule> rules = await Provider.of<JsonHandlerService>(context, listen: false)
        .getRulesList(context, mode, 50);

    Navigator.of(context).push(
        MaterialPageRoute(builder: (_) => GamePage(widget.players, rules)));

  }

  Widget card(String title, String description, String path, String mode) {
    return GestureDetector(
      onTap: () {
        mode != "Spin"
            ? onModeSelected(mode)
            : Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => SpinBottle()));
      },¨
`

if i dont add listen:false nothing happens and the new window dosent open as it should. if i do add listen:false the error breaks the program.

here is the error message:
![image](https://user-images.githubusercontent.com/38206067/112729212-56f20780-8f2b-11eb-8738-c403e612e222.png)

**Comment by rrousselGit** [comment]
This error is not possible to trigger if you passed "listen: false".

Are you sure that this isn't another Provider.of that is failing?

**Comment by rrousselGit** [comment]
This issue appears to be stale, so I will close it. Feel free to open a new one if you still have the problem
