### ISSUE TITLE
can i use context.watch() open a showdialog?

### ISSUE THREAD

**Issue by cjl84914** [rrousselGit/provider#633]
case code:
`class _MyState extends State<MyWidget> {
      @override
      Widget build(BuildContext context) {
             var state = context.watch<Model>().state;
             if(state==State.SomeThingsWrong) {
              showDialog(context: context, builder: (c) {
                return DialogContrainer();
              });
            }
             return Container();
       }
}`

console tips:
setState() or markNeedsBuild() called during build.

**Comment by rrousselGit** [comment]
You cannot call `showDialog` inside the `build` method.

Instead make a stateful widget, listen to your ChangeNotifier (with addListener), and have the listener call showDialog.

**Comment by cjl84914** [comment]
thinks, now i addListener in ChangeNotifier:
code :
class Model with ChangeNotifier {
  OnStateback _stateCallback;
}
class

**Comment by cjl84914** [comment]
thanks
