### ISSUE TITLE
Running the flutter app on the web I'm getting an exception InheritedProviderScope

### ISSUE THREAD

**Issue by NikolinNgjela** [rrousselGit/provider#634]
I'm running the flutter app on the web, and I'm getting an exception that is related to unsupported operation: Plaftorm._operatingSystem

```
Debug service listening on ws://127.0.0.1:30653/GCokvc4bvbQ=/ws
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building _InheritedProviderScope<PartRequestsState>(value:
<not yet loaded>):
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  _InheritedProviderScope<PartRequestsState>
  file:///C:/Users/flutter/.pub-cache/hosted/pub.dartlang.org/provider-5.0.0/lib/src/inherited_provider.dart:159:12

```
![image](https://user-images.githubusercontent.com/12495588/115363069-68dd6800-a1c2-11eb-8272-50ea2e81c753.png)

I've replaced all the usage of the Platform with https://pub.dev/packages/universal_platform on the project so far 

The same issue occurs with 4.3.3  too
`provider: 4.3.3 `

**Comment by rrousselGit** [comment]
It sounds like one of your providers threw an exception

**Comment by rrousselGit** [comment]
Do you still have the issue?

Provider isn't using Platform, so I doubt it's the problem.

**Comment by rrousselGit** [comment]
In the lack of an answer, I will close this.
