### ISSUE TITLE
Is there a way for providers to sync states between them.(bidirectional)

### ISSUE THREAD

**Issue by Oklahomawhore** [rrousselGit/provider#635]
**Use case**

I'm creating an app where I create two feed lists, where each provider manages a lists, but there's common items in
these lists. so when user taps like button or interacts with item that changes the item state, theses provider managed
lists needs their state be synced. 

Is there a way to do that?

**Comment by rrousselGit** [comment]
I would suggest "normalizing" your models

That means, rather than have a List<Item>, use a list<Id>
Then use the ID to listen to the item

This way there's only a single source of truth

**Comment by rrousselGit** [comment]
Closing since the issue appears to be stale.

For help request, I would suggest using StackOverflow instead
