### ISSUE TITLE
whats the solution for this please?

### ISSUE THREAD

**Issue by ahmedemam22** [rrousselGit/provider#639]
project give this error

Error

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/dynamic_theme-1.0.1/lib/dynamic_theme.dart:25:20: Error: The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorStateOfType'.
    return context.ancestorStateOfType(const TypeMatcher<DynamicThemeState>());
                   ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sidekick-0.1.3/lib/src/widgets/sidekick_team_builder.dart:75:17: Error: The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorStateOfType'.
        context.ancestorStateOfType(TypeMatcher<SidekickTeamBuilderState<T>>());
                ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/getflutter-1.1.3/lib/components/appbar/gf_appbar.dart:311:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
                                                        ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1944:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^

**Comment by rrousselGit** [comment]
Sounds like you are using packages that are too old

**Comment by ahmedemam22** [comment]
@rrousselGit yes ,what's the solution?

**Comment by rrousselGit** [comment]
Upgrade your packages

**Comment by harshLFC** [comment]
Upgrading packages did not work
