### ISSUE TITLE
Provider won't intentionally stream a null value after it's already streamed non-null data

### ISSUE THREAD

**Issue by sjrphx** [rrousselGit/provider#641]
I'm using a StreamProvider, which is given a value by a Firestore Stream. It initially starts out producing null, as expected. The stream is then updated to start producing values from a valid Firestore document, and the stream provider does too, as expected.

I then have a user action, which then should stop reading the Firestore document and give a null value to the stream/streamprovider and notify listeners that the stream now has a null value. It doesn't do this, and instead just keeps streaming the last-known non-null values. Stepping through the code, I see that databaseService.gameStream is called with a null input at the user action, as expected, but then the output from the StreamProvider doesn't change to null as the code specifies.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [ChangeNotifierProvider(create: (context) => AppUser())],
      child: InnerProviderClass(),
    );
  }
}

class InnerProviderClass extends StatelessWidget {
  final databaseService = DatabaseService();
  @override
  Widget build(BuildContext context) {
    AppUser appUser = Provider.of<AppUser>(context);
    return MultiProvider(
      providers: [
        StreamProvider<Game>.value(
          value: databaseService.gameStream(appUser.getCode),
          initialData: null,
          catchError: (_, err) {
            print(err);
            return null;
          },
        ),
      ],
      child: MaterialApp(
        navigatorKey: navigatorKey,
        title: 'Game',
        home: RouterNavigator(),
      ),
    );
  }
}

class DatabaseService {
  Stream<Game> gameStream(String gameCode) {
    return (gameCode != null)
        ? FirebaseFirestore.instance
            .collection('games')
            .doc(gameCode)
            .snapshots()
            .map((doc) => Game.fromDocument(doc))
        : null;
  }
}
```

**User Trigger that's supposed to change valid data to null data**
`Provider.of<AppUser>(context, listen: false).setGameCode(null); `

**This is from the AppUser model: 
`void setGameCode(String gameCode) async {     code = gameCode;     notifyListeners();   }`

**Comment by rrousselGit** [comment]
When the stream changes or goes to `null`, Streamprovider doesn't revert to `initialData`.

You may want to do:

```diff
class DatabaseService {
  Stream<Game> gameStream(String gameCode) {
    return (gameCode != null)
        ? FirebaseFirestore.instance
            .collection('games')
            .doc(gameCode)
            .snapshots()
            .map((doc) => Game.fromDocument(doc))
-        : null;
+        : Stream<Game>.value(null);
  }
}
```

**Comment by sjrphx** [comment]
> When the stream changes or goes to `null`, Streamprovider doesn't revert to `initialData`.
> 
> You may want to do:
> 
> ```diff
> class DatabaseService {
>   Stream<Game> gameStream(String gameCode) {
>     return (gameCode != null)
>         ? FirebaseFirestore.instance
>             .collection('games')
>             .doc(gameCode)
>             .snapshots()
>             .map((doc) => Game.fromDocument(doc))
> -        : null;
> +        : Stream<Game>.value(null);
>   }
> }
> ```

This fixed my issue! I had spent a lot of time trying to figure out what I had done wrong, thank you very much! 

I'm still not sure I quite understand how it works though. I was expecting the  ": null;" line to behave in the way that the ": Stream<Game>.value(null);" is behaving. When gameCode isn't null, it's producing a Stream<Game>.value without having to be contained in "Stream<Game>.value()" .Why does null require it? 

Thanks again!

**Comment by rrousselGit** [comment]
Closing since this was answered
