### ISSUE TITLE
.../pub.dartlang.org/provider-5.0.0/lib/src/inherited_provider.dart:164:11: Error: The argument type 'Widget?' can't be assigned to the parameter type 'Widget' because 'Widget?' is nullable and 'Widget' isn't.

### ISSUE THREAD

**Issue by Alihaile** [rrousselGit/provider#646]
please solf this error in the recent version 5.0.0
![null-error](https://user-images.githubusercontent.com/36104691/120918393-f1ee2700-c6bc-11eb-9360-f080a74eb711.PNG)

**Comment by rrousselGit** [comment]
Are you sure that your dependencies are up-to-date and your application is correctly migrated to nullsafety? 

This is working for me.

**Comment by rrousselGit** [comment]
This issue appears to be stale, so I will close it. Feel free to open a new issue if you still have the problem
