### ISSUE TITLE
Nested providers and root Provider

### ISSUE THREAD

**Issue by sm2017** [rrousselGit/provider#650]
**Is your feature request related to a problem? Please describe.**
`Navigator.of` in flutter has a `rootNavigator` param 

> If rootNavigator is set to true, the state from the furthest instance of this class is given instead. Useful for pushing contents above all subsequent instances of Navigator.

Is it possible to have a  `rootProvider` param in `context.read`,  `context.watch` and  `context.select`?

**Describe the solution you'd like**
By using `context.watch<T>(rootProvider: true)` we can access furthest instance of provider

**Comment by rrousselGit** [comment]
I do not like this solution. What is the use-case?

**Comment by sm2017** [comment]
@rrousselGit I am developing a very large application, **To optimize memory usage** I want to use nested providers of same type, let's call each provider an `scope`

Assume in the application you can post your `products` and search and find other people `products`, I want to keep `product` state in the provider and keep it sync across multiple providers

# Why nested providers?
Assume you have multiple pages to see product and some products are more important to user, such as `my products`, `favorited products`, these states fetches once and updates with Realtime data, these products never removed from memories , I want to have a `root` provider to keep these products

Other products are in nested providers, such as finding a product by searching a text, when the page removes I want to remove all products in this scope from memories

So, sometimes in the nested providers, I need to read root provider

**Comment by rrousselGit** [comment]
But why use two providers with the same type?

Couldn't you use two different classes, so that you can do `Provider.of<X>` vs `Provider.of<Y>`? Internally they could both extend the same class, they'd just be different.

**Comment by sm2017** [comment]
As the provider listen to real-time data to sync data, (i.e. when a product title updated) it has many many logics and the logic is same for all scopes

Your approach works too, I can create a provider(A) and have two extended provider(B and C) just for watching provider, but it add some unwanted complexity

Assume, I have a `ProductListTile` and use it in two scopes (nested scope, root(B provider) and child scope (C provider), I want to `select` a product by id in the current scope

How can I select the provider? to make `ProductListTile` usable in all scopes ? Is ```Provider.of<A>``` works? And it returns `C`?

**Comment by rrousselGit** [comment]
> Assume, I have a ProductListTile and use it in two scopes (nested scope, root(B provider) and child scope (C provider), 

The thing is, you shouldn't have scopes.

In general I recommend avoiding scoping providers

I'd recommend using a different architecture to solve the problem.

**Comment by sm2017** [comment]
Ok, thanks
