### ISSUE TITLE
A couple of null safety tweaks

### ISSUE THREAD

**Issue by davidmorgan** [rrousselGit/provider#652]
Hi Remi,

We're looking at rolling the latest `package:provider` into google and hit a couple of blocking issues.

We have also taken the time to investigate and have a proposed solution ;)

Both issues only show up with mixed null safe and legacy code.

1. Legacy inherited providers can't contain nulls any more. This is because of the use of `_value is! T` to check for failed initialization. Legacy code can't supply an explicitly nullable `T`, so `null` is never `T`. Proposed fix: use an additional `bool` to track whether initialization succeeded: https://github.com/davidmorgan/provider/commit/1d6ee87cd48da981e5fb9302a831ec7b56b9bcd0

2. Legacy code might want to inject a `Provider<T?>`, because legacy code is used to handling nulls. But, legacy code can't write `T?` so it can't supply the right key--it can only ever request non-nullable providers. Proposed fix: when running in unsound (mixed) mode, look for `Provider<T?>` if `Provider<T>` is not found: https://github.com/davidmorgan/provider/commit/1a55c485cba486480e86e686fde48878410c24fb

Both proposed fixes include test coverage; adding test coverage is a bit awkward because it requires tests that run in mixed mode, which needs a bit of care when running `flutter test`; I update `flutter_test.sh` to do that.

Please let me know if this seems a good direction, if so I will clean up the code and send PRs. Or, of course, happy to discuss :)

Thanks :)

**Comment by rrousselGit** [comment]
Hello!

I looked at both fixes and they look good.
Happy to review a PR!

**Comment by davidmorgan** [comment]
Great, thanks :) I should get to it tomorrow.
