### ISSUE TITLE
Parts of provider not working in release mode 

### ISSUE THREAD

**Issue by joeyyy688** [rrousselGit/provider#656]
Provider works perfectly in debug mode but in release mode, certain parts of it doesn't work at all. i.e. nothing happens after calling notifylisteners to update the UI. Certain parts of the Ui are even greyed out due to error, no error is also printed to the debug console also.

**Comment by rrousselGit** [comment]
Could you share a way to reproduce the problem?

**Comment by joeyyy688** [comment]
Could it be possible if we could video call so I show you everything?

**Comment by joeyyy688** [comment]
or what about a private chat please, later I can come here and explain how we got it fixed

**Comment by rrousselGit** [comment]
I would prefer if you could explain the problem in more detail here

**Comment by joeyyy688** [comment]
ok sure

**Comment by joeyyy688** [comment]
Consumer<AppState>(
      builder: (context, value, _) {
        return Container(
          margin: EdgeInsets.symmetric(horizontal: 40),
          //color: Colors.grey,
          height: 225,
          //width: 510,
          child: Stack(
            children: [
              Opacity(
                opacity: 0.99,
                child: Container(
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(8),
                      image: DecorationImage(
                          image: AssetImage("assets/images/circle-blues.png"),
                          fit: BoxFit.cover),
                    ),
                  ),
                ),
              ),
              Container(
                color: Colors.transparent,
                width: displayWidth(context) == 320.0
                    ? displayWidth(context) * 0.57
                    : displayWidth(context) * 0.72,
                padding: EdgeInsets.symmetric(
                  horizontal: 10,
                ),
                margin: EdgeInsets.only(
                  left: 10,
                  top: 15,
                ),
                child: Row(
                  children: [
                    Container(
                        //padding: EdgeInsets.symmetric(horizontal: 20),
                        child: Icon(
                      Icons.account_circle_sharp,
                      size: displayWidth(context) * 0.12,
                      color: Color(0xFFffd31a),
                    )),
                    Expanded(
                      child: Container(
                        padding: EdgeInsets.only(left: 20),
                        child: RichText(
                            // overflow: TextOverflow.clip,
                            softWrap: true,
                            textWidthBasis: TextWidthBasis.longestLine,
                            //overflow: TextOverflow.ellipsis,
                            textAlign: TextAlign.left,
                            text: TextSpan(
                                style: Theme.of(context).textTheme.headline1,
                                children: [
                                  TextSpan(
                                      text: "Name\n",
                                      style: TextStyle(
                                          color: Colors.white,
                                          fontSize:
                                              displayWidth(context) * 0.032)),
                                  TextSpan(
                                      text: "${value.name}",
                                      style: TextStyle(
                                          color: Colors.white,
                                          fontWeight: FontWeight.bold,
                                          fontSize:
                                              displayWidth(context) * 0.037))
                                ])),
                      ),
                    )
                  ],
                ),
              ),
              Container(
                color: Colors.transparent,
                width: displayWidth(context) == 320.0
                    ? displayWidth(context) * 0.57
                    : displayWidth(context) * 0.615,
                padding: EdgeInsets.symmetric(
                  horizontal: 10,
                ),
                margin: EdgeInsets.only(
                  left: 10,
                  top: 85,
                ),
                child: Row(
                  children: [
                    Container(
                        //padding: EdgeInsets.symmetric(horizontal: 20),
                        child: Icon(
                      Icons.badge,
                      size: displayWidth(context) * 0.12,
                      color: Color(0xFFffd31a),
                    )),
                    Container(
                      padding: EdgeInsets.only(left: 20),
                      child: RichText(
                          textAlign: TextAlign.left,
                          text: TextSpan(
                              style: Theme.of(context).textTheme.headline1,
                              children: [
                                TextSpan(
                                    text: "User ID  \n",
                                    style: TextStyle(
                                        color: Colors.white,
                                        fontSize:
                                            displayWidth(context) * 0.032)),
                                TextSpan(
                                    text:
                                        "${value.userid == null ? " " : value.userid}",
                                    style: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        color: Colors.white,
                                        fontSize:
                                            displayWidth(context) * 0.037))
                              ])),
                    )
                  ],
                ),
              ),
              Container(
                color: Colors.transparent,
                width: displayWidth(context) == 320.0
                    ? displayWidth(context) * 0.57
                    : displayWidth(context) * 0.615,
                padding: EdgeInsets.symmetric(
                  horizontal: 10,
                ),
                margin: EdgeInsets.only(
                  left: 10,
                  top: 150,
                ),
                child: Row(
                  children: [
                    Container(
                        //padding: EdgeInsets.symmetric(horizontal: 20),
                        child: Icon(
                      Icons.business_center_rounded,
                      size: displayWidth(context) * 0.12,
                      color: Color(0xFFffd31a),
                    )),
                    Expanded(
                      child: Container(
                        padding: EdgeInsets.only(left: 20),
                        child: RichText(
                            textAlign: TextAlign.left,
                            softWrap: true,
                            text: TextSpan(
                                
                                children: [
                                  TextSpan(
                                      text: "Dept  \n",
                                      style: TextStyle(
                                          color: Colors.white,
                                          fontSize:
                                              displayWidth(context) * 0.032)),
                                  TextSpan(
                                      text:
                                          "${value.dept == null ? " " : value.dept}",
                                      style: TextStyle(
                                          color: Colors.white,
                                          fontWeight: FontWeight.bold,
                                          fontSize:
                                              displayWidth(context) * 0.037))
                                ])),
                      ),
                    )
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );


The state of this not changing like it changes in debug mode, even though notifylisteners is being called after getting the data from an api 

This is just a section of the code

**Comment by rrousselGit** [comment]
Could you format it properly and share something that I can execute?

**Comment by joeyyy688** [comment]
Hello, I'd like to close this issue, I've managed to solve the problem. I wasn't doing something correctly

**Comment by joeyyy688** [comment]
Thanks for trying to help @rrousselGit

**Comment by iqtedar123** [comment]
> Hello, I'd like to close this issue, I've managed to solve the problem. I wasn't doing something correctly

what were you not doing correctly?

**Comment by joeyyy688** [comment]
> > Hello, I'd like to close this issue, I've managed to solve the problem. I wasn't doing something correctly
> 
> what were you not doing correctly?

I did not write a conditional statement properly. So I had to refactor that part of the code again

**Comment by ZMNOTZ** [comment]
I met the same bug...
