### ISSUE TITLE
Async Provider

### ISSUE THREAD

**Issue by bitsydarel** [rrousselGit/provider#66]
Hi,
Does provider support providing dependency asynchronously ?

Something similar to [Dagger Producers](https://google.github.io/dagger/producers.html) on Java (Android).

**Comment by rrousselGit** [comment]
Hello,
Can you explain further what that would mean?

**Comment by bitsydarel** [comment]
I mean let's say i want to do provide a dependency that need to be created asynchronously because it's expensive. Currently i cant do that using provider

**Comment by bitsydarel** [comment]
This is currently not possible. 

Provider<SomeValue> (
    builder: (context) async {
       //do some intensive stuff required to create the object.
      return the object.
    },
    child: const SomeWidget()
)

**Comment by rrousselGit** [comment]
`ChangeNotifierProvider`/`ListenableProvider`/`ValueListenableProvider`/`StreamProvider` can all handle asynchronous data.


Are you asking for a `FutureProvider`?

**Comment by bitsydarel** [comment]
Yes

**Comment by bitsydarel** [comment]
@rrousselGit Thanks! i will close this issue when the pull request will be merged.

**Comment by ozexpert** [comment]
@rrousselGit when is FutureProvider going to be released?

**Comment by rrousselGit** [comment]
I'd like to clarify https://github.com/rrousselGit/provider/issues/102 first. 
Once that's done, I can make a release.

In the mean time, you can use a git dependency using the `v3.0.0` branch.

**Comment by rrousselGit** [comment]
There is no such thing, no

**Comment by HadyMash** [comment]
@rrousselGit do you plan on implementing it at some stage or are there any workarounds?
