### ISSUE TITLE
The return type 'Widget?' isn't a 'Widget', as required by the closure's context.

### ISSUE THREAD

**Issue by umersaddiq** [rrousselGit/provider#661]
I am using consumer widget to avoid re-rendering, before null safety it works fine... But when I upgrade provider package to it gives me an error which I mentioned above it is not accepting ListView.builder() and says that The return type 'Widget?' isn't a 'Widget', as required by the closure's context

**Code Sample**

Consumer<GreatPlaces>(
        child: Center(
          child: const Text(
            'Got no places yet, start adding some',
          ),
        ),
        builder: (ctx, greatPlaces, ch) => greatPlaces.items.length <= 0
            ? ch
            : ListView.builder(
                itemBuilder: (ctx, index) => Center(),
                itemCount: 5,
              ),
      )

**Reference Image of Code** --> https://i.stack.imgur.com/sEAnv.png

**Comment by rrousselGit** [comment]
You need to do:


```dart
builder: (context, value, ch) =>
  greatPlaces.length <= 0?
      ch!  :
      ListView(...)
```

**Comment by HermarkDevv** [comment]
'm getting this error 'The return type 'T' isn't a 'Widget', as required by the closure's context.', please how do i go about it.


import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:provider/provider.dart';
import 'package:provider_architecture/core/viewmodels/basemodel.dart';

import '../../locator.dart';

class BaseView<T extends BaseModel> extends StatefulWidget {
  final Widget Function(BuildContext context, T model, Widget child) builder;
  final Function(T) onModelReady;

  BaseView({this.builder, this.onModelReady});

  @override
  _BaseViewState<T> createState() => _BaseViewState<T>();
}

class _BaseViewState<T extends BaseModel> extends State<BaseView<T>> {
  T model = locator<T>();
  @override
  void initState() {
    if (widget.onModelReady != null) {
      widget.onModelReady(model);
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<T>(
      create: (context) => locator<T>(),
      child: Consumer<T>(builder: widget.builder),
      builder: (context, child, ) => model,
    );
  }
}

**Comment by rrousselGit** [comment]
Consumer.builder's "child" parameter is nullable.
