### ISSUE TITLE
Provide access to state in RouteInformationParser to update state in response to user typing URL in web browser address bar

### ISSUE THREAD

**Issue by vgribok** [rrousselGit/provider#667]
**Is your feature request related to a problem? Please describe.**
While Provider/Consumer model enables state access through the tree of Widget builders, it is not, however, the only place where access to state is necessary in Flutter 2 apps. Declarative Navigator in Flutter 2 needs **access to state from the `RouteInformationParser` subclasses**, and those are not part of the Widget tree, and therefore supplying state to route parsers requires implementation of a system similar to the Provider/Consumer. Route parsers typically need to update app navigation state to display another screen after user types in a URL in a web browser address bar.

The request here is to make state accessible for subclasses of the `RouteInformationParser`.

**Describe the solution you'd like**
I would like to have a `RouteInformationParser` subclass with the version of the `Future<RoutePath> parseRouteInformation(RouteInformation)` method looking something like `Future<RoutePath> parseRouteInformation<TState>(RouteInformation, TState state)`;

**Describe alternatives you've considered**
I had to implement state holder/monitor system similar to the Provider to find state object by type on the state object collection.

**Additional context**
This issue comes to the fore with the release of Flutter 2 adding support for web/browser UI in addition to iOS & Andoird, and its [declarative Navigator](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade), plus its [set sister of classes](https://miro.medium.com/max/2400/1*hNt4Bc8FZBp_Gqh7iED3FA.png).

**Comment by rrousselGit** [comment]
Hello

Could you clarify what is preventing you from reading providers inside RouteInformationParser at the moment?
You could pass this class a BuildContext and have it use that context to read providers. Is that not enough?

**Comment by vgribok** [comment]
I only saw the samples where Providers and Consumers are used only within the widget tree. RouteInformationParser does not have access to the widget tree. It's instantiated to parse an URL and to _somehow_ get access to state to modify it so that a screen matching the user-entered route would be displayed. I would like to find out how a class like RouteInformationParser could become a consumer outside of the widget tree.

**Comment by rrousselGit** [comment]
But why not do:

```dart
class Parser extends RouteInformationParser {
  Parser(this.context)
 final BuildContext context
}

**Comment by rrousselGit** [comment]
Do you still have the problem or can this be closed?

**Comment by vgribok** [comment]
Please close. I haven't tried it yet, but I think I know how to do it. Thanks.
