### ISSUE TITLE
Feature: Selector/Consumer Builder returns Widget?

### ISSUE THREAD

**Issue by MateusAmin** [rrousselGit/provider#668]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to display something depending on a value in the provider.

**Describe the solution you'd like**
I can return null in the builder.

**Describe alternatives you've considered**
```dart
        Selector<T, W>(
          builder: (context, authed, __) {
            if (authed) {
              return Widget(),
              );
            } else {
              return SizedBox.shrink();
            }
          },
       )
```

Thanks for reading!

**Comment by rrousselGit** [comment]
Returning null is not possible.

Stateless/StatefulWidgets do not allow returning null.

**Comment by MateusAmin** [comment]
Thanks for the reply!

I suppose the generic advice would be to push the selector up one level in the tree or return a SizedBox.shrink() in place of null.

**Comment by rrousselGit** [comment]
Indeed this is a good solution
