### ISSUE TITLE
The parameter Listen : False doesn't work ? Provider

### ISSUE THREAD

**Issue by heXaCo0l** [rrousselGit/provider#671]
![123](https://user-images.githubusercontent.com/36626028/131226194-db523556-e4f8-4a2a-9b7d-148f2637ceae.JPG)
**Listen:False**
I'm trying to stop rebuild LandingUser Widget but it doesn't work with listen : false . And if it keep rebuilding ,I faces another issue I explained it // in the code below .

**LandingUser class**

```
class LandingUser extends StatelessWidget {
  const LandingUser({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    print("Landing User Rebuild ----------");
    final auth = Provider.of<AuthService?>(context , listen: false); // false not working
    print(auth);
    return StreamBuilder<MyUser?>(  
      stream: auth!.onChangeStateUser,
      builder: (context, snapshot) {  
        print(snapshot.hasData);    
        print(snapshot);
        if (snapshot.connectionState == ConnectionState.active) { 
          MyUser? user = snapshot.data;  
          print("user   $user");   
          if (user == null) {
            return Scaffold(body: Text('test login rebuild'),); // LogingScreen();
          } else {
            return Scaffold(body: Text('test Not null User rebuild'),); // UserProfile();
          }
        }else{
          //if(user==null){return LoginScreen();} //without if .. CircularProgressIndicator don't stop because I used in Login Screen page TextFormFeild and when foucse the widget rebuild itself and start loading again cuz the widget rebuilt .. this is another issue _!_
          return Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }
      
      },
    );
  }
}
```

### Root widget main : 

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("Main rebulided");
    return Provider<AuthService?>.value(
      value: AuthService(),
      child: MaterialApp(
       //.......

      ),
    );
  }
}

```

### auth!.onChangeStateUser Stream getter:

```
@override
  Stream<MyUser?>? get onChangeStateUser => _auth.authStateChanges().map((event) => _userFromFirebase(event));

```

### _userFromFirebase Private Func : 

```
  MyUser? _userFromFirebase(User? user) {
    if (user == null) {
      return null;
    }
    return MyUser(uid: user.uid);
  }

```

**_Ask me if do you want more code , Thanks in advance_**

**Comment by rrousselGit** [comment]
The problem is most likely not `listen`. Rather, you have an ancestor widget that rebuild, which caused your `LandingUser` to rebuild too.


But to begin with, that's not the real problem. Your issue is that your `onChangeStateUser` implementation is incorrect. 

It is critical that `auth.onChangeStateUser == auth.onChangeStateUser`, but it is not the case in your example.

Maybe you want:
```dart
@override
late final Stream<MyUser?> get onChangeStateUser = _auth.authStateChanges().map((event) => _userFromFirebase(event));
```

**Comment by heXaCo0l** [comment]
> The problem is most likely not `listen`. Rather, you have an ancestor widget that rebuild, which caused your `LandingUser` to rebuild too.
> 
> But to begin with, that's not the real problem. Your issue is that your `onChangeStateUser` implementation is incorrect.
> 
> It is critical that `auth.onChangeStateUser == auth.onChangeStateUser`, but it is not the case in your example.
> 
> Maybe you want:
> 
> ```dart
> @override
> late final Stream<MyUser?> get onChangeStateUser = _auth.authStateChanges().map((event) => _userFromFirebase(event));
> ```
Thanks for your replay!
Getters need a body how can I implement it ? and here is the class that contain the method `onChangeStateUser` . And I just called `onChangeStateUser`  in the main! . Thanks for your efforts 
```
class AuthService{
  final FirebaseAuth _auth = FirebaseAuth.instance;
  User? _user = _auth.currentUser;

  // current User
  MyUser? _userFromFirebase(User? user) {
    if (user == null) {
      return null;
    }
    return MyUser(uid: user.uid);
  }

  @override
  Future<MyUser?> currentUserAuth() async {
    final user = _auth.currentUser;
    return _userFromFirebase(user);
  }

  //late final Stream<MyUser?> get onChangeStateUser = _auth.authStateChanges().map((event) => _userFromFirebase(event));
  //late final Future<Stream<MyUser?>> get onChangeStateUser async => _auth.authStateChanges().map((event) => _userFromFirebase(event));

  Stream<MyUser?> get onChangeStateUser => _auth.authStateChanges().map((event) => _userFromFirebase(event));

}
```

**Comment by rrousselGit** [comment]
Sorry typo. I meant `late final Type name = `, without `get` keyword.
