### ISSUE TITLE
The following NoSuchMethodError was thrown building _InheritedProviderScope<AppLoadingModel>(value: <not yet loaded>):

### ISSUE THREAD

**Issue by dev-zl** [rrousselGit/provider#678]
I don't know this what error !
please help me.

provider: ^5.0.0

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _InheritedProviderScope<AppLoadingModel>(value: <not yet loaded>):
The getter '_parent' was called on null.
Receiver: null
Tried calling: _parent

The relevant error-causing widget was: 
  _InheritedProviderScope<AppLoadingModel> file:///E:/dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/provider-5.0.0/lib/src/inherited_provider.dart:159:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Element._debugCheckForCycles (package:flutter/src/widgets/framework.dart:3617:21)
#2      Element.inflateWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:3608:7)
#3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3610:6)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```
  runApp(MultiProvider(
    providers: [
     // Provider<AppLoadingModel>(create:(_)  => AppLoadingModel(),),
      ChangeNotifierProvider(
        create: (_) => AppLoadingModel(),
      ),
    ],
    child:  MyApp(),
  ));
```

```
class AppLoadingModel with ChangeNotifier ,DiagnosticableTreeMixin {
  bool state = true;

  bool get value => state;

  void show() {
    state = false;
    notifyListeners();
  }

  void hide() {
    state = true;
    notifyListeners();
  }

}
```

**Comment by rrousselGit** [comment]
Hello!
Do you have a complete way to reproduce the issue? This code should work fine.

**Comment by dev-zl** [comment]
> Hello!
> Do you have a complete way to reproduce the issue? This code should work fine.

Hi I find the problem，`child:  MyApp(),`   MyApp

**Comment by dev-zl** [comment]
@rrousselGit
