### ISSUE TITLE
Change Notifire Provider is not working in the main.dart file please correct is isssue....

### ISSUE THREAD

**Issue by MavaniVijay** [rrousselGit/provider#681]
**Describe the bug**

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

**Comment by davidmartos96** [comment]
@MavaniVijay  You should follow the issue template and provide both a description and a sample code that reproduces the issue you are having. Otherwise it's impossible to tell what could be happening.

**Comment by rrousselGit** [comment]
Closing as there is no information about the problem.

Feel free to open a new issue that fully describes the problem. 😄
