### ISSUE TITLE
Should we add `dispose` to ChangeNotifierProvider

### ISSUE THREAD

**Issue by filiph** [rrousselGit/provider#69]
I know `ChangeNotifierProvider` automatically disposes of the provided value itself. 

But I hit [a case](https://github.com/flutter/samples/blob/master/scoped_model_counter/lib/main.dart#L12) when I'm creating a `Timer` that modifies the `ChangeNotifier` during its lifetime. (That's obviously just a sample, and it's too synthetic and generally bad.) In this case, it would be nice to be able to dispose of the Timer with the ChangeNotifier.

I hypothesize that something similar will quite often happen in the real world as well. For example, you have a ChangeNotifier that you use as a "view model", and network events can change it. Now, you could put the network logic into the ChangeNotifier, but sometimes it's nicer to have it as a separate class. For example, you could have:

```dart
ChangeNotifierProvider(
  builder: (context) {
    var network = MyNetworkConnection();
    return MyModel(network);
  }
  dispose: ???,
  child: ...
}
```

Welp, I just realized that you can't do that, since the dispose callback wouldn't give you the `MyNetworkConnection` object. 

So, never mind. This is probably another use case for ProxyProvider, where I provide the `MyNetworkConnection` to the `ChangeNotifierProvider<MyModel>`.

Feel free to close this immediately. Just wanted to have this around for future reference.

**Comment by rrousselGit** [comment]
I don't see any clean way to do so with a custom callback. That's also why `StreamProvider.builder` is required to return a `StreamController` instead of `Stream`.

The best solution is probably a subclass of `MyModel`:


```dart
class MyNetworkModel  extends MyModel {
  MyNetworkModel._(this._network): super(_network);
  
  factory MyNetworkModel() {
    return MyNetworkModel._(MyNetworkConnection());
  }
  
  final MyNetworkConnection _network;
  
  @override
  void dispose() {
    _network.dispose();
    super.dispose();
  }
}
```


Note that the factory is not always necessary. If the superclass exposes the argument as a property a simple constructor is enough.
That's an example of the worst case scenario.

**Comment by subzero911** [comment]
Just encountered the same issue:
![image](https://user-images.githubusercontent.com/12999702/89306450-9015f880-d678-11ea-8639-0b9c1c5c75d6.png)
Provider widget has a `dispose` callback. But ChangeNotifierProvider has not.
Where to call a `close` method?

**Comment by rrousselGit** [comment]
Override "dispose"
