### ISSUE TITLE
"Null check operator used on a null value" when calling a Provider at dispose()

### ISSUE THREAD

**Issue by hakimLyon** [rrousselGit/provider#692]
@override
  void dispose() {
    Provider.of<ApplicationBloc>(context, listen: false).dispose(); ///_CastError (Null check operator used on a null value)
    locationSubScription.cancel();
    super.dispose();
  }

**Comment by LeonardoRosaa** [comment]
You can't access `InheritedWidgets` within `dispose` and is necessary cast your `Provider`. Example:

```dart
late final MyProvider myProvider;

@override
void initState() {
   myProvider = Provider.of<MyProvider>(context, listen: false);
   super.initState();
}

@override
void dispose() {
  myProvider.dispose();
  super.dispose();
}
```

**Comment by LeonardoRosaa** [comment]
@hakimLyon it's help you??

**Comment by hakimLyon** [comment]
thanks u @LeonardoRosaa
