### ISSUE TITLE
failed to pass Chinese parameters

### ISSUE THREAD

**Issue by bhlin790** [rrousselGit/provider#694]
**Describe the bug**
String address = EncryptUtil.encodeBase64('百');  // address = '55m+'
NavigatorUtils.push(context, '${Routers.modifyAddress}?address=$address');

Routers：
final String address = params['address']?.first ?? ''; // address = '55m '

**Comment by rrousselGit** [comment]
Hello

How is this related to provider? Did you maybe want to open an issue on the Flutter repository?

**Comment by rrousselGit** [comment]
:wave:
I'll close this issue since it seems unrelated to Provider and got no reply
