### ISSUE TITLE
Short blinking / appearance while user is signed in and the app is loading

### ISSUE THREAD

**Issue by desmeit** [rrousselGit/provider#699]
I have a simple authentification with firebase:

```
MultiProvider(
        providers: [
          Provider<AuthenticationService>(
            create: (_) => AuthenticationService(FirebaseAuth.instance),
          ),
          StreamProvider(
            create: (context) =>
                context.read<AuthenticationService>().authStateChanges,
            initialData: null,
          ),
```

The Authentification Wrapper checks if the user is signed in or not. Depending on this, it will be forwarded. 

```
final firebaseUser = context.watch<User>();

 if (firebaseUser != null ) {
     
     return CupertinoHomePage();
  
}

return Walkthrough();
```

The problem is, as long as the user is still NULL, the walkthrough screen is displayed for a short moment, a few milliseconds. After that it is redirected to CupertinoHomePage(). This short blinking/appearance does not look nice. Is there a way to query the status (e.g. like in Streambuilder) with 

`if (snapshot.connectionState == ConnectionState.active) `

or somethink like this? 

How can such an issue be solved?

[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
    • Flutter version 2.5.1 at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (9 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

**Comment by rrousselGit** [comment]
You may instead want to pass a valid `initialData` by waiting inside your `main` the first `User` instance

```dart
void main() async {
  final initialUser = await FirebaseAuth.instance.onAuthChange.first;

  ...

  StreamProvider(
    initialData: initialUser,
    create: (_) => onAuthChange,
  ),
}

**Comment by desmeit** [comment]
Okay thanks. I get

`The getter 'onAuthChange' isn't defined for the type 'FirebaseAuth'.`

What I'm doing wrong?

**Comment by rrousselGit** [comment]
I typed it from memory. The actual stream name is likely different

**Comment by desmeit** [comment]
I think its 

`userChanges().first`

I passed it to initialData but this is unfortunately not working. Its the same issue.

`if (firebaseUser != null ) {`

How exactly should the request look like?

Thanks for your help.

**Comment by rrousselGit** [comment]
You mean that `userChanges.first` emits `null`?

If so and if you're certain that the user is logged-in, maybe try `userChanges().firstWhere((e) => e != null)`

**Comment by desmeit** [comment]
No I mean that I am trying to build a function that prevents the walkthrough screen from displaying briefly while userchanges are being queried like my example above.

When I try this

```
  return StreamBuilder<User>(
      stream: context.read<AuthenticationService>().authStateChanges,
      builder: (context, AsyncSnapshot<User> snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final bool signedIn = snapshot.hasData;
          return signedIn ? CupertinoHomePage() : WalkThroughScreen();
        }
        return Scaffold(
            body: Container(child: Center(child: CircularProgressIndicator())));
      },
    );
```

then the issue does not occur. If I try it with

```

MultiProvider(
        providers: [
          Provider<AuthenticationService>(
            create: (_) => AuthenticationService(FirebaseAuth.instance),
          ),
          StreamProvider(
            create: (context) =>
                context.read<AuthenticationService>().authStateChanges,
            initialData: null,
          ),

...

final firebaseUser = context.watch<User>();

 if (firebaseUser != null ) {
     
     return CupertinoHomePage();
 
}

return Walkthrough();
```

I have the short blinking of WalkthroughScreen.
I am surprised because this structure is very often mentioned as an example. Instead of the stream builder. I want to prevent that while userchanges is still null, WalkthroughScreen is displayed.

**Comment by rrousselGit** [comment]
But as I mentioned your problem is `initialData: null`. If you don't want to show the `Walkthrough` page for a split second, you need to make sure that the initial data is not null

**Comment by desmeit** [comment]
Yes, I understand that. But what should I show? firebaseUser is related to userChanges. If userChanges is null, then firebaseUser is also null. What should I set in initialData instead?

**Comment by desmeit** [comment]
Excactly. But how can I make a difference between if the user is null OR its waiting for the user. Because during this time it is null as well.
