### ISSUE TITLE
The dispose method is not called

### ISSUE THREAD

**Issue by gisuper** [rrousselGit/provider#70]
The dispose method is not called

**Comment by rrousselGit** [comment]
Could you provide some code to reproduce?

**Comment by rrousselGit** [comment]
Had a quick look on your latest project.
Is this issue opened because of https://github.com/gisuper/my_flutter_app/commit/1b0fd0fda78fdd4db446bb2d5f9463e1ec3e5f9e ?



Looking at your code, the `Provider` is _always_ in the widget tree. So the dispose method cannot be called and it is working as intended.

Could you confirm that my assumptions are right?

**Comment by gisuper** [comment]
Method cannot execute how to free resources

**Comment by rrousselGit** [comment]
That's not enough information. I need a way to reproduce the error.

**Comment by gisuper** [comment]
`class CountBloc implements BlocBase {
  int _sumCount = 0;

  final StreamController<int> _streamController = StreamController<int>();
  StreamSink<int> get streamSink => _streamController.sink;

  final StreamController<int> _sumController = StreamController<int>();
  Stream<int> get stream => _sumController.stream;

  CountBloc() {
    _streamController.stream.listen(onData);
  }


  void onData(int event) {
    _sumCount = _sumCount + event;
    _sumController.add(_sumCount);
    print("_sumCount:$_sumCount");
  }

  @override
  void dispose() {
    print("dispose");
    _streamController.close();
    _sumController.close();
  }

  @override
  void init() {
    print("init");
  }

}`

**Comment by gisuper** [comment]
`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider<Bloc>(
      builder: (_) => Bloc(),
      dispose: (_, value) => value.dispose(),
      child: RootAppWidget(),
    );
  }
}`

**Comment by gisuper** [comment]
`class Bloc {
  final StreamController<int> _streamControllerAdd = StreamController();
  final StreamController<int> _streamControllerSum = StreamController();
  Stream<int> streamSum;
  StreamSink<int> addStreamSink;

  Bloc() {
    Stream<int> stream = _streamControllerAdd.stream.asBroadcastStream();
    streamSum = _streamControllerSum.stream.asBroadcastStream();
    addStreamSink = _streamControllerAdd.sink;
    stream.listen(onData);
  }


  void dispose() {
    print("dipose");
    _streamControllerAdd.close();
    _streamControllerSum.close();
  }

  int sum = 0;
  void onData(int event) {
    print("event:$event");
    sum = sum + event;
    _streamControllerSum.add(sum);
  }
}`

**Comment by gisuper** [comment]
`class PictureDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: StreamBuilder<int>(
          stream: Provider.of<Bloc>(context).streamSum,
          builder: (context, snapshot) {
            return Text(snapshot.data?.toString() ?? 'Foo');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(onPressed: (){
        Provider.of<Bloc>(context).addStreamSink.add(1);
      },child: Text("Add"),),
    );
  }
}`

**Comment by rrousselGit** [comment]
That's working as intended. 

Your `Provider` wraps the entire application, therefore, it never needs to be disposed.

**Comment by gisuper** [comment]
If the project has many modules and writes many streams , will it take up much memory?

**Comment by rrousselGit** [comment]
It depends on many parameters, including where the providers are placed and what are the exposed values.
But overall it's not the stream that eats memory, but the data inside it.

**Comment by gisuper** [comment]
Thank you. I'm a beginner
Provide Google is not recommended?

**Comment by rrousselGit** [comment]
I'm not related to Google. I can't speak for them to say if you should use or not https://github.com/google/flutter_provide

Maybe @filiph can answer you. Or make an issue on `provide` repository directly.

**Comment by leedstyh** [comment]
Hi @rrousselGit I'm facing the same issue here, would your help me checking my code here:

```

class CounterModel with ChangeNotifier {
  int _count = 0;
  int get counter => _count;

  void add() {
    _count++;
    notifyListeners();
  }

  @override
  dispose() {
    print("child.dispose()");
    super.dispose();
  }
}

class AppTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: _AppTestFirst(),
    );
  }
}

class _AppTestFirst extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("First Page"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => _AppTestSecond(),
          ));
        },
        child: Icon(Icons.navigate_next),
      ),
    );
  }
}

class _AppTestSecond extends StatelessWidget {
  final counterModel = CounterModel();
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<CounterModel>.value(
      value: counterModel,
      child: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Consumer<CounterModel>(
            builder: (_, CounterModel state, __) {
              return Text("${state.counter}");
            },
          ),
        ),
        floatingActionButton: Consumer<CounterModel>(
          builder: (_, CounterModel state, __) {
            return FloatingActionButton(
              onPressed: state.add,
              child: Icon(Icons.add),
            );
          },
        ),
      ),
    );
  }
}
```

After I click the back icon on the second page, I didn't get the message `child.dispose()` in console

**Comment by rrousselGit** [comment]
Only the default constructor of `ChangeNotifierProvider` disposes the `ChangeNotifier`.

Instead of creating the notifier as a field of _AppTestSecond, create it instead the _builder_ method of the default constructor

**Comment by leedstyh** [comment]
Thanks @rrousselGit , works like a charm

**Comment by alexsotocx** [comment]
@rrousselGit 

> Only the default constructor of ChangeNotifierProvider disposes the ChangeNotifier.

Question there, I'm facing the same but I need to use ChangeNotifier.value constructor because I need to Apply some async logic before the notifier is mounted to tree and pushed with the Route.

Is there a way to dispose the provider( pushed with ChangenotifierProvider.value) after the route has been pop?

**Comment by rrousselGit** [comment]
> but I need to use ChangeNotifier.value constructor because I need to Apply some async logic before the notifier is mounted to tree

You could still use the default constructor.

```dart
ChangeNotifierProvider<ChatProvider>(
  builder: (_) => chatProvider,
  child: Injector.getInjector().get<ChatScreen>(),
  key: Key('chat_provider_router'),
),
```

This should work as expected.

**Comment by alexsotocx** [comment]
Yes,  it does, but with the new update in the test it throws an error :( https://github.com/rrousselGit/provider/blob/master/packages/provider/lib/src/listenable_provider.dart#L136

**Comment by rrousselGit** [comment]
Which means that your `chatProvider` is used by another object somewhere else.

Are you sure that it is "legal" to dispose it on route pop? Because that "other object" may still be using it.

**Comment by alexsotocx** [comment]
Thanks @rrousselGit, for pointing me in the right direction (The listener part). 
After reading the provider code (https://github.com/rrousselGit/provider/blob/master/packages/provider/lib/src/listenable_provider.dart#L136) carefully, I discover that my Mock provider was returning null, so the assertion was failing.

Updated successfully

**Comment by rrousselGit** [comment]
Should that line be changed from `assert(!notifier.hasListeners)` to `assert(notifier.hasListeners == false)`?

This would make `null` a "valid value", for mock purposes.

**Comment by alexsotocx** [comment]
Well it will be easier, but i think it will make code not readable.  
Now I have a workaround to solve it.
```
class MockChatProvider extends Mock implements ChatProvider {
  bool get hasListeners => false;
}
```

But for testing people will have problems figuring out the problem
