### ISSUE TITLE
CheckboxListTile cannot work with Provider

### ISSUE THREAD

**Issue by imansejati** [rrousselGit/provider#714]
CheckboxListTile is working properly using flutter usual changestate, but not work with Provider, it's can tick (check/ uncheck) while using provider, it's not happened with Switch Widget or Checkbox Widget, I attach example code, please check

 `import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<CobaProvider>(
      create: (_) => CobaProvider(),
      child: MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: Text('percobaan'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Consumer<CobaProvider>(
                  builder: (context, cobaProvider, _) => CheckboxListTile(
                      title: Text('Percobaan'),
                      value: cobaProvider.value,
                      onChanged: (newValue) {
                        cobaProvider.value;
                        newValue;
                      }),
                ),
                Consumer<CobaProvider>(
                    builder: (context, cobaProvider, _) => Switch(
                        value: cobaProvider.value,
                        onChanged: (newValue) {
                          cobaProvider.value = newValue;
                        })),
                Consumer<CobaProvider>(
                    builder: (context, cobaProvider, _) => Checkbox(
                        value: cobaProvider.value,
                        onChanged: (newValue) {
                          cobaProvider.value = newValue!;
                        })),
              ],
            ),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
}

class CobaProvider extends ChangeNotifier {
  bool _value = true;

  bool get value => _value;
  set value(bool v) {
    _value = v;
    notifyListeners();
  }
}`

**Comment by clragon** [comment]
Your code for the `CheckboxListTile` is not setting the provider value.
This `onChanged` does nothing:
```dart
Consumer(
  builder: (context, cobaProvider, _) => CheckboxListTile(
      title: Text('Percobaan'),
      value: cobaProvider.value,
      onChanged: (newValue) {
        cobaProvider.value;
        newValue;
      }),
),
```

You have to actually assign the value too:
```dart
onChanged: (newValue) {
  if (newValue != null) {
    cobaProvider.value = newValue;
  }
}
```

**Comment by rrousselGit** [comment]
Closing as this was answered
