### ISSUE TITLE
notifyListeners() not updating UI in release app

### ISSUE THREAD

**Issue by Kshitipuranik-gif** [rrousselGit/provider#715]
**EXPECTED BEHAVIOR**
I am fetching two list from Firebase Database and filtering them according to isActive status. In one list RadioListTile used in list view for showing mobile numbers, after selecting one mobile from list, that number is added in another list on click of BLOCK NUMBER button. User can release the blocked number using, RELEASE NUMBER button, then that blocked number gets added in active list. This is the success scenario. 

**PROBLEM IS**
 The issue is when releasing number from blocked list, RELEASE NUMBER button is not disappearing in release apk, but it is working ok with debug apk. Also same behavior with search functionality. In both scenario, variables values are as expected in logs, but  UI not updating accordingly.

**HERE IS THE CODE**

  if (model.showReleaseBtn)...[
                              Column(
                                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                                children: <Widget>[
                                  ElevatedButton(
                                    style: ElevatedButton.styleFrom(
                                      primary: AppColors.colorBlockedList,
                                    ),
                                    child: Text(
                                      AppConstants.releaseNoButton,
                                      style: blockNoBtnTextStyle,
                                    ),
                                    onPressed: () async {
                                      await FirebaseAnalytics.instance
                                          .logEvent(
                                        name: 'releaseNumberOtpRecFlutter',
                                      );
                                      model.value = -1;
                                      model.addNumberToActiveList();

                                    },
                                  ),
                                  Padding(padding: EdgeInsets.only(top: 10)),
                                  Text(AppConstants.otpReceivedText,
                                      textAlign: TextAlign.center,
                                      style: otpMessageTextStyle),
                                  Padding(padding: EdgeInsets.only(top: 10)),
                                  Text(
                                    model.otpMessage!,
                                    style: otpReceivedTextStyle,
                                  ),
                                ],
                              ),
                            ]
---------------------------------
void addNumberToActiveList(){ // called after clicking RELEASE NUMBER
    print('Block number released hide release number button');
  
    hideBtn = true;
    showReleaseBtn = false;
    disableBlockBtn = false;
    resetData();
 
  }

void resetData(){
    if(selPK != 'key') {

      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.isInactiveAndroidAppText).set(false);

      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.usedByUidText).set("");
      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.userNameText).set("");
      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.otpText).set("");
      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.blockedTimeText).set("");

      dbRef.child(AppConstants.mobileCollectionText).child(selPK).child(
          AppConstants.isActiveText).set(true);

      selPK = 'key';
      _otpMessage= "";
      notifyListeners();
      print('notifyListeners called $selPK');
    }

  }

**Comment by cgbrucezjy** [comment]
I've got similar scenario, and see people got it working with --no-shrink or add internet permission in manifest, but mine still doesn't work

**Comment by Alpha17-2** [comment]
I am facing the same issue , tried all the hacks suggested by users on stackoverflow but , they ain't solving the issue .

**Comment by rrousselGit** [comment]
As mentioned in other similar issues, please include a minimal reproducible example, otherwise there's nothing I can do to help.

**Comment by titusfrezer** [comment]
Same here also, I tried to use this way:  
Widget _buildPlayerIndicator(context){
    if(Provider.of<PodcastPlayer>(context).currentPodcastId == -1 && Provider.of<MusicPlayer>(context).currentMusicId == -1){
     print("neither");
     return Container();
    }else{
      if(Provider.of<PodcastPlayer>(context).currentPodcastId != -1 ){
        return const NowPlayingPodcastIndicator();
      }else{
        return const NowPlayingMusicIndicator();
      }
    }
 }


The Provider snippet code: 
void controlAudioWave(bool isPlaying) {
    if (!isPlaying) {
      isWaving = true;
    } else {
      isWaving = false;
    }
    notifyListeners();
  }

I don't know why but the UI is not updating, it works fine on debug mode; It is a weird situation didn't find any solution.

**Comment by rrousselGit** [comment]
In the lack of a minimal reproducible example, I'll close this issue. If you still have this problem, please open a new issue with a clear description on how to reproduce the problem.

**Comment by titusfrezer** [comment]
Thank you I was expected to close it, once I dealt with the solution

**Comment by igloo12** [comment]
@rrousselGit i am getting this issue too. Works in develop but doesn't work when i compile for production
