### ISSUE TITLE
context.read sometimes returns null

### ISSUE THREAD

**Issue by MRezaKarimi** [rrousselGit/provider#733]
Sometimes, after doing hot restart, calling context.read causes this exception:
![Screenshot from 2022-02-08 10-48-56](https://user-images.githubusercontent.com/39339552/152938342-655d803c-0fdb-4ba3-864d-da1996f4321a.png)

And here is the code snippet where problem occurs:
![Screenshot from 2022-02-08 10-57-43](https://user-images.githubusercontent.com/39339552/152938542-1634bbdd-b22b-43cb-9cd5-07d3fea1e28c.png)

In both lines I read Auth provider. The first line (L33), always runs without any problem but second line sometimes causes null exception.

**Comment by rrousselGit** [comment]
Are you somehow using a `context` that is disposed? The error is Flutter throwing. Your `context` seems broken

**Comment by MRezaKarimi** [comment]
I encountered the same error when using BLoC, but after upgrading to flutter 2.10 the problem solved. So I think it's related to a flutter bug.

**Comment by AnkitPanchal10** [comment]
I am facing the same issue. After a hot restart, the value of ChangeNotier does not update. 

<img width="983" alt="Screenshot 2022-12-20 at 4 50 53 PM" src="https://user-images.githubusercontent.com/38405884/208655329-65ad9588-0118-4e31-a598-e016d5cc38bb.png">

<img width="1265" alt="Screenshot 2022-12-20 at 4 35 12 PM" src="https://user-images.githubusercontent.com/38405884/208652538-fb5d17f1-2436-4d23-94ab-19e7480f5243.png">

So, first, I call tryAutologout(), and it's working okay, but after that, when I try to fetch the value of userData at line 86, it gives a null value. I have checked that context is not broken or dirty, but the value of Auth is not updated.
