### ISSUE TITLE
Flutter provider not working in release apk and profile mode, but working fine in debug mode

### ISSUE THREAD

**Issue by minhnhatvdl** [rrousselGit/provider#739]
**Describe the bug**
I use a provider version 6.0.1. Flutter provider (watch, consumer) is not working in release apk and profile mode, but working fine in debug mode.
Anyone has the same problem ?
Thank you very much !!!

**Comment by rrousselGit** [comment]
@Joezzy this issue is closed because there is no way to reproduce the problem.

If you still have the problem, open a new issue with a way to reproduce it

**Comment by Joezzy** [comment]
> @Joezzy this issue is closed because there is no way to reproduce the problem.
> 
> If you still have the problem, open a new issue with a way to reproduce it

Never mind. I'm using GetX now...works better
