### ISSUE TITLE
Pass provider via navigator?

### ISSUE THREAD

**Issue by hirenm1990** [rrousselGit/provider#74]
Hello,

I am learning provider way & found difficulty in lifting state up. I have three screens,

- Item listing screen
- Create item screen
- Edit item screen

I lift state up in item's listing screen & use provider there. Which is working perfectly fine. But now I need to access that same provider in create & edit screen.

One thing I can do is, initiate provider in MaterialApp() declaration, but problem is I have another 4-5 providers for other parts of the application, & it's not feeling good to put all providers in MaterialApp().

So, what I have done is, I am passing itemProvider of listing screen to create & edit screen in Navigator as argument like this.

`Navigator.pushNamed(
                  context,
                  "item.create",
                  arguments: {
                    'itemProvider': Provider.of<ItemProvider>(context)
                  },
                )`

My question is, is it a good thing to do or is there any other way to do this?

**Comment by rrousselGit** [comment]
>  it's not feeling good to put all providers in MaterialApp().


Can you explain why? This is the correct solution

**Comment by hirenm1990** [comment]
Thanks for the reply. 

I am doing some initialization to get items from rest API, only if user is loggedin. So, I only put AuthProvider in materialapp().

Now thay you say, its fine to put all providers in materialapp, I will put conditions in api call to check for authentication.

Thanks...
