### ISSUE TITLE
Update provder from 5.0.0 to 6.0.2

### ISSUE THREAD

**Issue by RoyalCoder88** [rrousselGit/provider#740]
Hi friends,

**Before I used:

provider: ^5.0.0, I have implemented something like that:**

` final post = documentSnapshot.data() as Map?;
          if ((index + 1) % 5 == 0) {`
          
=> no I migrated to provider: ^6.0.2, the same code now I get this error for .data()  : 
`The method 'data' isn't defined for the type 'int'.
Try correcting the name to the name of an existing method, or defining a method named 'data'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)`
![error_1](https://user-images.githubusercontent.com/6507433/157896331-36164a55-aa93-4fd4-a6ac-d0de2ccc67ad.png)

**and for the + :**  

The operator '+' isn't defined for the type 'BuildContext'.
Try defining the operator '+'.dart[undefined_operator](https://dart.dev/diagnostics/undefined_operator)
No quick fixes available
![error_2](https://user-images.githubusercontent.com/6507433/157896288-432836ee-7fa7-4e41-851c-83c59c72b22b.png)

**P.S I'm using:**
Flutter version: Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (4 weeks ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

Please help me asap, thanks in advance!

**Comment by rrousselGit** [comment]
Hello

What exactly is the relationship with provider here? I don't see provider code in the code you gave.
