### ISSUE TITLE
A way to Provide state to a route and all routes pushed on from that route.

### ISSUE THREAD

**Issue by Turburlar** [rrousselGit/provider#741]
I have run into a problem, and I am not sure what the best solution is, or if there is a solution that Provider can provide for this...either way here it is.

I have a Page that I am pushing onto the Navigator stack and I am providing ChangeNotifier to it. All pages pushed on the stack after that page required the same ChangeNotifier, but they do not have access to it, because it is not above them in the tree.

I either have to place the ChangeNotifier above the navigator, which does not make sense, because that state is not known at that point, or I have to manually pass the ChangeNotifier around to all new routes, which is verbose and tedious.

Concrete example.

I have a tic tac toe app. I have an initial page that displays a list of of tic tac toe matches. The list of games is fetched from and endpoint that returns a json list of MatchInfo that contains matchId and matchName. I have a MatchInfosChangeNotifier that handles the list of MatchInfos. 

When the user selects a match I take the matchInfo matchId, and construct a MatchChangeNotifer which hits an endpoint that takes matchId and then encapsulates all the details of the match and all behaviours around updating the match. All data for a single match is exposed and manipulated through this ChangeNotifier. 

I then push on a route which is a MatchPage wrapped in a provider for MatchChangeNotifier. Inside of the MatchPage I can jump to the MatchMoveHistoryPage, and the MatchChatPage, and the MatchStrategyPage. All of these pages that will be pushed on the stack after the MatchPage all relate to a single instance of a Match, just like the initial MatchPage....therefore they all depend on the same MatchChangeNotifier.

In this scenario, it would be great if I could provide state when I call push, and all subsequent push will provide the same state, until the navigation stack has had the initial route popped off.

Does this request make any sense, or am I just completely going about things wrong?

**Comment by rrousselGit** [comment]
You will either have to place your provider above MaterialApp, or manually re-insert the provider in pushed routes

**Comment by Turburlar** [comment]
Does Riverpod provide a better story for this use case?

**Comment by rrousselGit** [comment]
Yes, at least in the version 2.0.0-dev

You can do (pseudo code, didn't check compilation errors):

```dart
// in the original route:
final container = ProviderScope.containerOf(context);

showDialog(
  context: context,
  builder: (context) {
    return ProviderScope(parent: container, child: MyDialog());
  },
);
```

This allows `MyDialog` to access providers that are scoped to the route that pushed the dialog
