### ISSUE TITLE
LateInitializationError: Field 'productProvider' has not been initialized.

### ISSUE THREAD

**Issue by AnilGusaiwal** [rrousselGit/provider#747]
======== Exception caught by widgets library =======================================================
The following LateError was thrown building Home_Screen(dirty, state: _Home_ScreenState#7e669):
LateInitializationError: Field 'productProvider' has not been initialized.

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:zometo/product_overview.dart';
import 'package:zometo/providers/product_provider.dart';
import 'package:zometo/review_card.dart';
import 'package:zometo/search/search.dart';
import 'package:zometo/singal_product.dart';
import 'package:provider/provider.dart';
import 'DrawerPages/drawer_page.dart';

class Home_Screen extends StatefulWidget {
  @override
  State<Home_Screen> createState() => _Home_ScreenState();
}

class _Home_ScreenState extends State<Home_Screen> {
  late ProductProvider productProvider;
  @override
  void initState() {
    ProductProvider productProvider = Provider.of(context, listen: false);
    productProvider.fatchHerbsProductData();
    super.initState();
  }

  Widget _buildHerbsProduct() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.all(6.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Fresh Fruits'),
              Text('View all'),
            ],
          ),
        ),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(
            children:
            productProvider.getHerbsProductDataList.map((herbsProductData) {
              return singalProduct(
                onTap: () {
                  Navigator.of(context).push(MaterialPageRoute(
                      builder: (context)=>
                          Product_Overview(
                              productImage:'https://www.linkpicture.com/q/leaf-removebg-preview.png',
                              productName: herbsProductData.productImage)));
                },
                  productImage:herbsProductData.productName,
                  productName: 'Fresh Basil',
              );
            }).toList(),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xfff6f1f1df),
      drawer: Drawer_page(),
      appBar: AppBar(
        iconTheme: IconThemeData(color: Colors.black),
        title: Text('Home', style: TextStyle(color: Colors.black)),
        backgroundColor: Color(0xffd6d738),
        actions: [
          CircleAvatar(
            backgroundColor: Color(0xffd6d738),
            child: IconButton(
                icon: Icon(Icons.shop),
                onPressed: () {
                  Navigator.of(context).push(
                      MaterialPageRoute(builder: (context) => Review_Card()));
                },
                color: Colors.black),
            radius: 15,
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: CircleAvatar(
              backgroundColor: Color(0xffd6d738),
              child: IconButton(
                icon: Icon(Icons.search),
                onPressed: () {
                  Navigator.of(context)
                      .push(MaterialPageRoute(builder: (context) => Search()));
                },
                color: Colors.black,
              ),
              radius: 15,
            ),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(6.0),
        child: ListView(
          children: [
            Container(
              height: 150,
              width: double.infinity,
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(10.0),
                image: DecorationImage(
                  fit: BoxFit.cover,
                  image: NetworkImage(
                      'https://image.shutterstock.com/image-photo/source-protein-vegetarians-top-view-600w-1198340449.jpg'),
                ),
              ),
              child: Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(right: 150),
                          child: Container(
                            height: 40,
                            width: 50,
                            decoration: BoxDecoration(
                              color: Colors.yellow,
                              borderRadius: BorderRadius.only(
                                  bottomRight: Radius.circular(50),
                                  bottomLeft: Radius.circular(50)),
                            ),
                            child: Text(
                              "Vegi",
                              style: TextStyle(
                                  fontSize: 22,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white,
                                  shadows: [
                                    BoxShadow(
                                      blurRadius: 9,
                                      color: Colors.green,
                                      offset: Offset(2, 2),
                                    ),
                                  ]),
                            ),
                          ),
                        ),
                        Text(
                          '   30% Off',
                          style: TextStyle(
                              fontSize: 40,
                              fontWeight: FontWeight.bold,
                              color: Colors.white),
                        ),
                        Text(
                          'On All Vegitables Products',
                          style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                              color: Colors.white),
                        ),
                        SizedBox(
                          height: 10,
                        ),
                        Text(
                          'Read Terms nad conditions',
                          style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: Colors.white),
                        ),
                      ],
                    ),
                  ),
                  Expanded(child: Container()),
                ],
              ),
            ),
            _buildHerbsProduct(),

          ],
        ),
      ),
    );
  }
}

**Comment by rrousselGit** [comment]
Hello!

This is unrelated to package:provider.

It seems like you tried to access the variable `_Home_ScreenState.productProvider` before it was initialized. Assign the variable and the error should disappear
