### ISSUE TITLE
Provide named dependencies

### ISSUE THREAD

**Issue by PenF00k** [rrousselGit/provider#75]
I want to have the ability to provide multiple implementations of one interface (or multiple instances of the same class) and to consume the one I need depending on the name.
Something like this to provide
MultiProvider(
      providers: [
            Provider<String>.value(value: "Object one", name: "oneone"),
            Provider<String>.value(value: "Object two", name: "twotwo"),
      ],
      .......
)

...and to consume
Provider.of<Object>(context, name: "oneone")
Provider.of<Object>(context, name: "twotwo")

How can achieve this?
Thanks :)

**Comment by rrousselGit** [comment]
You can't do that. Instead consider making custom classes:

```dart
class OneOne {
  OneOne(this.value);

  final String value;
}

Provider.value(value: OneOne("Object one"))
```

**Comment by matejwamf** [comment]
Is this dart limitation or design limitation?

named dependencies would be really cool for playground/testing where we could provide different flavours.

**Comment by rrousselGit** [comment]
Dart limitation (or Flutter depending on the point of view)

Either we need first class citizen class, or a "scope" feature on Flutter's Inheritedwidgets.

There are ways to achieve this feature without both, it requires some extremely unsane workarounds — which means the feature may stop working at a later time.

**Comment by matejwamf** [comment]
Gotcha. Thx.

I love provider 3 <3

It is genius at work
