### ISSUE TITLE
Update package to Flutter 3.0 compatible

### ISSUE THREAD

**Issue by Shadow60539** [rrousselGit/provider#754]
**Current bug behavior**

When starting my app or tests, I always get the warning `Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null`.

![bug](https://user-images.githubusercontent.com/59445273/169649773-c20e7b6f-bd4b-40a1-beef-891a32d2f89d.png)

**To Reproduce**

Update to the new flutter version `3.0.0` and start an application that uses this package.

**Comment by FZ985** [comment]
+1

**Comment by rrousselGit** [comment]
You're using version 5.0.0

Provider is at version 6.0.3, which doesn't use SchedulerBinding
