### ISSUE TITLE
Selective state recreation

### ISSUE THREAD

**Issue by clragon** [rrousselGit/provider#764]
**Is your feature request related to a problem? Please describe.**
Some of the objects I want to provide can hold state and also depend on other providers above them.
`Provider` offers two ways of handling this;
Either I use the `Provider.update` function to recreate my object with the new state of the other providers,
or I use a `ChangeNotifier` which then contains a method to update the object with the new parent states.

Since my objects hold state themselves, recreating them in the update function of a `ProxyProvider` without any conditions cannot work, because it leads to over-recreation. Any rebuild will recreate them, which is undesirable and I lose state.
This means I would have to fill the update function with If statements that only recreate said object if the parents changed, however, this would require state, so I have to make my widget stateful and store the last version of said parents, or something similar to that.
this does not seem very nice to me.

If my objects are `ChangeNotifiers` then I can use a `ChangeNotifierProxyProvider`, but `ChangeNotifierProxyProvider` is setup in a way that does not allow passing the dependencies into the object via the constructor.
If my object is a `ChangeNotifier`, I now have to create a new method to sideload my parent state,
which means my object can temporarily be in an "invalid" state, where the parent dependencies are not available yet.
This does not work well with objects that could be used without a `Provider`, where the parent dependencies _are required_.
If I do not want to change my objects, then I have to wrap them with a `ChangeNotifier` that then recreates them internally.
if they are themselves `ChangeNotifiers` then I now have a weird construct that wraps a `ChangeNotifier` with a `ChangeNotifier` so that I can replace the inner `ChangeNotifier`. it also means that I now have to unpack my inner `ChangeNotifier` everytime I grab it from context. This also does not seem appealing to me.

**Describe the solution you'd like**
It would be nice if there was some easy way of having my providers only recreate their value when their dependencies change, kind of like a `select` but for provider values. 

I am not sure if I just missed something or if the thing that I am attempting would be bad practice or abuse of the way `Provider` works.

Regardless, it is actually possible to _kind of_ add this functionality in a reusable way from the outside, with a `mixin` as I have done here:
https://gist.github.com/clragon/cadf818800c86b60b9c560673ecf6356
this adds a `guard` function matching each `ProxyProvider` / `ChangeNotifierProxyProvider` variant and works similar to a `select` by checking a list of values for deep equality. It is used like this:
```dart
class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) => ProxyProvider<Settings, Client>(
    update: guard(
      create: (context, value, value2) => Client(
        settings: value,
        dispose: (context, value) => value.dispose,
      ),
      dispose: (context, value) => value.dispose,
      child: /* whatever */,
    ),
  );
}
```

there are some problems with this, for example that it requires a mixin to hold the state for comparison and because the creation method is now held inside the guard function, I need to also pass the dispose function twice. 

If this functionality was provided inbuilt in some way, it would probably be easier and nicer. 
I am not sure how exactly this would take shape in the library, however.

edit: I have just thought about it, and this might be possible if I were to implement my own `Provider` based on one of the for this made classes. I haven't really looked at them before, so I don't know however.

**Describe alternatives you've considered**
Many of the alternatives have been listed above, but are undesirable in some way.

**Additional context**
I have setup a small project to play around with this conundrum.
In there, I am manually writing out all the code necessary to make this work without the guard mixin.

<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

// Parent class, represents a dependency of the Child
class Parent {
  Object id;

  Parent() : id = Object();
}

// Child class. depends on the parent but also holds own state.
// Becomes invalid if the Parent changes.
class Child with ChangeNotifier {
  final Parent parent;
  Object id;

  Child(this.parent) : id = Object();

  void changeId() {
    id = Object();
    notifyListeners();
  }
}

void main() {
  // intentionally disabled, check further down
  Provider.debugCheckInvalidValueType = null;
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // Parent can be replaced in some way.
  Parent parent = Parent();

  // keeps track of the previous parent
  Parent? _previousParent;

  @override
  Widget build(BuildContext context) => Provider.value(
        value: parent,
        // cannot use ChangeNotifierProxyProvider because it would force me
        // to change my Child class to accept a Parent in a method and not the constructor,
        // allowing it to be in an invalid state, where no parent is available.
        // this is kind of okay as long as the user always knows about this, but even then its not particularly nice.
        builder: (context, child) => ProxyProvider<Parent, Child>(
          update: (context, value, previous) {
            // prevents the Child state from being discarded if we are rebuilt without the Parent changing.
            // this requires us to hold the previous parent in state somewhere.
            // it also becomes very verbose the more parents we have, and is even with a single one quite much to write everytime.
            if (value != _previousParent) {
              _previousParent = value;
              return Child(value);
            } else {
              return previous!;
            }
          },
          builder: (context, child) => Scaffold(
            appBar: AppBar(
              title: const Text('Example'),
            ),
            body: Center(
              // listening to child changes because we are not using ChangeNotifierProxyProvider
              child: AnimatedBuilder(
                animation: Provider.of<Child>(context),
                builder: (context, child) {
                  return Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                          'Parent: ${Provider.of<Parent>(context).id.hashCode}'),
                      Text('Child: ${Provider.of<Child>(context).id.hashCode}'),
                      const SizedBox(height: 24),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          OutlinedButton(
                            onPressed:
                                Provider.of<Child>(context, listen: false)
                                    .changeId,
                            child: const Text('change child ID'),
                          ),
                          const SizedBox(width: 8),
                          OutlinedButton(
                            onPressed: () => setState(() => parent = Parent()),
                            child: const Text('change parent'),
                          ),
                        ],
                      ),
                    ],
                  );
                },
              ),
            ),
            // would cause the Child state to be discarded if we were not guarding it with an If statement.
            floatingActionButton: FloatingActionButton.extended(
              onPressed: () => setState(() {}),
              label: const Text('random setState'),
              icon: const Icon(Icons.shuffle),
            ),
          ),
        ),
      );
}
```

</details>

**Comment by rrousselGit** [comment]
Hello!

I don't think it makes sense to use `create` if you're storing the state outside of the provider.
If you want such a thing, consider using `MyProvider.value` instead

Using `Provider.value` you should have enough to make your own "proxy"variants which better fit your use-case, without forcing users to use a StatefulWidget+mixin to use them

**Comment by clragon** [comment]
Hi,

I am not sure if I can follow what you mean.
The only reason I am storing state is so that I can know when my dependencies have changed,
so that my object that I am providing can be recreated. 

Of course I could create my object inside of `didChangeDependencies` and use `Provider.value` which would have a similar outcome, meaning it would could be rebuilt arbitrarily and I would have to shield it with several if statements that check against the last known value of those dependencies. 
To make such a structure reusable, I would still have to use a mixin in the end, or not?

**Comment by rrousselGit** [comment]
You wouldn't need the mixin, because you could make a widget instead

You can create a reusable StatefulWidget which returns a provider and does the dependency tracking.

**Comment by clragon** [comment]
I see, that makes sense to me. 
Thank you for your help, I will solve this in that wy then!

**Comment by clragon** [comment]
I have given this some though and I believe the most elegant way of integrating this would be to add a "selector" parameter to `ProxyProvider` and `ChangeNotifierProxyProvider` (and maybe normal Provider too), which accepts a `List<dynamic> Function(BuildContext)`. 
The list would then be compared with `DeepCollectionEquality` and if it changed, the `create` function would be called again.

If that list by default would be empty, this could be done with full backwards compatibility, no breaking changes.
If the list by default contains all other Providers we depend on, that would perhaps be a breaking change, but very convenient for my usecase. 

This would also enable "stateless" (without a statefulwidget) recreation of Providers that depend on a Parameter that is passed in, for example an ID or something and for which it would be easier to recreate them than to reuse them like the update function in `ChangeNotifierProxyProvider` does.

**Comment by clragon** [comment]
i think this might be too specific to my usecase to be part of the library.
However, it would be alot simpler to implement if we had access to the delegate classes of the inbuilt providers.
