### ISSUE TITLE
community package transfer

### ISSUE THREAD

**Issue by clragon** [rrousselGit/provider#771]
**Is your feature request related to a problem? Please describe.**
I appreciate the provider package.
I use it much like inherited widgets except that I can use generics
and cut down on class delcarations.

According to your [tweet](https://twitter.com/remi_rousselet/status/1558718357578416131), 
the package might be "deprecated" (?) at some point.

I am not sure if this information is still up to date, but I am assuming that it is.
I would like to continue using this package in the future.

You have mentioned that you will provide a migration tool to upgrade from provider to riverpod.
Personally, I do not see riverpod as a replacement for provider.
I think riverpod is its own thing in alot of ways.
I would therefore like to avoid migrating to riverpod.

**Describe the solution you'd like**
In case you are still planning on deprecating the provider package,
or if you do not wish to continously maintain the provider package in the future,
would it be possible to transfer the package to the [flutter community](https://github.com/fluttercommunity/community) project instead?

Many packages depend on provider and I assume alot of them cannot be flawlessly translated to riverpod.
There might also be instances of people enjoying the workflow of provider alot better.
I think it would therefore be undesirable to deprecate this package.

**Additional context**
A package can be transfered to the community via [this guide](https://github.com/fluttercommunity/transfer-guide).
This can ensure that the package lives on and is maintained 
without being requiring the original creator to continously put maintenaince into it.

**Comment by rrousselGit** [comment]
This is too early to discuss.

As I mentioned, there's still a few things that needs to be sorted out to have a definitive answer to this question.

**Comment by rrousselGit** [comment]
But to be honest, for now I don't quite like the idea of transferring it.

It's not a case of "the current maintainers don't have the bandwidth to work on the project".
It'd be a depreciation notice

Transferring it goes against the objective. It'd imply that the project would not be deprecated

**Comment by clragon** [comment]
I understand. I believe it would be undesirable to deprecate the package, which is why I brought this up.
