### ISSUE TITLE
How to check if ChangeNotifier has been disposed

### ISSUE THREAD

**Issue by wemped** [rrousselGit/provider#78]
I'm just trying out Provider for the first time, and struggling to find the equivalent of `State`'s `mounted` property.

I have a class that mixes in `ChangeNotifier`. In one of its methods it awaits on a network call, then `notifyListeners()` with the result of that network call.

If the user has navigated away while the network call is pending, I get an error
```
E/flutter (27530): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: A XXX was used after being disposed.
E/flutter (27530): Once you have called dispose() on a XXX, it can no longer be used.
E/flutter (27530): #0      XXX&Object&ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
E/flutter (27530): #1      XXX&Object&ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
E/flutter (27530): #2      XXX&Object&ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
```

In the basic `StatefulWidget` scenario, I would just check `if (mounted)` before calling `setState`. Is there an equivalent for `ChangeNotifier`?

Thanks!

**Comment by rrousselGit** [comment]
You can override `dispose` to implement a `mounted` yourself

**Comment by jamesdixon** [comment]
Running into this myself and assume it's probably a common issue. Is there a recommended way of dealing with this scenario?

**Comment by jamesdixon** [comment]
@wemped did you ever come up with a solution for this issue?

**Comment by vedant-comspade** [comment]
@rrousselGit @wemped Can you show me how you did it?

**Comment by deshario** [comment]
@rrousselGit How to do it ?

**Comment by rrousselGit** [comment]
```dart
abstract class Example {
  bool _mounted = false;
  bool get mounted => _mounted;

  @override
  void dispose() {
    super.dispose();
    _mounted = true; 
  }
}
```

**Comment by marcglasberg** [comment]
`true` and `false` should be the opposite for the `_mounted` property in the above code...

**Comment by von-maurus** [comment]
> ```dart
> abstract class Example {
>   bool _mounted = false;
>   bool get mounted => _mounted;
> 
>   @override
>   void dispose() {
>     super.dispose();
>     _mounted = true; 
>   }
> }
> ```

Thank you!

**Comment by millerf** [comment]
I am using this
```
class MaybeChangeNotifier extends ChangeNotifier {
  @override
  notifyListeners() {
    if (hasListeners) {
      super.notifyListeners();
    }
  }
}
```

As hasListeners returns false when the Notifier was disposed
