### ISSUE TITLE
The following StateError was thrown building Product_detail_screen(dirty, dependencies: [_ModalScopeStatus])

### ISSUE THREAD

**Issue by sufiyanjamil** [rrousselGit/provider#781]
final productid = ModalRoute.of(context)!.settings.arguments as String;
    final productget =
        Provider.of<Productss>(context, listen: false).findById(productid);
    return Scaffold(
      appBar: AppBar(
        title: Text(productget.title),
      ),
      body: SingleChildScrollView(
        child: Expanded(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              Container(
                height: MediaQuery.of(context).size.height * 0.65,
                width: double.infinity,
                child: Image.network(productget.imageUrl),
              ),

**Comment by rrousselGit** [comment]
Please make a bit more effort when raising issues.

Sharing the error+stacktrace and formatting the code would be a good start.

**Comment by rrousselGit** [comment]
In the lack of an answer, I'll close this
