### ISSUE TITLE
Throw ProviderNotFoundException

### ISSUE THREAD

**Issue by vvvirani** [rrousselGit/provider#782]
I have already registered providers under MultiProviders class. Every provider class extends with ChangeNotifier class. But it throws ProviderNotFoundException exception.

I have used the latest package version: 6.0.3

I have attached a screenshot.

<img width="720" alt="Screenshot 2022-10-05 at 12 07 20 PM" src="https://user-images.githubusercontent.com/55572605/193996552-fa95210c-da53-4a39-b9cf-7a1d01fc22ff.png">

**Comment by rrousselGit** [comment]
I'll need a complete example. I can't help otherwise

**Comment by vvvirani** [comment]
This problem facing after updating flutter SDK 2.10.5 to 3.3.3.

I will share screenshot step by step.

**Comment by vvvirani** [comment]
Step 1: Create CartTest class with ChangeNotifier
<img width="539" alt="Screenshot 2022-10-05 at 12 38 02 PM" src="https://user-images.githubusercontent.com/55572605/194001178-f11ad1ec-a34e-4b73-aee7-667a00eecabb.png">

Step 2: Register CartTest call under MultiProvider class
<img width="497" alt="Screenshot 2022-10-05 at 12 39 06 PM" src="https://user-images.githubusercontent.com/55572605/194001395-458576d5-4b74-4b55-9cb5-f7de4b48c44f.png">

Step 3: Read CartTest class home screen
<img width="516" alt="Screenshot 2022-10-05 at 12 40 33 PM" src="https://user-images.githubusercontent.com/55572605/194001576-dae13bab-47f9-4305-99f1-6eba5ab08a11.png">

Throw error ProviderNotFoundException Could not find the current Provider<CartTest>

**Comment by rrousselGit** [comment]
That's not really what I asked for. I'd need a complete example, something I can execute (that's not your entire app).
You're cutting too much with your screenshot. So I can't know what happens.

But for starter it'd help if you could share the stacktrace and the code that the stacktrace points to.

**Comment by nervouna** [comment]
> I'd need a complete example, something I can execute (that's not your entire app).

@vvvirani To provide such example: 
```bash
flutter create bug
cd bug
flutter pub add provider
flutter pub get
```
Write the minimal code needed to reproduce the bug in `bug/lib/main.dart`, run it in the simulator to make sure the bug reproduces, then copy & paste your code here in the comments.

@rrousselGit perhaps detailed instructions should be included in the issue template? Since this package is recommended in flutter starter guides, starters (like me) will certainly come every now and then.

**Comment by vvvirani** [comment]
I have already solved this problem. Thank you.
