### ISSUE TITLE
How to fix typeEError

### ISSUE THREAD

**Issue by kelvinleungv** [rrousselGit/provider#789]
error:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/21992834/203506350-9ac61ec7-d330-4f63-bf81-a65911cd7d76.png">

use:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/21992834/203506256-626f0d1c-488f-450b-8563-ed3f26f948fe.png">

quetions: how to fix the error

**Comment by rrousselGit** [comment]
what does this have to do with provider?

**Comment by kelvinleungv** [comment]
> 

oh，sorry。I am a beginner of flutter. When I upgrade from flutter version 1.22.4 to version 3.3.6, the application project prompts a typeError，i don't know how to fix the error

**Comment by rrousselGit** [comment]
I understand that you're looking for help, but this isn't the correct place.

If you need help, go on StackOverflow or community groups like Slack/Discord. Here this is about provider bugs/feature requests, not help request
