### ISSUE TITLE
How to perform action later after network result?

### ISSUE THREAD

**Issue by anticafe** [rrousselGit/provider#79]
I'm not sure `provider` lib is able to do this, but let see my case:
- Assume in Login screen, I touch on Login button to log in.
- After logging successfully, I would like to open Home screen. But I see in Login screen, there is only `build()` method to update its UI but no place to handle Login success action.

Could you please share with me your experience in similar case? Thanks.

**Comment by rrousselGit** [comment]
You likely store a `Future` somewhere.

So you can trigger a navigation push after that future finished
