### ISSUE TITLE
ChangeNotifierProvider -> Consuming the Provider in a new route

### ISSUE THREAD

**Issue by nagringapp** [rrousselGit/provider#790]
**Describe the bug**
When creating the Provider using ChangeNotifierProvider, router that are pushed withing the new context no longer find the Provider. I had to move the provider to the root of the project.

**To Reproduce**

Please find details below:

**Expected behavior**
New routes should be able to consume the Provider created in the parent router - whenever a new context is set..

## Steps to Reproduce

// Create the Provider
class MyProvider extends ChangeNotifier {

}

// Initiate the provider in a screen
class MyMainPage extends StatefulWidget {
  const MyMainPage({super.key});

  @override
  State<MyMainPage> createState() => _MyMainPageState();
}

class _MyMainPageState extends State<MyMainPage> {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => MyProvider(),
      builder: (ctx, _) {
          Navigator.push(ctx, MaterialPageRoute(builder: (_) => MyPage())
      }
    );
  }
}

// Consume the Provider in the new Page
class MyPage extends StatefulWidget {
  const MyPage({super.key});

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {

    final provider = Provider.of<MyProvider>(context, listen: false);
    // !!!! ERROR !!!!

    return Container();
  }
}

**Expected results:** 
- On the MainPage I created the ChangeNotifierProvider to initiate the Provider itself
- I used the context returned from the builder to push to a new Route.
- On the new route I tried to create the provider based on the context and got an error.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>
═══════ Exception caught by widgets library ═══════════════════════════════════
Error: Could not find the correct Provider<MyProvider> above this Consumer<MyProvider> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that Consumer<MyProvider> is under your MultiProvider/Provider<MyProvider>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>().toString()),
    );
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context, child) {
        // No longer throws
        return Text(context.watch<Example>().toString());
      }
    );
  }
  ```

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter
```
```

```
```

```
```

</details>

**Comment by rrousselGit** [comment]
Hello!

This is expected. If a provider is inserted within a route, it is available only within that route. So other routes don't have access to it

If you want pushed routes to access providers from the origin route, you need to re-insert the providers in the new route.

**Comment by nagringapp** [comment]
It's interesting - The ChangeNotifierProvider generates a new BuilderContext on the Builder 

On my example above, I set the variable as ctx to differentiate to the widget context.

If I use Provider.of(context) it doesn't retrieve the provider;
If I use Provider.of(ctx) it does find the provider.

Why the Navigator doesn't follow the same logic?

Navigator.of(context) -> that's ok, to trigger an error
Navigator.of(ctx) -> I would expect that the new rout should be child of the ctx context created by the ChangeNotifierProvider.
