### ISSUE TITLE
After Hot Restart ChangeNotifierProvider does not update value. 

### ISSUE THREAD

**Issue by AnkitPanchal10** [rrousselGit/provider#795]
I am facing the same issue. After a hot restart, the value of ChangeNotier does not update. 

<img width="983" alt="Screenshot 2022-12-20 at 4 50 53 PM" src="https://user-images.githubusercontent.com/38405884/208655329-65ad9588-0118-4e31-a598-e016d5cc38bb.png">

<img width="1265" alt="Screenshot 2022-12-20 at 4 35 12 PM" src="https://user-images.githubusercontent.com/38405884/208652538-fb5d17f1-2436-4d23-94ab-19e7480f5243.png">

So, first, I call tryAutologout(), and it's working okay, but after that, when I try to fetch the value of userData at line 86, it gives a null value. I have checked that context is not broken or dirty, but the value of Auth is not updated.

**Comment by rrousselGit** [comment]
What's your provider? Why should the notifier update on hot-restart? Hot-restart destroys your application, so I don't get your question

**Comment by AnkitPanchal10** [comment]
After Hot-Restart, when the app was relaunched and the provider re-created, then it didn't get updated.

**Comment by rrousselGit** [comment]
What does "didn't get updated" mean?

**Comment by rohit3103** [comment]
I am facing this issue when I am passing the json data into provider nut it does not update

**Comment by muhammadusamaijaz** [comment]
@AnkitPanchal10 on hot restart, all providers re-created. at this point all providers have their member functions in fresh state, so all previous states will be vanished

**Comment by Richmond-Nunoo** [comment]
You can create a function that calls the data from firebase and then assign values to your provider . Call this function in the initstate of your app for it to work @AnkitPanchal10 !

**Comment by haroonkhan335** [comment]
Don't you think testing the credibility of your code is your first thing to do rather than opening an issue on a package that doesn't have anything to do with what you're doing?
