### ISSUE TITLE
Consumer using disposed provider on macos

### ISSUE THREAD

**Issue by gmparker2000** [rrousselGit/provider#807]
When building for macos I have a problem when I resize the window. The provider is being disposed and I get something like this:

```
  The following assertion was thrown building Consumer<BlahProvider>(dirty, dependencies: 
  [_InheritedProviderScope<BlahProvider?>]):
  A BlahProvider was used after being disposed.

  Once you have called dispose() on a BlahProvider, it can no longer be used.
```

Any ideas?

**Comment by johnxpres** [comment]
> When building for macos I have a problem when I resize the window. The provider is being disposed and I get something like this:
> 
> ```
>   The following assertion was thrown building Consumer<BlahProvider>(dirty, dependencies: 
>   [_InheritedProviderScope<BlahProvider?>]):
>   A BlahProvider was used after being disposed.
> 
>   Once you have called dispose() on a BlahProvider, it can no longer be used.
> ```
> 
> Any ideas?

This error occurs when you try to use a BlahProvider instance after it has been disposed of. When a ChangeNotifierProvider is removed from the widget tree or is no longer needed, its associated ChangeNotifier is disposed of using the dispose method. Once a ChangeNotifier has been disposed of, it can no longer be used, and any attempt to access its properties or call its methods will result in this error.
To fix this error, you should ensure that you are not using a disposed BlahProvider instance. This can be done by checking whether the BuildContext has access to a non-null BlahProvider instance using Provider.of<BlahProvider>(context, listen: false) or context.read<BlahProvider>() before using it. If the provider is null or has been disposed of, you should recreate the provider or avoid using it.
Additionally, you can also avoid this error by ensuring that you dispose of the ChangeNotifierProvider instance properly when it is no longer needed, such as when the widget that uses it is removed from the widget tree or when the state that uses it is no longer needed. This can be done by wrapping the widget tree that uses the provider in a Consumer widget, or by manually removing the provider from the widget tree using removeProvider method of the ProviderContainer.

**Comment by rrousselGit** [comment]
Closing as this was answered
