### ISSUE TITLE
MultiProvider Provider not working in flutter web. when i add one file in between provider file and main.dart file .

### ISSUE THREAD

**Issue by vijayvaghela72** [rrousselGit/provider#809]
this is my main.dart file 

`
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<DashboardProvider>(
          create: (context) => DashboardProvider(),
        ),
      ],
      child: MaterialApp(
        title: 'test',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.grey,
        ),
        home: TestPage(),
      ),
    );
  }
}`

=>  this testpage file ,

`// for testing only

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:provider/provider.dart';
import 'package:viewo_chat_support_app/src/features/authentication/login.dart';
import '../../Features/chat_dashboard/chat_dashboard.dart';
import '../chat_dashboard/chat_dashboard_provider.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => HomePageView(),
            ),
          );
          Navigator.push(
            context,
            CupertinoPageRoute(
              builder: (context) => ChangeNotifierProvider<DashboardProvider>(
                create: (context) => DashboardProvider(),
                child: const HomePageView(),
              ),
            ),
          );
        },
        child: Container(
          color: Colors.red,
          child: Text('texting'),
        ),
      ),
    ));
  }
}
`

this my home page file ,

`class HomePageView extends StatefulWidget {
  const HomePageView({super.key});

  @override
  State<HomePageView> createState() => _HomePageViewState();
}

DashboardProvider? chatDashboardProvider;

class _HomePageViewState extends State<HomePageView> {
  @override
  void initState() {
    chatDashboardProvider =
        Provider.of<DashboardProvider>(context, listen: false);
    chatDashboardProvider!.initializedVariables();
    chatDashboardProvider!.isLoading = true;

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
 return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Viewo Chat Support',
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        backgroundColor: Colors.grey,
      ),
      body: Container(child : Text('hello')));}

}
`

case is if directly give navigation to main to home page then provider work but when i try using intermediate file, just one button to navigat to home screen which give me provider could not find even i have added MultiProvider but not working 

please help me ...

Thank you ...! :)

**Comment by rrousselGit** [comment]
What does "not working" means in this case?

Please format your code too :)

**Comment by vijayvaghela72** [comment]
this main.dart file, 

```import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'src/Features/authentication/login.dart';
import 'src/common_widgets/token.dart';
import 'src/features/authentication/temp.dart';
import 'src/features/chat_dashboard/chat_dashboard_provider.dart';
import 'src/features/chat_dashboard/chat_dashboard.dart';
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart';

Box? authenticationTokenBox;
void main() async {
  // for widget binding
  WidgetsFlutterBinding.ensureInitialized();
  // initialization of firebase
  await Firebase.initializeApp(
    options: const FirebaseOptions(
     
    ),
  );

  // Initialize hive local storage
  await Hive.initFlutter();
  await Hive.initFlutter();
  // Open the token
  await Hive.openBox('authenticationBox');
  authenticationTokenBox = Hive.box('authenticationBox');

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<DashboardProvider>(
          create: (context) => DashboardProvider(),
        ),
      ],
      
      child: MaterialApp(
        title: 'Support',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.grey,
        ),
        home: TestPage(), //  HomePageView(),
      ),
    );
  }
}
```
here i have declare DashboardProvider ,
this is test.dart file 

``` 
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:provider/provider.dart';
import 'package:viewo_chat_support_app/src/features/authentication/login.dart';
import '../../Features/chat_dashboard/chat_dashboard.dart';
import '../chat_dashboard/chat_dashboard_provider.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => HomePageView(),
            ),
          );
        },
        child: Container(
          color: Colors.red,
          child: Text('texting'),
        ),
      ),
    ));
  }
}
```

chat_dashbord.dart file 
```import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:viewo_chat_support_app/src/common_widgets/snackbar.dart';
import '../../common_widgets/token.dart';
import '../../constants/constant.dart';
import '../../features/chatting/chatting.dart';
import '../code_editor/code_editor.dart';
import 'chat_dashboard_provider.dart';
import 'package:provider/provider.dart';
import 'package:responsive_builder/responsive_builder.dart';

class HomePageView extends StatefulWidget {
  const HomePageView({super.key});

  @override
  State<HomePageView> createState() => _HomePageViewState();
}

DashboardProvider? chatDashboardProvider;

class _HomePageViewState extends State<HomePageView> {
  @override
  void initState() {
    chatDashboardProvider =
        Provider.of<DashboardProvider>(context, listen: false);
    chatDashboardProvider!.initializedVariables();
    chatDashboardProvider!.isLoading = true;
    getToken();
    super.initState();
  }

  getToken() async {
    try {
      await FirebaseAuth.instance
          .signInWithEmailAndPassword(
        email: 'flutterdeveloper72@gmail.com',
        password: '***********',
      )
          .then((value) async {
        final tokenResult = await FirebaseAuth.instance.currentUser;
        final idToken = await tokenResult!.getIdToken();
        Auth.authenticationToken = idToken;
        print("idToken : $idToken");
        getAllData();
      });

    } catch (e) {
      setSnackbar("exeception : $e", context);
    }
  }

  getAllData() async {
    chatDashboardProvider!.setChatRoomAPI(context);
    chatDashboardProvider!.getRoomMessagesAPI(context);
    chatDashboardProvider!.isLoading = false;
    setState(() {});
  }
  @override
  Widget build(BuildContext context) {
    height = MediaQuery.of(context).size.height;
    width = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Viewo Chat Support',
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        backgroundColor: Colors.grey,
      ),
      body: // some Body code here
  }
  ```
  
  now, problem in flutter web , 
  
  main.dart -> temp.dart -> chat_dashboard.dart 
  
Error: Could not find the correct Provider<DashboardProvider> above this HomePageView Widget.

in this case it's working fine 

main.dart -> chat_dashbord.dart

=> working properly

**Comment by rrousselGit** [comment]
Right but I can't run your code so can't help you.

**Comment by rrousselGit** [comment]
In the lack of a reproducible example, I'll close this
