### ISSUE TITLE
How do we pass widget parameters to the constructed changenotifier? Or is there a better alternative?

### ISSUE THREAD

**Issue by tylandercasper** [rrousselGit/provider#814]
I'm trying to do something that I thought was pretty simple but is turning out to be complex:

I've got a for loop which passes data to it's children, and than each children creates a ChangeNotifier that uses that data. 

`children: [
  for (var item in context.select((ParentChangeNotifier t) => t.items))                    
	   ChildWidget(data: item)                    
],`				

And than in the ChildWidget  I'd like to do:
`ChangeNotifier<ChildWidgetChangeNotifier>(
      create: (_) => ChildWidgetChangeNotifier(data:data))`

This works fine the first time I do it, but the data field isn't getting updated when the parameter changes to a different item. 

so say the loop creates
item1:childWidget1:ChildWidgetChangeNotifier data= item1
item2:childWidget2:ChildWidgetChangeNotifier data= item2

If I delete item1 I would expect it to be:
item2:childWidget1:ChildWidgetChangeNotifier data= item2

but instead it produces::
item2:childWidget1::ChildWidgetChangeNotifier data= item1

I had assumed (obviously incorrectly) that everything is rebuilt when a widget parameter changes, but now that that doesnt work I'm not sure how pass the new parameter to the change notifier.

**Comment by rrousselGit** [comment]
You shouldn't use the default constructor.

Instead use `ChangeNotifierProvider.value(value: data)`

**Comment by tylandercasper** [comment]
Well, in this case I'm not passing a ChangeNotifier. data is just some json data that ChildWidgetChangeNotifier needs.

**Comment by tylandercasper** [comment]
Right, that's my question. How do I update the changenotifiers data when the widget parameter has changed?

I know if it were data from another provider, I could use the ChangeNotifierProxyProvider and use the update method to do something like model..data=data, but is there an equivalent event I could hook into to change the value if it's a widget parameter change?

I apologize if I'm being unclear. I did read through the documention but couldn't find anything that addressed the issue.

**Comment by rrousselGit** [comment]
You could make a StatefulWidget and store the ChangeNotifier in the state. Then update the notifier in didUpdateWidget
