### ISSUE TITLE
Function parameters cannot be the same as listener parameters

### ISSUE THREAD

**Issue by arianshi** [rrousselGit/provider#815]
**Describe the bug**
Function parameters cannot be the same as listener parameters

https://user-images.githubusercontent.com/122079456/236607874-d251e9c1-7f82-4cb6-bd9a-a427f5a76613.mov

When I try to use number as a parameter, it is the same as the variable name monitored by the provider, and cannot be updated.

**Comment by rrousselGit** [comment]
That'd unrelated to provider. That's how Dart works.

Use this.number=numbers
