### ISSUE TITLE
Use `Selector` with Records instead of Tuple

### ISSUE THREAD

**Issue by jagomf** [rrousselGit/provider#830]
In `Selector` docs, [current recommendation is to use `tuple` package](https://github.com/rrousselGit/provider/blob/9f66261ac6f0155d8d4a941147bbded36dc89e30/lib/src/selector.dart#L126).

Probably the best recommendation now would be to use native **Dart 3 Records**. Docs and example should be updated accordingly.

**Comment by rrousselGit** [comment]
Fancy making a PR? :)

**Comment by tienthai0205** [comment]
Hi @rrousselGit I'd like to take this issue, can you assign it to me? Thanks

**Comment by rrousselGit** [comment]
Sure, feel free to make a PR
