### ISSUE TITLE
Provider<DateTime Function()> it's a good practice ?

### ISSUE THREAD

**Issue by lsaudon** [rrousselGit/provider#834]
I would like to have a provider to request the current date.
Is there any contraindication to doing it this way?

```dart
    Provider<DateTime Function()>(
      create: (context) => () => DateTime.now(),
      child: const MaterialApp(
        home: MyHomePage(),
      ),
    );
```

**Comment by rrousselGit** [comment]
It's alright. Although you probably should make a typedef for the function

And you could alternatively use the pkg:clock package, which is typically used for time mocking. It's already used by Flutter I believe
