### ISSUE TITLE
Fix description in pub.dev

### ISSUE THREAD

**Issue by gazialankus** [rrousselGit/provider#84]
The description under "About" in https://pub.dev/packages/provider has small mistakes: 

A~~n~~ helper to easily expose~~s~~ a value using InheritedWidget without having to write one.

Cheers.

**Comment by rrousselGit** [comment]
It's already changed on master, just not deployed

**Comment by filiph** [comment]
FWIW, if there's a cosmetic change that you'd like to push to pub.dev, it's possible and encouraged. Just publish a minor version (`2.0.2`) or a "plus" version (`2.0.1+1`). The choice is completely up to personal taste.
