### ISSUE TITLE
Provider 6.1.0 appears to be missing devtools extension assets

### ISSUE THREAD

**Issue by kenzieschmoll** [rrousselGit/provider#847]
I downloaded provider 6.1.0 from https://pub.dev/packages/provider and the devtools extension assets are not there `extension/devtools/build`. Can you release 6.1.1 with the extension assets? thanks

**Comment by rrousselGit** [comment]
Seems like the pubignore didn't work properly. I'll fix it

**Comment by rrousselGit** [comment]
6.1.1 is out
