### ISSUE TITLE
Cannot use parent class of provided class

### ISSUE THREAD

**Issue by Jannik-dev** [rrousselGit/provider#866]
**Description**
Hi, I have raised this issue in the bloc package and was delegated to provider (https://github.com/felangel/bloc/issues/4077). I am encountering the following issue, when I provide a certain class and try to use subclasses in a bloc builder an ProviderNotFoundException is thrown.

Consider the following example:

```dart 
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class AbstractCubit<T> extends Cubit<T> {
  AbstractCubit(super.initialState);
}

class IntCubit extends AbstractCubit<int> {
  IntCubit() : super(0);

  void doStuff() {
    emit(1);
  }
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider<IntCubit>(
      create: (context) => IntCubit(),
      child: const MaterialApp(
        title: 'Flutter Demo',
        home: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: const BlocWidget<int>(),
    );
  }
}

class BlocWidget<T> extends StatelessWidget {
  const BlocWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AbstractCubit<T>, T>(
      builder: (BuildContext context, T state) {
        return const Text('test');
      },
    );
  }
}
```

**Expected Behavior**
The BlocBuilder<AbstractCubit<T>, T> uses the provided IntCubit (since IntCubit is an AbstractCubit<int>).

**Comment by rrousselGit** [comment]
Correct. This is unsupported.

If you wish for your object to be used with `AbstractCubit` instead of `IntCubit`, have your provider use `AbstractCubit`:

```dart
BlocProvider<AbstractCubit<int>>(
```

**Comment by Jannik-dev** [comment]
Thanks for the quick reply, but simply providing `AbstractCubit` instead of `IntCubit` does not work, since I need the `IntCubit` functionality in another part of the app (in this example the `doStuff` method). But I don't want to use `IntCubit` in `BlocWidget`, because it does not need it.

My only idea right now is to provide `IntCubit` as `AbstractCubit` and as `IntCubit` but I dislike this approach too, because there could be more classes in the hierarchy.

**Comment by rrousselGit** [comment]
What you're asking is not possible in any case. You'll always have to write extra logic to support both `context.watch<AbstractCubit<int>>` and `context.watch<IntCubit>`

**Comment by Jannik-dev** [comment]
Why cannot `context.watch<AbstractCubit<int>>` use the `IntCubit`? I mean, the `IntCubit` is an `AbstractCubit<int>`. Is there no simple way how I can use abstractions?

**Comment by rrousselGit** [comment]
That's not how InheritedWidgets work. They use exact type matching. There's no such thing as specifying a type, but getting a subclass instead. You have to manually expose your provider with said type. No way around it.

**Comment by Jannik-dev** [comment]
Thank you very much for your explanation
