### ISSUE TITLE
postfix with notify listeners wont  show  value 

### ISSUE THREAD

**Issue by GaneshTamang** [rrousselGit/provider#870]
```
_count++
notifylisteners()
```
examples code _count++ is postfix with this  watching provider value wont change tried wont change if can only change if put in preifix as 
```
++_count
notifylisteners()
```

**Comment by rrousselGit** [comment]
This is very unlikely to be a provider bug. To begin with, you didn't change a single line of Provider code. NotifyListeners is from Flutter afterall.

I'd suggest asking for help on StackOverflow/Discord instead, or make a complete minimal reproducible example.
