### ISSUE TITLE
Why when creating a Consumer, an optional child is asked? When is it used? 

### ISSUE THREAD

**Issue by stephane-archer** [rrousselGit/provider#878]
Why when creating a Consumer, an optional child is asked? When is it used? The builder is what decides what is shown from my understanding.
```
(new) Consumer<VideoCodecChangeNotifier> Consumer({
  Key? key,
  required Widget Function(BuildContext, VideoCodecChangeNotifier, Widget?) builder,
  Widget? child,
})
```

**Comment by Melvin-2007** [comment]
The child widget passed to the Consumer won't rebuild when the value changes. This allows you to include widgets inside the child that you don't want to rebuild when the value changes.

**Comment by rrousselGit** [comment]
This is explained by the IDE documentation of the Consumer class.

See also: https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/Consumer-class.html
