### ISSUE TITLE
Add a way to know if a provider's value has been created

### ISSUE THREAD

**Issue by ChreSyr** [rrousselGit/provider#886]
In my app, i have a FavoritesCubit that streams data from my database. Every time the UserCubit changes, the stream of FavoritesCubit is canceled and then restarted. For this, i use BlocListener, from flutter_bloc package.

FavoritesCubit contains data that are only accessible through a secondary page in my app, it is not on the home page.

The thing is, when i launch my app, the BlocListener instantly prevents my FavoritesCubit of the changes. So the BlocProvider instantly creates the FavoritesCubit, and dependency injection is useless.

I wish i could detect, from the BlocListener, if the FavoritesCubit has already been created or not. This way, it will only be updated when needed.

I think something like this would be enough :

```
class Provider<T> extends InheritedProvider<T> {
  static bool hasValue<T>(BuildContext context) => _inheritedElementOf<T>(context).hasValue;
}
```

So i would write :

```
BlocListener<UserCubit, UserModel?>(
  listenWhen: (previous, current) => previous?.favorites != current?.favorites,
  listener: (context, user) {
    if (Provider.hasValue<FavoritesCubit>(context)) {
      context
          .read<FavoritesCubit>()
          .onUserFavoritesChanged(user?.favorites ?? []);
    }
  },
),
```

What do you guys think about it ?

**Comment by rrousselGit** [comment]
It's already supported, through nullable values.

You can do:

```dart
final exists = context.read<T?>() != null;
```

If the value doesn't exist, when using a nullable value, you'll get `null`

**Comment by ChreSyr** [comment]
Thanks !!
