### ISSUE TITLE
Although there are no listeners, but the number of listeners is still greater than 0, is this normal?

### ISSUE THREAD

**Issue by lbgitjp** [rrousselGit/provider#889]
**Describe the bug**

The following code no one listen Counter's change, but **print(context.read<Counter>().hasListeners1)** still output true.

**To Reproduce**

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class Counter with ChangeNotifier {
  int value = 0;

  bool get hasListeners1 => hasListeners;
}

void main() {
  runApp(
    ChangeNotifierProvider(
      create: (context) => Counter(),
      builder: (context, child) {
        print(context.read<Counter>().hasListeners1);

        return Container();
      },
    ),
  );
}
```

**Expected behavior**
In the code above,  **print(context.read<Counter>().hasListeners1)** should output **false**.

Thanks!

**Comment by rrousselGit** [comment]
There is a listener. The provider package is listening to the ChangeNotifier.
That's not possible to change
