### ISSUE TITLE
Cannot watch / select inside go_router redirect

### ISSUE THREAD

**Issue by EArminjon** [rrousselGit/provider#892]
**Describe the bug**

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for GoRouteInformationProvider:
Tried to use `context.select` outside of the `build` method of a widget.

Any usage other than inside the `build` method of a widget are not supported.
'package:provider/src/inherited_provider.dart':
Failed assertion: line 266 pos 12: 'widget is LayoutBuilder || debugDoingBuild'
```

go router documentation :
```dart
/// If [BuildContext.dependOnInheritedWidgetOfExactType] is used during the
/// redirection (which is how `of` method is usually implemented), a
/// re-evaluation will be triggered if the [InheritedWidget] changes.
final GoRouterRedirect? redirect;
```

context.watch and context.select use dependOnInheritedWidgetOfExactType but an assert prevent them to be used inside go_router redirect.

If I edit provider code as bellow it works well, redirection are well re-evaluated as expected (it's maybe not the good solution, I just did it for demo purpose) : 

<img width="575" alt="image" src="https://github.com/user-attachments/assets/836028be-74be-4a73-89ea-99db35c946b6">

**To Reproduce**

Call context.watch or context.select inside GoRouter route redirect callback.

**Expected behavior**
Context.watch or context.select should be callable inside GoRouter redirect.

**Comment by rrousselGit** [comment]
I cannot reasonably depend on go_router just for an assert.

So this would require removing the assert entirely, which I rather would not do.

**Comment by EArminjon** [comment]
Router is coming from In flutter/lib/src/widgets/router.dart, it's not linked with GoRouter directly.

**Comment by rrousselGit** [comment]
If it's Router from Flutter, maybe.
Still, I'd like not to change this value too much.

To begin with, the issue is State.didChangeDependencies here.

This lifecycle isn't supported, regardless of Router.

**Comment by EArminjon** [comment]
I think you refer to the discussion here i believe. We can close this issue so.

As an alternative we can use GoRouter `refreshListenable` as context watch/select will not be supported.
