### ISSUE TITLE
HookProvider

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/provider#9]
Hooks allow some very powerful provider:

```dart
HookProvider<MyBloc>(
  value: () {
    final bloc = useMemoized(() => MyBloc());
    useEffect(() => bloc.dipose, [bloc]);
    return bloc;
  },
  child: Container();
);
```

**Comment by jogboms** [comment]
I'm watching this.

**Comment by rrousselGit** [comment]
I'm still hesitating. This would add a new dependency on `provider`
package. Peoples may not want to download `flutter_hooks` when using
`Provider`

**Comment by rrousselGit** [comment]
Will do.

This allows to heavily simplify the implementation of other providers (as a `StreamProvider` is just a `useStream` hook on a HookProvider)

Which means I can _finally_ continue that hanging PR because I won't have to reimplement the whole world.

**Comment by jogboms** [comment]
I haven't been updating for a while, I completely missed when you removed this.

**Comment by rrousselGit** [comment]
Do you need it?

**Comment by jogboms** [comment]
I had on an older project that needed revamp but its fine I replaced it with the generic provider. Big ups!

**Comment by rrousselGit** [comment]
Good! Because I have other plans that are incompatible with `HookProvider`, and `Provider` seems to solve all the use-cases anyway. 😄
