### ISSUE TITLE
how to add circularprogressindicator while loading data from firestore ?

### ISSUE THREAD

**Issue by TaifRaoof** [rrousselGit/provider#90]
Hi 
when loading data from firestore or api the red screen with size , length error appear for while before show items so i want to add circularprogressindicator while loading data?
i am using stream provider with firestore

**Comment by TheJulianJES** [comment]
It's easily possible. You could just check if your data is null and then display a loading indicator. There are tons of other ways as well.
It would be better to provide a code sample and I'm also not sure if this question was better to be asked on StackOverflow.

**Comment by rrousselGit** [comment]
As said by @TheJulianJES, such question belong to Stackoverflow
