### ISSUE TITLE
Infinite Listview with provider 

### ISSUE THREAD

**Issue by mfarkan** [rrousselGit/provider#94]
I'm making fintech app with flutter and i was managed login workflow with this library but i have three listview (datas came from API , im not sure how big it is ) such as ; Income,Outcome and AllOfThem.

I know ListView.Builder and scrollController but sometimes i need to add some items to list and call the API for adding items also change the UI screen.

Can i manage this , using your library ?

If answer is **yes** , **How** ? If answer is **no** , **Why** ?

**Comment by rrousselGit** [comment]
That's possible. But github is not a place for such question.

Consider asking it on Stackoverflow or Gitter.

**Comment by mfarkan** [comment]
okey , thank you for your reply :)

**Comment by rlee1990** [comment]
@mfarkan did you manage to find a solution? I'm running into the same issue.

**Comment by mfarkan** [comment]
i forget this issue but i have found some youtube videos and they're using refreshIndicator with FutureBuilder i decided to use that , if you use this way search youtube with this keywords "Infinite ListView in Flutter with RefreshIndicator."

Happy Coding ,
