### ISSUE TITLE
Status not changing when user authenticating.

### ISSUE THREAD

**Issue by mfarkan** [rrousselGit/provider#96]
Hi , i have some issue or some miss understanding in here. I'm trying to authentication flow.When i click the login button without delaye status is not changing but if i add future delaye in signIn method status flow like this ; 

UnAuthenticated => Authenticating => Authenticated

without future delayed ;

UnAuthenticated ==> Authenticated

PS:I have dummy repository for authentication and it has future delayed itself.

here is my sample of project ; 

https://file.io/QxnV8h

Thank you ,

**Comment by rrousselGit** [comment]
Hello, thanks for the report!

Sadly even when looking in your reproduction repository, I fail to understand the issue. Could you clarify?

**Comment by mfarkan** [comment]
when i was change this code like this ; 

```
  Future<bool> signIn(String email, String password) async {
    try {
      _status = AuthenticationStates.Authenticating;
      notifyListeners();
      _repo.signInPasswordWithEmail(email, password);
      _status = AuthenticationStates.Authenticated;
      notifyListeners();
      return true;
    } catch (e) {
      _status = AuthenticationStates.AuthenticationFailure;
      notifyListeners();
      return false;
    }
  }
```
Status never change Authenticating.

But i change like this ; 

status is changing ; 

```
  Future<bool> signIn(String email, String password) async {
    try {
      _status = AuthenticationStates.Authenticating;
      notifyListeners();
      await Future.delayed(const Duration(seconds: 3));
      _repo.signInPasswordWithEmail(email, password);
      _status = AuthenticationStates.Authenticated;
      notifyListeners();
      return true;
    } catch (e) {
      _status = AuthenticationStates.AuthenticationFailure;
      notifyListeners();
      return false;
    }
  }
```

**Comment by rrousselGit** [comment]
From the looks of it, it works as expected.

The switch between `Authentificating` and `Authentificated` is synchronous on the first code snippet. So it shows `Authentificated` directly.

**Comment by mfarkan** [comment]
oh my god ?? how can i see this ?? method is future but im calling like a sync method. sorry for the issue :(
